    <h2>Sestavy</h2>
<p>    
Po klepnutí na tlačítko Sestavy se vám zobrazí všechny pevné a volitelné sestavy, které jsou vytvořeny. Rozdíl mezi pevnou a volitelnou sestavou je ten, že pevnou sestavu na rozdíl od té volitelné nelze již dále upravovat. Oba druhy sestav lze buď zobrazit nebo zobrazit a následně vytisknout či generovat sestavu do PDF souboru. Tyto funkce mají společnou jednu věc a tou je, že pokud klepnete na jednu z ikon (list, tiskárna, PDF soubor), tak se vám nejdříve zobrazí dialogové okno s filtrem, kde lze vyplnit následijící položky:
    <dl>
        <dt>Pořadové číslo</dt>
        <dd>Zadává se celočíselná kladná hodnota a to Od – Do</dd>
    </dl> 
    <dl>
        <dt>Datum</dt>
        <dd>Zadává se platný formát včetně dne, měsíce, roku. Pokud klepnete do textového pole data, tak se vám zobrazí graficky zpracovaný kalendář, ve kterém se můžete pohybovat pomocí myši. V případě, že chcete data jen z dneška, tak stačí pouze zaškrtnout pole Dnešní</dd>
    </dl> 
    <dl>
        <dt>Rok</dt>
        <dd>Zde vyberte rok, kterého se mají data sestavy týkat.</dd>
    </dl> 
</p>
<p>
Poslední funkce, kterou v sekci Sestavy naleznete, je možnost vytvořit sestavu. K tomu slouží nápis Nová sestava. Pokud na tento nápis klepnete, budete přesměrováni na novou stránku, kde naleznete formulář sloužící k vytvoření sestavy. 
</p>
