    <h2>Nová sestava</h2>
<p>    
Tento formulář se dělí do čtyř podsekci (Sestava, Filtr dokumentu, Přiděleno / předáno a Adresáti / Odesílatelé) a obsahuje následující položky:
</p>

<br>
<h3>Sestava</h3>
<p>
Do této sekce se zadávají informační údaje týkající se nové sestavy.
    <dl>
        <dt>Název sestavy</dt>
        <dd>Zde se zadává název pro sestavu.</dd>
    </dl> 
    <dl>
        <dt>Popis sestavy</dt>
        <dd>Sem můžete zadat charakterizující popis tvořené sestavy.</dd>
    </dl> 
    <dl>
        <dt>Typ sestavy</dt>
        <dd>Zde máte na výběr mezi volitelnou a pevnou sestavou.</dd>
    </dl> 
    <dl>
        <dt>Filtrovat?</dt>
        <dd>Pokud zaškrtnete tuto možnost, zadáváte tím, zda má být zobrazen výběr rozsahu podle pořadového čísla nebo data.</dd>
    </dl> 
</p>

<br>
<h3>Filtr dokumentu</h3>
<p>
    Zde se zadávají údaje týkající se filtru dokumentů. Podle toho, co všechno vyplníte, bude filtr fungovat.
    <dl>
        <dt>Typ dokumentu</dt>
        <dd>Zde máte po kliknutí na šipku směřující dolů na výběr hned z několika možností.</dd>
    </dl> 
    <dl>
        <dt>Stav dokumentu</dt>
        <dd>Zde máte na výběr opět z několika možností. Najdete zde možnost jakýkoliv stav, nový/rozpracovaný, přidělen/předán, vyřizuje se, vyřízen, vyřazen.</dd>
    </dl> 
    <dl>
        <dt>Číslo jednací</dt>
        <dd>Zde můžete zadat jednací číslo.</dd>
    </dl> 
    <dl>
        <dt>Název spisu</dt>
        <dd>Toto je prostor pro zadání názvu spisu.</dd>
    </dl> 
    <dl>
        <dt>Věc</dt>
        <dd>Zde můžete zadat předmět zprávy.</dd>
    </dl> 
    <dl>
        <dt>Popis</dt>
        <dd>Popis rozšiřuje informace o tom, o jaký dokument se jedná.</dd>
    </dl> 
    <dl>
        <dt>Způsob doručení</dt>
        <dd>Zde máte v rozbalovacím menu na výběr možnosti Všechny, Pouze doručené přes elektronickou podatelnu, Pouze doručené přes email, Pouze doručené přes datovou schránku.</dd>
    </dl> 
    <dl>
        <dt>Způsob doručení přes epodatelnu</dt>
        <dd>Opět i zde na vás čeká rozbalovací menu s těmito možnostmi – Všechny, Pouze doručené přes elektronickou podatelnu, Pouze doručené přes email, Pouze doručené přes datovou schránku, Doručené mimo epodatelnu</dd>
    </dl> 
    <dl>
        <dt>Datum doručení/vzniku</dt>
        <dd>Sem můžete zadat datum vzniku/doručení pomocí implementovaného kalendáře.</dd>
    </dl> 
    <dl>
        <dt>Číslo jednací odesilatele</dt>
        <dd>Pokud máte číslo jednací odesilatele, tak toto je místo, kde můžete toto pole vyplnit.</dd>
    </dl> 
    <dl>
        <dt>Číslo doporučeného dopisu</dt>
        <dd>Sem můžete zadat číslo doporučeného dopisu a rovněž máte možnost vybrat pomocí zaškrtávacího boxu možnost Pouze doručené</dd>
    </dl> 
    <dl>
        <dt>Poznámka</dt>
        <dd>Toto textové pole je určené pro různé poznámky.</dd>
    </dl> 
    <dl>
        <dt>Způsob vyřízení</dt>
        <dd>Zde máte opět na výběr z několika možností. Můžete zvolit možnost jakýkoliv způsob vyřízení, vyřízení prvopisem, postoupení, vzetí na vědomí, úřední záznam, storno, jiný způsob.</dd>
    </dl> 
    <dl>
        <dt>Datum vyřízení</dt>
        <dd>Do tohoto pole můžete za pomocí implementovaného kalendáře zadat datum vyřízení.</dd>
    </dl> 
    <dl>
        <dt>Způsob odeslání</dt>
        <dd>Zde máte opět na výběr z několika možností. Můžete zvolit možnost jakýkoliv způsob odeslání, emailem, datovou schránkou, poštou, faxem, telefonicky</dd>
    </dl> 
    <dl>
        <dt>Datum odeslání</dt>
        <dd>Do tohoto pole můžete za pomocí implementovaného kalendáře zadat datum odeslání.</dd>
    </dl> 
    <dl>
        <dt>Druh odeslání</dt>
        <dd>Zvolte jednu z možností pomocí zaškrtávacího boxu.</dd>
    </dl> 
    <dl>
        <dt>Spisový znak</dt>
        <dd>Zapiště spisový znak</dd>
    </dl> 
    <dl>
        <dt>Skartační znak</dt>
        <dd>Zde zvolte jednu z možností skartačních znaků.</dd>
    </dl> 
    <dl>
        <dt>Skartační lhůta</dt>
        <dd>Toto pole je určené pro udání skartační lhůty.</dd>
    </dl> 
    <dl>
        <dt>Spouštěcí událost</dt>
        <dd>Zde máte v rozbalovacím menu na výběr několik možností</dd>
    </dl> 
    <dl>
        <dt>Poznámka k vyřízení</dt>
        <dd>Podsekce Přiděleno / předáno</dd>
    </dl> 
    <dl>
        <dt>Přiděleno</dt>
        <dd>Zapište, na koho má být přiděleno nebo využijte možností zaškrtávacího boxu a to buď Přiděleno na mé jméno nebo Přiděleno na mou organizační jednotku</dd>
    </dl> 
    <dl>
        <dt>Předáno</dt>
        <dd>Zapište, na koho má být předáno nebo využijte možností zaškrtávacího boxu a to buď Předáno na mé jméno nebo Předáno na mou organizační jednotku</dd>
    </dl> 
</p>


<br>
<h3>Adresáti/Odesílatelé</h3>
<p>
Sem se zadávají informace o adresátovi/odesilateli.
    <dl>
        <dt>Typ subjektu</dt>
        <dd>V rozbalovací menu vyberte jednu z možností</dd>
    </dl> 
    <dl>
        <dt>Název subjektu, jméno, IČ</dt>
        <dd>Zde se zadávají výše zmíněné položky.</dd>
    </dl> 
    <dl>
        <dt>Ulice</dt>
        <dd>Prostor pro adresu</dd>
    </dl> 
    <dl>
        <dt>PSČ a město</dt>
        <dd>Prostor pro PSČ a město</dd>
    </dl> 
    <dl>
        <dt>Email</dt>
        <dd>Prostor pro emailovou adresu.</dd>
    </dl> 
    <dl>
        <dt>Telefon</dt>
        <dd>Prostor pro telefonní spojení.</dd>
    </dl> 
    <dl>
        <dt>ID datové schránky</dt>
        <dd>Do tohoto pole se zadává ID datové schránky.</dd>
    </dl> 
</p>
<p>
Jakmile máte všechny informace vyplněné, můžete kliknout na tlačítko Vytvořit. V případě, že jste si vytvoření sestavy rozmysleli, klikněte na tlačítko Zrušit a všechna zadaná data budou ztracena.
</p>
    
