    <h2>Vítejte v systému spisové služby</h2>
    <p>
        Jestliže chcete v systému Spisové služby provádět hlubší změny a úpravy, tak
        je pro vás vyčleněna položka Administrace v pravém horním rohu. Pokud na tuto
        položku najedete a kliknete, otevře se vám úvodní stránka administrace. V ní
        naleznete tato tlačítka menu:
    </p>
    <ul>
        <li>Nastavení</li>
        <li>E-podatelna</li>
        <li>Spisy</li>
        <li>Odesílatelé/Adresáti</li>
        <li>Zaměstnanci</li>
        <li>Org. jednotky</li>
        <li>Oprávnění</li>
        <li>Soubory</li>
        <li>Spisové znaky</li>
        <li>Protokoly</li>
    </ul>
    <br />