    <h2>Seznam dokumentů</h2>

    <p>
    Seznam dokumentů je úvodní stránka, která se otevře ihned po přihlášení do systému. Pokud tento seznam dokumentů chcete vidět v budoucnu při práci se Spisovou službou, stačí klepnout na tlačítko Seznam dokumentů.
    </p>
    <p>
    Pokud chcete vidět detaily dokumentu, stačí najet a klepnout na jeho název (věc) a budete přesměrováni do detailů daného dokumentu.     
    </p>
    <p>
    Tlačítko Seznam dokumentů v sobě skrývá seznam všech dokumentů uložených v systému Spisové služby. Tyto dokumenty jsou rozřazeny do přehledné tabulky. V této tabulce naleznete následující položky:
    </p>
    <dl>
        <dt>Typ dokumentu</dt>
        <dd>Ten je vyjádřen ikonou, která představuje typ dokumentu (příchozí, odchozí atd.).</dd>
    </dl>
    <dl>
        <dt>Přijato</dt>
        <dd>Tento sloupec zobrazuje datum přijetí/vytvoření dokumentu.</dd>
    </dl>
    <dl>
        <dt>Číslo jednací, JID, Název spisu</dt>
        <dd>Zde jsou vypsány všechny identifikační údaje dokumentu.</dd>
    </dl>
    <dl>
        <dt>Věc, Adresáti/Odesilatelé, počet listů a příloh</dt>
        <dd>V tomto sloupci naleznete předmět zprávy, seznam adresátů či odesilatelů a také zde zjistíte, kolik listů dokument má a počet příloh.</dd>
    </dl>
    <dl>
        <dt>Přiděleno</dt>
        <dd>Tento sloupec zobrazuje jméno pracovníka a organizační jednotku pracovníka, které byl daný dokument přidělen.</dd>
    </dl>
    <dl>
        <dt>Stav</dt>
        <dd>Poslední sloupec je vyhrazen pro určení stavu, v jakém se dokument nachází a od kdy se v něm nachází.</dd>
    </dl>

    <p>
        Pod tlačítkem Seznam dokumentů se neskrývá pouze soupis všech dokumentů, ale naleznete zde i další důležité funkce, kterými jsou Seřadit podle, Akce, Tisk stránky, Generování stránky v PDF, Filtr a Vyhledávání.
    </p>
    
    <br />
    <h3>Tisk stránky</h3>
    <p>
        Pokud si potřebujete vytisknout seznam dokumentu, tak využijte ikony tiskárny, kterou naleznete v pravé horní části obrazovky. Jakmile na ni klepnete, seznam se upraví do verze pro tisk a vy jej můžete vytisknout.
    </p>        

    <br />
    <h3>Vygenerování stránky v PDF</h3>
    <p>
    V případě, že potřebujete elektronickou podobu seznamu dokumentu, můžete stránku vygenerovat do PDF. Stačí jen najet a klepnout na ikonu PDF, která se nachází hned vedle ikony tiskárny.
    </p>
    
    <br />
    <h3>Seřadit podle</h3>
    <p>
    Těsně nad tabulkou se nachází rozbalovací menu s tlačítkem Seřadit. Pomocí této funkce můžete položky v tabulce řadit podle těchto kritérií:
    <ul>
        <li>Stavu dokumentu (vzestupně i sestupně)</li>
        <li>Čísla jednacího (vzestupně i sestupně)</li>
        <li>JID (vzestupně i sestupně)</li>
        <li>Data přijetí/vzniku (vzestupně i sestupně)</li>
        <li>Věci (vzestupně i sestupně)</li>
        <li>Přidělené osoby (vzestupně i sestupně)</li>
    </ul>    
    </p>
    
    <br />
    <h3>Hromadná operace</h3>
    <p>
    Každá položka má u sebe na začátku řádku zaškrtávací box, který souvisí s funkcí hromadné operace, která se nachází v patičce tabulky společně s možnostmi Zaškrtnout vše / Odškrtnout vše.
    <br />
    Celá funkce funguje tak, že zaškrtnete ty položky, u kterých chcete provést jednotnou akci, poté klepnete na rozbalovací menu v patičce tabulky, vyberete jednu z akcí a klepnete na tlačítko Provést.
    </p>

    <br />
    <h3>Filtrování</h3>
    <p>
    Pokud chcete vybrat jeden z možných filtrů, klepněte na šipku směřující dolů a zobrazí se vám rozbalovací menu s jednotlivými názvy filtrů. Filtrovat dokumenty lze podle několika kritérií:
    </p>

    <dl>
        <dt>K převzetí</dt>
        <dd>Zobrazí se dokumenty, které jsou předány vám nebo na vaší organizační jednotku.</dd>
    </dl>
    <dl>
        <dt>Předané</dt>
        <dd>Zobrazí se dokumenty, které jsou ve stavu předání na jiného uživatele či organizační jednotku.</dd>
    </dl>
    <dl>
        <dt>Nové</dt>
        <dd>Zobrazí se dokumenty, které ještě nikdo nezačal vyřizovat.</dd>
    </dl>
    <dl>
        <dt>Vyřizuje se</dt>
        <dd>Zobrazí se dokumenty, které jsou ve stavu vyřizování (některý uživatel na nich pracuje).</dd>
    </dl>
    <dl>
        <dt>Vyřízené</dt>
        <dd>Zobrazí se vyřízené dokumenty.</dd>
    </dl>
    <dl>
        <dt>Všechny</dt>
        <dd>
            Zobrazí se všechny dokumenty, které má uživatel právo vidět. Vedoucí s tímto filtrem 
            uvidí i dokumenty v podřízených organizačních jednotkách.
        </dd>
    </dl>
    <dl>
        <dt>Doporučené</dt>
        <dd>Zobrazí se všechny dokumenty, které mají způsob odeslání poštou doporučeně.</dd>
    </dl>
    <dl>
        <dt>K odeslání</dt>
        <dd>Zobrazí se všechny dokumenty připravené k odeslání.</dd>
    </dl>
    <dl>
        <dt>Odeslané</dt>
        <dd>Zobrazí se všechny dokumenty, které jsou již odeslané.</dd>
    </dl>
    <p>Zaškrtávací pole:</p>
    <dl>
        <dt>Nezobrazovat vyřízené dokumenty</dt>
        <dd>Volba dává smysl prakticky jen pro filtry výpravny. Pokud zvolíte tuto volbu a zároveň filtr "Všechny", zobrazí se nové + vyřizované dokumenty.</dd>
    </dl>
    <dl>
        <dt>Zobrazit jen dokumenty na mé jméno</dt>
        <dd>Omezí výsledky filtrování pouze na vašeho uživatele.</dd>
    </dl>
    <p>Dokumenty, které se už nachází ve spisovně, se zde nezobrazí.</p>

    <br /><br /><br />
    <h3>Vyhledávání</h3>
    <p>
    Poslední funkcí je vyhledávání, to naleznete napravo od filtru. Vyhledávat lze podle věci, popisu, čísla jednacího nebo podle JID. Toto vyhledávání je pouze jednodušší odnoží daleko dokonalejšího vyhledávacího enginu, který se skrývá pod položkou Pokročilé vyhledávání, kde je možné vyhledávat prakticky cokoliv. Pokud chcete cokoliv najít podle výše uvedených kritérií, stačí pouze do textového pole napsat výraz, JID, číslo jednací a klepnout na tlačítko hledat, které se nachází hned vedle textového pole.    
    </p>
