    <h2>Seznam dokumentů</h2>

    <p>
        Seznam dokumentů je primární stránka, která se otevře vždy, když se přihlásíte do systému.
    Pokud tento seznam dokumentů chcete vidět v budoucnu při práci se Spisovou službou,
    stačí kliknout na tlačítko Seznam dokumentů.
    </p>
    <p>
        Jak již napovídá sám název této sekce, tak toto tlačítko v sobě skrývá seznam všech dokumentů
    uložených v systému Spisové služby. Tyto dokumenty jsou rozřazeny do přehledné tabulky a to podle
    jednacího čísla. V této tabulce ale naleznete i jiné informace než je jednací číslo,
    jsou zde i tyto následující informace:

    <dl>
        <dt>Typ dokumentu</dt>
        <dd>Ten je znázorněn ikonou podle toho, jaký typ dokumentu nastavíte.</dd>
    </dl>
    <dl>
        <dt>Přijato</dt>
        <dd>Tento sloupec zobrazuje datum přijetí.</dd>
    </dl>
    <dl>
        <dt>Číslo jednací, JID, Spisová značka</dt>
        <dd>Zde jsou vypsány všechny identifikační údaje dokumentu.</dd>
    </dl>
    <dl>
        <dt>Věc, Adresáti/Odesilatelé, počet listů a příloh</dt>
        <dd>V tomto sloupci naleznete předmět zprávy, seznam adresátů nebo odesilatelů a také zde zjistíte, kolik listů dokument má a také počet příloh.</dd>
    </dl>
    <dl>
        <dt>Přiděleno</dt>
        <dd>Tento sloupec zobrazuje jméno osoby, které byl daný dokument přidělen.</dd>
    </dl>
    <dl>
        <dt>Stav</dt>
        <dd>Poslední sloupec je vyhrazen pro určení stavu, v jakém se dokument nachází.</dd>
    </dl>

    </p>
    <p>
        Pod tlačítkem Seznam dokumentů se neskrývá pouze soupis všech dokumentů, ale naleznete zde i
    dvě důležité funkce, které vám pomohou se naprosto bez problému orientovat i ve velkém množství dokumentů ve Spisové službě.
    Jedná se o funkci filtr a vyhledávání.
    </p>
    <p>
        Filtry naleznete pod položkou Filtr, který se nachází hned pod nadpisem Seznam Dokumentů.
    Pokud chcete vybrat jeden z filtrů, klikněte na šipku směřující dolů a zobrazí se vám rozbalovací menu s jednotlivými názvy filtrů.
    Filtrovat dokumenty lze podle několika kriterií:

    <dl>
        <dt>Dokumenty na mé jméno</dt>
        <dd>Po zvolení této možnosti se vám zobrazí jen ty dokumenty, které jsou vystaveny pro vaši osobu.</dd>
    </dl>
    <dl>
        <dt>Dokumenty, které mi byly přiděleny</dt>
        <dd>Tento filtr vám ukáže jen ty dokumenty, které vám přidělila jiná osoba.</dd>
    </dl>
    <dl>
        <dt>Dokumenty, na kterých jsem kdy pracoval</dt>
        <dd>Jakmile vyberete tuto možnost, zobrazí se vám všechny dokumenty, na kterých jste podílel.</dd>
    </dl>
    <dl>
        <dt>Vlastní dokumenty, které jsem ještě nepředal</dt>
        <dd>Tato možnost vám ukáže vámi vytvořené dokumenty, které jste ještě nikomu nepřidělili.</dd>
    </dl>
    <dl>
        <dt>Dokumenty, které vyřizuji</dt>
        <dd>Po zvolení tohoto filtru se vám zobrazí ty dokumenty, které vyřizujete.</dd>
    </dl>
    <dl>
        <dt>Všechny nové dokumenty, které nebyly ještě předány</dt>
        <dd>Po zvolení této možnosti se vám zobrazí všechny nové dokumenty, které čekají na rozdělení.</dd>
    </dl>
    <dl>
        <dt>Všechny dokumenty, které se vyřizují</dt>
        <dd>Tento filtr má za úkol ukázat vám všechny dokumenty, které se nacházejí ve stavu vyřizování.</dd>
    </dl>
    <dl>
        <dt>Zobrazit všechny dokumenty</dt>
        <dd>Jakmile zvolíte tento filtr, zobrazí se vám všechny dokumenty.</dd>
    </dl>

    </p>
    <p>
        Druhou funkcí je vyhledávání, to naleznete napravo od filtru. Vyhledávat lze podle věci, popisu, čísla jednacího nebo podle JID.
    Toto vyhledávání je pouze jednodušší odnoží daleko dokonalejšího vyhledávacího enginu, který se skrývá
    pod položkou Vyhledat, kde je možné vyhledávat prakticky cokoliv.
    Pokud chcete cokoliv najít podle výše uvedených kritérií, stačí pouze do textového pole
    napsat výraz, JID, číslo jednací a kliknout na tlačítko hledat, které se nachází hned vedle textového pole.
