    <h2>Detail dokumentu</h2>
    
    <p>
    Tato stránka má své submenu, které obsahuje následující položky:

    <dl>
        <dt>Upravit metadata</dt>
        <dd>Pokud si přejete změnit něco z modré sekce detailů dokumentu, jako například Název spisu, Věc, přidat/odebrat přílohu, atd., tak klepněte na tlačítko Upravit metadata.</dd>
    </dl>
    <dl>
        <dt>Upravit vyřízení</dt>
        <dd>
            Pokud si přejete změnit cokoliv v druhé sekci detailů (šedivá), jako např. Spisový znak, Počet listů, přílohy, Způsob vyřízení atd., tak najeďte a klepněte v submenu na Upravit vyřízení.
            <br>
            Tato položka je přístupná až ve stavu vyřizení.
        </dd>
    </dl>
    <dl>
        <dt>Předat dokument</dt>
        <dd>Jakmile na toto tlačítko v submenu klepnete, tak se zobrazí dialogové okno a v něm můžete vyplnit poznámku k předání a poté zvolit organizační jednotku či zaměstnance, na kterého bude dokument převeden.</dd>
    </dl> 
    <dl>
        <dt>Převzít dokument</dt>
        <dd>Byl-li vám předán dokument, tímto tlačítkem potvrdíte přijetí dokumentu.</dd>
    </dl>    
    <dl>
        <dt>Odmítnout převzetí</dt>
        <dd>Byl-li vám předán dokument, ale zjistíte, že vám nepatří, můžete tímto tlačítkem převzetí odmítnout a vrátit zpět původci.</dd>
    </dl> 
    <dl>
        <dt>Zrušit převzetí dokumentu</dt>
        <dd>Pokud jste předali dokument jinam a později se rozhodli předání zrušit, můžete tak učinit tímto tlačítkem</dd>
    </dl> 
    <dl>
        <dt>Označit k vyřízení</dt>
        <dd>Tímto tlačítkem převezmete dokument k vyřízení.</dd>
    </dl> 
    <dl>
        <dt>Vytvořit odpověd</dt>
        <dd>Pokud klepnete na toto tlačítko, budete přesměrování na formulář pro vytvoření nového dokumentu s tím, že formulář bude částečně předvyplněn a bude spojen s dokumentem, u kterého jste klepnuli na tlačítko vytvořit odpověď.</dd>
    </dl>    
    <dl>
        <dt>Odeslat dokument</dt>
        <dd>
        Kliknutím na toto tlačítko, přejdete na obrazovku s možnosti odeslat dokument přiřazeným subjektům.
        <br>Položka je přístupná pouze ve stavu vyřízení.
        </dd>
    </dl>   
    <dl>
        <dt>Označit dokument za vyřízený</dt>
        <dd>
        Na toto tlačítko kliknete, až budete mít všechny náležitosti vyřizování dokončeny. Nebude-li některá položka vyplněna, budete na toto upozorněni.        
        </dd>
    </dl>     
    </p>
    
    
    <br>
    <h3>Základní informace</h3>
    <p>
    <dl>
        <dt>JID</dt>
        <dd>
            Jednoznačné identifikační číslo dokumentu.
            <br>Tato položka je automaticky vyplňována systémem.
        </dd>
    </dl>     
    <dl>
        <dt>Typ dokumentu</dt>
        <dd>Určuje typ dokumentu</dd>
    </dl>     
    <dl>
        <dt>Číslo jednací</dt>
        <dd>
            Číslo jednací dokumentu
            Tuto položku generuje systém. Po uložení dokumentu je k dispozici tlačítko pro vygenerování čísla jednacího.
        </dd>
    </dl>         
    <dl>
        <dt>Název spisu</dt>
        <dd>
            Obsahuje název spisu, ke kterému je dokument připojen.
            <br>Není-li připojen, je možné dokument přiřadit do spisu. Stačí klepnout na odkaz Připojit spis. Pokud na tento nápis klepnete, otevře se nové dialogové okno, kde se zobrazí struktura všech spisů, které jsou v systému vytvořeny. Poté stačí jen klepnout na jednu ze značek a ta bude hned přidělena k vašemu novému dokumentu. Další možnost je vytvořit spis nový, k tomu slouží vrchní část dialogového okna, kde se vyplňuje Typ spisu, Název spisu, Popis a Připojit k. Poté stačí klepnout na tlačítko Vytvořit.
        </dd>
    </dl>         
    <dl>
        <dt>Věc</dt>
        <dd>
            Představuje název dokumentu. 
            <br>Pracovníci podatelny nemají ze své podstaty tuto položku povinnou. Ostatním pracovníkům je však tato položka již povinná.
        </dd>
    </dl>         
    <dl>
        <dt>Popis</dt>
        <dd>Popis rozšiřuje informace o tom, o jaký dokument se jedná.</dd>
    </dl>         
    <dl>
        <dt>Datum doručení/vzniku</dt>
        <dd>Označuje datum a čas, kdy byl dokument doručen nebo vytvořen. Při vytváření je předvyplněno aktuální datum a čas. Tato položka je editovatelná pouze na začátku. V průběhu evidence již nelze tuto hodnotu měnit.</dd>
    </dl>         
    <dl>
        <dt>Číslo jednací odesilatele</dt>
        <dd>Pokud je hodnota dostupná, představuje položka číslo jednací odesilatele, která může identifikovat původ.</dd>
    </dl>         
    <dl>
        <dt>Číslo doporučeného dopisu</dt>
        <dd>Je-li dokument doručen doporučeně, představuje tato položka číslo doporučeného dopisu.</dd>
    </dl>         
    <dl>
        <dt>Spojit s dokumentem</dt>
        <dd>
            Je-li hodnota dostupná, přestavuje informaci o souvisejícím dokumentu, se kterým je tento dokument spojen.
            <br>Pokud chcete dokument spojit s již existujícím dokumentem, stačí klepnout na nápis Spojit s dokumentem. Otevře se vám nové dialogové okno, ve kterém je vyhledávací pole dokumentů. Do něho je nutné zadat alespoň dva znaky z jednacího čísla nebo JID. Poté stačí jen klepnout na odkaz daného dokumentu.
        </dd>
    </dl>         
    <dl>
        <dt>Počet listů</dt>
        <dd>Udává počet listinných listů</dd>
    </dl>         
    <dl>
        <dt>Počet listů příloh</dt>
        <dd>Udává počet listů příloh</dd>
    </dl>         
    <dl>
        <dt>Typ přílohy</dt>
        <dd>Udává druh přílohy</dd>
    </dl>      
    <dl>
        <dt>Identifikátor e-podatelny</dt>
        <dd>Obsahuje informace o zprávě, ze které byl dokument vytvořen</dd>
    </dl>     
    </p>
    
    <br>
<h3>Vyřízení</h3>
<p>
    <dl>
        <dt>Způsob vyřízení</dt>
        <dd>označuje způsob vyřízení dokumentu</dd>
    </dl>    
    <dl>
        <dt>Datum vyřízení</dt>
        <dd>představuje datum vyřízení dokumentu</dd>
    </dl>    
    <dl>
        <dt>Spisový znak</dt>
        <dd>Přestavuje spisový znak včetně názvu věcné skupiny</dd>
    </dl>    
    <dl>
        <dt>Skartační znak</dt>
        <dd>Představuje skartační znak (převzato ze spisového znaku)</dd>
    </dl>    
    <dl>
        <dt>Skartační lhůta</dt>
        <dd>Představuje skartační lhůtu (převzato ze spisového znaku)</dd>
    </dl>    
    <dl>
        <dt>Spouštěcí událost</dt>
        <dd>Představuje způsob spuštění události (převzato ze spisového znaku)</dd>
    </dl>    
    <dl>
        <dt>Počet listů</dt>
        <dd>Udává počet listinných listů</dd>
    </dl>         
    <dl>
        <dt>Počet listů příloh</dt>
        <dd>Udává počet listů příloh</dd>
    </dl>         
    <dl>
        <dt>Typ přílohy</dt>
        <dd>Udává druh přílohy</dd>
    </dl> 
    <dl>
        <dt>Uložení dokumentu</dt>
        <dd>Představuje poznámku k uložení dokumentu</dd>
    </dl>    
    <dl>
        <dt>Poznámka k vyřízení</dt>
        <dd>představuje poznámku k vyřízení dokumentu</dd>
    </dl>    
    </p>


<br>
<h3>Předání</h3>
<p>
    <dl>
        <dt>Vytvořil</dt>
        <dd>obsahuje jméno a organizační jednotku toho, kdo tento dokument vytvořil</dd>
    </dl>   
    <dl>
        <dt>Vytvořil dne</dt>
        <dd>obsahuje datum a čas vytvoření dokumentu</dd>
    </dl>   
    <dl>
        <dt>Přiděleno</dt>
        <dd>obsahuje jméno a organizační jednotku toho, komu je tento dokument přidělen</dd>
    </dl> 
    <dl>
        <dt>Přiděleno dne</dt>
        <dd>obsahuje datum a čas přidělení dokumentu</dd>
    </dl>   
    <dl>
        <dt>Poznámka pro přiděleného</dt>
        <dd>představuje poznámku při přidělení</dd>
    </dl>    
    <dl>
        <dt>Předáno</dt>
        <dd>obsahuje jméno a organizační jednotku toho, komu je tento dokument předán</dd>
    </dl> 
    <dl>
        <dt>Předáno dne</dt>
        <dd>obsahuje datum a čas předání dokumentu</dd>
    </dl>   
    <dl>
        <dt>Poznámka pro předávajícího </dt>
        <dd>představuje poznámku při předání</dd>
    </dl> 
    <dl>
        <dt>Lhůta k vyřízení</dt>
        <dd>představuje počet dní, kdy je potřeba dokument vyřídit.</dd>
    </dl>    
</p>  
    
   <br> 
   <h3>Adresáti / odesílatelé</h3>
   <p>
        V tomto bloku se objevuje seznam všech subjektů, které dokument obsahuje.
    <dl>
        <dt>Připojit subjekt</dt>
        <dd>
            Zde máte na výběr. Buď můžete vyhledat subjekt formou našeptávače, nebo subjekt vyhledat přes odkaz seznam. Formou našeptávače stačí postupně zadat jméno a adresu subjektu a ze seznamu vybrat.
            <br>
            Pokud daný subjekt v databázi neexistuje, je možné tento subjekt vytvořit pomoci tlačítka Vytvořit nový subjekt. Tam stačí vyplnit a klintou na tlačítko.
        </dd>
    </dl>  
    <dl>
        <dt>Obnovit seznam subjektů</dt>
        <dd>Pokud chcete obnovit seznam subjektů, pak klepněte právě na tento nápis ve formuláři. </dd>
    </dl>        
   </p>

   <br> 
   <h3>Přílohy</h3>
    <p>
        V tomto bloku se objevuje seznam všech příloh, které dokument obsahuje. Kliknutím na název je možné přílohu otevřít.
    <dl>
        <dt>Přidat přílohu</dt>
        <dd>Jestliže chcete přidat k dokumentu přílohu, klepněte na položku Přidat přílohu. V sekci Přílohy se vám zobrazí nové položky, kde vyplníte Název přílohy, Popis, vyberete Typ souboru a u položky Soubor klepnete na tlačítko Procházet, kde musíte najít a vybrat soubor, který chcete zvolit jako přílohu. Poté již jen klepnete na tlačítko Upload.</dd>
    </dl>  
    <dl>
        <dt>Obnovit seznam příloh</dt>
        <dd>Pokud chcete obnovit seznam příloh, pak klepněte právě na tento nápis ve formuláři. </dd>
    </dl>     
    </p>

   <br> 
   <h3>Odeslání</h3>
    <p>
        V tomto bloku se objevuje záznam odeslaných dokumentů.
    </p>    
   
   <br> 
   <h3>Historie</h3>    
    <p>
    V detailech dokumentu lze také sledovat historii dokumentu, díky které se dozvíte základní informace o tom, co se s dokumentem dělo od jeho vzniku a po jeho vyřízení.
    <br>
    Pokud chce mít ještě podrobnější přehled, využijte Transakční protokol, do kterého se zapisují i předání a další podrobné informace. Transakční protokol je dělaný formou dialogového okna.
        
    </p>    
    