    <h2>Nový dokument</h2>
    <p>
    Pokud chcete vytvořit nový dokument do Spisové služby, najeďte a klikněte na
    tlačítko Nový dokument. Otevře se vám nová stránka s formulářem, pomocí kterého
    můžete vytvořit nový dokument. Formulář obsahuje následující položky:
    </p>
<dl>
    <dt>JID</dt>
    <dd>Tato položka je automaticky vyplňována systémem.</dd>
    <dt>Číslo jednací</dt><dd>I tato položka je jakousi automatickou řadou, kterou systém vyplňuje sám.</dd>
    <dt>Typ dokumentu</dt><dd>Zde máte po kliknutí na šipku směřující dolů na výběr hned z několika možností. Naleznete zde možnost příchozí, vlastní, odpověď, příchozí – doručeno emailem, příchozí – doručeno datovou schránkou, příchozí – doručeno datovým nosičem, příchozí – doručeno faxem, příchozí – doručeno v listinné podobě.</dd>
    <dt>Spisová značka</dt><dd>Pokud chcete přiřadit k vašemu novému dokumentu spisovou značku, stačí kliknout na tlačítko Připojit spisovou značku. Pokud na tento nápis kliknete, otevře se nové dialogové okno, kde se zobrazí struktura všech spisů, které jsou v systému vytvořeny. Poté stačí jen kliknout na jednu ze značek a ta bude hned přidělena k vašemu novému dokumentu. Další možnost je vytvořit spis nový, k tomu slouží vrchní část dialogového okna, kde se vyplňuje Typ spisu, Spisová značka/název, Popis a Připojit k. Poté stačí kliknout na tlačítko Vytvořit.</dd>
    <dt>Věc</dt><dd>Toto je první povinná položka, kterou musíte vyplnit, aby se povedlo nový dokument vytvořit.</dd>
    <dt>Popis</dt><dd>Popis rozšiřuje informace o tom, o jaký dokument se jedná.</dd>
    <dt>Datum doručení/vzniku</dt><dd>Datum doručení/vzniku se vyplňuje automaticky podle vašeho času a data nastaveného ve vašem systému ve vašem PC.</dd>
    <dt>Číslo jednací odesilatele</dt><dd>Pokud máte číslo jednací odesilatele, tak toto je místo, kde ho můžete vyplnit.</dd>
    <dt>Poznámka</dt><dd>Toto textové pole je určené pro různé poznámky.</dd>
    <dt>Spojit s dokumentem</dt><dd>Pokud chcete nový dokument spojit s již existujícím dokumentem, stačí kliknout na nápis Spojit s dokumentem. Otevře se vám nové dialogové okno, ve kterém je vyhledávací pole dokumentů. Do něho je nutné zadat alespoň dva znaky z jednacího čísla nebo JID. Poté stačí jen kliknout na odkaz daného dokumentu.</dd>
    <dt>Počet listů</dt><dd>Zde se zadává, kolik listů má váš nový dokument.</dd>
    <dt>Počet listů příloh</dt><dd>Zde se zadává, kolik listů mají přílohy vašeho nového dokumentu.</dd>
    <dt>Přiděleno</dt><dd>Tato položka je automaticky vyplněna vaším jménem, které máte zadané v systému Spisové služby.</dd>
    <dt>Lhůta k vyřízení</dt><dd>Lhůta k vyřízení je druhou povinnou položkou, kterou je nutné zadat.</dd>
    <dt>Poznámka</dt><dd>Zde je prostor k vašim poznámkám k předání/vyřízení nového dokumentu.</dd>
    <dt>Připojit subjekt</dt><dd>V sekci Adresáti/Odesilatelé lze z vašeho adresáře přiřadit subjekt do nového dokumentu, stačí abyste najeli a klikli na nápis Připojit subjekt a v dialogovém okně buď zvolili možnost Nový subjekt nebo abyste vybrali jeden z již existujících subjektů a klikli u něj na položku adresát, odesilatel nebo adresát i odesilatel.</dd>
    <dt>Obnovit seznam subjektů</dt><dd>Pokud chcete obnovit seznam subjektů, stačí kliknout právě na tento nápis ve formuláři.</dd>
    <dt>Přidat přílohu</dt><dd>Jestliže chcete přidat k novému dokumentu přílohu, klikněte na položku Přidat přílohu. Otevře se vám nové dialogové okno, kde vyplníte Název přílohy, Popis, Typ souboru a u položky Soubor kliknete na tlačítko procházet, kde musíte najít a vybrat soubor, který chcete vybrat jako přílohu. Poté již jen kliknete na tlačítko Upload.</dd>
    <dt>Obnovit seznam příloh</dt><dd>Pokud chcete obnovit seznam příloh, pak klikněte právě na tento nápis ve formuláři.</dd>
</dl>
<p>
Jakmile máte vše potřebné vyplněno, stačí jen kliknout na tlačítko Vytvořit a
v tu chvíli se do systému zařadí vámi vytvořený dokument. Pakliže jste si vytvoření
nového dokumentu rozmysleli, klikněte na tlačítko Zrušit a všechny zadané údaje budou
vymazány.
</p>




