    <h2>Nový dokument</h2>
    <p>
    Pokud chcete vytvořit nový dokument do Spisové služby, najeďte a klikněte na
    tlačítko Nový dokument. Otevře se vám nová stránka s formulářem, pomocí kterého
    můžete vytvořit nový dokument. Formulář obsahuje následující položky:
    </p>
    
    <br />
    <h3>Základní informace</h3>
    <p>
    <dl>
        <dt>JID</dt>
        <dd>
            Jednoznačné identifikační číslo dokumentu.
            <br />Tato položka je automaticky vyplňována systémem.
        </dd>
    </dl>     
    <dl>
        <dt>Typ dokumentu</dt>
        <dd>Určuje typ dokumentu</dd>
    </dl>     
    <dl>
        <dt>Číslo jednací</dt>
        <dd>
            Číslo jednací dokumentu
            Tuto položku generuje systém. Po uložení dokumentu je k dispozici tlačítko pro vygenerování čísla jednacího.
        </dd>
    </dl>         
    <dl>
        <dt>Věc</dt>
        <dd>
            Představuje název dokumentu. 
            <br />Pracovníci podatelny nemají ze své podstaty tuto položku povinnou. Ostatním pracovníkům je však tato položka již povinná.
        </dd>
    </dl>         
    <dl>
        <dt>Popis</dt>
        <dd>Popis rozšiřuje informace o tom, o jaký dokument se jedná.</dd>
    </dl>         
    <dl>
        <dt>Datum doručení/vzniku</dt>
        <dd>Označuje datum a čas, kdy byl dokument doručen nebo vytvořen. Při vytváření je předvyplněno aktuální datum a čas. Tato položka je editovatelná pouze na začátku. V průběhu evidence již nelze tuto hodnotu měnit.</dd>
    </dl>         
    <dl>
        <dt>Číslo jednací odesilatele</dt>
        <dd>Pokud je hodnota dostupná, představuje položka číslo jednací odesilatele, která může identifikovat původ.</dd>
    </dl>         
    <dl>
        <dt>Číslo doporučeného dopisu</dt>
        <dd>Je-li dokument doručen doporučeně, představuje tato položka číslo doporučeného dopisu.</dd>
    </dl>         
    <dl>
        <dt>Počet listů</dt>
        <dd>Počet listů, jde-li o dokument v listinné podobě</dd>
    </dl>         
    <dl>
        <dt>Počet listů příloh</dt>
        <dd>Počet listů nebo počet svazků příloh v listinné podobě</dd>
    </dl>         
    <dl>
        <dt>Počet a druh příloh v nelistinné podobě</dt>
        <dd></dd>
    </dl>      
    <dl>
        <dt>Lhůta k vyřízení</dt>
        <dd>Počet dní, dokdy je potřeba dokument vyřídit.</dd>
    </dl>   
    </p>

<br />
<h3>Předání</h3>
<p>
    <dl>
        <dt>Poznámka pro příjemce</dt>
        <dd></dd>
    </dl>    
    <dl>
        <dt>Předat</dt>
        <dd>Formou našeptávače můžete zvolit osobu nebo organizační jednotku, které bude dokument předán. Nebo můžete zvolit ze seznamu.</dd>
    </dl> 
 
</p>  
    
   <br /> 
   <h3>Adresáti / odesílatelé</h3>
   <p>
        V tomto bloku se objevuje seznam všech subjektů, které dokument obsahuje.
    <dl>
        <dt>Připojit subjekt</dt>
        <dd>
            Zde máte na výběr. Buď můžete vyhledat subjekt formou našeptávače, nebo subjekt vyhledat přes odkaz seznam. Formou našeptávače stačí postupně zadat jméno a adresu subjektu a ze seznamu vybrat.
            <br />
            Pokud daný subjekt v databázi neexistuje, je možné tento subjekt vytvořit pomoci tlačítka Vytvořit nový subjekt. Tam stačí vyplnit a klintou na tlačítko.
        </dd>
    </dl>  
    <dl>
        <dt>Obnovit seznam subjektů</dt>
        <dd>Pokud chcete obnovit seznam subjektů, pak klepněte právě na tento nápis ve formuláři. </dd>
    </dl>        
   </p>

   <br /> 
   <h3>Přílohy</h3>
    <p>
        V tomto bloku se objevuje seznam všech příloh, které dokument obsahuje. Kliknutím na název je možné přílohu otevřít.
    <dl>
        <dt>Přidat přílohu</dt>
        <dd>Jestliže chcete přidat k dokumentu přílohu, klepněte na položku Přidat přílohu. V sekci Přílohy se vám zobrazí nové položky, kde vyplníte Název přílohy, Popis, vyberete Typ souboru a u položky Soubor klepnete na tlačítko Procházet, kde musíte najít a vybrat soubor, který chcete zvolit jako přílohu. Poté již jen klepnete na tlačítko Upload.</dd>
    </dl>  
    </p>

    <p>
Jakmile máte vše potřebné vyplněno, stačí jen kliknout na tlačítko Vytvořit a
v tu chvíli se do systému zařadí vámi vytvořený dokument. Pakliže jste si vytvoření
nového dokumentu rozmysleli, klikněte na tlačítko Zrušit a všechny zadané údaje budou
vymazány.
</p>
