    <h2>Odeslat dokument</h2>
    
    <p>
Na této stránce získáte přehled o tom, komu bude soubor odeslán, jaké jsou přílohy tohoto dokumentu a také jaký je způsob odeslání. K tomu slouží rozbalovací menu, které naleznete pod adresáty, a tam může zvolit následující možnosti odeslání:
    </p>
    
    <dl>
        <dt>Neodesílat</dt>
        <dd>U tohoto adresáta nebude aplikováno žádné odesílání</dd>
    </dl>  
    <dl>
        <dt>Odeslat emailem</dt>
        <dd>Poté, co vyberete tuto možnost, zobrazí se vám doplňující pole, kterými jsou Předmět zprávy a Text zprávy. Některé z těchto položek jsou součástí tvorby, tudíž pokud je máte vyplněné, tak se vám automaticky vyplní i zde.</dd>
    </dl>  
    <dl>
        <dt>Odeslat datovou schránkou</dt>
        <dd>V případě, že zvolíte tuto možnost, tak se vám zobrazí doplňující pole – Předmět zprávy, Číslo jednací odesilatele, Spisová značka odesilatele, Číslo jednací adresáta, Spisová značka adresáta a zaškrtávací boxy Do vlastních rukou? a Doručit fikcí?. Některé z těchto položek jsou součástí tvorby, tudíž pokud je máte vyplněné, tak se vám automaticky vyplní i zde.</dd>
    </dl>  
    <dl>
        <dt>Odeslat poštou</dt>
        <dd>Jakmile zvolíte tuto možnost, zobrazí se vám následující doplňující pole – Datum odeslání, Druh zásilky, Cena Kč a Hmotnost.</dd>
    </dl>  
    <dl>
        <dt>Odeslat faxem</dt>
        <dd>Poté, co zvolíte tuto možnost, zobrazí se vám tyto položky – Datum odeslání, Číslo faxu a Zpráva pro příjemce.</dd>
    </dl>      
    
    <p>
Jakmile máte vše zkontrolováno a správně zadáno, můžete klepnout na tlačítko Předat podatelně či Odeslat.
</p>

    
