    {if count($seznamSubjektu)>0}
    <table class="seznam">
        {foreach $seznamSubjektu as $subjekt}
        <tr>
            <td class="icon">
                <img id="subjekt_ikona_{$subjekt->id}" src="{$baseUri}images/icons/subjekt_{$subjekt->rezim_subjektu|lower}.png" alt="{$subjekt->rezim_subjektu}" title="{$subjekt->rezim_subjektu}" width="32" height="32" />
            </td>
            <td class="meta">
                <strong>{=Subjekt::displayName($subjekt,'jmeno_item')}</strong>
                <div class="info">
                <span>{$subjekt->type} - {=Subjekt::typ_subjektu($subjekt->type)}</span>
                <br />
                <span>
                    {if $subjekt->rezim_subjektu == 'O'}
                    odesílatel
                    {elseif $subjekt->rezim_subjektu == 'A'}
                    adresát
                    {elseif $subjekt->rezim_subjektu == 'AO'}
                    odesílatel i adresát
                    {else}
                    nespecifikováno
                    {/if}
                </span>

                <br />
                {=Subjekt::displayName($subjekt,'adresa')}
                </div>
                <div class="vyber">
                    <a href="{link :Spisovka:Subjekty:odebrat, 'id'=>$subjekt->id, 'dok_id'=>$dokument_id }" onclick="return odebratSubjekt(this, {!$dokument_id});">odebrat</a>&nbsp;&nbsp;
                    <a href="{link :Spisovka:Subjekty:upravit, 'id'=>$subjekt->id, 'dok_id'=>$dokument_id }" onclick="return subjektzmenit(this);">změnit</a>&nbsp;&nbsp;
                </div>
            </td>
            <td class="meta_plus">
                &nbsp;
                <div class="info">
                <dl>
                    <dt>email:</dt>
                    <dd>{$subjekt->email}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>telefon:</dt>
                    <dd>{$subjekt->telefon}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>isds:</dt>
                    <dd>{$subjekt->id_isds}&nbsp;</dd>
                </dl>

                </div>
            </td>
        </tr>
        {/foreach}
    </table>
    {else}
    <div class="prazdno">Nebyly zjištěny žádné subjekty.</div>
    {/if}
    