    <h2>Nový subjekt</h2>

    <div class="detail_blok">
        <div class="detail_hlavicka">Info</div>
        {$novyForm->render('begin')}
        <dl class="detail_item">
            <dt>{$novyForm['type']->label}</dt>
            <dd>{$novyForm['type']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>{$novyForm['nazev_subjektu']->label}</dt>
            <dd>{$novyForm['nazev_subjektu']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['ic']->label}</dt>
            <dd>{$novyForm['ic']->control} <a href="#" onclick="return aresSubjekt('novyForm');">Vyhledat pomoci systému ARES</a></dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['dic']->label}</dt>
            <dd>{$novyForm['dic']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>{$novyForm['titul_pred']->label}</dt>
            <dd>{$novyForm['titul_pred']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['jmeno']->label}</dt>
            <dd>{$novyForm['jmeno']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['prostredni_jmeno']->label}</dt>
            <dd>{$novyForm['prostredni_jmeno']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['prijmeni']->label}</dt>
            <dd>{$novyForm['prijmeni']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['titul_za']->label}</dt>
            <dd>{$novyForm['titul_za']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['rodne_jmeno']->label}</dt>
            <dd>{$novyForm['rodne_jmeno']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>{$novyForm['datum_narozeni']->label}</dt>
            <dd>{$novyForm['datum_narozeni']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['misto_narozeni']->label}</dt>
            <dd>{$novyForm['misto_narozeni']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['okres_narozeni']->label}</dt>
            <dd>{$novyForm['okres_narozeni']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['stat_narozeni']->label}</dt>
            <dd>{$novyForm['stat_narozeni']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>{$novyForm['adresa_ulice']->label}</dt>
            <dd>
                {$novyForm['adresa_ulice']->control}
                č.p. {$novyForm['adresa_cp']->control}
                č.o. {$novyForm['adresa_co']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>PSČ a město</dt>
            <dd>
                {$novyForm['adresa_psc']->control}
                {$novyForm['adresa_mesto']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['adresa_stat']->label}</dt>
            <dd>{$novyForm['adresa_stat']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>{$novyForm['email']->label}</dt>
            <dd>{$novyForm['email']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['telefon']->label}</dt>
            <dd>{$novyForm['telefon']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$novyForm['id_isds']->label}</dt>
            <dd>{$novyForm['id_isds']->control} <a href="#" onclick="return isdsSubjekt('novyForm');">Vyhledat pomoci systému ISDS</a></dd>
        </dl>

        <dl class="detail_item">
            <dt>{$novyForm['poznamka']->label}</dt>
            <dd>{$novyForm['poznamka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>&nbsp;</dt>
            <dd>{$novyForm['novy']->control} {$novyForm['storno']->control}</dd>
        </dl>


        {$novyForm->render('end')}
    </div>
