    <h2>Nastavení</h2>
    <p>
        Nejprve se podíváme na sekci Nastavení. V ní lze změnit obecné informace o organizaci a také nastavení Masky čísla jednacího.
        Jestliže chcete měnit informace o organizaci stačí najet na nápis Upravit.
        Poté můžete měnit následující informace:
    </p>
    <dl>
        <dt>Název</dt><dd>Tato položka je povinnou.</dd>
        <dt>Plný název</dt><dd>Oficiální název organizace.</dd>
        <dt>Zkratka</dt><dd>Tato položka je povinnou.</dd>
        <dt>Ulice</dt>
        <dt>Město</dt>
        <dt>PSČ</dt>
        <dt>Stát</dt>
        <dt>IČ</dt>
        <dt>DIČ</dt>
        <dt>Telefon</dt>
        <dt>Email</dt>
        <dt>URL</dt><dd>Adresa vašich oficiálních stránek.</dd>
    </dl>
<p>
Jakmile máte vše vyplněné najeďte a klikněte na tlačítko Uložit.
Pokud se rozhodnete, že nechcete provádět žádné úpravy klikněte na tlačítko Zrušit.
Pokud chcete změnit masku čísla jednacího stačí jen najet na nápis Upravit pod odstavcem Čísla jednacího. Jakmile na tento nápis kliknete může zadat jedinou položku a tou je Maska. Ta se může skládat do z několika masek, které máte vypsané v tabulce pod textovým polem Maska. Tabulka zobrazuje jak označení masky, tak ukázku a také popis, který popisuje danou masku.
Jakmile máte masku čísla jednacího vytvořenou stačí kliknout na tlačítko Uložit.
V případě, že jste si úpravu masky čísla jednacího rozmysleli, klikněte na tlačítko Zrušit.
</p>