    <h2>Nastavení</h2>
    <p>
        První položkou na liště menu je sekce Nastavení. V ní lze změnit obecné informace o organizaci a také nastavení Masky čísla jednacího.
        <br>Jestliže chcete měnit informace o organizaci, stačí najet na nápis Upravit.
        <br>Poté můžete měnit následující informace:

    </p>
    <dl>
        <dt>Název</dt><dd>Tato položka je povinnou.</dd>
        <dt>Plný název</dt><dd>Oficiální název organizace.</dd>
        <dt>Zkratka</dt><dd>Tato položka je povinnou.</dd>
        <dt>Ulice</dt>
        <dt>Město</dt>
        <dt>PSČ</dt>
        <dt>Stát</dt><dd>V rozbalovacím menu je na výběr Česká republika a Slovenská republika</dd>
        <dt>IČ</dt>
        <dt>DIČ</dt>
        <dt>Telefon</dt>
        <dt>Email</dt>
        <dt>URL</dt><dd>Adresa vašich oficiálních stránek.</dd>
    </dl>
<p>
Jakmile máte vše vyplněné, najeďte a klepněte na tlačítko Uložit.
V případě, že se rozhodnete, že nechcete provádět žádné úpravy, klepněte na tlačítko Zrušit.
</p>

<br>
<h3>Změna čísla jednacího</h3>
<p>
Pokud chcete změnit masku čísla jednacího, stačí jen najet na nápis Upravit pod odstavcem Čísla jednacího. Jakmile na tento nápis klepnete, můžete zadat jedinou položku a tou je Maska. Ta se může skládat z několika masek, které máte vypsané v tabulce pod textovým polem Maska. Tabulka zobrazuje jak označení masky, tak ukázku a také popis, který popisuje danou masku.
<br>Jakmile máte masku čísla jednacího vytvořenou, stačí klepnout na tlačítko Uložit.
<br>V případě, že jste si úpravu masky čísla jednacího rozmysleli, klepněte na tlačítko Zrušit.
</p>
<h3>Ostatní nastavení</h3>
    <dl>
        <dt>Vynutit protokol HTTPS</dt>
        <dd>Pokud je zapnuto, aplikace automaticky provede přesměrování na protokol HTTPS. Přes HTTP nebude aplikace přístupná.<br />
        Z bezpečnostních důvodů doporučujeme zapnout, pokud má server spisovky nainstalován platný certifikát.</dd>
        <dt>Povolit předání vyřízeného dokumentu</dt><dd>Ve vyjímečných případech je možné povolit předávání vyřízených dokumentů. To umožní, aby konečný vlastník dokumentu byl jiný, než pracovník, který dokument vyřídil.<br />
        Možnost dává smysl jen pro organizace, které se rozhodnou nepoužívat spisovnu, jelikož po převzetí dokumentu se stává vlastníkem spisovna.
        </dd>
        <dt>Odeslání Českou poštou</dt>
        <dd>Tato nastavení se použijí při tisku poštovního podacího archu.</dd>
        
    </dl>
