{*
 * @version    $Id: template.phtml 2 2009-07-13 20:58:52Z david@grudl.com $
 * @param Paginator $paginator
 * @param array     $steps
 *}

<div class="paginator">
        <div class="paginator_info">Zobrazeno {$paginator->getLength()} z {$paginator->getItemCount()} záznamů.</div>
{if $paginator->pageCount > -1}
    {if $paginator->isFirst()}
        <span class="button">první</span>
        <span class="button">předchozí</span>
    {else}
    <a href="{link this, 'page' => $paginator->getFirstPage()}" {!$onclick}>první</a>
        {if ($paginator->page - 1)==1}
        <a href="{link this, 'page' => $paginator->page - 1}" {!$onclick}>předchozí</a>
        {else}
        <a href="{link this, 'page' => $paginator->page - 1}" {!$onclick}>předchozí</a>
        {/if}
    {/if}

    {foreach $steps as $step}
    {if $step == $paginator->page}
        <span class="current">{$step}</span>
    {elseif $step==1}
        <a href="{link this, 'page' => $step}" {!$onclick}>{$step}</a>
        {else}
        <a href="{link this, 'page' => $step}" {!$onclick}>{$step}</a>
    {/if}
    {if $iterator->nextValue > $step + 1}<span>…</span>{/if}
    {/foreach}

    {if $paginator->isLast()}
    <span class="button">další</span>
        <span class="button">poslední</span>
    {else}
    <a href="{link this, 'page' => $paginator->page + 1}" {!$onclick}>další</a>
        <a href="{link this, 'page' => $paginator->getLastPage()}" {!$onclick}>poslední</a>
    {/if}


{/if}
</div>