    <h2>Vyhledat dokumenty</h2>
    <p>
    <div>Vyhledávání dokumentů lze provádět buď přes stránku Seznam dokumentů a</div>
    <div>nebo můžete použít daleko variabilnější vyhledávání přes tlačítko Vyhledat.</div>
    <div>Hledání je možné podle následujících kritérií:</div>

    <dl>
        <dt>Dokument</dt>
        <dd>Typu dokumentu</dd>
        <dd>Stavu dokumentu</dd>
        <dd>Jednacího čísla</dd>
        <dd>Spisové značky</dd>
        <dd>Věci</dd>
        <dd>Popisu</dd>
        <dd>Data doručení/vzniku</dd>
        <dd>Jednacího čísla odesilatele</dd>
        <dd>Poznámky</dd>
        <dd>Počtu listů</dd>
        <dd>Počtu listů příloh</dd>
        <dd>Způsobu vyřízení</dd>
        <dd>Data vyřízení</dd>
        <dd>Data odeslání</dd>
        <dd>Spisového znaku</dd>
        <dd>Skartačního znaku</dd>
        <dd>Skartační lhůty</dd>
        <dd>Spouštěcí události</dd>
        <dd>Počtu listů</dd>
        <dd>Počtu listů příloh</dd>
        <dd>Uložení dokumentu</dd>
        <dd>Poznámky k vyřízení</dd>
        <dd>Zaměstnanci</dd>
        <dt>Přidělení</dt>
        <dt>Předání</dt>
        <dt>Organizační jednotka</dt>
        <dd>Přidělení</dd>
        <dd>Předání</dd>
        <dt>Adresáti/odesílatelé</dt>
        <dd>Typu subjektu</dd>
        <dd>Názvu subjektu</dd>
        <dd>IČ</dd>
        <dd>Ulice, č.p., č.o.</dd>
        <dd>PSČ a města</dd>
        <dd>Státu</dd>
        <dd>Emailu</dd>
        <dd>Telefonu</dd>
        <dd>ID datové schránky</dd>
    </dl>
    <p>
    <div>Jakmile zadáte ta kritéria, podle kterých chcete vyhledat dokumenty, tak</div>
    <div>klikněte na tlačítko vyhledat.</div>
 