    <h2>Vyhledat dokumenty</h2>
    <p>
    <div>Vyhledávání dokumentů lze provádět přes stránku Seznam dokumentů volbou pokročilé vyhledávání</div>
    <div>Hledání je možné podle následujících kritérií:</div>

    <dl>
        <dd>Typu dokumentu</dd>
        <dd>Jednacího čísla</dd>
        <dd>Názvu spisu</dd>
        <dd>Věci</dd>
        <dd>Popisu</dd>
        <dd>Způsobu doručení přes epodatelnu</dd>
        <dd>Způsobu doručení</dd>
        <dd>Data doručení/vzniku</dd>
        <dd>Jednacího čísla odesilatele</dd>
        <dd>Čísla doporučeného dopisu</dd>
        <dd>Poznámky</dd>
        <dd>Způsobu vyřízení</dd>
        <dd>Data vyřízení</dd>
        <dd>Způsobu odeslání</dd>
        <dd>Data odeslání</dd>
        <dd>Druhu odeslání</dd>
        <dd>Spisového znaku</dd>
        <dd>Skartačního znaku</dd>
        <dd>Skartační lhůty</dd>
        <dd>Spouštěcí události</dd>
        <dd>Poznámky k vyřízení</dd>
        <dd>Přidělení</dd>
        <dd>Předání</dd>
        <dd>Organizační jednotka</dd>
        <dd>Přidělení</dd>
        <dd>Předání</dd>
        <dd>Typu subjektu</dd>
        <dd>Názvu subjektu</dd>
        <dd>IČ</dd>
        <dd>Ulice, č.p., č.o.</dd>
        <dd>PSČ a města</dd>
        <dd>Státu</dd>
        <dd>Emailu</dd>
        <dd>Telefonu</dd>
        <dd>ID datové schránky</dd>
    </dl>
    <p>
    <div>Jakmile zadáte ta kritéria, podle kterých chcete vyhledat dokumenty, tak</div>
    <div>klikněte na tlačítko vyhledat.</div>
 