    <h2>Detail spisu</h2>
    <p>
Pokud si chcete prohlédnout detaily spisu, stačí na něj najet a klepnout na název spisu v menu Spisy, který si chcete prohlédnout. Jakmile tak učiníte, zobrazí se vám stránka s detaily spisu.
</p><p>
    Informace o spisu obsahují všechny položky, které se zadávají při tvorbě nového spisu, plus zde vidíte stav a vedle něj také možnost Uzavřít spis. Pod touto položkou se ještě nachází odkaz Upravit, pomocí kterého lze informace o spisu upravovat.
    </p>