    <h2>Detail spisu</h2>
    <p>
        Pokud kliknete na tlačítko Nové zprávy, zobrazí se vám tabulka přijatých zpráv,
        která je řazená podle ID a obsahuje pouze zprávy se stavem nový přijatý. Položky
        ID a Věc jsou navzájem propojené a pokud na jednu z těchto položek kliknete, zobrazí
        se vám detaily dané zprávy. Když si takto jednu zprávu otevřete, máte kromě informací
        o Identifikátoru DZ v E-podatelně, typu zprávy, schránce, věci, odesilateli, ověření,
        doručení, přijetí do E-podatelny, obsahu zprávy a příloh možnost zvolit jednu z variant.
        Buď můžete zprávu zaevidovat do spisové služby, nebo můžete zprávu zaevidovat v jiné
        evidenci anebo je pro vás určená třetí možnost, kterou je odmítnutí zprávy.
    </p>