    <h2>Nový spis / věcná skupina</h2>
    <p>
        Pokud chcete vytvořit spis nebo věcnou skupinu, klikněte na tlačítko Spisy,
        které naleznete na liště menu. Jakmile na toto tlačítko kliknete, zobrazí se
        vám soupis jednotlivých spisů a věcných skupin, který již známe ze spisové
        služby. Zde však navíc máte možnost ne jen editovat již existující spisy,
        ale vy je zde můžete i tvořit. Stačí kliknout na nápis Nový spis/věcná
        skupina. Jakmile na tento nápis kliknete, otevře se vám nová obrazovka, kde
        můžete zadat následující informace:
    </p>
    <dl>
        <dt>Typ spisu</dt><dd>Zde máte na výběr jednu ze dvou možností, buď možnost vytvořit spis nebo věcnou skupinu.</dd>
        <dt>Spisová značka/název</dt><dd>Tato položka je povinná.</dd>
        <dt>Popis</dt>
        <dt>Připojit k</dt><dd>V v rozbalovacím menu zde naleznete vypsány všechny spisy a věcné skupiny, ke kterým lze nový spis/věcnou skupinu připojit.</dd>
        <dt>Spisový znak</dt><dd>Podle toho, jaký spisový znak vyberete, se vám vyplní i následující položky (skartační znak, skartační lhůta a spouštěcí událost).</dd>
    </dl>
    <p>
        Poté již stačí najet a kliknout na tlačítko Vytvořit. Pokud jste si tvorbu
        spisu či věcné skupiny rozmysleli, klikněte jen na tlačítko Zrušit.
    </p>