    <h2>Spisy</h2>
    <p>
        Pokud chcete zkontrolovat, zda nejsou ve schránce nějaké nové zprávy, stačí jen
        kliknout na tlačítko Zkontrolovat schránku. Systém sám provede připojení k ISDS
        schránce stejně jako k emailové schránce a zjistí, zda nejsou ve schránkách nové
        zprávy. Pokud ano, tak se vám nové zprávy zobrazí na předních místech tabulky
        přijatých zpráv. V případě, že schránky neobsahují žádné nové zprávy, tak systém
        vás o tom bude informovat prostřednictvím informačních titulků nad tabulkou přijatých
        zpráv.
    </p>