    <h2>Seznam spisů</h2>
<p>
Po klepnutí na tlačítko Spisy se vám zobrazí seznam všech spisů, které jsou vytvořeny. Jednotlivé spisy lze rozklepnout a podívat se na bližší informace o spisu.
</p>

<br>
<h3>Nový spis</h3>
<p>
V horní části okna naleznete odkaz Nový spis, pomocí kterého lze nový spis vytvořit. Jakmile na tento odkaz klepnete, tak jste přesměrováni na stránku s formulářem k tvorbě nového spisu
</p>

<br>
<h3>Hledat</h3>
<p>
Další funkcí, kterou v sekci Spisy můžete využít, je funkce hledat, která je zde dostupná pouze v jednoduché formě. Tudíž stačí do textového pole napsat název nebo část názvu spisu a poté klepnout na tlačítko hledat.
</p>

