@{block title}Detail zprávy{/block}
@{block debug}
<?php echo "Zprava: "; print_r($Zprava); ?>
<?php echo "Prilohy: "; print_r($Prilohy); ?>
<?php echo "Original: "; print_r($Original); ?>
@{/block}
@{block content}

    <div class="navigate">
    <a href="{link :Epodatelna:Default:default}">Seznam příchozích zpráv</a> - Detail zprávy
    </div>

    <div id="dokument_blok_volby">
       {if $Zprava->stav >=10}
       {$Zprava->stav_info}
       {else}
       <a href="{link :Epodatelna:Evidence:novy, 'id'=>$Zprava->id}">Zaevidovat do spisové služby</a>
       <a href="{link :Epodatelna:Evidence:jiny, 'id'=>$Zprava->id}" id="dialog-evidence">Zaevidovat v jiné evidenci</a>
       <a href="{link :Epodatelna:Evidence:odmitnout, 'id'=>$Zprava->id }" id="dialog-odmitnout">Odmítnout</a>
       <!--<a href="{link :Epodatelna:Evidence:odpoved, 'id'=>$Zprava->id }">Odpovědět</a>-->
       {/if}
    </div>


    <div id="dokument_blok_hlavni">
        <dl class="detail_item">
            <dt>Identifikátor DZ v e-podatelně:</dt>
            <dd>OSS-EP-I-{$Zprava->poradi}-{$Zprava->rok}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Typ zprávy:</dt>
            <dd>
            {if !empty($Zprava->email_signature) }
                Emailová zpráva
            {elseif !empty($Zprava->isds_signature) }
                Datová zpráva z ISDS
            {else}
                Typ nezjištěn
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Schránka:</dt>
            <dd>{$Zprava->adresat}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd class="nadpis"><u>{$Zprava->predmet}</u>&nbsp;</dd>
        </dl>

        <dl class="detail_item">
            <dt>Odesílatel:</dt>
            <dd>{$Zprava->odesilatel}&nbsp;</dd>
        </dl>
        {if !empty($Zprava->email_signature) }
        <dl class="detail_item">
            <dt>Ověření:</dt>
            <dd>
            {if isset($Original['signature'])}
                {if $Original['signature']['signed'] == 1 }
                <span style="color:#009900;">{$Original['signature']['status']}</span>
                <br /><br />
                {if isset($Original['signature']['cert_info']['organizace'])}{$Original['signature']['cert_info']['organizace']}<br />{/if}
                {if isset($Original['signature']['cert_info']['jmeno'])}{$Original['signature']['cert_info']['jmeno']}<br />{/if}
                {$Original['signature']['cert_info']['email']}<br />
                {if isset($Original['signature']['cert_info']['adresa'])}{$Original['signature']['cert_info']['adresa']}<br />{/if}
                Platnost: {=date('j.n.Y',$Original['signature']['cert_info']['platnost_od'])} - {=date('j.n.Y',$Original['signature']['cert_info']['platnost_do'])}<br />
                CA: {$Original['signature']['cert_info']['CA']}
                {elseif $Original['signature']['signed'] == -1}
                <span style="color:#990000;">{$Original['signature']['status']}</span>
                {else}
                <span style="color:#684A03;">{$Original['signature']['status']}</span>
                {/if}
            {else}
                <span style="color:#990000;">Nepodařilo se zjístit důvěryhodnost zprávy</span>
            {/if}
            </dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Doručeno:</dt>
            <dd>{$Zprava->doruceno_dne|edatetime}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Přijato epodatelnou:</dt>
            <dd>{$Zprava->prijato_dne|edatetime}&nbsp;</dd>
        </dl>
    </div>

    <div id="dokument_blok_poznamka">
        <div class="h2">Obsah zprávy</div>
        <pre>{!$Zprava->popis}</pre>
    </div>

    <div id="dokument_blok_prilohy">
    <div class="h2">
        Přílohy
    </div>
    <div id="dok-prilohy">
    {if count($Prilohy)>0}
    <table class="seznam">
        {foreach $Prilohy as $priloha}
        <tr>
            <td class="icon">
                <img src="{$baseUri}images/mimetypes/{$priloha['mimetype']|webalize}.png" alt="{$priloha['mimetype']}" title="{$priloha['mimetype']}" width="32" height="32" />
            </td>
            <td class="meta">
                <a href="{link :Epodatelna:Prilohy:download, 'id'=>$Zprava->id, 'file'=>$priloha['id']}">{$priloha['name']}</a>
                <div class="info">
                <span>{$priloha['size']|bytes}, {$priloha['mimetype']}</span>
                </div>
            </td>
        </tr>
        {/foreach}
    </table>
    {else}
        <div class="prazdno">Zpráva neobsahuje žádné přílohy.</div>
    {/if}
    </div>
    </div>
    <div id="dialog"></div>