<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link rel="shortcut icon" href="{$baseUri}favicon.ico" type="image/x-icon" />
    <title>Spisová služba</title>
    <style type="text/css" media="screen, print">
        <?php echo file_get_contents(APP_DIR .'/../public/css/printdetail_site.css'); ?>
    </style>
</head>
<body>
<div id="content">
    <div id="dokument_blok_hlavni">
        <dl class="detail_item">
            <dt>Pořadí DZ v e-podatelně:</dt>
            <dd>OSS-EP-O-{$Zprava->poradi}-{$Zprava->rok}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Typ zprávy:</dt>
            <dd>
            {if !empty($Zprava->email_signature) }
                Emailová zpráva
            {elseif !empty($Zprava->isds_signature) }
                Datová zpráva z ISDS
            {else}
                Typ nezjištěn
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Schránka:</dt>
            <dd>{$Zprava->adresat}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd class="nadpis"><u>{$Zprava->predmet}</u>&nbsp;</dd>
        </dl>

        <dl class="detail_item">
            <dt>Adresát:</dt>
            <dd>{$Zprava->odesilatel}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Odesláno:</dt>
            <dd>{$Zprava->doruceno_dne|edatetime}&nbsp;</dd>
        </dl>
    </div>

    <div id="dokument_blok_poznamka">
        <div class="h2">Obsah zprávy</div>
        <pre>{!$Zprava->popis}</pre>
    </div>

    <div id="dokument_blok_prilohy">
    <div class="h2">
        Přílohy
    </div>
    <div id="dok-prilohy">
    {if count($Prilohy)>0}
    <table class="seznam">
        {foreach $Prilohy as $priloha}
        <tr>
            <td class="icon">
                {if file_exists(APP_DIR ."/../public/images/mimetypes/". String::webalize($priloha['mimetype']) .".png")}
                <img src="{$baseUri}images/mimetypes/{$priloha['mimetype']|webalize}.png" alt="{$priloha['mimetype']}" title="{$priloha['mimetype']}" width="32" height="32" />
                {else}
                <img src="{$baseUri}images/mimetypes/application-octet-stream.png" alt="{$priloha['mimetype']}" title="{$priloha['mimetype']}" width="32" height="32" />
                {/if}   
            </td>
            <td class="meta">
                <strong>{$priloha['name']}</strong>
                <div class="info">
                <span>{$priloha['size']|bytes}, {$priloha['mimetype']}</span>
                </div>
            </td>
        </tr>
        {/foreach}
    </table>
    {else}
        <div class="prazdno">Zpráva neobsahuje žádné přílohy.</div>
    {/if}
    </div>
    </div>
    
</div>
</body>
</html>    