<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link rel="shortcut icon" href="{$publicUrl}favicon.ico" type="image/x-icon" />
    <title>Spisová služba</title>
    <style type="text/css" media="screen, print">
        <?php echo file_get_contents(APP_DIR .'/../public/css/print_site.css'); ?>
    </style>
</head>
<body>
    <table id="table_top">
        <tr>
            <td align="left" valign="top">Seznam odchozích zpráv</td>
            <td align="right" valign="top">{$Urad->nazev}</td>
        </tr>
    </table>
    <div id="dokumenty">
    {if count($seznam)>0}
    <table>

        <tr>
            <th class="typ">Typ zprávy</th>
            <th class="prijato">Odesláno</th>
            <th class="cislo_jadnaci">ID</th>
            <th class="vec">Věc<br />Adresát</th>
            <th class="prideleno">Schránka</th>
            <th class="stav">Stav</th>
        </tr>

        {foreach $seznam as $ep}
        <tr>
            <td class="typ">
                {if !empty($ep->email_id)}
                <img src="{$publicUrl}images/icons/typdok1.png" alt="Email" title="Email" width="24" height="16" />
                {else if !empty($ep->isds_id)}
                <img src="{$publicUrl}images/icons/typdok2.png" alt="ISDS" title="ISDS" width="24" height="16" />
                {/if}
            </td>
            <td class="prijato">
                <span title="{$ep->doruceno_dne|edatetime}">{$ep->doruceno_dne|edate}</span>
            </td>
            <td class="cislo_jadnaci">
                &nbsp;<strong>
                   OSS-EP-O-{$ep->poradi}-{$ep->rok}
                </strong>
            </td>
            <td class="vec">
                <strong>
                    {$ep->predmet}
                </strong>
                <br />
                {$ep->odesilatel}
            </td>
            <td class="prideleno">
                {$ep->adresat}
            </td>
            <td class="stav" title="{$ep->stav_info}">
                {if ($ep->stav==0)}
                neodesláno
                {elseif ($ep->stav==1)}
                odesláno
                {else}
                nelze zjístit stav
                {/if}
            </td>
        </tr>
        {/foreach}
    </table>
    <div id="tisk_podpis">
        &nbsp;<br />
        Vytištěno dne: {=date("j.n.Y G:i")}
        <br />
        Vytiskl: {=Nette\Environment::getUser()->getIdentity()->name}
    </div>
    {else}
        <div class="prazdno">Nejsou žádné odchozí zprávy.</div>
    {/if}
    </div>
</body>
</html>    