{block title}Seznam zpráv{/block}
@{block debug}
<?php print_r($seznam); ?>
@{/block}
{block content}

<h2>Seznam příchozích zpráv</h2>

    <div id="dokumenty">
    {if count($seznam)>0}
    <table>

        <tr>
            <th class="typ">Typ zprávy</th>
            <th class="prijato">Doručeno<br />Přijato EP</th>
            <th class="cislo_jadnaci">ID</th>
            <th class="vec">Věc<br />Odesilatel/-é</th>
            <th class="prideleno">Schránka</th>
            <th class="stav">Stav</th>
        </tr>

        {foreach $seznam as $ep}
        <tr>
            <td class="typ">
                {if !empty($ep->email_signature)}
                <img src="{$baseUri}images/icons/typdok1.png" alt="Email" title="Email" width="24" height="16" />
                {else if !empty($ep->isds_signature)}
                <img src="{$baseUri}images/icons/typdok2.png" alt="ISDS" title="ISDS" width="24" height="16" />
                {/if}
            </td>
            <td class="prijato">
                {$ep->doruceno_dne|date:%d.%m.%Y}
                <br />
                {$ep->prijato_dne|date:%d.%m.%Y}
            </td>
            <td class="cislo_jadnaci">
                &nbsp;<strong><a href="{link :Epodatelna:Default:detail, 'id'=>$ep->epodatelna_id}">
                   OSS-EP-I-{$ep->poradi}-{$ep->rok}
                </a></strong>
            </td>
            <td class="vec">
                <strong title="{$ep->popis}"><a href="{link :Epodatelna:Default:detail, 'id'=>$ep->epodatelna_id}">
                    {$ep->predmet}
                </a></strong>
                <br />
                {$ep->odesilatel}
            </td>
            <td class="prideleno">
                {$ep->adresat}
            </td>
            <td class="stav" title="{$ep->stav_info}">
                {if ($ep->stav==0)}
                nový
                {elseif ($ep->stav==1)}
                nový přijatý
                {elseif ($ep->stav==10)}
                evidovaný
                {elseif ($ep->stav==11)}
                jiná evidence:
                <br />
                {$ep->evidence}
                {elseif ($ep->stav==100)}
                zamítnutý
                {else}
                nelze zjístit stav
                {/if}
            </td>
        </tr>
        {/foreach}
    </table>
    {widget vp}
    {else}
        <div class="prazdno">Nejsou žádné příchozí zprávy.</div>
    {/if}
    </div>
