{block title}Nové příchozí zprávy{/block}
{block debug}
{/block}
{block content}

    <h2>Nové příchozí zprávy</h2>

    {widget seznamstatu}

    <div id="zkontrolovat_status"></div>
    <script type="text/javascript">
        zkontrolovatSchranku();
        zkontrolovatOdchoziSchranku();        
    </script>


    <div id="zkontrolovat_seznam">
    <form action="{link :Epodatelna:Evidence:hromadna}" method="post" id="h_evidence">
        
    </form>
    </div>
    <div id="dialog"></div>