{block title}Detail spisu{/block}
{assign Select2 => true}
@{block javascript}{if ($FormUpravit=='info')}
	<script type="text/javascript">

                function vybratSpisovyZnak() {

                    var spisz_skart = new Array();
                    var spisz_lhuta = new Array();
                    var spisz_udalost = new Array();
                    spisz_skart['0'] = '';
                    spisz_lhuta['0'] = '';
                    spisz_udalost['0'] = '';
                {if count($SpisoveZnaky)>0}
                {foreach $SpisoveZnaky as $sznak}
                    spisz_skart[{$sznak->id}] = {$sznak->skartacni_znak};
                    spisz_lhuta[{$sznak->id}] = {$sznak->skartacni_lhuta};
                    spisz_udalost[{$sznak->id}] = {$sznak->spousteci_udalost_id};
                {/foreach}
                {/if}

                    var frm_spis  = document.forms['frm-upravitForm'].spisovy_znak_id;
                    var frm_skart  = document.forms['frm-upravitForm'].skartacni_znak;
                    var frm_lhuta  = document.forms['frm-upravitForm'].skartacni_lhuta;
                    var frm_udalost  = document.forms['frm-upravitForm'].spousteci_udalost_id;

                    var key  = document.forms['frm-upravitForm'].spisovy_znak_id.selectedIndex;
                    var value = document.forms['frm-upravitForm'].spisovy_znak_id.options[key].value;
                    document.forms['frm-upravitForm'].skartacni_znak.value = spisz_skart[value];
                    document.forms['frm-upravitForm'].skartacni_lhuta.value = spisz_lhuta[value];
                    //document.forms['frm-novyForm'].spousteci_udalost.value = spisz_udalost[value];
                    select_set_value(document.forms['frm-upravitForm'].spousteci_udalost_id,spisz_udalost[value]);
                    return true;
                }


	</script>
{/if}@{/block}
{block content}
    <div class="navigate">
    <a href="{link :Admin:Spisy:seznam}">Spisy</a> - Detail
    </div>
    <h2>{$Spis->nazev}</h2>

    <div id="tisk">
        <a href="{link :Admin:Spisy:detail, 'id'=>$Spis->id, 'print' => 1}" title="vytisknout tuto stránku" target="_blank">
            <img src="{$baseUri}images/icons/printer.png" alt="printer.png" width="32" height="32" />
        </a>
        <a href="{link :Admin:Spisy:detail, 'id'=>$Spis->id, 'pdfprint' => 1}" title="Vytisknout tuto stránku do PDF" target="_blank">
            <img src="{$baseUri}images/mimetypes/application-pdf.png" alt="application-pdf.png" width="32" height="32" />
        </a>        
    </div>     
    
        {if ($FormUpravit=='info')}
    <div class="detail_blok">
        <div class="detail_hlavicka">Info</div>
        {control $spisForm}
    </div>
        {else}
    <div class="detail_blok">
        <div class="detail_hlavicka">Info</div>
        <dl class="detail_item">
            <dt>Typ spisu:</dt>
            <dd>{=Spis::typSpisu($Spis->typ)}&nbsp;</dd>
        </dl>

        <dl class="detail_item">
            <dt>Název:</dt>
            <dd>{$Spis->nazev}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{!$Spis->popis|enl2br}&nbsp;</dd>
        </dl>

        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{$SpisZnak_nazev}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Spis->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$Spis->skartacni_lhuta}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{=SpisovyZnak::spousteci_udalost($Spis->spousteci_udalost_id,10)}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Stav:</dt>
            <dd>
                {=Spis::stav($Spis->stav)}
                &nbsp;&nbsp;
                {if $Spis->stav==1}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{link :Admin:Spisy:stav, 'id'=>$Spis->id, 'stav'=>'uzavrit'}" onclick="return confirm('Opravdu chcete uzavřít tento spis?');">Uzavřít spis/složku</a>{/if}
                {if $Spis->stav==0}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{link :Admin:Spisy:stav, 'id'=>$Spis->id, 'stav'=>'otevrit'}" onclick="return confirm('Opravdu chcete otevřít tento spis?');">Otevřít spis/složku</a>{/if}

            </dd>
        </dl>
        <a href="{link :Admin:Spisy:detail, 'id'=>$Spis->id, 'upravit'=>'info'}">Upravit</a>
        {if 0}
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{link :Admin:Spisy:odebrat2, 'id'=>$Spis->id}" title="Odstraní tento spis/složku. Všechny jeho podřízené spisy odstraněny nebudou, ale budou přiřazeny nadřazenému spisu/složce." onclick="return confirm('Opravdu chcete odstranit tento spis/složku? Všechny podřízené spisy odstraněny nebudou, ale budou přiřazeny nadřazenému spisu/složce.');">Odebrat</a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{link :Admin:Spisy:odebrat1, 'id'=>$Spis->id}" title="Odstraní tento spis/složku včetně všech jeho podřízených spisů." onclick="return confirm('Opravdu chcete odstranit tento spis/složku včetně všech podřízených spisů?');">Odebrat včetně podřízených spisů</a>
        {/if}
        
    </div>
        {/if}
