{block title}Nový spis / věcná skupina{/block}
@{block javascript}
	<script type="text/javascript" src="{$baseUri}js/webtoolkit.aim.js"></script>
	<script type="text/javascript">

                function vybratSpisovyZnak() {

                    var spisz_skart = new Array();
                    var spisz_lhuta = new Array();
                    var spisz_udalost = new Array();
                    spisz_skart['0'] = '';
                    spisz_lhuta['0'] = '';
                    spisz_udalost['0'] = '';
                {if count($SpisoveZnaky)>0}
                {foreach $SpisoveZnaky as $sznak}
                    spisz_skart[{$sznak->spisznak_id}] = {$sznak->skartacni_znak};
                    spisz_lhuta[{$sznak->spisznak_id}] = {$sznak->skartacni_lhuta};
                    spisz_udalost[{$sznak->spisznak_id}] = {=SpisovyZnak::spousteci_udalost($sznak->spousteci_udalost)};
                {/foreach}
                {/if}

                    var frm_spis  = document.forms['frm-novyForm'].spisovy_znak;
                    var frm_skart  = document.forms['frm-novyForm'].skartacni_znak;
                    var frm_lhuta  = document.forms['frm-novyForm'].skartacni_lhuta;
                    var frm_udalost  = document.forms['frm-novyForm'].spousteci_udalost;

                    var key  = document.forms['frm-novyForm'].spisovy_znak.selectedIndex;
                    var value = document.forms['frm-novyForm'].spisovy_znak.options[key].value;
                    document.forms['frm-novyForm'].skartacni_znak.value = spisz_skart[value];
                    document.forms['frm-novyForm'].skartacni_lhuta.value = spisz_lhuta[value];
                    document.forms['frm-novyForm'].spousteci_udalost.value = spisz_udalost[value];
                    return true;
                }


	</script>
@{/block}
{block content}
    <div class="navigate">
    <a href="{link :Admin:Spisy:seznam}">Spisy</a> - Nový spis / věcná skupina
    </div>
    <h2>Nový spis / věcná skupina</h2>

    <div class="detail_blok">
        <div class="detail_hlavicka">Info</div>
        {control $novyForm}
    </div>
