{block title}Spisy{/block}
{block content}

    <div class="dokument_blok2">
        <a href="{link :Admin:Spisy:novy}">Nový spis</a>
    </div>

    <div id="tisk">
        <a href="{link this, 'print' => 1}" title="vytisknout tuto stránku" target="_blank">
            <img src="{$baseUri}images/icons/printer.png" alt="printer.png" width="32" height="32" />
        </a>
        <a href="{link this, 'pdfprint' => 1}" title="Vytisknout tuto stránku do PDF" target="_blank">
            <img src="{$baseUri}images/mimetypes/application-pdf.png" alt="application-pdf.png" width="32" height="32" />
        </a>        
    </div>

    <div id="search">
        {control searchForm}
    </div>

    {if count($seznam)>0}
    <table>
        {foreach $seznam as $spis}
        <tr class="item{=str_replace("."," item",$spis->sekvence)}" id="sitem{$spis->id}">
            <td>
                {!=str_repeat("&nbsp;", 10*$spis->uroven)}
                {if $spis->typ=='VS'}
                <img src="{$baseUri}images/icons/folder_yellow.png" alt="Složka" title="Složka" width="16" height="16" onclick="return toggle('item{!$spis->id}');" />
                {elseif $spis->typ=='SP'}
                <img src="{$baseUri}images/icons/folder_green.png" alt="Spisový plán" title="Spisový plán" width="16" height="16" onclick="return toggle('item{!$spis->id}');" />
                {else}
                <img src="{$baseUri}images/icons/spisy.png" alt="Spis" title="Spis" width="16" height="16" />
                {/if}
                &nbsp;&nbsp;
                <a href="{link :Admin:Spisy:detail, id => $spis->id}">{$spis->nazev}</a>
            </td>
        </tr>
        {/foreach}

    </table>
    {widget vp}
    {else}
    <div class="prazdno">Nebyly zjištěny žádné spisy.</div>
    {/if}