{block title}Seznam spisů{/block}
{block content}
    <div class="navigate">
    Spisy
    </div>

    <h2>Spisy</h2>

    <div class="blok_menu">
        <a href="{link :Admin:Spisy:novy}">Nový spis / věcná skupina</a>
    </div>

    {if count($seznam)>0}
    <table>
        {foreach $seznam as $spis}
        <tr class="{$spis->class}" id="sitem{$spis->id}">
            <td>
                {!=str_repeat("&nbsp;", 5*$spis->uroven)}
                {if $spis->typ=='VS'}
                <img src="{$baseUri}images/icons/folder_yellow.png" alt="Věcná skupina" title="Věcná skupna" width="16" height="16" onclick="return toggle('item{!$spis->id}');" />
                {else}
                <img src="{$baseUri}images/icons/spisy.png" alt="Spis" title="Spis" width="16" height="16" />
                {/if}
                &nbsp;&nbsp;
                <a href="{link :Admin:Spisy:detail, id => $spis->id}">{$spis->nazev}</a>
            </td>
        </tr>
        {/foreach}
        
    </table>
    {else}
    <div class="prazdno">Nebyly zjištěny žádné spisy.</div>
    {/if}

    <pre><?php //print_r($seznam); ?></pre>
    <?php //Debug::dump($seznam); ?>

