    <h2>Zaevidovat dokument</h2>

<p>    
V této obrazovce se provádí zaevidování zprávy do spisové služby.
</p>
<p>
Princip je stejný jako založení nového dokumentu. Rozdíl je pouze v předvyplění některých hodnot převzaté ze zprávy.
</p>

<br>
<h3>Základní informace</h3>
<p>
    <dl>
        <dt>Typ dokumentu</dt>
        <dd>představuje typ dokumentu – zde podstatě jen jedna volba</dd>
    </dl>    
    <dl>
        <dt>Věc</dt>
        <dd>představuje název dokumentu – předvyplněno z předmětu zprávy</dd>
    </dl>    
    <dl>
        <dt>Popis</dt>
        <dd>představuje krátký popis dokumentu</dd>
    </dl>    
    <dl>
        <dt>Datum a čas doručení</dt>
        <dd>představuje datum a čas doručení zprávy – nejedná se o datum vzniku dokumentu</dd>
    </dl>    
    <dl>
        <dt>Číslo jednací odesilatele</dt>
        <dd>obsahuje číslo jednací odesílatele</dd>
    </dl>    
    <dl>
        <dt>Poznámka</dt>
        <dd>představuje doplňující informace – zde konkrétně obsah zprávy</dd>
    </dl>    
    <dl>
        <dt>Spojit s dokumentem</dt>
        <dd>v případě priorace umožňuje spojit tento dokument s jiným souvisejícím dokumentem</dd>
    </dl>    
    <dl>
        <dt>Počet listů / Počet listů příloh</dt>
        <dd>představuje počet listu v listinné podobě a počet příloh</dd>
    </dl>    
    <dl>
        <dt>Identifikátor e-podatelny</dt>
        <dd>představuje identifikaci zprávy. V případě dostupnosti e-podpisu se zobrazí jeho obsah a kontrola platnosti certifikátu</dd>
    </dl>    
</p>

<br>
<h3>Předání</h3>
<p>
    <dl>
        <dt>Přiděleno</dt>
        <dd>obsahuje jméno toho, kdo tento dokument vytvořil</dd>
    </dl>    
    <dl>
        <dt>Lhůta k vyřízení</dt>
        <dd>představuje počet dní, kdy je potřeba dokument vyřídit. Lhůta se vztahuje na datum doručení, nikoli na datum vytvoření.</dd>
    </dl>    
    <dl>
        <dt>Poznámka</dt>
        <dd>představuje poznámku při předání</dd>
    </dl>    
    <dl>
        <dt>Předat</dt>
        <dd>Zde je možné dokument již přímo předat pracovníkovi nebo organizační jednotce. Položka pracuje formou našeptávače, takže stačí postupně zadat jméno a ze seznamu vybrat.</dd>
    </dl>    
</p>

<br>
<h3>Odesílatel zprávy</h3>
<p>
Tento blok obsahuje identifikaci subjektu získané ze zprávy.
</p>   

<br>
<h3>Nalezené shody s odesilatelem zprávy</h3>
<p>
V tomto bloku se zobrazuje seznam subjektů, které byly nalezeny v databázi, a shoduji se se subjektem zprávy.
</p>
<p>
Pokud aplikace nenalezla shodný subjekt, je možné subjekt dodatečně vyhledat nebo založit nový subjekt.
<br>
Položka vyhledat subjekt je formou našeptávače. Stačí postupně zadat jméno a adresu a ze seznamu vybrat.
<br>
Pokud daný subjekt v databázi neexistuje, je možné tento subjekt vytvořit pomoci tlačítka Vytvořit nový subjekt z odesílatele. Tam stačí zkontrolovat, případně poupravit a přidat.
</p>
<p>
Nalezené subjekty, které se připojí k dokumentu, je potřeba označit.
</p>

<br>
<h3>Přílohy</h3>
<p>
V tomto bloku se objevuje seznam všech příloh, které zpráva obsahuje. Kliknutím na název je možné přílohu otevřít a ověřit.
</p>

<br>
<p>
Po vyplnění a zkontrolování se nakonec kline na tlačítko vytvořit.
</p>    