    <h2>Odmítnout zprávu</h2>

<p>    
K této volbě se přistupuje přes detail příchozí zprávy odkazem Odmítnou.
</p>

<p>
Zobrazí se dialogové okno s formulářem. 
<br />
Položka důvod odmítnutí je povinná a je třeba ji vyplnit. Představuje důvod odmítnutí zpráv.
<br />
Dále je možné zaslat zpětnou reakci na odmítnutí zpět k odesilateli. Stačí zaškrtnout volbu "Poslat upozornění odesílatel?" a vyplnit další položky.
</p>    