    <h2>Zápůjčky</h2>

<p>    
Obsahuje seznam zápůjček.
</p>
    
<p>
Pracovník spisové služby vidí pouze vlastní zápůjčky. Může zde výběrem hromadně provést volbu vracení dokumentů zpět do spisovny.
</p>
<p>
Pracovník spisovny má vyšší pravomoc. Může vidět všechny zápůjčky nebo je vyfiltrovat dle zvoleného filtru. Pracovník spisovny zde může provést hromadné operace – schválení zápůjčky, odmítnutí zápůjčky, vracení dokumentů.
</p>

<br>
<h3>Žádanka o zápůjčku</h3>
<p>
Kliknutím na odkaz se zobrazí formulář pro vyplnění žádanky.
</p>

<br>
<h3>Hledat</h3>
<p>
Obsahuje jednoduchý vyhledávací formulář, odkud může vyhledat konkrétní žádanku. A to podle názvu dokumentu, popisu, čísla jednacího nebo JID.
</p>

<br>
<h3>Filtr</h3>
<p>
    <dl>
        <dt>Aktuální zápůjčky</dt>
        <dd>zobrazí pouze zapůjčené dokumenty nebo zápůjčky čekající na schválení</dd>
    </dl>
    <dl>
        <dt>Zapůjčené zápůjčky</dt>
        <dd>zobrazí pouze zapůjčené dokumenty</dd>
    </dl>
    <dl>
        <dt>Zápůjčky ke schválení</dt>
        <dd>zobrazí pouze zápůjčky čekající na schválení</dd>
    </dl>
    <dl>
        <dt>Historie zápůjček</dt>
        <dd>zobrazí již vracené nebo odmítnuté zápůjčky</dd>
    </dl>
    <dl>
        <dt>Odmítnuté zápůjčky</dt>
        <dd>zobrazí pouze odmítnuté zápůjčky</dd>
    </dl>
</p>



<br>
<h3>Sloupce</h3>
<p>
    <dl>
        <dt>Od</dt>
        <dd>obsahuje datum od kdy je dokument zapůjčen</dd>
    </dl>
    <dl>
        <dt>Do</dt>
        <dd>obsahuje datum předpokládaného vracení dokumentu</dd>
    </dl>
    <dl>
        <dt>Číslo jednací / JID</dt>
        <dd>obsahuje číslo jednací a jednoznačné identifikační číslo dokumentu</dd>
    </dl>
    <dl>
        <dt>Věc</dt>
        <dd>obsahuje název dokumentu</dd>
    </dl>
    <dl>
        <dt>Důvod</dt>
        <dd>obsahuje text důvodu zápůjčky</dd>
    </dl>
    <dl>
        <dt>Zapůjčeno komu</dt>
        <dd>obsahuje jméno osoby, které byl dokument zapůjčen</dd>
    </dl>
    <dl>
        <dt>Stav</dt>
        <dd>obsahuje aktuální stav zápůjčky – zapůjčena, čeká na schválení, vrácena, odmítnuta</dd>
    </dl>
</p>

<br>
<h3>Hromadná operace</h3>
<p>
Na konci seznamu se nachází pole pro volbu hromadné operace.
<br>
Zde se nachází volby "vrátit vybrané zápůjčky". V případě pracovníka spisovny ještě volby "schválit vybrané zápůjčky" nebo "odmítnout vybrané zápůjčky". Označením vybraných zápůjček nebo zvolením zaškrtnout vše a potvrzením volby, dojde ke zvolené akce.
</p>
    
