    <h2>Detail zápůjčky</h2>
<p>    
Obsahuje detailní informace o zápůjčce.
</p>

<br />
<h3>Volby</h3>
<p>
    <dl>
        <dt>Vrátit dokument</dt>
        <dd>vrátí daný dokument zpět do spisovny</dd>
    </dl>    
    <dl>
        <dt>Schválení zápůjčky</dt>
        <dd>potvrzení zápůjčky dokumentu (pouze pracovník spisovny)</dd>
    </dl>    
    <dl>
        <dt>Odmítnutí zápůjčky</dt>
        <dd>zamítnutí zápůjčky dokumentu (pouze pracovník spisovny)</dd>
    </dl>    
</p>

<br />
<h3>Položky</h3>
<p>
    <dl>
        <dt>Zapůjčený dokument</dt>
        <dd>obsahuje číslo jednací a název dokumentu</dd>
    </dl>    
    <dl>
        <dt>Zapůjčeno komu</dt>
        <dd>obsahuje jméno pracovníka, kterému byl dokument zapůjčen</dd>
    </dl>    
    <dl>
        <dt>Důvod zapůjčení</dt>
        <dd>obsahuje důvod zapůjčení</dd>
    </dl>    
    <dl>
        <dt>Datum výpůjčky</dt>
        <dd>obsahuje datum začátku výpůjčky</dd>
    </dl>    
    <dl>
        <dt>Datum vracení</dt>
        <dd>obsahuje předpokládané datum vracení dokumentu</dd>
    </dl>    
    <dl>
        <dt>Stav</dt>
        <dd>obsahuje aktuální stav zápůjčky – zapůjčena, čeká na schválení, vrácena, odmítnuta</dd>
    </dl>    
</p>    