    <h2>Žádanka o zápůjčku</h2>

<p>
Chce-li si pracovník vypůjčit dokument, který se nachází ve spisovně, musí podat žádost o zápůjčku.
</p>
<p>
Pracovník vyplní všechny položky žádanky a potvrdí vytvoření. Jedná-li se o pracovníka spisové služby, podléhá žádanka schválení pracovníkem spisovny. Ten pak rozhodne o schválení nebo odmítnutí zápůjčky.
Pokud žádanku vyplňuje sám pracovník spisovny, je tato zápůjčka po uložení automaticky schválená.
</p>

<p>
Ve formuláři pracovník vyplní číslo jednací nebo název dokumentu. Tato volba probíhá formou našeptávače. Tudíž musí pracovník vědět o jaký dokument má zájem. Postupným vyplňováním čísla jednacího nebo názvu se zobrazí seznam nalezených dokumentů uložených ve spisovně. Pracovník pak daný dokument vybere.
<br>
Označil-li pracovník dokument ze seznamu dokumentu, je tato položka vyplněna.
</p>

<p>
Položka "zapůjčeno komu" je opět výběrová formou našeptávače. V případě pracovníka spisové služby je tato položka automaticky vyplněna jménem pracovníka. V případě pracovníka spisovny se položka vyplní postupným zadáváním jména pracovníka. Ze seznamu pak vybere požadovanou osobu.
</p>

<p>
Položka "důvod zapůjčení" je nepovinná, ale doporučuje se vyplnit pro snadné rozhodování při schvalování zápůjčky.
</p>
<p>
Položky "datum výpůjčky" a "datum vracení" je potřeba vyplnit. V případě neupřesněného data vracení, zvolí pracovník pravděpodobné datum vracení.
</p>    