{block title}Sestavy{/block}
{block content}

    <h2>Sestavy</h2>
    
    <div class="blok_menu">
        <a href="{link :Spisovka:Sestavy:nova}">Nová sestava</a>
    </div>

    <div class="detail_blok">
    {if count($sestavy)>0}
    <table class="seznam">
        {foreach $sestavy as $sestava}
        <?php $filtr = ($sestava->filtr == 1)?'onclick="return filtrSestavy(this);"':" target='_blank'"; ?>
        <tr>
            <td class="icon">
                <img src="{$baseUri}images/icons/book.png" alt="book.png" width="32" height="32" />
            </td>
            <td class="meta">
                <a href="{link :Spisovka:Sestavy:detail, id => $sestava->id}" {!$filtr}>{$sestava->nazev}</a>&nbsp;
                <div class="info">
                    {$sestava->popis}
                </div>
            </td>
            <td class="seznam-sestav-pruh-ikon">
                <a href="{link :Spisovka:Sestavy:detail, id => $sestava->id}" {!$filtr} title="Zobrazit sestavu">
                    <img src="{$baseUri}images/icons/list.png" alt="list.png" width="32" height="32" />
                </a>
                <a href="{link :Spisovka:Sestavy:tisk, id => $sestava->id}" {!$filtr} title="Zobrazit a vytisknout sestavu">
                    <img src="{$baseUri}images/icons/printer.png" alt="printer.png" width="32" height="32" />
                </a>
                <a href="{link :Spisovka:Sestavy:pdf, id => $sestava->id}" {!$filtr} title="Vytisknout sestavu do PDF">
                    <img src="{$baseUri}images/mimetypes/application-pdf.png" alt="application-pdf.png" width="32" height="32" />
                </a>
                <a n:if="$sestava->canUserModify()" href="{link :Spisovka:Sestavy:upravit, id => $sestava->id}" title="Upravit vlastnosti sestavy">
                    <img src="{$baseUri}images/icons/edit.png" alt="edit.png" width="32" height="32" />
                </a>
                <a n:if="$sestava->canUserDelete()" href="{link :Spisovka:Sestavy:smazat, id => $sestava->id}" title="Smazat sestavu" onclick="return confirm('Opravdu chcete tuto sestavu smazat?')">
                    <img src="{$baseUri}images/icons/delete.png" alt="delete.png" width="32" height="32" />
                </a>
            </td>
        </tr>
        {/foreach}
    </table>
    {widget vp}
    {else}
    <div class="prazdno">Nebyly zjištěny žádné sestavy.</div>
    {/if}
    </div>

    <div id="dialog"></div>
    