{block title}{$Sestava->nazev}{/block}
{block content}
    <table id="table_top">
        <tr>
            <td align="left" valign="top">{$Sestava->nazev}</td>
            <td align="right" valign="top">{$Urad->nazev}, {=date('Y')}</td>
        </tr>
    </table>
    {if count($seznam)>0}
    <table>
        <tr>
            {foreach $sloupce as $sl}
            <th>{$sloupce_nazvy[$sl]}</th>
            {/foreach}
        </tr>
        {foreach $seznam as $dok}
        <tr>
            {foreach $sloupce as $sl}
            <td>
            {if $sl=='spis'}
                {if count($dok->spisy)>0}
                {foreach $dok->spisy as $spis}
            {$spis->nazev}
                {/foreach}
                {else}
            &nbsp;
                {/if}
            {elseif $sl=='subjekty'}
                {if count($dok->subjekty)>0}
                {foreach $dok->subjekty as $subjekt}
            {=Subjekt::displayName($subjekt,'plna_adresa')}<br />
                {/foreach}
                {else}
            &nbsp;
                {/if}
            {elseif $sl=='pocet_nelistu'}
                {=count($dok->prilohy)}
            {elseif $sl=='vyridil'}
                {if empty($dok->prideleno->prideleno_jmeno)}
            &nbsp;
                {else}
            {$dok->prideleno->prideleno_jmeno}
                {/if}
            {elseif $sl=='datum_odeslani'}
                {if count($dok->odeslani)}
                {foreach $dok->odeslani as $odes}
            {$odes->datum_odeslani|edate}<br />
                {/foreach}
                {else}
            &nbsp;
                {/if}
            {elseif $sl=='zaznam_vyrazeni'}
            &nbsp;
            {elseif $sl=='datum_vzniku'}
            {$dok->datum_vzniku|edate}



                
            {else}
            {$dok->$sl}
            {/if}
            </td>
            {/foreach}
        </tr>
        {/foreach}


    </table>
    <div>
        &nbsp;<br />
        Vytištěno dne: {=date("j.n.Y G:i")}
        <br />
        Vytiskl: {=Environment::getUser()->getIdentity()->name}
    </div>    
    {elseif isset($prilis_mnoho)}
    <div style="text-align: center; margin-top: 15px; color: red;">
        Tato sestava obsahuje příliš mnoho dokumentů pro zobrazení na této obrazovce. Jejich zobrazení by trvalo hodně dlouho.
        <p>
        Chcete-li přesto zobrazit všech {$pocet_dokumentu} dokumentů, klikněte na odkaz pokračovat a vyčkejte dokud se sestava celá nenačte. Jinak zvolte jiné parametry.

        <div>
            <a href="{$reload_url}">Pokračovat</a>
        </div>

    </div>
    {else}
    <div style="text-align: center; margin-top: 15px;">
        Tato sestava neobsahuje žádné dokumenty.
    </div>
    {/if}

<pre>
<?php //print_r($seznam); ?>
</pre>