{block title}{$Sestava->nazev}{/block}
{block content}
    <table id="table_top">
        <tr>
            <td align="left" valign="top">{$Sestava->nazev}</td>
            <td align="right" valign="top">{$Urad->nazev}, {$rok}</td>
        </tr>
    </table>
    {if count($seznam)>0}
    <table>
    {include detail_data.phtml}    
    </table>
    <div>
        &nbsp;<br />
        Vytištěno dne: {=date("j.n.Y G:i")}
        <br />
        Vytiskl: {=Environment::getUser()->getIdentity()->name}
    </div>    
    {elseif isset($prilis_mnoho)}
    <div style="text-align: center; margin-top: 15px; color: red;">
        Tato sestava obsahuje příliš mnoho dokumentů pro zobrazení na této obrazovce. Jejich zobrazení by trvalo hodně dlouho.
        <p>
        Chcete-li přesto zobrazit všech {$pocet_dokumentu} dokumentů, klikněte na odkaz pokračovat a vyčkejte dokud se sestava celá nenačte. Jinak zvolte jiné parametry.

        <div>
            <a href="{$reload_url}">Pokračovat</a>
        </div>

    </div>
    {else}
    <div style="text-align: center; margin-top: 15px;">
        Tato sestava neobsahuje žádné dokumenty.
    </div>
    {/if}

<pre>
<?php //print_r($seznam); ?>
</pre>