    <form action="" method="get" onsubmit="return zobrazSestavu(this);">
        <input type="hidden" name="url" value="<?php echo $_GET['url'] ?>">
        <dl class="detail_item">
            <dt>Pořadové číslo:</dt>
            <dd>
                od: <input type="text" name="pc_od" size="10" />
                do: <input type="text" name="pc_do" size="10" />
                <span class="normal">(celočíselná kladná hodnota)</span>
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum:</dt>
            <dd>
                od: <input type="text" name="d_od" size="10" class="datepicker" />
                do: <input type="text" name="d_do" size="10" class="datepicker" />
                <span class="normal">(platný formát data včetně dne, měsíce a roku)</span>
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Rok:</dt>
            <dd>
                <select name="rok"><?php $rok = date("Y"); ?>
                    {for $r=($rok-10);$r<($rok+2);$r++}
                    <option value="{$r}"{if $r==$rok} selected{/if}>{$r}</option>
                    {/for}
                </select>
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>&nbsp;</dt>
            <dd>
                <input type="submit" name="filtrovat" value="Zobrazit" />
                <input type="button" name="storno" value="Zrušit" onclick="return zrusitFiltrSestavy();" />
            </dd>
        </dl>

    </form>
    <script type="text/javascript">
        $(function() {
            var date = new Date();
            var year = date.getYear() + 1900;
            var year_before = year - 15;
            var year_after = year + 2;
            $("input.datepicker").datepicker(
            {
                showButtonPanel: true,
                changeMonth: true,
                changeYear: true,
                yearRange: year_before+':'+year_after,
                dateFormat : "dd.mm.yy",
                closeText:"Zrušit",
                prevText:"Předchozí",
                nextText:"Další",
                currentText:"Dnes",
                monthNames:["Leden","Únor","Březen","Duben","Květen","Červen","Červenec","Srpen","Září","Říjen","Listopad","Prosinec"],
                monthNamesShort:["Leden","Únor","Březen","Duben","Květen","Červen","Červenec","Srpen","Září","Říjen","Listopad","Prosinec"],
                dayNames:["Neděle","Pondělí","Úterý","Středa","Čtvrtek","Pátek","Sobota"],
                dayNamesMin:["Ne","Po","Út","St","Čt","Pá","So"]
            });
            $('input.datetimepicker').datepicker(
            {
                duration: '',
                changeMonth: true,
                changeYear: true,
                yearRange: '2007:2020',
                showTime: true,
                time24h: true,
                currentText: 'Dnes',
                closeText: 'OK'
            });
        });
    </script>