@{block title}{$nadpis}{/block}
{assign Select2 => true}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovka:Sestavy:default}">Sestavy</a> - {$nadpis}
    </div>

    <h2>{$nadpis}</h2>

    {$form->render('begin')}
    <div id="dokument_blok_hlavni">
        <div class="h2">
            Sestava
        </div>
        <dl class="detail_item">
            <dt>Název sestavy:</dt>
            <dd>{$form['sestava_nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis sestavy:</dt>
            <dd>{$form['sestava_popis']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Typ sestavy:</dt>
            <dd>{$form['sestava_typ']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Filtrovat? </dt>
            <dd>{$form['sestava_filtr']->control} (zobrazit výběr rozsahu podle pořadového čísla nebo data)</dd>
        </dl>
    </div>

    <div id="dokument_blok_vyrizeni">
        <div class="h2">
            Filtr dokumentu
        </div>
        <dl class="detail_item">
            <dt>Typ dokumentu:</dt>
            <dd>{$form['dokument_typ_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Stav dokumentu:</dt>
            <dd>{$form['stav_dokumentu']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací:</dt>
            <dd>{$form['cislo_jednaci']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Název spisu:</dt>
            <dd>{$form['spisova_znacka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd>{$form['nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{$form['popis']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob doručení přes epodatelnu:</dt>
            <dd>{$form['typ_doruceni']->control}</dd>
        </dl>        
        <dl class="detail_item">
            <dt>Způsob doručení:</dt>
            <dd>{$form['zpusob_doruceni_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum doručení/vzniku </dt>
            <dd>od: {$form['datum_vzniku_od']->control} {$form['datum_vzniku_cas_od']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$form['datum_vzniku_do']->control} {$form['datum_vzniku_cas_do']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$form['cislo_jednaci_odesilatele']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo doporučeného dopisu:</dt>
            <dd>{$form['cislo_doporuceneho_dopisu']->control}</dd>
            <dd>{$form['cislo_doporuceneho_dopisu_pouze']->control} pouze doporučené</dd>
        </dl>         
        <dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{$form['poznamka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob vyřízení:</dt>
            <dd>{$form['zpusob_vyrizeni']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyřízení:</dt>
            <dd>od: {$form['datum_vyrizeni_od']->control} {$form['datum_vyrizeni_cas_od']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$form['datum_vyrizeni_do']->control} {$form['datum_vyrizeni_cas_do']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob odeslání:</dt>
            <dd>{$form['zpusob_odeslani']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum odeslání:</dt>
            <dd>od: {$form['datum_odeslani_od']->control} {$form['datum_odeslani_cas_od']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$form['datum_odeslani_do']->control} {$form['datum_odeslani_cas_do']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <?php if (1) { ?>
        <dl class="detail_item">
            <dt>Druh zásilky:</dt>
            <dd>
                <?php
                $druh_zasilky = array();
                if ( isset($params['druh_zasilky']) && !empty($params['druh_zasilky']) ) {
                    $druh_zasilky_a = unserialize($params['druh_zasilky']);
                    foreach ( $druh_zasilky_a as $druh ) {
                        $druh_zasilky[$druh] = $druh;
                    }
                }
                ?>
                {foreach $DruhZasilky as $dz_index=>$dz_nazev}
                <input type="checkbox" name="druh_zasilky[{$dz_index}]" <?php echo isset($druh_zasilky[$dz_index])?' checked="checked"':''; ?> />&nbsp;{$dz_nazev}
                {/foreach}
                &nbsp;
            </dd>
        </dl>     
        <?php }//if 0 ?>        
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{$form['spisovy_znak_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$form['skartacni_znak']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$form['skartacni_lhuta']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{$form['spousteci_udalost']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{$form['poznamka_vyrizeni']->control}&nbsp;</dd>
        </dl>
    </div>

    <div id="dokument_blok_poznamka">
        <div class="h2">
            Přiděleno / předáno
        </div>
        <span n:if="!$vidiVsechnyDokumenty">Poznámka: Sestava bude zahrnovat jen dokumenty, ke kterým máte přístup.</span>
        <dl class="detail_item">
            <dt>Přiděleno:</dt>
            <dd>
            {$form['prideleno_text']->control}
            <br />{$form['prideleno_osobne']->control} Přiděleno na mé jméno
            <br />{$form['prideleno_na_organizacni_jednotku']->control} Přiděleno na mou organizační jednotku

        <script type="text/javascript">
        <!--
        function pridelenoPredanoSearchHandler(type, payload) {
            $('#'+type).remove();

            var list = $('<ul id="'+type+'"></ul>').insertAfter('input[name='+type+'_text]');

            for (var i in payload.autoComplete) {
                $('<li></li>').html(payload.autoComplete[i]).appendTo(list);
            }            
        }
        function pridelenoSearchHandler(payload) {
            pridelenoPredanoSearchHandler('prideleno', payload);
        }
        function predanoSearchHandler(payload) {
            pridelenoPredanoSearchHandler('predano', payload);
        }
        function keyUpHandler(type, element) {
            if ( $(element).val().length > 2 )
                $.getJSON({link autoComplete!}, { typ: type == 'prideleno' ? 1 : 2, text: $(element).val()},
                window[type+'SearchHandler']);
            else
                $('#'+type).remove();
        }
        $('input[name=prideleno_text]').keyup(function(event) {
            keyUpHandler('prideleno', this);
        });
        <?php if ( isset($params['prideleno_text']) && !empty($params['prideleno_text']) ) { 
                $prideleno_checked = "''"; $prideleno_org_checked = "''";
                if ( isset($params['prideleno']) ) {
                    $prideleno_checked = "'". implode(",",$params['prideleno']) ."'";
                }
                if ( isset($params['prideleno_org']) ) {
                    $prideleno_org_checked = "'". implode(",",$params['prideleno_org']) ."'";
                }                        
        ?>
        $.getJSON({link autoComplete!}, { typ: 1, text: '<?php echo $params['prideleno_text'] ."', user: $prideleno_checked, org: $prideleno_org_checked"; ?>}, pridelenoSearchHandler);
        <?php } ?>
                
        -->
        </script>
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Předáno:</dt>
            <dd>
            {$form['predano_text']->control}
            <br />{$form['predano_osobne']->control} Předáno na mé jméno
            <br />{$form['predano_na_organizacni_jednotku']->control} Předáno na mou organizační jednotku
        <script type="text/javascript">
        <!--
        $('input[name=predano_text]').keyup(function(event) {
            keyUpHandler('predano', this);
        });
        <?php if ( isset($params['predano_text']) && !empty($params['predano_text']) ) { 
                $predano_checked = "''"; $predano_org_checked = "''";
                if ( isset($params['predano']) ) {
                    $predano_checked = "'". implode(",",$params['predano']) ."'";
                }
                if ( isset($params['predano_org']) ) {
                    $predano_org_checked = "'". implode(",",$params['predano_org']) ."'";
                }                        
        ?>
        $.getJSON({link autoComplete!}, { typ: 2, text: '<?php echo $params['predano_text'] ."', user: $predano_checked, org: $predano_org_checked"; ?>}, predanoSearchHandler);
        <?php } ?>
                
        -->
        </script>
            </dd>
        </dl>
    </div>
 
    <div id="dokument_blok_poznamka">
        <div class="h2">
            Adresáti / odesílatelé
        </div>
        <dl class="detail_item">
            <dt>Typ subjektu:</dt>
            <dd>{$form['subjekt_type']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>Název subjektu, jméno, IČ:</dt>
            <dd>{$form['subjekt_nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Ulice</dt>
            <dd>
                {$form['adresa_ulice']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>PSČ a město:</dt>
            <dd>
                {$form['adresa_psc']->control}
                {$form['adresa_mesto']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>{$form['subjekt_email']->label}:</dt>
            <dd>{$form['subjekt_email']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$form['subjekt_telefon']->label}:</dt>
            <dd>{$form['subjekt_telefon']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$form['subjekt_isds']->label}:</dt>
            <dd>{$form['subjekt_isds']->control}</dd>
        </dl>

    </div>

    <div id="dokument_blok_akce">
        {$form['odeslat']->control}
        &nbsp;&nbsp;
        {$form['storno']->control}
    </div>
    {$form->render('end')}

    <div id="dialog"></div>