@{block title}{$nadpis}{/block}
{assign Select2 => true}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovka:Sestavy:default}">Sestavy</a> - {$nadpis}
    </div>

    <h2>{$nadpis}</h2>

    {$form->render('begin')}
    <div id="dokument_blok_hlavni">
        <div class="h2">
            Sestava
        </div>
        {input sestava_nazev}
        {input sestava_popis}
        {input sestava_typ}
        <dl class="detail_item">
            <dt>{$form['sestava_filtr']->caption}</dt>
            <dd>{$form['sestava_filtr']->control} (zobrazit výběr rozsahu podle pořadového čísla nebo data)</dd>
        </dl>
    </div>
    
    <div id="dokument_blok_poznamka">
        <div class="h2">
            Zobrazované údaje
        </div>
        {input zobrazeni_cas}
        {input zobrazeni_adresa}
        <p><strong>Výběr sloupců:</strong></p>
        {input sloupce_smer_dokumentu}
        {input sloupce_poznamka}
        {input sloupce_poznamka_predani}
        {input sloupce_prazdny}
    </div>
    
    {include ../Vyhledat/form_common.phtml}

    {include ../Vyhledat/form_predani.phtml}
 
    {include ../Vyhledat/form_subjekt.phtml}

    <div id="dokument_blok_akce">
        {$form['odeslat']->control}
        &nbsp;&nbsp;
        {$form['storno']->control}
    </div>
    {$form->render('end')}

    <div id="dialog"></div>