@{block title}Nová sestava{/block}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovka:Sestavy:default}">Sestavy</a> - Nová sestava
    </div>

    <h2>Nová sestava</h2>

    {$newForm->render('begin')}
    <div id="dokument_blok_hlavni">
        <div class="h2">
            Sestava
        </div>
        <dl class="detail_item">
            <dt>Název sestavy:</dt>
            <dd>{$newForm['sestava_nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis sestavy:</dt>
            <dd>{$newForm['sestava_popis']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Typ sestavy:</dt>
            <dd>{$newForm['sestava_typ']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Filtrovat? </dt>
            <dd>{$newForm['sestava_filtr']->control} (zobrazit výběr rozsahu podle pořadového čísla nebo data)</dd>
        </dl>
    </div>

    <div id="dokument_blok_vyrizeni">
        <div class="h2">
            Filtr dokumentu
        </div>
        <dl class="detail_item">
            <dt>Typ dokumentu:</dt>
            <dd>{$newForm['dokument_typ_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Stav dokumentu:</dt>
            <dd>{$newForm['stav_dokumentu']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací:</dt>
            <dd>{$newForm['cislo_jednaci']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Název spisu:</dt>
            <dd>{$newForm['spisova_znacka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd>{$newForm['nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{$newForm['popis']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob doručení přes epodatelnu:</dt>
            <dd>{$newForm['typ_doruceni']->control}</dd>
        </dl>        
        <dl class="detail_item">
            <dt>Způsob doručení:</dt>
            <dd>{$newForm['zpusob_doruceni_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum doručení/vzniku </dt>
            <dd>od: {$newForm['datum_vzniku_od']->control} {$newForm['datum_vzniku_cas_od']->control} datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$newForm['datum_vzniku_do']->control} {$newForm['datum_vzniku_cas_do']->control} datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$newForm['cislo_jednaci_odesilatele']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo doporučeného dopisu:</dt>
            <dd>{$newForm['cislo_doporuceneho_dopisu']->control}</dd>
            <dd>{$newForm['cislo_doporuceneho_dopisu_pouze']->control} pouze doporučené</dd>
        </dl>           
        <dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{$newForm['poznamka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob vyřízení:</dt>
            <dd>{$newForm['zpusob_vyrizeni']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyřízení:</dt>
            <dd>od: {$newForm['datum_vyrizeni_od']->control} {$newForm['datum_vyrizeni_cas_od']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$newForm['datum_vyrizeni_do']->control} {$newForm['datum_vyrizeni_cas_do']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob odeslání:</dt>
            <dd>{$newForm['zpusob_odeslani']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum odeslání:</dt>
            <dd>od: {$newForm['datum_odeslani_od']->control} {$newForm['datum_odeslani_cas_od']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$newForm['datum_odeslani_do']->control} {$newForm['datum_odeslani_cas_do']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <?php if (1) { ?>
        <dl class="detail_item">
            <dt>Druh zásilky:</dt>
            <dd>
                {foreach $DruhZasilky as $dz_index=>$dz_nazev}
                <input type="checkbox" name="druh_zasilky[{$dz_index}]" />&nbsp;{$dz_nazev}
                {/foreach}
                &nbsp;
            </dd>
        </dl>     
        <?php }//if 0 ?>        
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{$newForm['spisovy_znak_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$newForm['skartacni_znak']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$newForm['skartacni_lhuta']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{$newForm['spousteci_udalost']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{$newForm['poznamka_vyrizeni']->control}&nbsp;</dd>
        </dl>
    </div>

    {if $isPrivilege}
    <div id="dokument_blok_poznamka">
        <div class="h2">
            Přiděleno / předáno
        </div>
        <dl class="detail_item">
            <dt>Přiděleno:</dt>
            <dd>
            {$newForm['prideleno_text']->control}
            <br />{$newForm['prideleno_osobne']->control} Přiděleno na mé jméno
            <br />{$newForm['prideleno_na_organizacni_jednotku']->control} Přiděleno na mou organizační jednotku
            <script type="text/javascript">
            <!--
		$('#frmnewForm-prideleno_text').focus().keyup(function(event) {
                    if ( $('#frmnewForm-prideleno_text').val().length > 2 ) {
			$.getJSON({link autoComplete!}, { typ: 1, text: $('#frmnewForm-prideleno_text').val()}, function(payload) {
				$('#prideleno').remove();

				var list = $('<ul id="prideleno"></ul>').insertAfter('#frmnewForm-prideleno_text');

				for (var i in payload.autoComplete) {
					$('<li></li>').html(payload.autoComplete[i]).appendTo(list);
				}
			});
                    } else {
                        $('#prideleno').remove();
                    }
		});
            -->
            </script>
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Předáno:</dt>
            <dd>
            {$newForm['predano_text']->control}
            <br />{$newForm['predano_osobne']->control} Předáno na mé jméno
            <br />{$newForm['predano_na_organizacni_jednotku']->control} Předáno na mou organizační jednotku
            <script type="text/javascript">
            <!--
		$('#frmnewForm-predano_text').focus().keyup(function(event) {
                    if ( $('#frmnewForm-predano_text').val().length > 2 ) {
			$.getJSON({link autoComplete!}, { typ: 2, text: $('#frmnewForm-predano_text').val()}, function(payload) {
				$('#predano').remove();

				var list = $('<ul id="predano"></ul>').insertAfter('#frmnewForm-predano_text');

				for (var i in payload.autoComplete) {
					$('<li></li>').html(payload.autoComplete[i]).appendTo(list);
				}
			});
                    } else {
                        $('#predano').remove();
                    }
		});
            -->
            </script>
            </dd>
        </dl>
    </div>
    {/if}

    <div id="dokument_blok_poznamka">
        <div class="h2">
            Adresáti / odesílatelé
        </div>
        <dl class="detail_item">
            <dt>Typ subjektu:</dt>
            <dd>{$newForm['subjekt_type']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>Název subjektu, jméno, IČ:</dt>
            <dd>{$newForm['subjekt_nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Ulice</dt>
            <dd>
                {$newForm['adresa_ulice']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>PSČ a město:</dt>
            <dd>
                {$newForm['adresa_psc']->control}
                {$newForm['adresa_mesto']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>{$newForm['subjekt_email']->label}:</dt>
            <dd>{$newForm['subjekt_email']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$newForm['subjekt_telefon']->label}:</dt>
            <dd>{$newForm['subjekt_telefon']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$newForm['subjekt_isds']->label}:</dt>
            <dd>{$newForm['subjekt_isds']->control}</dd>
        </dl>

    </div>

    <div id="dokument_blok_akce">
        {$newForm['novy']->control}
        &nbsp;&nbsp;
        {$newForm['storno']->control}
    </div>
    {$newForm->render('end')}

    <div id="dialog"></div>