{capture $html_out}
    {if count($seznam)>0}
    <style type="text/css" media="screen, print">
        table { 
            border-spacing: 0;
            border-collapse: collapse;
        }
        td, th { border : 1px solid gray; padding : 3px, 2px; }
    </style>
    <table>
    {include detail_data.phtml}    
    </table>
    {else}
    <div style="text-align: center; margin-top: 15px;">
        Tato sestava neobsahuje žádné dokumenty.
    </div>
    {/if}
{/capture}<?php

            $app_info = Nette\Environment::getVariable('app_info');
            $app_info = explode("#",$app_info);
            $app_name = (isset($app_info[2]))?$app_info[2]:'OSS Spisová služba v3';

            $pdf = new mPDF('', 'A4-L',9,'Helvetica');
            $pdf->SetCreator($app_name);
            $pdf->SetAuthor(Nette\Environment::getUser()->getIdentity()->display_name);
            $pdf->SetTitle('Sestava');
            
            $pdf->defaultheaderfontsize = 10;	/* in pts */
            $pdf->defaultheaderfontstyle = B;	/* blank, B, I, or BI */
            $pdf->defaultheaderline = 1; 	/* 1 to include line below header/above footer */

            $pdf->defaultfooterfontsize = 9;	/* in pts */
            $pdf->defaultfooterfontstyle = B;	/* blank, B, I, or BI */
            $pdf->defaultfooterline = 1; 	/* 1 to include line below header/above footer */


            $pdf->SetHeader($Sestava->nazev.'||'.$Urad->nazev .', '. $rok);
            $pdf->SetFooter("{DATE j.n.Y}/".Nette\Environment::getUser()->getIdentity()->display_name."||{PAGENO}/{nb}");	/* defines footer for Odd and Even Pages - placed at Outer margin */
            
            $pdf->WriteHTML($html_out);
            $pdf->Output('sestava.pdf', 'I');
            
?>