{capture $html_out}
    {if count($seznam)>0}
    <table cellspacing="0" cellpadding="1" border="1">
        <tr>
            {foreach $sloupce as $sl}
            <th>{$sloupce_nazvy[$sl]}</th>
            {/foreach}
        </tr>
        {foreach $seznam as $dok}
        <tr>
            {foreach $sloupce as $sl}
            <td>
            {if $sl=='spis'}
                {if isset($dok->spisy)}
                {foreach $dok->spisy as $spis}
            {$spis->nazev}
                {/foreach}
                {else}
            &nbsp;
                {/if}
            {elseif $sl=='subjekty'}
                {if count($dok->subjekty)>0}
                {foreach $dok->subjekty as $subjekt}
            {=Subjekt::displayName($subjekt,'plna_adresa')}<br />
                {/foreach}
                {else}
            &nbsp;
                {/if}
            {elseif $sl=='pocet_nelistu'}
                {=count($dok->prilohy)}
            {elseif $sl=='vyridil'}
                {if empty($dok->prideleno->prideleno_jmeno)}
            &nbsp;
                {else}
            {$dok->prideleno->prideleno_jmeno}
                {/if}
            {elseif $sl=='datum_odeslani'}
                {if count($dok->odeslani)}
                {foreach $dok->odeslani as $odes}
            {$odes->datum_odeslani|edate}<br />
                {/foreach}
                {else}
            &nbsp;
                {/if}
            {elseif $sl=='zaznam_vyrazeni'}
            &nbsp;
            {elseif $sl=='datum_vzniku'}
            {$dok->datum_vzniku|edate}
            {elseif $sl=='podpis'}
            <span style="color:white;">____________________</span>
            {else}
            {$dok->$sl}
            {/if}
            </td>
            {/foreach}
        </tr>
        {/foreach}


    </table>
    {else}
    <div style="text-align: center; margin-top: 15px;">
        Tato sestava neobsahuje žádné dokumenty.
    </div>
    {/if}
{/capture}<?php

            $app_info = Environment::getVariable('app_info');
            $app_info = explode("#",$app_info);
            $app_name = (isset($app_info[2]))?$app_info[2]:'OSS Spisová služba v3';

            //$pdf = new mPDF();
            $pdf = new mPDF('', 'A4-L',9,'Helvetica');
            //$pdf = new SestavaPDF('', 'A4-L',9,'Helvetica');
            $pdf->SetCreator($app_name);
            $pdf->SetAuthor(Environment::getUser()->getIdentity()->name);
            $pdf->SetTitle('Sestava');
            
            $pdf->defaultheaderfontsize = 10;	/* in pts */
            $pdf->defaultheaderfontstyle = B;	/* blank, B, I, or BI */
            $pdf->defaultheaderline = 1; 	/* 1 to include line below header/above footer */

            $pdf->defaultfooterfontsize = 9;	/* in pts */
            $pdf->defaultfooterfontstyle = B;	/* blank, B, I, or BI */
            $pdf->defaultfooterline = 1; 	/* 1 to include line below header/above footer */


            $pdf->SetHeader($Sestava->nazev.'||'.$Urad->nazev .', '. $rok);
            $pdf->SetFooter("{DATE j.n.Y}/".Environment::getUser()->getIdentity()->name."||{PAGENO}/{nb}");	/* defines footer for Odd and Even Pages - placed at Outer margin */
            
            $pdf->WriteHTML($html_out);
            $pdf->Output('sestava.pdf', 'I');
            
?>