@{block title}Upravit sestavu{/block}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovka:Sestavy:default}">Sestavy</a> - Upravit sestavu
    </div>

    <h2>Upravit sestavu</h2>

    {$upravitForm->render('begin')}
    <div id="dokument_blok_hlavni">
        <div class="h2">
            Sestava
        </div>
        <dl class="detail_item">
            <dt>Název sestavy:</dt>
            <dd>{$upravitForm['sestava_nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis sestavy:</dt>
            <dd>{$upravitForm['sestava_popis']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Typ sestavy:</dt>
            <dd>{$upravitForm['sestava_typ']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Filtrovat? </dt>
            <dd>{$upravitForm['sestava_filtr']->control} (zobrazit výběr rozsahu podle pořadového čísla nebo data)</dd>
        </dl>
    </div>

    <div id="dokument_blok_vyrizeni">
        <div class="h2">
            Filtr dokumentu
        </div>
        <dl class="detail_item">
            <dt>Typ dokumentu:</dt>
            <dd>{$upravitForm['dokument_typ_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Stav dokumentu:</dt>
            <dd>{$upravitForm['stav_dokumentu']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací:</dt>
            <dd>{$upravitForm['cislo_jednaci']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Název spisu:</dt>
            <dd>{$upravitForm['spisova_znacka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd>{$upravitForm['nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{$upravitForm['popis']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob doručení přes epodatelnu:</dt>
            <dd>{$upravitForm['typ_doruceni']->control}</dd>
        </dl>        
        <dl class="detail_item">
            <dt>Způsob doručení:</dt>
            <dd>{$upravitForm['zpusob_doruceni_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum doručení/vzniku </dt>
            <dd>od: {$upravitForm['datum_vzniku_od']->control} {$upravitForm['datum_vzniku_cas_od']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$upravitForm['datum_vzniku_do']->control} {$upravitForm['datum_vzniku_cas_do']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$upravitForm['cislo_jednaci_odesilatele']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo doporučeného dopisu:</dt>
            <dd>{$upravitForm['cislo_doporuceneho_dopisu']->control}</dd>
            <dd>{$upravitForm['cislo_doporuceneho_dopisu_pouze']->control} pouze doporučené</dd>
        </dl>         
        <dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{$upravitForm['poznamka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob vyřízení:</dt>
            <dd>{$upravitForm['zpusob_vyrizeni']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyřízení:</dt>
            <dd>od: {$upravitForm['datum_vyrizeni_od']->control} {$upravitForm['datum_vyrizeni_cas_od']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$upravitForm['datum_vyrizeni_do']->control} {$upravitForm['datum_vyrizeni_cas_do']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob odeslání:</dt>
            <dd>{$upravitForm['zpusob_odeslani']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum odeslání:</dt>
            <dd>od: {$upravitForm['datum_odeslani_od']->control} {$upravitForm['datum_odeslani_cas_od']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$upravitForm['datum_odeslani_do']->control} {$upravitForm['datum_odeslani_cas_do']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <?php if (1) { ?>
        <dl class="detail_item">
            <dt>Druh zásilky:</dt>
            <dd>
                <?php
                $druh_zasilky = array();
                if ( isset($params['druh_zasilky']) && !empty($params['druh_zasilky']) ) {
                    $druh_zasilky_a = unserialize($params['druh_zasilky']);
                    foreach ( $druh_zasilky_a as $druh ) {
                        $druh_zasilky[$druh] = $druh;
                    }
                }
                ?>
                {foreach $DruhZasilky as $dz_index=>$dz_nazev}
                <input type="checkbox" name="druh_zasilky[{$dz_index}]" <?php echo isset($druh_zasilky[$dz_index])?' checked="checked"':''; ?> />&nbsp;{$dz_nazev}
                {/foreach}
                &nbsp;
            </dd>
        </dl>     
        <?php }//if 0 ?>        
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{$upravitForm['spisovy_znak_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$upravitForm['skartacni_znak']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$upravitForm['skartacni_lhuta']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{$upravitForm['spousteci_udalost']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{$upravitForm['poznamka_vyrizeni']->control}&nbsp;</dd>
        </dl>
    </div>

    {if $isPrivilege}
    <div id="dokument_blok_poznamka">
        <div class="h2">
            Přiděleno / předáno
        </div>
        <dl class="detail_item">
            <dt>Přiděleno:</dt>
            <dd>
            {$upravitForm['prideleno_text']->control}
            <br />{$upravitForm['prideleno_osobne']->control} Přiděleno na mé jméno
            <br />{$upravitForm['prideleno_na_organizacni_jednotku']->control} Přiděleno na mou organizační jednotku
            <script type="text/javascript">
            <!--
		$('#frmupravitForm-prideleno_text').focus().keyup(function(event) {
                    if ( $('#frmupravitForm-prideleno_text').val().length > 2 ) {
			$.getJSON({link autoComplete!}, { typ: 1, text: $('#frmupravitForm-prideleno_text').val()}, function(payload) {
				$('#prideleno').remove();

				var list = $('<ul id="prideleno"></ul>').insertAfter('#frmupravitForm-prideleno_text');

				for (var i in payload.autoComplete) {
					$('<li></li>').html(payload.autoComplete[i]).appendTo(list);
				}
			});
                    } else {
                        $('#prideleno').remove();
                    }
		});
                <?php if ( isset($params['prideleno_text']) && !empty($params['prideleno_text']) ) { 
                        $prideleno_checked = "''"; $prideleno_org_checked = "''";
                        if ( isset($params['prideleno']) ) {
                            $prideleno_checked = "'". implode(",",$params['prideleno']) ."'";
                        }
                        if ( isset($params['prideleno_org']) ) {
                            $prideleno_org_checked = "'". implode(",",$params['prideleno_org']) ."'";
                        }                        
                ?>
			$.getJSON({link autoComplete!}, { typ: 1, text: '<?php echo $params['prideleno_text'] ."', user: $prideleno_checked, org: $prideleno_org_checked"; ?>}, function(payload) {
				$('#prideleno').remove();

				var list = $('<ul id="prideleno"></ul>').insertAfter('#frmupravitForm-prideleno_text');

				for (var i in payload.autoComplete) {
					$('<li></li>').html(payload.autoComplete[i]).appendTo(list);
				}
			});            
                <?php } ?>
                
            -->
            </script>
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Předáno:</dt>
            <dd>
            {$upravitForm['predano_text']->control}
            <br />{$upravitForm['predano_osobne']->control} Předáno na mé jméno
            <br />{$upravitForm['predano_na_organizacni_jednotku']->control} Předáno na mou organizační jednotku
            <script type="text/javascript">
            <!--
		$('#frmupravitForm-predano_text').focus().keyup(function(event) {
                    if ( $('#frmupravitForm-predano_text').val().length > 2 ) {
			$.getJSON({link autoComplete!}, { typ: 2, text: $('#frmupravitForm-predano_text').val()}, function(payload) {
				$('#predano').remove();

				var list = $('<ul id="predano"></ul>').insertAfter('#frmupravitForm-predano_text');

				for (var i in payload.autoComplete) {
					$('<li></li>').html(payload.autoComplete[i]).appendTo(list);
				}
			});
                    } else {
                        $('#predano').remove();
                    }
		});
                <?php if ( isset($params['predano_text']) && !empty($params['predano_text']) ) { 
                        $predano_checked = "''"; $predano_org_checked = "''";
                        if ( isset($params['predano']) ) {
                            $predano_checked = "'". implode(",",$params['predano']) ."'";
                        }
                        if ( isset($params['predano_org']) ) {
                            $predano_org_checked = "'". implode(",",$params['predano_org']) ."'";
                        }                        
                ?>            
			$.getJSON({link autoComplete!}, { typ: 2, text: '<?php echo $params['predano_text'] ."', user: $predano_checked, org: $predano_org_checked"; ?>}, function(payload) {
				$('#predano').remove();

				var list = $('<ul id="predano"></ul>').insertAfter('#frmupravitForm-predano_text');

				for (var i in payload.autoComplete) {
					$('<li></li>').html(payload.autoComplete[i]).appendTo(list);
				}
			});            
                <?php } ?>
            -->
            </script>
            </dd>
        </dl>
    </div>
    {/if}

    <div id="dokument_blok_poznamka">
        <div class="h2">
            Adresáti / odesílatelé
        </div>
        <dl class="detail_item">
            <dt>Typ subjektu:</dt>
            <dd>{$upravitForm['subjekt_type']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>Název subjektu, jméno, IČ:</dt>
            <dd>{$upravitForm['subjekt_nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Ulice</dt>
            <dd>
                {$upravitForm['adresa_ulice']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>PSČ a město:</dt>
            <dd>
                {$upravitForm['adresa_psc']->control}
                {$upravitForm['adresa_mesto']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>{$upravitForm['subjekt_email']->label}:</dt>
            <dd>{$upravitForm['subjekt_email']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$upravitForm['subjekt_telefon']->label}:</dt>
            <dd>{$upravitForm['subjekt_telefon']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$upravitForm['subjekt_isds']->label}:</dt>
            <dd>{$upravitForm['subjekt_isds']->control}</dd>
        </dl>

    </div>

    <div id="dokument_blok_akce">
        {$upravitForm['upravit']->control}
        &nbsp;&nbsp;
        {$upravitForm['storno']->control}
    </div>
    {$upravitForm->render('end')}

    <div id="dialog"></div>