    <h2>Seznam spisů ve spisovně</h2>
    
<p>
Obsahuje seznam spisů uložené ve spisovně. Běžný pracovník vidí pouze spisy ze své organizační jendotky. Pracovník spisovny vidí všechny.
</p>

<br>
Seznam spisů obsahuje následující sloupce:
<br><br>
    <ul>
	<li><strong>Spis</strong> (název spisu)
	<li><strong>Počet dokumentů</strong> (počet dokumentů, které spis obsahuje)
	<li><strong>Přiděleno</strong> (organizační jednotka, která spis vlastní)
	<li><strong>Předáno</strong> (organizační jednotka, které byl spis předán)
	<li><strong>Spisový znak</strong>
	<li><strong>Skartační znak a lhůta</strong>
	<li><strong>Stav</strong> (zobrazuje aktuální stav spisu)
    </ul>


<br>
<h3>Hledat</h3>
<p>
Další funkcí, kterou můžete využít, je funkce hledat, která je zde dostupná pouze v jednoduché formě. Tudíž stačí do textového pole napsat název nebo část názvu spisu a poté klepnout na tlačítko hledat.
</p>

<br>
<h3>Tisk</h3>
<p>
Seznam spisů je možné vytisknout na obrazovku nebo do formátu PDF. Oproti seznamu, kterou vidíte na obrazovce, se v tisku zobrazí i seznam dokumentů, které ke spisu patří.
</p>

<br>
<h3>Akce</h3>
<p>
Každá položka má u sebe na začátku řádku zaškrtávací box, který souvisí s funkcí Akce, která se nachází v patičce tabulky společně s možnostmi zaškrtnout vše / Odškrtnout vše.
<br>
Celá funkce funguje tak, že zaškrtnete ty položky, u kterých chcete provést jednotnou akci, poté klepnete na rozbalovací menu v patičce tabulky, vyberete jednu z akcí a klepnete na tlačítko provést.
</p>