    <h2>Detail spisu</h2>

    <p>
Pokud si chcete prohlédnout detaily spisu, stačí na něho najet a klepnout na název spisu, který si chcete prohlédnout. Jakmile tak učiníte, zobrazí se vám stránka s detaily spisu. Tato stránka by se dala rozdělit na dvě části – Informace o spisu a Seznam dokumentů.
</p>
<p>    
Informace o spisu obsahují všechny položky, které se zadávají při tvorbě nového spisu.
</p>
<p>
V sekci Seznam dokumentů můžete vidět všechny dokumenty, které spis obsahuje.
</p>       
