    <h2>Seznam spisů pro příjem do spisovny</h2>
    
<p>
Obsahuje seznam všech spisů, které jsou určeny pro příjem do spisovny.
<br>
To znamená, že pracovník spisové služby spisy předal do spisovny, ale pracovník spisovny tyto spisy ještě nepřijal.
</p>
<p>
Je možné mezi spisy listovat, vyhledávat, zobrazit detail spisu.
</p>

<br>
Seznam spisů obsahuje následující sloupce:
<br><br>
    <ul>
	<li><strong>Spis</strong> (název spisu)
	<li><strong>Počet dokumentů</strong> (počet dokumentů, které spis obsahuje)
	<li><strong>Přiděleno</strong> (organizační jednotka, která spis vlastní)
	<li><strong>Předáno</strong> (organizační jednotka, které byl spis předán)
	<li><strong>Spisový znak</strong>
	<li><strong>Skartační znak a lhůta</strong>
	<li><strong>Stav</strong> (zobrazuje aktuální stav spisu)
    </ul>

<br>
<h3>Hledání</h3>

<p>
Lze použít jednoduché hledání pomoci uvedeného formuláře. Hledat lze podle názvu spisu. 
</p>      

<br>
<h3>Hromadná operace</h3>
<p>
Na konci seznamu se nachází pole pro volbu hromadné operace. Zde se nachází pouze volba "převzetí vybraných spisů do spisovny". Označením vybraných spisů nebo zvolením zaškrtnout vše a potvrzením volby, dojde k hromadnému převzetí spisů do spisovny.
</p>