    <h2>Informace o uživateli</h2>
    <p>
        Poslední položkou, kterou jsme si ještě neukázali, je odhlášení ze systému. To se
        provádí jednoduše přes tlačítko Odhlásit, které naleznete v horní pravé části okna.
        Jakmile na toto tlačítko kliknete, budete bezpečně odhlášeni ze systému a budete
        přesměrováni na úvodní stránku spisové služby s přihlašovacím formulářem.
    </p>
