    <h2>Přihlášení do systému</h2>
    <br />
    <div>Uživatelské rozhraní by se dalo rozdělit zhruba do tří částí. První část by se</div>
    <div>dala nazvat jako ovládací (administrační) část, kde můžete přepínat mezi </div>
    <div>Spisovou službou a E-podatelnou, dále zde naleznete dvě tlačítka určená k </div>
    <div>nastavování a správě Spisové služby a E-podatelny a posledním tlačítko je</div>
    <div>určené k odhlášení ze systému.</div>
    <div>Druhá část jsou tlačítka menu, kde naleznete pro Spisovou službu tato tlačítka</div>
    <dl>
        <dd>Seznam dokumentů</dd>
        <dd>Nový dokument</dd>
        <dd>Spisy</dd>
        <dd>Sestavy a Vyhledat</dd>
    </dl>.
    <p>
    Pro E-podatelnu je zde jiná skupina tlačítek menu – Zkontrolovat schránku,
    Nové zprávy, Příchozí zprávy, Odchozí zprávy.Poslední část je tzv. tělo
    stránky, kde se zobrazuje vždy aktuální otevřená stránka.
    </p>
