<div style="text-align: left; padding: 10px 50px;">
    <h2>Registrace nového uživatele do spisové služby</h2>
    Přihlášení proběhlo v pořádku. Přihlášený uživatel však není evidován ve spisové službě. 
    <br />
    Pro použití aplikace je potřeba, abyste se zaregistrovat do spisové služby. V následujícím formuláři vyplňte své jméno, telefon, email a svou pozici. Kliknutím na tlačítko "Vytvořit účet" dojde k Vašemu zaregistrováni. 
    <br />
    Pro plnou funkčnost bude potřeba Vám přidělit potřebné oprávnění. Kontaktujte svého správce, který má na starost spisovou službu, a požádejte o přidělení role.

</div>
<div id="form_user_registration">
{control userRegistrationForm}
</div>