@{block title}Zaevidovat dokument{/block}
@{block debug}
<?php /*print_r($Subjekt);*/ ?>
<?php /*print_r($Prilohy);*/ ?>
<?php print_r($Dok); ?>
<?php /*print_r($Identifikator);*/ ?>
<?php /*print_r($Original);*/ ?>
@{/block}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovka:Dokumenty:default}">Seznam dokumentů</a> - Nový dokument
    </div>

    {$novyForm->render('begin')}
    <div id="dokument_blok_hlavni">
        {if 0}
        <dl class="detail_item">
            <dt>Číslo jednací{if $Typ_evidence == 'sberny_arch'} / pořadí{/if}:</dt>
            <dd>
                <span id="dok_cjednaci">{$cjednaci->cislo_jednaci}</span>&nbsp;
                {if $Typ_evidence == 'sberny_arch'} / {$novyForm['poradi']->control} &nbsp; <a href="{link :Spisovka:Dokumenty:cjednaci, 'id'=>$Dok->id}" id="dialog-cjednaci">Vložit do existujícího spisu</a> {/if}
            </dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Typ dokumentu:</dt>
            <dd>{$novyForm['dokument_typ_id']->control}</dd>
        </dl>
        {if 0}
        <dl class="detail_item">
            <dt>Název spisu:</dt>
            <dd>
                {if $Typ_evidence == 'sberny_arch'}
                &nbsp;
                {else}
                <span id="dok_spis">
                {if count($Spisy)>0 }
                    {foreach $Spisy as $s}
                    {$s->nazev}<br />
                    {/foreach}
                {else}
                    nepřidělen k žádnému spisu
                {/if}

                </span>

                <a href="{link :Spisovka:Spisy:vyber, 'id'=>$Dok->id}" id="dialog-spis">Připojit spis</a>
                {/if}
            </dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd>{$novyForm['nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{$novyForm['popis']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum a čas doručení:</dt>
            <dd>{$novyForm['datum_vzniku']->control} {$novyForm['datum_vzniku_cas']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$novyForm['cislo_jednaci_odesilatele']->control}</dd>
        </dl>
        <!--<dl class="detail_item">
            <dt>Zmocnění:</dt>
            <dd><span id="dok_zmocneni"></span>&nbsp;<a href="{link :Spisovka:Dokumenty:zmocneni, 'id'=>$Dok->dokument_id}" id="dialog-zmocneni">Připojit zmocnění</a></dd>
        </dl>-->
        <dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{$novyForm['poznamka']->control}</dd>
        </dl>
        {if $Typ_evidence == 'priorace'}
        <dl class="detail_item">
            <dt>Spojit s dokumentem:</dt>
            <dd>
                <span id="dok_spojit">
                {if count($SouvisejiciDokumenty)>0 }
                    {foreach $SouvisejiciDokumenty as $s}
                    <a href="{link :Spisovka:Dokumenty:detail, 'id'=>$s->id}">{$s->cislo_jednaci} ({$s->jid})</a>
                    {if 0}&nbsp;&nbsp;&nbsp;[<a href="{link :Spisovka:Spojit:odebrat, 'id'=>$Dok->id, 'spojeny'=>$s->id}">odebrat spojení</a>]{/if}
                    {/foreach}
                {/if}
                </span>
                &nbsp;[<a href="{link :Spisovka:Spojit:vyber, 'id'=>$Dok->id}" id="dialog-spojit">spojit s dokumentem</a>]
            </dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Počet listů:</dt>
            <dd>{$novyForm['pocet_listu']->control}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: normal;">Počet listů příloh: </span>{$novyForm['pocet_priloh']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Identifikátor epodatelny:</dt>
            <dd><pre>{$Identifikator['popis']}</pre></dd>
        </dl>
        {if $Identifikator['typ'] == "email" }
        <dl class="detail_item">
            <dt>Ověření identifikátoru:</dt>
            <dd>
            {if $Identifikator['cert_signed'] >= 0 }
                {$Identifikator['cert_log']['aktualne']['date']} &nbsp;
                {if $Identifikator['cert_log']['aktualne']['status']==1 }
                <span style="color:#009900;">{$Identifikator['cert_log']['aktualne']['message']}</span>
                {else}
                <span style="color:#990000;">{$Identifikator['cert_log']['aktualne']['message']}</span>
                {/if}
                <br />
                {$Identifikator['cert_log']['prijato']['date']} &nbsp;
                {if $Identifikator['cert_log']['prijato']['status']==1 }
                <span style="color:#009900;">{$Identifikator['cert_log']['prijato']['message']}</span>
                {else}
                <span style="color:#990000;">{$Identifikator['cert_log']['prijato']['message']}</span>
                {/if}
                <br />
                {$Identifikator['cert_log']['doruceno']['date']} &nbsp;
                {if $Identifikator['cert_log']['doruceno']['status']==1 }
                <span style="color:#009900;">{$Identifikator['cert_log']['doruceno']['message']}</span>
                {else}
                <span style="color:#990000;">{$Identifikator['cert_log']['doruceno']['message']}</span>
                {/if}
            {else}
                <span style="color:#990000;">{$Identifikator['cert_status']}</span>
            {/if}
            </dd>
        </dl>
        {/if}

    </div>

    <div id="dokument_blok_poznamka">
        <div>Předání / vyřízení</div>
        <dl class="detail_item">
            <dt>Přiděleno:</dt>
            <dd>
                {$Prideleno}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Lhůta k vyřízení:</dt>
            <dd>{$novyForm['lhuta']->control} dní</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{$novyForm['predani_poznamka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Předat:</dt>
            <dd>
                <input type="text" name="predano_autocomplete" id="predat_autocomplete" size="40" />
                &nbsp;&nbsp;&nbsp;
                <a href="{link :Spisovka:Uzivatel:vyber, 'id'=>$user->id, 'dok_id'=>$Dok->id, 'novy'=>1}" id="dialog-uzivatel">Vyhledat ze seznamu</a>
            </dd>
        </dl>
        <div id="predano"></div>

    </div>
    
    <div id="dokument_blok_subjekty">
        <div class="h2">
            Odesílatel zprávy
        </div>
        <div id="dok-subjekty1">
        <table class="seznam">
            <tr>
            <td class="icon">
                <img src="{$baseUri}images/subjekt/ovm.png" alt="obrazek" title="obrazek" width="32" height="32" />
            </td>
            <td class="meta">
                <strong>
                    {if !empty($Subjekt['original']->nazev_subjektu)}{$Subjekt['original']->nazev_subjektu}<br />{/if}
                    {if !empty($Subjekt['original']->prijmeni)}{$Subjekt['original']->prijmeni}<br />{/if}
                    &nbsp;
                </strong>
                <div class="info">
                    <span>{if !empty($Subjekt['original']->type)}{$Subjekt['original']->type} - {=Subjekt::typ_subjektu($Subjekt['original']->type)}{/if}&nbsp;</span>
                <br />
                {=Subjekt::displayName($Subjekt['original'],'adresa')}
                </div>
            </td>
            <td class="meta_plus">
                &nbsp;
                <div class="info">
                <dl>
                    <dt>email:</dt>
                    <dd>{if !empty($Subjekt['original']->email)}{$Subjekt['original']->email}{/if}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>isds:</dt>
                    <dd>{if !empty($Subjekt['original']->id_isds)}{$Subjekt['original']->id_isds}{/if}&nbsp;</dd>
                </dl>

                </div>
            </td>
        </tr>
        </table>
        </div>

        <br />
        <div class="h2">
            Nalezené shody s odesilatelem zprávy
        </div>
        <div class="blok_akce">
            <dl class="detail_item">
                <dt>Vyhledat subjekt:</dt>
                <dd>
                    <input type="text" name="subjekt_autocomplete" id="subjekt_epod_autocomplete" size="60" />
                    <a href="{link :Epodatelna:Subjekty:vyber, 'id'=>0, 'epod_id'=>$Zprava->id}" id="dialog-subjekt">Seznam</a>
                </dd>
            </dl>
            <dl class="detail_item" id="subjekt_novy">
                <dt>&nbsp;</dt>
                <dd>
                    <script type="text/javascript">
                        var subjekt_original = <?php echo json_encode($Subjekt['original']); ?>;
                    </script>
                    <a href="" id="novysubjekt_click">Vytvořit nový subjekt z odesílatele</a>
                    <input type="hidden" name="subjekt_dokument_id" id="subjekt_dokument_id" value="{$Dok->id}" />
                </dd>
            </dl>


            


        </div>
        <div id="dok-subjekty">
        {if count($Subjekt['databaze'])>0}
        <table class="seznam" id="subjekty-table">
            <tr>
            <td class="icon">
                Použít
            </td>
            <td class="icon">
                &nbsp;
            </td>
            <td class="meta">
                &nbsp;
            </td>
            <td class="meta_plus">
                &nbsp;
            </td>
            </tr>
            {foreach $Subjekt['databaze'] as $subjekt}
            <tr id="epodsubjekt-{$subjekt->subjekt_id}">
            <td class="icon">
                <input type="checkbox" name="subjekt[{$subjekt->id}]" />
            </td>
            <td class="icon">
                <img src="{$baseUri}images/subjekt/{$subjekt->type|lower}.png" alt="{$subjekt->type}" title="{$subjekt->type}" width="32" height="32" />
            </td>
            <td class="meta">
                <strong>{=Subjekt::displayName($subjekt,'jmeno_item')}</strong>
                <div class="info">
                <span>{$subjekt->type} - {=Subjekt::typ_subjektu($subjekt->type)}</span>
                <br />
                {=Subjekt::displayName($subjekt,'adresa')}
                </div>
                {if 0}
                <div class="vyber">
                    <a href="{link :Epodatelna:Subjekty:upravit, 'id'=>$subjekt->id, 'epod_id'=>$Zprava->id}" onclick="return subjektzmenit(this);">změnit</a>&nbsp;&nbsp;                    
                </div>
                {/if}
            </td>
            <td class="meta_plus">
                &nbsp;
                <div class="info">
                <dl>
                    <dt>email:</dt>
                    <dd>{$subjekt->email}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>telefon:</dt>
                    <dd>{$subjekt->telefon}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>isds:</dt>
                    <dd>{$subjekt->id_isds}&nbsp;</dd>
                </dl>

                </div>
            </td>
        </tr>
        {/foreach}
        </table>
        {else}
        <div class="prazdno">
            Nebyly nalezeny žádné shody s odesílatelem.
            <br />
            Odesílatel není v databázi nebo se nepodařilo jeho záznam nalézt.
        </div>
        {/if}
        </div>
        
    </div>

    <div id="dokument_blok_prilohy">
    <div class="h2">
        Přílohy
    </div>
    <div id="dok-prilohy">
    {if count($Prilohy)>0}
    <table class="seznam">
        {foreach $Prilohy as $priloha}
        <tr>
            <td class="icon">
                <img src="{$baseUri}images/mimetypes/{$priloha['mimetype']|webalize}.png" alt="{$priloha['mimetype']}" title="{$priloha['mimetype']}" width="32" height="32" />
            </td>
            <td class="meta">
                <a href="{link :Epodatelna:Prilohy:download, 'id'=>$Zprava->id, 'file'=>$priloha['id']}">{$priloha['name']}</a>
                <div class="info">
                <span>{$priloha['size']|bytes}, {$priloha['mimetype']}</span>
                </div>
            </td>
        </tr>
        {/foreach}
    </table>
    {else}
        <div class="prazdno">Zpráva neobsahuje žádné přílohy.</div>
    {/if}
    </div>
    </div>

    <div id="dokument_blok_akce">
        {$novyForm['novy']->control}
        &nbsp;&nbsp;
        {$novyForm['storno']->control}
    </div>
    {$novyForm->render('end')}

    <div id="dialog"></div>