<!-- Stara verze Nette neumoznuje definovat block, aniz by byl vykreslen ,
    proto musime testovat, zda je promenna definovana
-->
{block test}
{if isset($title)}
    <h2 class="seznam">{$title}</h2>
    {foreach $Napovedy[$module] as $presenters_i => $presenters}
    <h3>{=isset($HelpName[$module.'/'.$presenters_i])?$HelpName[$module.'/'.$presenters_i]:$presenters_i}</h3>
    {if count($presenters)>0}
        <ul>
        {foreach $presenters as $actions}
            {if isset($HelpName[$actions->code])}
            <li><a href="{$klientUri}{$actions->url}">{$HelpName[$actions->code]}</a></li>
            {else}
            <li>{$actions->name}</li>
            {/if}
        {/foreach}
        </ul>
    {/if}
    {/foreach}
{/if}
{/block}

{include #test, title => 'Spisová služba', module => 'spisovka' }
{include #test, title => 'E-podatelna', module => 'epodatelna' }
{include #test, title => 'Spisovna', module => 'spisovna' }
{include #test, title => 'Administrace', module => 'admin' }
