{block title}Seznam dokumentů{/block}
{block content}
    <div class="navigate">
    <a href="{link :Admin:Spisznak:seznam}">Seznam spisových znaků</a> - Detail
    </div>
    <h2>{$SpisZnak->nazev}{if !empty($SpisZnak->popis)} - {$SpisZnak->popis}{/if}</h2>

        {if ($FormUpravit=='info')}
    <div class="detail_blok">
        <div class="detail_hlavicka">Info</div>
        {control $upravitForm}
    </div>
        {else}
    <div class="detail_blok">
        <div class="detail_hlavicka">Info</div>

        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{$SpisZnak->nazev}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Věcná skupina:</dt>
            <dd>{$SpisZnak->popis}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$SpisZnak->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$SpisZnak->skartacni_lhuta}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{=SpisovyZnak::spousteci_udalost($SpisZnak->spousteci_udalost_id,10)}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Možnost vybrat:</dt>
            <dd>{if $SpisZnak->selected==1}ano{else}ne{/if}&nbsp;</dd>
        </dl>        
        <dl class="detail_item">
            <dt>Stav:</dt>
            <dd>{=SpisovyZnak::stav($SpisZnak->stav)}&nbsp;</dd>
        </dl>
        <a href="{link :Admin:Spisznak:detail, 'id'=>$SpisZnak->id, 'upravit'=>'info'}">Upravit</a>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{link :Admin:Spisznak:odebrat2, 'id'=>$SpisZnak->id}" title="Odstraní tento spisový znak. Všechny jeho podřízené spisové znaky odstraněny nebudou, ale budou přiřazeny nadřazenému spisovému znaku." onclick="return confirm('Opravdu chcete odstranit tento spisový znak? Všechny podřízené spisové znaky odstraněny nebudou, ale budou přiřazeny nadřazenému spisovému znaku.');">Odebrat</a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{link :Admin:Spisznak:odebrat1, 'id'=>$SpisZnak->id}" title="Odstraní tento spisový znak včetně všech jeho podřízených spisových znaků." onclick="return confirm('Opravdu chcete odstranit tento spisový znak včetně všech podřízených spisových znaků?');">Odebrat včetně podřízených spisových znaků</a>
    </div>
        {/if}
