    <h2>Seznam příloh</h2>
    <p>
        Jakmile kliknete na tlačítko Soubory, zobrazí se vám seznam všech příloh ve
        spisové službě a e-podatelně. Na každém řádku máte ikonu znázorňující typ
        souboru, dále je zde název, popis souboru a jeho velikost, informaci o tom,
        kdy byl soubor do systému nahrán a kým. Pokud kliknete na název souboru,
        budete si moci soubor otevřít či stáhnout do počítače.
    </p>