@{block title}Zápůjčka{/block}
@{block debug}
<?php echo "\n\nZapujčka: "; print_r($Zapujcka); ?>

@{/block}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovna:Zapujcky:default}">Zápůjčky</a> - detail zápůjčky
    </div>

    <div id="dokument_blok_volby">
        {if $Zapujcka->stav == 1 && $Opravnen_schvalit_zapujcku}
        <a href="{link :Spisovna:Zapujcky:schvalit, 'id'=>$Zapujcka->id}">Schválení zápůjčky</a>
        <a href="{link :Spisovna:Zapujcky:odmitnuti, 'id'=>$Zapujcka->id}">Odmítnutí zápůjčky</a>
        {/if}
        {if $Zapujcka->stav == 2}
        <a href="{link :Spisovna:Zapujcky:vratit, 'id'=>$Zapujcka->id}">Vrátit dokument</a>
        {/if}
    </div>

    <div id="dokument_blok_hlavni">
        <dl class="detail_item">
            <dt>Zapůjčený dokument:</dt>
            <dd><a href="{link :Spisovka:Dokumenty:detail, 'id'=>$Zapujcka->dokument_id}">{$Zapujcka->cislo_jednaci}{if $Typ_evidence=='sberny_arch'}{$Oddelovac_poradi}{$Zapujcka->poradi}{/if} - {$Zapujcka->nazev}</a></dd>
        </dl>
        <dl class="detail_item">
            <dt>Zapůjčeno komu:</dt>
            <dd>{=Osoba::displayName($Zapujcka)}</dd>
        </dl>        
        <dl class="detail_item">
            <dt>Důvod zapůjčení:</dt>
            <dd>{!$Zapujcka->duvod|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum výpůjčky:</dt>
            <dd>{$Zapujcka->date_od|edate}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vrácení:</dt>
            <dd>{$Zapujcka->date_do|edate}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Stav:</dt>
            <dd>{=Zapujcka::stav($Zapujcka->stav)}</dd>
        </dl>        
        
    </div>


    <div id="dialog"></div>