@{block title}Zápůjčka{/block}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovka:Zapujcky:default}">Zápůjčky</a> - detail zápůjčky
    </div>

    <div id="error">
        <h2>Požadovaná zápůjčka neexistuje!</h2>
        <p>
            Pokoušíte se zobrazit zápůjčku, která neexistuje.
            <br />
            Zkontrolujte správnost zadané adresy nebo odkazu.
        </p>
    </div>