    <h2>Detail role</h2>

    <p>
        Pokud chcete vidět a upravovat Oprávnění pro již existující role, stačí najet a klepnout na jeden z názvů rolí. Otevře se vám nová obrazovka se základními informacemi a oprávněním. Základní informace můžete upravovat tak, že klepnete na nápis Upravit.
    </p>    
    <p>
    V případě, že budete chtít upravovat oprávnění dané role, pod základními informacemi naleznete soupis oprávnění přístupu do různých sekcí. Na konci každého řádku se nacházejí dva zaškrtávací boxy. Když zaškrtnete první, tak tím dané oprávnění povolujete, pokud ho chcete naopak zakázat, zaškrtněte druhé pole. Jakmile máte všechny změny zaškrtané, najeďte do dolní části obrazovky a klepněte na tlačítko Upravit oprávnění. V horní části okna budete informování o úspěšném změnění práv.    
    </p>