    <h2>Nová role</h2>
<p>    
Pokud chcete do seznamu přidat ještě nějakou další roli, stačí najet na odkaz Nová role a klepnout na něj. Po otevření nové obrazovky na vás čeká formulář s následujícími položkami:

    <dl>
        <dt>Název role</dt>
        <dd>Jedná se obecný název role. Bude uvedeno při identifikaci role uživatelem.</dd>
    </dl>
    <dl>
        <dt>Kódové označení</dt>
        <dd>Tato položka obsahuje jedinečný kód role, která se používá pro vnitřní použití aplikace.</dd>
    </dl>
    <dl>
        <dt>Popis role</dt>
        <dd>Stručný popis role</dd>
    </dl>
    <dl>
        <dt>Dědí z role</dt>
        <dd>U této položky máte možnost v rozbalovacím menu vybrat jednu z rolí, která bude určovat oprávnění i pro vaši novou roli.</dd>
    </dl>

Jakmile máte vše nastavené, stačí klepnout na tlačítko Vytvořit. Pokud jste se rozhodli, že nepotřebujete vytvářet novou roli, klepněte na tlačítko Zrušit.
</p>
    