    <h2>Seznam spisů</h2>

    <div>Po kliknutí na tlačítko Spisy se vám zobrazí seznam všech spisů, které jsou</div>
    <div>vytvořeny. Jednotlivé spisy lze rozkliknout a podívat se na bližší informace o</div>
    <div>spisu, ty lze upravit poté, co kliknete na nápis Upravit. Dále zde také najdete</div>
    <div>seznam všech dokumentů, které mají otevřený spis nastavený jako spisovou</div>
    <div>značku.</div>
    <br/>
