    <h2>Seznam spisů</h2>
<p>
Po klepnutí na tlačítko Spisy se vám zobrazí seznam spisů, které jsou přiděleny na vaši organizační jednotku. Jednotlivé spisy lze rozklepnout a podívat se na bližší informace o spisu.
</p>

<br />
Seznam spisů obsahuje následující sloupce:
<br /><br />
    <ul>
        <li><strong>Spis</strong> (název spisu)</li>
        <li><strong>Počet dokumentů</strong> (počet dokumentů, které spis obsahuje)</li>
        <li><strong>Přiděleno</strong> (organizační jednotka, která spis vlastní)</li>
        <li><strong>Předáno</strong> (organizační jednotka, které byl spis předán)</li>
        <li><strong>Spisový znak</strong></li>
        <li><strong>Skartační znak a lhůta</strong></li>
        <li><strong>Stav</strong> (zobrazuje aktuální stav spisu)</li>
    </ul>


<br />
<h3>Nový spis</h3>
<p>
V horní části okna naleznete odkaz Nový spis, pomocí kterého lze nový spis vytvořit. Jakmile na tento odkaz klepnete, tak jste přesměrováni na stránku s formulářem k tvorbě nového spisu
</p>

<br />
<h3>Hledat</h3>
<p>
Další funkcí, kterou v sekci Spisy můžete využít, je funkce hledat, která je zde dostupná pouze v jednoduché formě. Tudíž stačí do textového pole napsat název nebo část názvu spisu a poté klepnout na tlačítko hledat.
</p>

<br />
<h3>Tisk</h3>
<p>
Seznam spisů je možné vytisknout na obrazovku nebo do formátu PDF. Oproti seznamu, kterou vidíte na obrazovce, se v tisku zobrazí i seznam dokumentů, které ke spisu patří.
</p>

<br />
<h3>Akce</h3>
<p>
Každá položka má u sebe na začátku řádku zaškrtávací box, který souvisí s funkcí Akce, která se nachází v patičce tabulky společně s možnostmi zaškrtnout vše / Odškrtnout vše.
<br />
Celá funkce funguje tak, že zaškrtnete ty položky, u kterých chcete provést jednotnou akci, poté klepnete na rozbalovací menu v patičce tabulky, vyberete jednu z akcí a klepnete na tlačítko provést.
</p>

