    <h2>Detail spisu</h2>

    <p>
Pokud si chcete prohlédnout detaily spisu, stačí na něho najet a klepnout na název spisu, který si chcete prohlédnout. Jakmile tak učiníte, zobrazí se vám stránka s detaily spisu. Tato stránka by se dala rozdělit na dvě části – Informace o spisu a Seznam dokumentů.
</p>
<p>    
Informace o spisu obsahují všechny položky, které se zadávají při tvorbě nového spisu, plus zde vidíte stav, přiděleno a předáno. 
<br />
Spis může upravovat pouze organizační jednotka, která spis vlastní (je uveden v položce přiděleno).
<br />
Rozhodnete-li se spis uzavřít, je k tomu dispozici tlačítko uzavřít spis. Případně v nutných případech spis znovu otevřít.
<br />
Spis i všechny jeho dokumenty jsou ve vlastnictví organizační jednotky. Pokud by bylo potřeba kteroukoli část předat jiné organizační jednotce, pak se celý spis předá. K tomu slouží tlačítko "Předat spis". Po jeho kliknutí se zobrazí seznam všech organizačních jednotek a kliknutím na organizační jednotku se spis předá.
Proces předávání je dvoukrokový. To znamená, že předaná strana musí potvrdit převzetí spisu. To provede kliknutím na tlačítko "Převzít spis" nebo může spis odmítnout kliknutím na "Odmítnout převzetí". Pokud předávající nepotvrdí převzetí, je spis nadále ve vlastnictví přiděleného. Tento může převzetí spisu zrušit.
</p>
<p>
V sekci Seznam dokumentů můžete vidět všechny dokumenty, které spis obsahuje a také zde máte nad seznamem odkaz Nový dokument, na který když klepnete, tak se vám zobrazí formulář pro tvorbu nového dokumentu s předvyplněnou položkou spisu.
</p>    