    <h2>Nový spis</h2>
<p>
Pokud ve spisech klepnete na odkaz Nový spis, zobrazí se vám formulář sloužící k tvorbě spisů. Obsahuje tyto položky:

    <dl>
        <dt>Název spisu</dt>
        <dd>Jedná se o povinnou položku</dd>
    </dl> 
    <dl>
        <dt>Popis</dt>
        <dd>Popis spisu</dd>
    </dl> 
    <dl>
        <dt>Složka</dt>
        <dd>Vyberte v rozbalovacím menu požadovanou složku</dd>
    </dl> 
    <dl>
        <dt>Spisový znak</dt>
        <dd>Vyberte v rozbalovacím menu požadovaný spisový znak</dd>
    </dl> 
    <dl>
        <dt>Skartační znak</dt>
        <dd>Vyberte v rozbalovacím menu požadovaný skartační znak</dd>
    </dl> 
    <dl>
        <dt>Skartační lhůta</dt>
        <dd>Jakmile vyberete Spisový a skartační znak, tak se skartační lhůta vyplní automaticky</dd>
    </dl> 
    <dl>
        <dt>Spouštěcí událost</dt>
        <dd>Vyberte v rozbalovacím menu požadovanou událost</dd>
    </dl> 
    <dl>
        <dt>Datum otevření</dt>
        <dd>Automaticky se vyplní datum podle vašeho systémového času</dd>
    </dl> 
    <dl>
        <dt>Datum uzavření</dt>
        <dd>Automaticky se vyplní datum podle vašeho systémového času, jakmile uzavřete spis</dd>
    </dl> 

</p>
<p>
Jakmile máte vše vyplněno, můžete klepnout na tlačítko Vytvořit nebo pokud jste si tvorbu nového spisu rozmysleli, tak klikněte na tlačítko Zrušit.
</p>
    
