@{block title}Seznam spisů{/block}
@{block debug}
<?php print_r($seznam); ?>
@{/block}
@{block content}

    <h2>Seznam spisů</h2>

    <div id="search">
        {control searchForm}
    </div>

    <div id="dokumenty">
    {if count($seznam)>0}
    <form action="{link this}" method="post">
        <input type="hidden" name="url_referer" value="">
    <table>
        <tr>
            <th class="akce">&nbsp;</th>
            <th>Spisy</th>
        </tr>
        {foreach $seznam as $spis}
        <tr class="{$spis->class}" id="sitem{$spis->spis_id}">
            <td class="akce">
                {if $spis->typ=='S'}
                <input type="checkbox" class="checkbox" name="spis_vyber[]" value="{$spis->id}" title="Vybrat tento spis" />
                {/if}&nbsp;
            </td>
            <td>
                {!=str_repeat("&nbsp;", 5*$spis->uroven)}
                {if $spis->typ=='VS'}
                <img src="{$baseUri}images/icons/folder_yellow.png" alt="složka" title="složka" width="16" height="16" onclick="return toggle('item{!$spis->id}');" />
                &nbsp;&nbsp;
                {$spis->nazev}
                {else}
                <img src="{$baseUri}images/icons/spisy.png" alt="Spis" title="Spis" width="16" height="16" />
                &nbsp;&nbsp;
                <a href="{link :Spisovna:Spisy:detail, 'id'=>$spis->id }">{$spis->nazev}</a>
                {/if}
            </td>
        </tr>
        {/foreach}

    </table>
    <div id="hromadna_akce">
        <span id="checkbox_all_on">Zaškrtnout vše</span> / <span id="checkbox_all_off">Odškrtnout vše</span>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Vybrané položky:&nbsp;&nbsp;
        <select name="hromadna_akce">
            <option value="">(žádná akce)</option>
            {if isset($akce_select)}{foreach $akce_select as $as_index => $as_value}
            <option value="{$as_index}">{$as_value}</option>
            {/foreach}{/if}
        </select>
        <input type="submit" name="hromadna_submit" value="Provést" />
    </div>
    </form>
    {widget vp}
    {else}
    <br class="clear">
    <div class="prazdno">Nebyly zjištěny žádné spisy.</div>
    {/if}
    </div>