@{block title}Seznam spisů{/block}
@{block debug}
<?php print_r($seznam); ?>
@{/block}
@{block content}
    <div class="navigate">
    <a href="{link :Spisovna:Dokumenty:default}">Seznam dokumentů</a> -
    <a href="{link :Spisovna:Spisy:default}">Seznam spisů</a> -
    Detail spisu
    </div>

    <h2>{$Spis->nazev}</h2>

    <div class="detail_blok">
        <div class="detail_hlavicka">Informace o spisu</div>
        <dl class="detail_item">
            <dt>Spisová značka:</dt>
            <dd>{$Spis->nazev}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{$Spis->popis}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{=Spis::spisovyZnak($Spis,1)}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Spis->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$Spis->skartacni_lhuta}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{=SpisovyZnak::spousteci_udalost($Spis->spousteci_udalost_id,10)}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Stav:</dt>
            <dd>
                {=Spis::stav($Spis->stav)}
            </dd>
        </dl>
    </div>

    <div class="detail_blok">
        <div class="detail_hlavicka">Seznam dokumentů</div>
    </div>
    <div id="dokumenty">
    {if count($seznam)>0}
    <table>

        <tr>
            <th class="typ">Typ dokumentu</th>
            <th class="prijato">Přijato<br />Vyřízeno</th>
            <th class="cislo_jadnaci">Číslo jednací<br />JID<br />Spisová značka</th>
            <th class="vec">Věc<br />Adresáti/odesílatelé<br />počet listů a příloh</th>
            <th class="prideleno">Přiděleno</th>
            <th class="stav">Spisový znak<br/>Skartační znak<br/>Skartační lhůta</th>
        </tr>

        {foreach $seznam as $dok}
        <tr>
            <td class="typ">
                <img src="{$baseUri}images/icons/smer{$dok->typ_dokumentu->smer}.png" alt="{$dok->typ_dokumentu->nazev}" title="{$dok->typ_dokumentu->nazev}" width="16" height="16" />
            </td>
            <td class="prijato">
                <span title="{$dok->datum_vzniku|edatetime}">{$dok->datum_vzniku|edate}</span>
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
            </td>
            <td class="cislo_jadnaci">
                &nbsp;<strong><a href="{link :Spisovna:Dokumenty:detail, 'id'=>$dok->id}">
                   {$dok->cislo_jednaci}{if $Typ_evidence=='sberny_arch'}{$Oddelovac_poradi}{$dok->poradi}{/if}
                </a></strong>
                <div class="small">&nbsp;{$dok->jid}</div>
                {if count($dok->spisy)>0}
                {foreach $dok->spisy as $spis}
                <a href="{link :Spisovna:Spisy:detail, 'id'=>$spis->id}">{$spis->nazev}</a><br />
                {/foreach}
                {/if}
            </td>
            <td class="vec">
                <strong title="{$dok->popis}"><a href="{link :Spisovna:Dokumenty:detail, 'id'=>$dok->id}">
                    {$dok->nazev}
                </a></strong>
                <br />
                {if count($dok->subjekty)>0}
                {foreach $dok->subjekty as $subjekt}
                {=Subjekt::displayName($subjekt,'plna_adresa')}<br />
                {/foreach}
                {else}
                nejsou přiděleny žádné subjekty!<br />
                {/if}
                <span style="font-size: 8pt;">přílohy:
                {=($dok->pocet_listu)+0} listů,
                {=($dok->pocet_priloh)+0} list. příloh,
                {=(count($dok->prilohy)+0)} příloh</span>
            </td>
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                001.200.5456
                <br />
                {$dok->skartacni_znak} / {$dok->skartacni_lhuta}
            </td>
        </tr>
        {/foreach}


    </table>
    {else}
        <div>&nbsp;</div>
        {if isset($no_items)}
        {if $no_items==1}
        <div class="prazdno">Nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==2}
        <div class="prazdno">K danému filtru nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==3}
        <div class="prazdno">Dokument odpovidající hledanému výrazu nebyl nalezen.</div>
        {/if}
        {else}
    <div class="prazdno">K tomuto spisu nebyly zjištěny žádné dokumenty.</div>
        {/if}
    {/if}
    </div>