@{block title}Spis{/block}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovka:Dokumenty:default}">Seznam dokumentů</a> -
    <a href="{link :Spisovka:Spisy:default}">Seznam spisů</a> -
    Detail spisu
    </div>

    <div id="error">
        <h2>Požadovaný spis neexistuje!</h2>
        <p>
            Pokoušíte se zobrazit spis, který neexistuje.
            <br />
            Zkontrolujte správnost zadané adresy nebo odkazu.
        </p>
    </div>