@{block title}Seznam spisů pro příjem do spisovny{/block}
@{block debug}
<?php print_r($seznam); ?>
@{/block}
@{block content}

    <h2>Seznam spisů pro příjem do spisovny</h2>

    <div id="dokument_blok_volby">
        {$spisplanForm->render('begin')}
        {$spisplanForm['spisplan']->label} {$spisplanForm['spisplan']->control}
        {$spisplanForm['go_spisplan']->control}
        {$spisplanForm->render('end')}
    </div>

    {if isset($SpisovyPlan) }

    <h2>{$SpisovyPlan->nazev}</h2>

    <div class="dokument_blok">
        <dl class="detail_item">
            <dt>Spisový znak: </dt>
            <dd>
                {=Spis::spisovyZnak($SpisovyPlan)}&nbsp;
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Otevřeno dne: </dt>
            <dd>
                {$SpisovyPlan->datum_otevreni|edate}&nbsp;
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Uzavřeno dne:</dt>
            <dd>
                {$SpisovyPlan->datum_uzavreni|edate}&nbsp;
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznamka:</dt>
            <dd>
                {!$SpisovyPlan->popis|enl2br}&nbsp;
            </dd>
        </dl>
    </div>
    <br />

    <div id="search">
        {control searchForm}
    </div>

    <div id="dokumenty">
    {if count($seznam)>0}
    <form action="{link this}" method="post">
        <input type="hidden" name="url_referer" value="">
    <table>
        <tr>
            <th class="akce">&nbsp;</th>
            <th>Spis / Věcná skupina</th>
        </tr>
        {foreach $seznam as $spis}
        <tr class="{$spis->class}" id="sitem{$spis->spis_id}">
            <td class="akce">
                {if $spis->typ=='S'}
                <input type="checkbox" class="checkbox" name="spis_vyber[]" value="{$spis->id}" title="Vybrat tento spis" />
                {/if}&nbsp;
            </td>
            <td>
                {!=str_repeat("&nbsp;", 5*$spis->uroven)}
                {if $spis->typ=='VS'}
                <img src="{$baseUri}images/icons/folder_yellow.png" alt="Věcná skupina" title="Věcná skupna" width="16" height="16" onclick="return toggle('item{!$spis->id}');" />
                &nbsp;&nbsp;
                {$spis->nazev}
                {else}
                <img src="{$baseUri}images/icons/spisy.png" alt="Spis" title="Spis" width="16" height="16" />
                &nbsp;&nbsp;
                <a href="{link :Spisovna:Spisy:detail, 'id'=>$spis->id }">{$spis->nazev}</a>
                {/if}
            </td>
        </tr>
        {/foreach}

    </table>
    <div id="hromadna_akce">
        <span id="checkbox_all_on">Zaškrtnout vše</span> / <span id="checkbox_all_off">Odškrtnout vše</span>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Vybrané položky:&nbsp;&nbsp;
        <select name="hromadna_akce">
            <option value="">(žádná akce)</option>
            <option value="prevzit_spisovna">převzetí vybraných spisů do spisovny</option>
        </select>
        <input type="submit" name="hromadna_submit" value="Provést" />
    </div>
    </form>
    {widget vp}
    {else}
    <br class="clear">
    <div class="prazdno">Nebyly zjištěny žádné spisy.</div>
    {/if}
    </div>
    {else}
    <br class="clear">
    <div class="prazdno">Nebyl zjištěn žádný spisový plán.</div>
    {/if}
