<div class="ciselnik">

    <div class="blok_menu">
        <a n:href="this, novy => 1">Nový záznam</a>
    </div>

{if count($data)>0}
    <table class="spisovka">
        <tr>
            {foreach $cols as $col_name => $col_params}
            <th>{$col_params['title']}</th>
            {/foreach}
        </tr>
        {foreach $data as $row}
        <tr>
            {foreach $cols as $col_name => $col_params}
            <td>
            {if $col_params['link']}
            <a n:href="this, edit => $row->$primaryKeyName" {if isset($row->fixed) && $row->fixed}onclick="return confirm('Záznam by neměl být nikdy měněn! Pokračujte pouze pokud opravdu víte, co děláte.')"{/if}>
            {/if}
            {if $col_params['form'] == "checkbox" }
                {if $row->$col_name == 1}ano{else}ne{/if}
            {elseif $col_params['form'] == "select" }
                {if isset($col_params['form_select'][$row->$col_name])}{$col_params['form_select'][$row->$col_name]}{else}{$row->$col_name}{/if}
            {elseif $col_params['form'] == "selectStav" }
                {if $row->$col_name == 1}Aktivní{else}Neaktivní{/if}
            {elseif $col_name == "fixed" }
                {if $row->$col_name == 1}ano{else}ne{/if}
            {elseif empty($row->$col_name) && $col_params['link']}
                (bez názvu)
            {else}
                {$row->$col_name}
            {/if}
            {if $col_params['link']}
                </a>
            {/if}
            </td>
            {/foreach}
        </tr>
        {/foreach}        
    </table>
{else}    
<div class="ciselnik_noresult">Nenalezena žádná data.</div>    
{/if}
</div>