@{block title}Seznam dokumentů k odeslání{/block}
@{block debug}
<?php print_r($seznam); ?>
@{/block}
@{block content}
    <h2>Seznam dokumentů k odeslání</h2>

    <div id="tisk">
        <!-- <a href="{link this, 'print' => 1}" title="vytisknout podací arch na doporučené dopisy" target="_blank">
            <img src="{$baseUri}images/icons/printer.png" alt="printer.png" width="32" height="32" />
        </a> -->
        <a href="{link this, 'print' => 1}" title="Vytisknout podací arch na doporučené dopisy" target="_blank">
            <img src="{$baseUri}images/icons/printer.png" alt="application-pdf.png" width="32" height="32" />
        </a>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{link this, 'print_balik' => 1}" title="Vytisknout podací arch na balíky" target="_blank">
            <img src="{$baseUri}images/icons/printer.png" alt="application-pdf.png" width="32" height="32" />
        </a>          
        
    </div>
    
    <div id="filtr" style="margin-bottom: 0px">
        <a href="{link :Spisovka:Vypravna:filtrovat}" onclick="return dialog(this, 'Výběr filtrování');">Filtrovat</a>{if $zobraz_zrusit_filtr}&nbsp;&nbsp;<a href="{link :Spisovka:Vypravna:reset, 'reset' => 'filtr'}" >Zrušit filtr</a>&nbsp;&nbsp;&nbsp;{/if}   
    </div>
    <div id="search" style="margin-bottom: 0px">
        {control searchForm}
        <div id="search_advanced">
        {if !empty($zobraz_zrusit_hledani)}<a href="{link :Spisovka:Vypravna:reset, 'reset' => 'hledat'}" style="color:#ff0000;">Zrušit vyhledávání</a>&nbsp;&nbsp;&nbsp;{/if}        
        </div>
    </div>    
    
    <br style="clear:both;" />
    
    <div id="seradit" style="margin: 3px 0px;">
    {control seraditForm}
    </div>    
    
    <div id="dokumenty">
    {if count($seznam)>0}
    <form action="{link this}" method="post">
        <input type="hidden" name="url_referer" value="">
    <table>
        <tr>
            <th class="akce">&nbsp;</th>
            <th class="typ">Způsob odeslání</th>
            <th class="cislo_jednaci">Číslo jednací<br />JID<br />Název spisu</th>
            <th class="vec">Adresát</th>
            <th class="uzel">Předal</th>
            <th class="prideleno">Druh zásilky/cena/hmotnost/zpráva</th>
        </tr>
        {foreach $seznam as $dok}
        <tr>
            <td class="akce">
                <input type="checkbox" class="checkbox" name="dokument_vyber[]" value="{$dok->dokodes_id}" title="Vybrat tento záznam" />
            </td>
            <td class="typ">
                {$dok->zpusob_odeslani_nazev}
            </td>
            <td class="cislo_jednaci">
                &nbsp;<strong><a href="{link :Spisovka:Dokumenty:detail, 'id'=>$dok->dokument_id}" title="Zobrazit detail dokumentu">
                   {if empty($dok->dok_cislo_jednaci)}
                   (není evidován)
                   {else}
                   {$dok->dok_cislo_jednaci}{if $Typ_evidence=='sberny_arch'}{$Oddelovac_poradi}{$dok->dok_poradi}{/if}
                   {/if}
                </a></strong>
                <div class="small">&nbsp;{$dok->dok_jid}</div>
            </td>
            <td class="vec">
                <strong><a href="{link :Spisovka:Vypravna:detail, 'id'=>$dok->dokodes_id}" title="Zobrazit detail záznamu" onclick="return vypravnaDetail(this);">{=Subjekt::displayName($dok,'jmeno_item')}</a></strong>
                <div class="mezera">
                {if $dok->zpusob_odeslani_id == 1 }    
                {=Subjekt::displayName($dok,'email')}
                {elseif $dok->zpusob_odeslani_id == 2 }    
                {=Subjekt::displayName($dok,'isds')}
                {elseif $dok->zpusob_odeslani_id == 4 }    
                {$dok->cislo_faxu}
                {else}    
                {=Subjekt::displayName($dok,'adresa')}
                {/if}    
                </div>
            </td>
            <td class="uzel">
                {=Osoba::displayName($dok,'user')}
            </td>
            <td class="prideleno">
                {if $dok->zpusob_odeslani_id == 3 }    
                {!=DruhZasilky::vypis($dok->druh_zasilky)}
                {if !empty($dok->cena_zasilky)}<br />cena: {$dok->cena_zasilky} Kč{/if}
                {if !empty($dok->hmotnost_zasilky)}<br />hmotnost: {$dok->hmotnost_zasilky} Kč{/if}
                {elseif $dok->zpusob_odeslani_id == 4 }    
                <a href="{link :Spisovka:Vypravna:zobrazfax, 'id'=>$dok->dokodes_id}" onclick="return zobrazFax(this);" title="Zobrazit zprávu pro příjemce">zobrazit zprávu</a>
                {/if}                 
                &nbsp;
            </td>
        </tr>
        {/foreach}


    </table>
    <div id="hromadna_akce">
        <span id="checkbox_all_on">Zaškrtnout vše</span> / <span id="checkbox_all_off">Odškrtnout vše</span>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Vybrané položky:&nbsp;&nbsp;
        <select name="hromadna_akce">
            <option value="">(žádná akce)</option>
            <option value="odeslat">odesláno</option>
            <option value="vratit">vrátit</option>
        </select>
        <input type="submit" name="hromadna_submit" value="Provést" />
    </div>
    </form>
    {else}
        <div>&nbsp;</div>
        <div class="prazdno">Nebyly zjištěny žádné dokumenty k odeslání.</div>
    {/if}
    </div>

    <div id="dialog"></div>