{capture $html_out}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <title>Podací arch</title>
    <style type="text/css" media="screen, print">
        <?php echo file_get_contents(APP_DIR .'/../public/css/podacicc_arch.css'); ?>
    </style>
	<STYLE>
		<!-- 
		BODY,DIV,TABLE,THEAD,TBODY,TFOOT,TR,TH,TD,P { font-family:"Arial"; font-size:x-small }
		 -->
	</STYLE>    
</head>
<body>
<TABLE FRAME=VOID CELLSPACING=0 COLS=13 RULES=NONE BORDER=0>
	<COLGROUP><COL WIDTH=1><COL WIDTH=104><COL WIDTH=179><COL WIDTH=134><COL WIDTH=158><COL WIDTH=29><COL WIDTH=36><COL WIDTH=53><COL WIDTH=21><COL WIDTH=73><COL WIDTH=77><COL WIDTH=77><COL WIDTH=89></COLGROUP>
	<TBODY>
		<TR>
			<TD WIDTH=1 HEIGHT=22 ALIGN=LEFT><BR></TD>
			<TD ROWSPAN=2 WIDTH=104 ALIGN=LEFT><BR><IMG SRC="{$baseUri}images/ceska_posta.jpg" WIDTH=40 HEIGHT=27 HSPACE=31 VSPACE=6>
			</TD>
			<TD WIDTH=179 ALIGN=LEFT><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD WIDTH=134 ALIGN=LEFT><BR></TD>
			<TD WIDTH=158 ALIGN=LEFT><B>POŠTOVNÍ PODACÍ ARCH</B></TD>
			<TD WIDTH=29 ALIGN=LEFT><BR></TD>
			<TD WIDTH=36 ALIGN=LEFT><BR></TD>
			<TD WIDTH=53 ALIGN=LEFT><BR></TD>
			<TD WIDTH=21 ALIGN=LEFT><BR></TD>
			<TD WIDTH=73 ALIGN=LEFT><BR></TD>
			<TD WIDTH=77 ALIGN=LEFT><BR></TD>
			<TD WIDTH=77 ALIGN=LEFT><BR></TD>
			<TD WIDTH=89 ALIGN=LEFT><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=17 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><B><FONT SIZE=1><BR></FONT></B></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=22 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT colspan="11">Česká pošta, s.p., IČ 47114983</TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=15 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><FONT SIZE=1>Číslo přílohy</FONT></TD>
                        <TD STYLE="border-top: 3px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000;" ALIGN=LEFT>&nbsp;<BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=23 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT colspan="10"><B>ODESÍLATEL _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ </B></TD>
			<TD ALIGN=LEFT><FONT SIZE=1>přijímací knihy</FONT></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000;" ALIGN=LEFT><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=27 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT>Datum:</TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000" ALIGN=LEFT><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=17 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000;" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000;" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000;" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-left: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000" ALIGN=CENTER><FONT SIZE=1>Udaná cena</FONT></TD>
			<TD STYLE="border-top: 3px solid #000000; border-left: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-left: 1px solid #000000" ALIGN=CENTER>Placeno</TD>
			<TD STYLE="border-top: 3px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=17 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-right: 1px solid #000000" ALIGN=CENTER>Podací </TD>
			<TD STYLE="border-right: 1px solid #000000" ALIGN=CENTER>Jméno a příjmení adresáta</TD>
			<TD STYLE="border-right: 1px solid #000000" ALIGN=CENTER>Adresní pošta</TD>
			<TD STYLE="border-right: 1px solid #000000" ALIGN=CENTER><BR></TD>
			<TD STYLE="border-left: 1px solid #000000; border-right: 1px solid #000000" COLSPAN=2 ALIGN=CENTER>Hmotnost</TD>
			<TD STYLE="border-left: 1px solid #000000; border-right: 3px solid #000000" COLSPAN=2 ALIGN=CENTER>Dobírka</TD>
			<TD ALIGN=CENTER><FONT SIZE=1>Vplacená </FONT></TD>
			<TD STYLE="border-left: 1px solid #000000" ALIGN=LEFT>Cena služby</TD>
			<TD STYLE="border-left: 1px solid #000000" ALIGN=CENTER>v hotovosti</TD>
			<TD STYLE="border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=17 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-right: 1px solid #000000" ALIGN=CENTER>číslo</TD>
			<TD STYLE="border-right: 1px solid #000000" ALIGN=CENTER>(název organizace)</TD>
			<TD STYLE="border-right: 1px solid #000000" ALIGN=CENTER>(PSČ, místo určení)</TD>
			<TD STYLE="border-right: 1px solid #000000" ALIGN=CENTER>Ulice, číslo domu</TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000" ALIGN=CENTER><FONT SIZE=1>částka</FONT></TD>
			<TD STYLE="border-bottom: 1px solid #000000; border-left: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000; border-left: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=CENTER>Poznámka</TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=17 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-right: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-right: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-right: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER>kg</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER>g</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER>Kč</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=CENTER>h</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER>Kč</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER>Kč</TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=CENTER>Kč</TD>
			<TD STYLE="border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=CENTER><FONT SIZE=1>(doplňkové služby)</FONT></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=17 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT>Převod:</TD>
			<TD STYLE="border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000" ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT><BR></TD>
		</TR>

            
                <TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 1px solid #000000; border-bottom: 1px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD STYLE="border-right: 3px solid #000000" HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-bottom: 3px solid #000000; border-left: 3px solid #000000; border-right: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;@"><BR></TD>
		</TR>
		<TR>
			<TD HEIGHT=32 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><FONT SIZE=1>11-038                     Vydáno ČP, s.p.</FONT></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT SDNUM="1029;0;0">Převod - úhrn:</TD>
			<TD ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 3px solid #000000" ALIGN=LEFT SDNUM="1029;0;0"><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-bottom: 3px solid #000000; border-left: 3px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-bottom: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-bottom: 3px solid #000000; border-left: 1px solid #000000; border-right: 1px solid #000000" ALIGN=LEFT SDNUM="1029;0;0,00"><BR></TD>
			<TD STYLE="border-top: 3px solid #000000; border-left: 3px solid #000000" ALIGN=LEFT><BR></TD>
		</TR>
	</TBODY>
</TABLE>
<!-- ************************************************************************** -->
</BODY>

</HTML>
{/capture}<?php

            $app_info = Environment::getVariable('app_info');
            $app_info = explode("#",$app_info);
            $app_name = (isset($app_info[2]))?$app_info[2]:'OSS Spisová služba v3';

            $pdf = new mPDF('', 'A4-L',9,'Helvetica');
            $pdf->SetCreator($app_name);
            $pdf->SetAuthor(Environment::getUser()->getIdentity()->name);
            $pdf->SetTitle('Poštovní podací arch');
            
            $pdf->WriteHTML($html_out);
            $pdf->Output('podaci_arch.pdf', 'I');
            //echo $html_out;
            
?>