{capture $html_out}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <title>Podací arch</title>
    <style type="text/css" media="screen, print">
        <?php echo file_get_contents(APP_DIR .'/../public/css/podaci_arch_new.css'); ?>
    </style>
</head>
<body>
<h1>POŠTOVNÍ PODACÍ ARCH</h1>

<img src="{$baseUri}images/ceska_posta1.png" widht="146" height="20" />


<p>Podavatel:</p>
<p>Odesílatel:</p>
    
<div class="placeno">
Placeno v hotovosti/Placeno převodem/Výplatní stroj (* Nehodící se škrtněte)
</div>
    
<table>
    <tr>
        <th class="w1">Poř. číslo</th>
        <th class="w2">Podací znaky</th>
        <th class="w3">Adresát - jméno, příjmení,<br> ulice, číslo domu,<br> PSČ, místo určení,<br> telefonní kontakt, email <sup>1)</sup></th>
        <th class="w4">Dobírka <sup>1)</sup></th>
        <th class="w5">Udaná cena <sup>2)</sup></th>
        <th class="w6">Poznámka,<br> doplňkové služby <sup>1)</sup></th>
    </tr>
{for $i=0;$i<10;$i++}    
    <tr>
        <td class="w1">&nbsp;</td>
        <td class="w2">&nbsp;</td>
        <td class="w3">&nbsp;</td>
        <td class="w4">&nbsp;</td>
        <td class="w5">&nbsp;</td>
        <td class="w6">&nbsp;</td>
    </tr>
{/for}
</table>

<div class="pod">
    <div class="posta">
    Česká pošta, s.p., IČ 47114983
    </div>

    <div class="razitko">
    Potvrzení pošty (otisk razítka APOST)
    </div>
</div>

<ol class="poznamky">
    <li>Vyplní odesílatel</li>
    <li>U Doporučených zásilek – standard, Doporučených zásilek, Doporučených zásilek do zahraničí, Doporučených slepeckých zásilek a
Doporučených slepeckých zásilek do zahraničí se neuvádí a sloupec se proškrtne.</li>
</ol>

</body>
</html>  
{/capture}<?php

            $app_info = Environment::getVariable('app_info');
            $app_info = explode("#",$app_info);
            $app_name = (isset($app_info[2]))?$app_info[2]:'OSS Spisová služba v3';

            $pdf = new mPDF('', 'A4',9,'Times');
            $pdf->SetCreator($app_name);
            $pdf->SetAuthor(Environment::getUser()->getIdentity()->name);
            $pdf->SetTitle('Poštovní podací arch');
            $pdf->SetMargins(0,0,2);
            
            $pdf->WriteHTML($html_out);
            $pdf->Output('podaci_arch.pdf', 'I');
            //echo $html_out;
            
?>