{if !$isPrint}<div id="dokument_blok_volby">
    <a href="{link :Spisovka:Vypravna:zobrazfax, 'id'=>$dokument->dokodes_id,'print'=>1}" target="_blank">Vytisknout zprávu</a>
</div>
<br />
{else}
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
  <title>Tisk faxu</title>
  </head>
  <body>
{/if}
<div>
{!$dokument->zprava|enl2br}
</div>
{if $isPrint}
  </body>
</html>
{/if}