    {$searchForm->render('begin')}
    <div id="dokument_blok_vyrizeni">
        <div class="h2">
            Dokument
        </div>
        <dl class="detail_item">
            <dt>Typ dokumentu:</dt>
            <dd>{$searchForm['dokument_typ_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Stav dokumentu:</dt>
            <dd>{$searchForm['stav_dokumentu']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací:</dt>
            <dd>{$searchForm['cislo_jednaci']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisová značka:</dt>
            <dd>{$searchForm['spisova_znacka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd>{$searchForm['nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{$searchForm['popis']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob doručení:</dt>
            <dd>{$searchForm['typ_doruceni']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum doručení/vzniku </dt>
            <dd>od: {$searchForm['datum_vzniku_od']->control} {$searchForm['datum_vzniku_cas_od']->control}</dd>
            <dd>do: {$searchForm['datum_vzniku_do']->control} {$searchForm['datum_vzniku_cas_do']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$searchForm['cislo_jednaci_odesilatele']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{$searchForm['poznamka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob vyžízení:</dt>
            <dd>{$searchForm['zpusob_vyrizeni']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyřízení:</dt>
            <dd>od: {$searchForm['datum_vyrizeni_od']->control} {$searchForm['datum_vyrizeni_cas_od']->control}&nbsp;</dd>
            <dd>do: {$searchForm['datum_vyrizeni_do']->control} {$searchForm['datum_vyrizeni_cas_do']->control}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob odeslání:</dt>
            <dd>{$searchForm['zpusob_odeslani']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum odeslání:</dt>
            <dd>od: {$searchForm['datum_odeslani_od']->control} {$searchForm['datum_odeslani_cas_od']->control}&nbsp;</dd>
            <dd>do: {$searchForm['datum_odeslani_do']->control} {$searchForm['datum_odeslani_cas_do']->control}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{$searchForm['spisovy_znak_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$searchForm['skartacni_znak']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$searchForm['skartacni_lhuta']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{$searchForm['spousteci_udalost']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{$searchForm['poznamka_vyrizeni']->control}&nbsp;</dd>
        </dl>
    </div>

    <div id="dokument_blok_poznamka">
        <div class="h2">
            Přidělěno / předáno
        </div>
        <dl class="detail_item">
            <dt>Přiděleno:</dt>
            <dd>
            {$searchForm['prideleno']->control}
            <br />{$searchForm['prideleno_osobne']->control} Přidělěno na mé jméno
            <br />{$searchForm['prideleno_na_organizacni_jednotku']->control} Přidělěno na mou organizační jednotku
            <script type="text/javascript">
            <!--
		$('#frmsearchForm-prideleno').focus().keyup(function(event) {
                    if ( $('#frmsearchForm-prideleno').val().length > 2 ) {
			$.getJSON({link autoComplete!}, { typ: 1, text: $('#frmsearchForm-prideleno').val()}, function(payload) {
				$('#prideleno').remove();

				var list = $('<ul id="prideleno"></ul>').insertAfter('#frmsearchForm-prideleno');

				for (var i in payload.autoComplete) {
					$('<li></li>').html(payload.autoComplete[i]).appendTo(list);
				}
			});
                    } else {
                        $('#prideleno').remove();
                    }
		});
            -->
            </script>
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Předáno:</dt>
            <dd>
            {$searchForm['predano']->control}
            <br />{$searchForm['predano_osobne']->control} Předáno na mé jméno
            <br />{$searchForm['predano_na_organizacni_jednotku']->control} Předáno na mou organizační jednotku
            <script type="text/javascript">
            <!--
		$('#frmsearchForm-predano').focus().keyup(function(event) {
                    if ( $('#frmsearchForm-predano').val().length > 2 ) {
			$.getJSON({link autoComplete!}, { typ: 2, text: $('#frmsearchForm-predano').val()}, function(payload) {
				$('#predano').remove();

				var list = $('<ul id="predano"></ul>').insertAfter('#frmsearchForm-predano');

				for (var i in payload.autoComplete) {
					$('<li></li>').html(payload.autoComplete[i]).appendTo(list);
				}
			});
                    } else {
                        $('#predano').remove();
                    }
		});
            -->
            </script>
            </dd>
        </dl>
    </div>

    <div id="dokument_blok_poznamka">
        <div class="h2">
            Adresáti / odesílatelé
        </div>
        <dl class="detail_item">
            <dt>Typ subjektu:</dt>
            <dd>{$searchForm['subjekt_type']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>Název subjektu, jméno, IČ:</dt>
            <dd>{$searchForm['subjekt_nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Ulice</dt>
            <dd>
                {$searchForm['adresa_ulice']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>PSČ a město:</dt>
            <dd>
                {$searchForm['adresa_psc']->control}
                {$searchForm['adresa_mesto']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>{$searchForm['subjekt_email']->label}:</dt>
            <dd>{$searchForm['subjekt_email']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$searchForm['subjekt_telefon']->label}:</dt>
            <dd>{$searchForm['subjekt_telefon']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$searchForm['subjekt_isds']->label}:</dt>
            <dd>{$searchForm['subjekt_isds']->control}</dd>
        </dl>

    </div>

    <div id="dokument_blok_akce">
        {$searchForm['vyhledat']->control}
    </div>
    {$searchForm->render('end')}

    <div id="dialog"></div>

    <script type="text/javascript">
        $(function() {
            var date = new Date();
            var year = date.getYear() + 1900;
            var year_before = year - 15;
            var year_after = year + 2;
            $("input.datepicker").datepicker(
            {
                showButtonPanel: true,
                changeMonth: true,
                changeYear: true,
                yearRange: year_before+':'+year_after,
                dateFormat : "dd.mm.yy",
                closeText:"Zrušit",
                prevText:"Předchozí",
                nextText:"Další",
                currentText:"Dnes",
                monthNames:["Leden","Únor","Březen","Duben","Květen","Červen","Červenec","Srpen","Září","Říjen","Listopad","Prosinec"],
                monthNamesShort:["Leden","Únor","Březen","Duben","Květen","Červen","Červenec","Srpen","Září","Říjen","Listopad","Prosinec"],
                dayNames:["Neděle","Pondělí","Úterý","Středa","Čtvrtek","Pátek","Sobota"],
                dayNamesMin:["Ne","Po","Út","St","Čt","Pá","So"]
            });
            $('input.datetimepicker').datepicker(
            {
                duration: '',
                changeMonth: true,
                changeYear: true,
                yearRange: '2007:2020',
                showTime: true,
                time24h: true,
                currentText: 'Dnes',
                closeText: 'OK'
            });
        });
    </script>