    <div id="dokument_blok_vyrizeni">
        <div class="h2">
            Filtr dokumentu
        </div>
        <dl class="detail_item">
            <dt>Typ dokumentu:</dt>
            <dd>{$form['dokument_typ_id']->control}</dd>
        </dl>
        {if isset($form['stav_dokumentu'])}
        <dl class="detail_item">
            <dt>Stav dokumentu:</dt>
            <dd>{$form['stav_dokumentu']->control}</dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Číslo jednací:</dt>
            <dd>{$form['cislo_jednaci']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Název spisu:</dt>
            <dd>{$form['spisova_znacka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd>{$form['nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{$form['popis']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob doručení přes epodatelnu:</dt>
            <dd>{$form['typ_doruceni']->control}</dd>
        </dl>        
        <dl class="detail_item">
            <dt>Způsob doručení:</dt>
            <dd>{$form['zpusob_doruceni_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum doručení/vzniku </dt>
            <dd>od: {$form['datum_vzniku_od']->control} {$form['datum_vzniku_cas_od']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$form['datum_vzniku_do']->control} {$form['datum_vzniku_cas_do']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$form['cislo_jednaci_odesilatele']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo doporučeného dopisu:</dt>
            <dd>{$form['cislo_doporuceneho_dopisu']->control}</dd>
            <dd>{$form['cislo_doporuceneho_dopisu_pouze']->control} pouze doporučené</dd>
        </dl>         
        <dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{$form['poznamka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob vyřízení:</dt>
            <dd>{$form['zpusob_vyrizeni']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyřízení:</dt>
            <dd>od: {$form['datum_vyrizeni_od']->control} {$form['datum_vyrizeni_cas_od']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$form['datum_vyrizeni_do']->control} {$form['datum_vyrizeni_cas_do']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <dl class="detail_item">
            <dt>Způsob odeslání:</dt>
            <dd>{$form['zpusob_odeslani']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum odeslání:</dt>
            <dd>od: {$form['datum_odeslani_od']->control} {$form['datum_odeslani_cas_od']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
            <dd>do: {$form['datum_odeslani_do']->control} {$form['datum_odeslani_cas_do']->control}&nbsp; datum (d.m.r) / čas (h:m:s)</dd>
        </dl>
        <?php if (1) { ?>
        <dl class="detail_item">
            <dt>Druh zásilky:</dt>
            <dd>
                <?php
                $druh_zasilky = array();
                if ( isset($params['druh_zasilky']) && !empty($params['druh_zasilky']) ) {
                    $druh_zasilky_a = unserialize($params['druh_zasilky']);
                    foreach ( $druh_zasilky_a as $druh ) {
                        $druh_zasilky[$druh] = $druh;
                    }
                }
                ?>
                {foreach $DruhZasilky as $dz_index=>$dz_nazev}
                <input type="checkbox" name="druh_zasilky[{$dz_index}]" <?php echo isset($druh_zasilky[$dz_index])?' checked="checked"':''; ?> />&nbsp;{$dz_nazev}
                {/foreach}
                &nbsp;
            </dd>
        </dl>     
        <?php }//if 0 ?>        
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{$form['spisovy_znak_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$form['skartacni_znak']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$form['skartacni_lhuta']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{$form['spousteci_udalost']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{$form['poznamka_vyrizeni']->control}&nbsp;</dd>
        </dl>
    </div>
