    <h2>Detail příchozí zprávy</h2>

<p>
Obsahuje detail příchozí zprávy.
</p>

<br />
<h3>Volby</h3>
<p>
    <dl>
        <dt>Zaevidovat do spisové služby</dt>
        <dd>kliknutím přejde k formuláři pro zaevidování do spisové služby</dd>
    </dl>    
    <dl>
        <dt>Zaevidovat v jiné evidenci</dt>
        <dd>kliknutím se zobrazí dialogové okno s vyplněním názvu jiné evidence</dd>
    </dl>    
    <dl>
        <dt>Odmítnout</dt>
        <dd>kliknutím dojde k zobrazení dialogového okna s formulářem pro vyplnění k odmítnutí zprávy</dd>
    </dl>    
</p>

<br />
<h3>Položky</h3>
<p>
    <dl>
        <dt>Identifikátor DZ v e-podatelně</dt>
        <dd>jednoznačný identifikátor e-podatelny</dd>
    </dl>    
    <dl>
        <dt>Typ zprávy</dt>
        <dd>obsahuje typ zprávy – email, datová zpráva</dd>
    </dl>    
    <dl>
        <dt>Schránka</dt>
        <dd>obsahuje schránku, kam byla zpráva přijata</dd>
    </dl>    
    <dl>
        <dt>Věc</dt>
        <dd>obsahuje předmět zprávy</dd>
    </dl>    
    <dl>
        <dt>Odesílatel</dt>
        <dd>obsahuje jméno a adresu odesílatele</dd>
    </dl>    
    <dl>
        <dt>Doručeno</dt>
        <dd>obsahuje datum a čas doručení do schránky</dd>
    </dl>    
    <dl>
        <dt>Přijato e-podatelnou</dt>
        <dd>obsahuje datum čas přijetí e-podatelnou</dd>
    </dl>    
    <dl>
        <dt>Identifikátor e-podatelny</dt>
        <dd>obsahuje identifikační prvky zprávy</dd>
    </dl>    
    <dl>
        <dt>Obsah zprávy</dt>
        <dd>obsahuje obsah zprávy</dd>
    </dl>    
    <dl>
        <dt>Přílohy</dt>
        <dd>obsahuje seznam příloh, které zpráva obsahuje</dd>
    </dl>    
</p>    
