    <h2>Detail zprávy</h2>
    <p>
        Pokud si přejete přejít do soupisu zpráv z E-podatelny, stačí jen kliknout na
        tlačítko E-podatelna, které naleznete v pravém horním rohu obrazovky. Jakmile
        na toto tlačítko kliknete, budete přesměrování na E-podatelnu. Uživatelské
        rozhraní se v ničem neliší, jen tlačítka menu jsou jiná a také je změněná grafika.
        Naleznete zde tato tlačítka:
    </p>
    <ul>
        <li>Zkontrolovat schránku</li>
        <li>Nové zprávy</li>
        <li>Příchozí zprávy</li>
        <li>Odchozí zprávy</li>
    </ul>
    <p>
        Úvodní stránka po přesměrování do E-podatelny je shodná s tlačítkem Nové zprávy.
        Tělo stránky tvoří tabulka přijatých zpráv, která obsahuje tyto údaje:
    </p>
    <ul>
        <li>Typ zprávy</li>
        <li>Doručeno/přijato EP</li>
        <li>ID</li>
        <li>Věc/odesilatel(é)</li>
        <li>Schránka</li>
        <li>Stav</li>
    </ul>
    <br />