    <h2>Seznam nových příchozích zpráv</h2>

<p>    
Obsahuje seznam všech nových zpráv.
</p>

<h3>Popis sloupců</h3>
<p>
    <dl>
        <dt>Typ zprávy</dt>
        <dd>obsahuje grafickou značku typu zprávy – pošta, email, datová zpráva</dd>
    </dl>
    <dl>
        <dt>Doručeno</dt>
        <dd>Obsahuje datum doručení do schránky</dd>
    </dl>
    <dl>
        <dt>Přijato EP</dt>
        <dd>Obsahuje datum přijetí e-podatelnou</dd>
    </dl>
    <dl>
        <dt>ID</dt>
        <dd>Jednoznačné identifikační číslo e-podatelny</dd>
    </dl>
    <dl>
        <dt>Věc</dt>
        <dd>Název zprávy (předmět emailu nebo datové zprávy)</dd>
    </dl>
    <dl>
        <dt>Odesílatel/-é</dt>
        <dd>Obsahuje jméno a adresu odesílatele případně odesílatelů</dd>
    </dl>
    <dl>
        <dt>Schránka</dt>
        <dd>Schránka, na kterou byla zpráva přijata.</dd>
    </dl>
    <dl>
        <dt>Stav</dt>
        <dd>Obsahuje aktuální stav zprávy v e-podatelně – nový přijatý, evidovaný, zamítnutý, jiná evidence</dd>
    </dl>
</p>    