    <h2>Seznam odchozích zpráv</h2>

<p>    
Obsahuje seznam všech odchozích zpráv.
</p>

<p style="color:red">
Obsahuje pouze odeslané zprávy pomocí spisové služby. Neslouží jako seznam odchozích zpráv z datové schránky nebo emailové schránky na cizím serveru.    
</p>

<h3>Popis sloupců</h3>
<p>
    <dl>
        <dt>Typ zprávy</dt>
        <dd>obsahuje grafickou značku typu zprávy – email, datová zpráva</dd>
    </dl>
    <dl>
        <dt>Odesláno</dt>
        <dd>Obsahuje datum odeslání z e-podatelny</dd>
    </dl>
    <dl>
        <dt>ID</dt>
        <dd>Jednoznačné identifikační číslo e-podatelny</dd>
    </dl>
    <dl>
        <dt>Věc</dt>
        <dd>Název zprávy (předmět emailu nebo datové zprávy). Pokud jej uživatel nezmění, je název zprávy stejný jako název dokumentu.</dd>
    </dl>
    <dl>
        <dt>Adresát</dt>
        <dd>Obsahuje jméno a adresu adresáta, kterému byla zpráva zaslána</dd>
    </dl>
    <dl>
        <dt>Odeslal</dt>
        <dd>Jméno uživatele, který zprávu odeslal</dd>
    </dl>
</p>        