    <h2>Seznam odchozích zpráv</h2>

<p>    
Obsahuje seznam všech odchozích zpráv.
</p>

<p style="color:red">
Obsahuje pouze seznam odeslaných zpráv z e-podatelny. Neslouží jako seznam odchozích zpráv z datové schránky nebo emailové schránky na cizím serveru.    
</p>

<h3>Popis sloupců</h3>
<p>
    <dl>
        <dt>Typ zprávy</dt>
        <dd>obsahuje grafickou značku typu zprávy – email, datová zpráva</dd>
    </dl>
    <dl>
        <dt>Odesláno</dt>
        <dd>Obsahuje datum odeslání z e-podatelny</dd>
    </dl>
    <dl>
        <dt>ID</dt>
        <dd>Jednoznačné identifikační číslo e-podatelny</dd>
    </dl>
    <dl>
        <dt>Věc</dt>
        <dd>Název zprávy (předmět emailu nebo datové zprávy)</dd>
    </dl>
    <dl>
        <dt>Adresát</dt>
        <dd>Obsahuje jméno a adresu adresáta, kterému byla zpráva zaslána</dd>
    </dl>
    <dl>
        <dt>Schránka</dt>
        <dd>Schránka, ze které byla zpráva odeslána.</dd>
    </dl>
    <dl>
        <dt>Stav</dt>
        <dd>Obsahuje aktuální stav zprávy v e-podatelně – odesláno, neodesláno</dd>
    </dl>
</p>        