    <h2>Detail odchozí zprávy</h2>

<p>    
Zobrazuje detailní informace odeslané zprávy.
</p>

<h3>Položky</h3>
    <dl>
        <dt>Pořadí DZ v e-podatelně</dt>
        <dd>obsahuje jednoznačné identifikační číslo e-podatelny</dd>
    </dl>
    <dl>
        <dt>Typ zprávy</dt>
        <dd>obsahuje typ odeslané zprávy – email, datová zpráva</dd>
    </dl>
    <dl>
        <dt>Schránka</dt>
        <dd>obsahuje schránku, odkud byla zpráva odeslána</dd>
    </dl>
    <dl>
        <dt>Věc</dt>
        <dd>obsahuje předmět zprávy</dd>
    </dl>
    <dl>
        <dt>Adresát</dt>
        <dd>obsahuje jméno a email nebo ID datové schránky adresáta</dd>
    </dl>
    <dl>
        <dt>Odesláno</dt>
        <dd>obsahuje datum a čas odeslání zprávy z e-popdatelny</dd>
    </dl>
    <dl>
        <dt>Obsah zprávy</dt>
        <dd>obsahuje obsah odeslané zprávy</dd>
    </dl>
    <dl>
        <dt>Přílohy</dt>
        <dd>obsahuje seznam příloh, které byly odeslány</dd>
    </dl>


    