    <h2>Nové příchozí zprávy</h2>
<p>    
Zde se vypisují jak nové zprávy, které byly aktuálně přijaty ze schránek, tak i dosud nezaevidované zprávy.
</p>
<p>
Každá zpráva obsahuje možnost volby evidence a zpracovává se zvlášť.
</p>

<br>
<h3>Možnosti evidence</h3>

    <dl>
        <dt>Nedělat nic</dt>
        <dd>S touto zprávou nebude dělat nic. Ponechá se na pozdější zpracování.</dd>
    </dl>
    <dl>
        <dt>Evidovat</dt>
        <dd>
            
Zaeviduje zprávu do spisové služby.<br>
V uvedeném formuláři pracovník podatelny vyplní potřebné údaje.

<br><br>
<strong>Subjekt</strong><br>
Pokud daný odesílatel existuje v databázi, bude zde nabídnut.<br>
Není-li nabídnut, ale v databázi existuje, pak lze daný subjekt vyhledat pomoci našeptávače. Stačí zadat pár znaků a v seznamu se objeví nalezené subjekty. Na vybraný subjekt pak stačí kliknout.<br>
Není-li subjekt v databázi, je možné subjekt vytvořit volbou Vytvořit nový subjekt z odesílatele.<br>
V nalezených subjektů pak označte subjekt, který bude k dokumentu přidělen.
<br><br>
<strong>Předání</strong><br>
Zprávu je možné i přímo předat. Položka předat je opět našeptávač, takže stačí zadat pár znaků jména a ze seznamu nalezených vybrat.
            
        </dd>
    </dl>
    <dl>
        <dt>Evidovat do jiné evidence</dt>
        <dd>Tato volba zaeviduje zprávu do jiné evidence. V poli se zadá název evidence. Tato zpráva nebude součásti spisové služby.</dd>
    </dl>
    <dl>
        <dt>Odmítnout</dt>
        <dd>Tato volba označí zprávu za odmítnutou. Kromě poznámky důvodu odmítnutí je možnost zaslat odmítavou zprávu zpět odesílateli.</dd>
    </dl>

</p>

<p>
Potvrzení volby se vtahuje pouze na jednu zprávu. Nelze zpracovat zprávy najednou jedním tlačítkem. 
</p>
    