    <h2>Transakční protokoly</h2>
    <p>
Poslední tlačítko sekce Administrace jsou Protokoly. V nich naleznete přístupy uživatelů, kteří vstoupili do systému Spisová služba. Pokud tento seznam uživatelů chcete zobrazit, klikněte pouze na nápis Přístupy uživatelů. Jakmile kliknete na tento nápis, zobrazí se vám soupis uživatelů v následujícím formátu – rok-měsíc-den hh:mm:ss – uživatel z IP adresy – úspěšnost připojení.

    </p>