    <h2>Přístupy uživatelů</h2>
    <p>
        Na úvodní stránce naleznete přihlašovací formulář, do kterého je nutné zadat vaše
        uživatelské jméno a heslo. Poté stačí kliknout na tlačítko Přihlásit. Pokud jste
        zadali správné údaje, budete přesměrováni do spisové služby. V případě   špatného
        uvedení uživatelského jména či hesla budete vyzváni k zadání správných údajů.
    </p>