    <h2>Detail dokumentu</h2>
    
    <br />
    <h3>Základní informace</h3>
    <p>
    <dl>
        <dt>JID</dt>
        <dd>
            Jednoznačné identifikační číslo dokumentu.
        </dd>
    </dl>     
    <dl>
        <dt>Typ dokumentu</dt>
        <dd>Určuje typ dokumentu</dd>
    </dl>     
    <dl>
        <dt>Číslo jednací</dt>
        <dd>
            Číslo jednací dokumentu
        </dd>
    </dl>         
    <dl>
        <dt>Název spisu</dt>
        <dd>
            Obsahuje název spisu, ke kterému je dokument připojen.
        </dd>
    </dl>         
    <dl>
        <dt>Věc</dt>
        <dd>
            Představuje název dokumentu. 
        </dd>
    </dl>         
    <dl>
        <dt>Popis</dt>
        <dd>Popis rozšiřuje informace o tom, o jaký dokument se jedná.</dd>
    </dl>         
    <dl>
        <dt>Datum doručení/vzniku</dt>
        <dd>Označuje datum a čas, kdy byl dokument doručen nebo vytvořen.</dd>
    </dl>         
    <dl>
        <dt>Číslo jednací odesilatele</dt>
        <dd>Pokud je hodnota dostupná, představuje položka číslo jednací odesilatele, která může identifikovat původ.</dd>
    </dl>         
    <dl>
        <dt>Číslo doporučeného dopisu</dt>
        <dd>Je-li dokument doručen doporučeně, představuje tato položka číslo doporučeného dopisu.</dd>
    </dl>         
    <dl>
        <dt>Spojit s dokumentem</dt>
        <dd>
            Je-li hodnota dostupná, přestavuje informaci o souvisejícím dokumentu, se kterým je tento dokument spojen.
        </dd>
    </dl>         
    <dl>
        <dt>Počet listů</dt>
        <dd>Udává počet listinných listů</dd>
    </dl>         
    <dl>
        <dt>Počet listů příloh</dt>
        <dd>Udává počet listů příloh</dd>
    </dl>         
    <dl>
        <dt>Identifikátor e-podatelny</dt>
        <dd>Obsahuje informace o zprávě, ze které byl dokument vytvořen</dd>
    </dl>     
    </p>
    
    <br />
<h3>Vyřízení</h3>
<p>
    <dl>
        <dt>Způsob vyřízení</dt>
        <dd>označuje způsob vyřízení dokumentu</dd>
    </dl>    
    <dl>
        <dt>Datum vyřízení</dt>
        <dd>představuje datum vyřízení dokumentu</dd>
    </dl>    
    <dl>
        <dt>Spisový znak</dt>
        <dd>Přestavuje spisový znak včetně názvu věcné skupiny</dd>
    </dl>    
    <dl>
        <dt>Skartační znak</dt>
        <dd>Představuje skartační znak (převzato ze spisového znaku)</dd>
    </dl>    
    <dl>
        <dt>Skartační lhůta</dt>
        <dd>Představuje skartační lhůtu (převzato ze spisového znaku)</dd>
    </dl>    
    <dl>
        <dt>Spouštěcí událost</dt>
        <dd>Představuje způsob spuštění události (převzato ze spisového znaku)</dd>
    </dl>    
    <dl>
        <dt>Počet listů</dt>
        <dd>Udává počet listinných listů</dd>
    </dl>         
    <dl>
        <dt>Počet listů příloh</dt>
        <dd>Udává počet listů příloh</dd>
    </dl>         
    <dl>
        <dt>Uložení dokumentu</dt>
        <dd>Představuje poznámku k uložení dokumentu</dd>
    </dl>    
    <dl>
        <dt>Poznámka k vyřízení</dt>
        <dd>představuje poznámku k vyřízení dokumentu</dd>
    </dl>    
    </p>


<br />
<h3>Vytvořil a vyřídil</h3>
<p>
    <dl>
        <dt>Vytvořil</dt>
        <dd>obsahuje jméno a organizační jednotku toho, kdo tento dokument vytvořil</dd>
    </dl>   
    <dl>
        <dt>Vytvořil dne</dt>
        <dd>obsahuje datum a čas vytvoření dokumentu</dd>
    </dl>   
    <dl>
        <dt>Vyřídil</dt>
        <dd>obsahuje jméno a organizační jednotku toho, komu je tento dokument vyřídil</dd>
    </dl> 
    <dl>
        <dt>Datum vyřízení</dt>
        <dd>obsahuje datum a čas vyřízení dokumentu</dd>
    </dl>   
</p>  
    
   <br /> 
   <h3>Adresáti / odesílatelé</h3>
   <p>
        V tomto bloku se objevuje seznam všech subjektů, které dokument obsahuje.
   </p>

   <br /> 
   <h3>Přílohy</h3>
    <p>
        V tomto bloku se objevuje seznam všech příloh, které dokument obsahuje. Kliknutím na název je možné přílohu otevřít.
    </p>

   <br /> 
   <h3>Odeslání</h3>
    <p>
        V tomto bloku se objevuje záznam odeslaných dokumentů.
    </p>    
   
   <br /> 
   <h3>Historie</h3>    
    <p>
    V detailech dokumentu lze také sledovat historii dokumentu, díky které se dozvíte základní informace o tom, co se s dokumentem dělo od jeho vzniku a po jeho vyřízení.
    <br />
    Pokud chce mít ještě podrobnější přehled, využijte Transakční protokol, do kterého se zapisují i předání a další podrobné informace. Transakční protokol je dělaný formou dialogového okna.
        
    </p>    
