    <h2>Seznam dokumentů pro příjem do spisovny</h2>

<p>
Obsahuje seznam dokumentů, které jsou určeny pro příjem do spisovny. 
<br>
To znamená, že pracovník spisové služby dokumenty předal do spisovny, ale pracovník spisovny tyto dokumenty ještě nepřijal.
</p>

<p>
Popis jednotlivých sloupců:

    <dl>
        <dt>Typ dokumentu</dt>
        <dd>zobrazuje typ dokumentu – vlastní/doručený</dd>
    </dl>
    <dl>
        <dt>Přijato</dt>
        <dd>obsahuje datum, kdy byl přijat/vytvořen do spisové služby</dd>
    </dl>
    <dl>
        <dt>Vyřízeno</dt>
        <dd>obsahuje datum, kdy byl dokument vyřízen</dd>
    </dl>
    <dl>
        <dt>Skartační rok</dt>
        <dd>obsahuje rok skartace</dd>
    </dl>
    <dl>
        <dt>Číslo jednací / pořadí</dt>
        <dd>obsahuje číslo jednací dokumentu. V případě sběrného archu i jeho pořadí</dd>
    </dl>
    <dl>
        <dt>JID</dt>
        <dd>jednoznačné identifikační číslo dokumentu</dd>
    </dl>
    <dl>
        <dt>Název spisu</dt>
        <dd>obsahuje název spisu, do kterého je dokument připojen</dd>
    </dl>
    <dl>
        <dt>Věc</dt>
        <dd>název dokumentu</dd>
    </dl>
    <dl>
        <dt>Adresáti/Odesílatelé</dt>
        <dd>obsahuje seznam adres subjektů přidělené k dokumentu</dd>
    </dl>
    <dl>
        <dt>Přiděleno</dt>
        <dd>obsahuje jméno a organizační jednotku toho, kdo dokument vyřídil</dd>
    </dl>
    <dl>
        <dt>Spisový znak, skartační znak / lhůta</dt>
        <dd>obsahuje skartační informace od dokumentu</dd>
    </dl>
    <dl>
        <dt>Stav</dt>
        <dd>zobrazuje aktuální stav dokumentu – vyřízen, zapůjčen, ke skartaci, skartován, archivován</dd>
    </dl>

</p>

<br>
<h3>Filtrování</h3>

<p>
    <dl>
        <dt>Podle stavu</dt>
        <dd>zobrazí pouze dokumenty podle zvoleného stavu (předáno do spisovny, ve spisovně, ke skartaci, archivován, skartován)</dd>
    </dl>
    <dl>
        <dt>Podle skartačního znaku</dt>
        <dd>zobrazí pouze dokumenty podle zvoleného skartačního znaku</dd>
    </dl>
    <dl>
        <dt>Podle způsobu vyřízení</dt>
        <dd>zobrazí pouze dokumenty podle zvoleného způsobu vyřízení</dd>
    </dl>
</p>

<br>
<h3>Řazení</h3>

<p>
Seřadí seznam dokumentu podle volby.
</p>

<br>
<h3>Hledání</h3>

<p>
Lze použít jednoduché hledání pomoci uvedeného formuláře. Hledat lze podle věci, popisu, čísla jednacího a JID.
<br>
Jakékoli další hodnoty nebo specifické hodnoty, lze využít volby "Pokročilé vyhledávání". Zobrazí se dialogové okno s formulářem, kde vyplníte potřebné hodnoty.
<br>
Aplikace si pamatuje nastavené hodnoty. Chcete-li vyhledávací filtr zrušit, klikněte na tlačítko "Zrušit vyhledávání".
</p>      

<br>
<h3>Hromadná operace</h3>
<p>
Na konci seznamu se nachází pole pro volbu hromadné operace.
Zde se nachází pouze volba převzetí vybraných dokumentů do spisovny. Označením vybraných dokumentů nebo zvolením zaškrtnout vše a potvrzením volby, dojde k hromadnému převzetí dokumentů do spisovny.
</p>