------------------------;

ALTER TABLE `{tbls3}stat` ADD UNIQUE KEY `kod` (`kod`);

INSERT IGNORE INTO `{tbls3}stat` (`kod`, `nazev`,  `stav`) VALUES
('AFG','Islámská republika Afghánistán',0),
('ALB','Albánská republika',0),
('ATA','Antarktida',0),
('DZA','Alžírská demokratická a lidová republika',0),
('ASM','Americká Samoa',0),
('AND','Andorrské knížectví',0),
('AGO','Angolská republika',0),
('ATG','Antigua a Barbuda',0),
('AZE','Ázerbájdžánská republika',0),
('ARG','Argentinská republika',0),
('AUS','Austrálie',0),
('AUT','Rakouská republika',0),
('BHS','Bahamské společenství',0),
('BHR','Království Bahrajn',0),
('BGD','Bangladéšská lidová republika',0),
('ARM','Arménská republika',0),
('BRB','Barbados',0),
('BEL','Belgické království',0),
('BMU','Bermudy',0),
('BTN','Bhútánské království',0),
('BOL','Mnohonárodní stát Bolívie',0),
('BIH','Bosna a Hercegovina',0),
('BWA','Republika Botswana',0),
('BVT','Bouvetův ostrov',0),
('BRA','Brazilská federativní republika',0),
('BLZ','Belize',0),
('IOT','Britské indickooceánské území',0),
('SLB','Šalomounovy ostrovy',0),
('VGB','Britské Panenské ostrovy',0),
('XKO','Republika Kosovo',0),
('BRN','Brunej Darussalam',0),
('BGR','Bulharská republika',0),
('MMR','Republika Myanmarský svaz',0),
('BDI','Republika Burundi',0),
('BLR','Běloruská republika',0),
('KHM','Kambodžské království',0),
('CMR','Kamerunská republika',0),
('CAN','Kanada',0),
('CPV','Kapverdská republika',0),
('CYM','Kajmanské ostrovy',0),
('CAF','Středoafrická republika',0),
('LKA','Srílanská demokratická socialistická republika',0),
('TCD','Čadská republika',0),
('CHL','Chilská republika',0),
('CHN','Čínská lidová republika',0),
('TWN','Tchaj-wan (čínská provincie)',0),
('CXR','Vánoční ostrov',0),
('CCK','Kokosové (Keelingovy) ostrovy',0),
('COL','Kolumbijská republika',0),
('COM','Komorský svaz',0),
('MYT','Mayotte',0),
('COG','Konžská republika',0),
('COD','Demokratická republika Kongo',0),
('COK','Cookovy ostrovy',0),
('CRI','Kostarická republika',0),
('HRV','Chorvatská republika',0),
('CUB','Kubánská republika',0),
('CYP','Kyperská republika',0),
('BEN','Beninská republika',0),
('DNK','Dánské království',0),
('DMA','Dominické společenství',0),
('DOM','Dominikánská republika',0),
('ECU','Ekvádorská republika',0),
('SLV','Salvadorská republika',0),
('GNQ','Republika Rovníková Guinea',0),
('ETH','Etiopská federativní demokratická republika',0),
('ERI','Eritrea',0),
('EST','Estonská republika',0),
('FRO','Faerské ostrovy',0),
('FLK','Falklandské ostrovy (Malvíny)',0),
('SGS','Jižní Georgie a Jižní Sandwichovy ostrovy',0),
('FJI','Fidžijská republika',0),
('FIN','Finská republika',0),
('ALA','Alandské ostrovy',0),
('FRA','Francouzská republika',0),
('GUF','Francouzská Guyana',0),
('PYF','Francouzská Polynésie',0),
('ATF','Francouzská jižní území',0),
('DJI','Džibutská republika',0),
('GAB','Gabonská republika',0),
('GEO','Gruzie',0),
('GMB','Gambijská republika',0),
('PSE','Okupované palestinské území',0),
('DEU','Spolková republika Německo',0),
('GHA','Ghanská republika',0),
('GIB','Gibraltar',0),
('KIR','Republika Kiribati',0),
('GRC','Řecká republika',0),
('GRL','Grónsko',0),
('GRD','Grenada',0),
('GLP','Guadeloupe',0),
('GUM','Guam',0),
('GTM','Guatemalská republika',0),
('GIN','Guinejská republika',0),
('GUY','Guyanská republika',0),
('HTI','Republika Haiti',0),
('HMD','Heardův ostrov a McDonaldovy ostrovy',0),
('VAT','Svatý stolec (Vatikánský městský stát)',0),
('HND','Honduraská republika',0),
('HKG','Zvláštní administrativní oblast Číny Hongkong',0),
('HUN','Maďarsko',0),
('ISL','Islandská republika',0),
('IND','Indická republika',0),
('IDN','Indonéská republika',0),
('IRN','Íránská islámská republika',0),
('IRQ','Irácká republika',0),
('IRL','Irsko',0),
('ISR','Stát Izrael',0),
('ITA','Italská republika',0),
('CIV','Republika Pobřeží Slonoviny',0),
('JAM','Jamajka',0),
('JPN','Japonsko',0),
('KAZ','Republika Kazachstán',0),
('JOR','Jordánské hášimovské království',0),
('KEN','Keňská republika',0),
('PRK','Korejská lidově demokratická republika',0),
('KOR','Korejská republika',0),
('KWT','Stát Kuvajt',0),
('KGZ','Kyrgyzská republika',0),
('LAO','Laoská lidově demokratická republika',0),
('LBN','Libanonská republika',0),
('LSO','Království Lesotho',0),
('LVA','Lotyšská republika',0),
('LBR','Liberijská republika',0),
('LBY','Libye',0),
('LIE','Lichtenštejnské knížectví',0),
('LTU','Litevská republika',0),
('LUX','Lucemburské velkovévodství',0),
('MAC','Zvláštní administrativní oblast Číny Macao',0),
('MDG','Madagaskarská republika',0),
('MWI','Republika Malawi',0),
('MYS','Malajsie',0),
('MDV','Maledivská republika',0),
('MLI','Republika Mali',0),
('MLT','Maltská republika',0),
('MTQ','Martinik',0),
('MRT','Mauritánská islámská republika',0),
('MUS','Mauricijská republika',0),
('MEX','Spojené státy mexické',0),
('MCO','Monacké knížectví',0),
('MNG','Mongolsko',0),
('MDA','Moldavská republika',0),
('MNE','Černá Hora',0),
('MSR','Montserrat',0),
('MAR','Marocké království',0),
('MOZ','Mosambická republika',0),
('OMN','Sultanát Omán',0),
('NAM','Namibijská republika',0),
('NRU','Republika Nauru',0),
('NPL','Nepálská federativní demokratická republika',0),
('NLD','Nizozemské království',0),
('CUW','Curaçao',0),
('ABW','Aruba',0),
('SXM','Svatý Martin (nizozemská část)',0),
('BES','Bonaire, Svatý Eustach a Saba',0),
('NCL','Nová Kaledonie',0),
('VUT','Republika Vanuatu',0),
('NZL','Nový Zéland',0),
('NIC','Nikaragujská republika',0),
('NER','Nigerská republika',0),
('NGA','Nigerijská federativní republika',0),
('NIU','Niue',0),
('NFK','Ostrov Norfolk',0),
('NOR','Norské království',0),
('MNP','Společenství Ostrovy Severní Mariany',0),
('UMI','Menší odlehlé ostrovy USA',0),
('FSM','Federativní státy Mikronésie',0),
('MHL','Republika Marshallovy ostrovy',0),
('PLW','Republika Palau',0),
('PAK','Pákistánská islámská republika',0),
('PAN','Panamská republika',0),
('PNG','Papua Nová Guinea',0),
('PRY','Paraguayská republika',0),
('PER','Peruánská republika',0),
('PHL','Filipínská republika',0),
('PCN','Pitcairn',0),
('POL','Polská republika',0),
('PRT','Portugalská republika',0),
('GNB','Republika Guinea-Bissau',0),
('TLS','Demokratická republika Východní Timor',0),
('PRI','Portoriko',0),
('QAT','Stát Katar',0),
('REU','Réunion',0),
('ROU','Rumunsko',0),
('RUS','Ruská federace',0),
('RWA','Republika Rwanda',0),
('BLM','Svatý Bartoloměj',0),
('SHN','Svatá Helena, Ascension a Tristan da Cunha',0),
('KNA','Svatý Kryštof a Nevis',0),
('AIA','Anguilla',0),
('LCA','Svatá Lucie',0),
('MAF','Svatý Martin (francouzská část)',0),
('SPM','Saint Pierre a Miquelon',0),
('VCT','Svatý Vincenc a Grenadiny',0),
('SMR','Republika San Marino',0),
('STP','Demokratická republika Svatý Tomáš a Princův ostrov',0),
('SAU','Království Saúdská Arábie',0),
('SEN','Senegalská republika',0),
('SRB','Republika Srbsko',0),
('SYC','Seychelská republika',0),
('SLE','Republika Sierra Leone',0),
('SGP','Singapurská republika',0),
('VNM','Vietnamská socialistická republika',0),
('SVN','Slovinská republika',0),
('SOM','Somálská republika',0),
('ZAF','Jihoafrická republika',0),
('ZWE','Republika Zimbabwe',0),
('ESP','Španělské království',0),
('SSD','Jihosúdánská republika',0),
('SDN','Súdánská republika',0),
('ESH','Západní Sahara',0),
('SUR','Surinamská republika',0),
('SJM','Svalbard a Jan Mayen',0),
('SWZ','Svazijské království',0),
('SWE','Švédské království',0),
('CHE','Švýcarská konfederace',0),
('SYR','Syrská arabská republika',0),
('TJK','Republika Tádžikistán',0),
('THA','Thajské království',0),
('TGO','Republika Togo',0),
('TKL','Tokelau',0),
('TON','Království Tonga',0),
('TTO','Republika Trinidad a Tobago',0),
('ARE','Spojené arabské emiráty',0),
('TUN','Tuniská republika',0),
('TUR','Turecká republika',0),
('TKM','Turkmenistán',0),
('TCA','Ostrovy Turks a Caicos',0),
('TUV','Tuvalu',0),
('UGA','Ugandská republika',0),
('UKR','Ukrajina',0),
('MKD','Bývalá jugoslávská republika Makedonie',0),
('EGY','Egyptská arabská republika',0),
('GBR','Spojené království Velké Británie a Severního Irska',0),
('GGY','Guernsey',0),
('JEY','Jersey',0),
('IMN','Ostrov Man',0),
('TZA','Tanzanská sjednocená republika',0),
('USA','Spojené státy americké',0),
('VIR','Americké Panenské ostrovy',0),
('BFA','Burkina Faso',0),
('URY','Uruguayská východní republika',0),
('UZB','Republika Uzbekistán',0),
('VEN','Bolívarovská republika Venezuela',0),
('WLF','Ostrovy Wallis a Futuna',0),
('WSM','Nezávislý stát Samoa',0),
('YEM','Jemenská republika',0),
('ZMB','Zambijská republika',0);
