{block title}Seznam dokumentů{/block}
{block content}
    <div class="navigate">
    Transakční protokoly
    </div>

    <h2>Transakční protokoly</h2>

    <table class="file_seznam">

        <tr>
            <td class="icon">
                <img src="{$baseUri}images/icons/ciselnik.png" alt="ciselnik.png" title="číselník" width="32" height="32" />
            </td>
            <td class="meta">
                <a href="{link :Admin:Protokol:prihlaseni}">Přístupy uživatelů</a>
                <div class="popis">
                    protokol přístupu uživatelů do systému
                </div>
            </td>
        </tr>



    </table>
