{block title}číselníky{/block}
{block content}
    <div class="navigate">
    číselníky
    </div>

    <h2>Číselníky</h2>

    <table class="file_seznam">

        <tr>
            <td class="icon">
                <img src="{$baseUri}images/icons/ciselnik.png" alt="ciselnik.png" title="číselník" width="32" height="32" />
            </td>
            <td class="meta">
                <a href="{link :Admin:Ciselniky:zpvyrizeni}">Způsob vyřízení</a>
                <div class="popis">
                    Správa způsobu vyřízení
                </div>
            </td>
        </tr>
        <tr>
            <td class="icon">
                <img src="{$baseUri}images/icons/ciselnik.png" alt="ciselnik.png" title="číselník" width="32" height="32" />
            </td>
            <td class="meta">
                <a href="{link :Admin:Ciselniky:zpvyrizeni}">Způsob odeslání</a>
                <div class="popis">
                    Správa způsobu odeslání dokumentu
                </div>
            </td>
        </tr>


    </table>
