{block title}Administrace{/block}
{block content}
<h2>Vítejte v administraci</h2>

{if $NovaVerze['aktualni']==0}
<div id="flash_version">
    <strong>Je k dispozici nová verze!</strong>
    <br /><br />
    Doporučujeme provést aktualizaci na novou verzi.
    <br />
    Přejděte na stránky OSS Spisové služby a stáhněte si aktualizační balík. Poté proveďte aktualizaci dle přiložených pokynů.
    
    <br /><br />
    Vaše současná verze je <strong>{$NovaVerze['soucasna_verze']}</strong>. Nová verze je <strong>{$NovaVerze['aktualni_verze']}</strong>.
    
</div>
{/if}