@{block title}{$title}{/block}
{assign Select2 => true}
@{block debug}
<?php print_r($seznam); ?>
<?php print_r($zapujcky); ?>
@{/block}
@{block content}
    <h2>{$title}</h2>

    <div id="tisk">
        <a href="{link this, 'print' => 1}" title="vytisknout tuto stránku" target="_blank">
            <img src="{$baseUri}images/icons/printer.png" alt="printer.png" width="32" height="32" />
        </a>
        <a href="{link this, 'pdfprint' => 1}" title="Vytisknout tuto stránku do PDF" target="_blank" >
            <img src="{$baseUri}images/mimetypes/application-pdf.png" alt="application-pdf.png" width="32" height="32" />
        </a>        
    </div>    
    
    <div id="filtr">
        {$filtrForm->render('begin')}
        {$filtrForm['filtr']->label} {$filtrForm['filtr']->control}
        {$filtrForm['go_filtr']->control}
        {$filtrForm->render('end')}
    </div>
    <div id="search">
        {control searchForm}
        <div id="search_advanced">
        {if !empty($s3_hledat)}<a href="{link :Spisovna:Vyhledat:reset}" style="color:#ff0000;">Zrušit vyhledávání</a>&nbsp;&nbsp;&nbsp;{/if}
        <a href="{link :Spisovna:Vyhledat:default}" id="dialog-search">Pokročilé vyhledávání</a>
        {if is_array($s3_hledat)}<br/><br/>Aplikováno pokročilé vyhledávání{/if}
        </div>
    </div>
    
    
    <br style="clear:both;" />

    <div style="margin: 3px 0px;" id="seradit">
    {control seraditForm}
    </div>

    <div id="dokumenty">
    {if count($seznam)>0}
    <form action="{link this}" method="post">
        <input type="hidden" name="url_referer" value="">
    <table>
        <tr>
            <th class="akce">&nbsp;</th>
            <th class="typ">Typ dokumentu</th>
            <th class="prijato">Přijato<br />Vyřízeno<br />Skartační rok</th>
            <th class="cislo_jadnaci">Číslo jednací<br />JID<br />Název spisu</th>
            <th class="vec">Věc<br />Adresáti/odesílatelé<br />počet listů a příloh</th>
            <th class="prideleno">Přiděleno / Vyřídil</th>
            <th class="stav">Spisový znak<br/>Skartační znak / lhůta<br/>Stav</th>
        </tr>
        {foreach $seznam as $dok}
        <tr>
            <td class="akce">
                {if $dok->stav_dokumentu==7 && !isset($zapujcky[$dok->id])}
                <input type="checkbox" class="checkbox" name="dokument_vyber[]" value="{$dok->id}" title="Vybrat tento dokument" />
                {/if}
                {if isset($is_prijem)}
                <input type="checkbox" class="checkbox" name="dokument_vyber[]" value="{$dok->id}" title="Vybrat tento dokument" />
                {/if}
            </td>
            <td class="typ">
                <img src="{$baseUri}images/icons/smer{$dok->typ_dokumentu->smer}.png" alt="{$dok->typ_dokumentu->nazev}" title="{$dok->typ_dokumentu->nazev}" width="16" height="16" />
                {if !empty($dok->epod_is_email)}
                <img src="{$baseUri}images/icons/typdok1.png" alt="přijato emailem" title="přijato emailem" width="24" height="16" />
                {elseif !empty($dok->epod_is_isds)}
                <img src="{$baseUri}images/icons/typdok2.png" alt="přijato datovou schránkou" title="přijato datovou schránkou" width="24" height="16" />
                {/if}
            </td>
            <td class="prijato">
                <span title="{$dok->datum_vzniku|edatetime}">{$dok->datum_vzniku|edate}</span>
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
                <br />
                <span><strong>{$dok->skartacni_rok}</strong></span>
            </td>
            <td class="cislo_jadnaci">
                &nbsp;<strong><a href="{link :Spisovna:Dokumenty:detail, 'id'=>$dok->id}">
                   {$dok->cislo_jednaci}{if $Typ_evidence=='sberny_arch'}{$Oddelovac_poradi}{$dok->poradi}{/if}
                </a></strong>
                <div class="small">&nbsp;{$dok->jid}</div>
                {if isset($dok->spisy)}
                {foreach $dok->spisy as $spis}
                <a href="{link :Spisovna:Spisy:detail, 'id'=>$spis->id}">{$spis->nazev}</a><br />
                {/foreach}
                {/if}
            </td>
            <td class="vec">
                <strong title="{$dok->popis}"><a href="{link :Spisovna:Dokumenty:detail, 'id'=>$dok->id}">
                    {$dok->nazev}
                </a></strong>
                <br />
                <div class="mezera">
                {if count($dok->subjekty)>0}

                {foreach $dok->subjekty as $subjekt}
                {=Subjekt::displayName($subjekt,'plna_adresa')}<br />
                {/foreach}
                {else}
                nejsou přiděleny žádné subjekty!
                <br />
                {/if}
                </div>
                <span class="small">přílohy:
                {=($dok->pocet_listu)+0} listů,
                {=($dok->pocet_priloh)+0} list. příloh,
                {=(count($dok->prilohy)+0)} příloh</span>
                <br/>
                <span class="small">způsob vyřízení:
                {$dok->zpusob_vyrizeni}</span>

            </td>
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                {$dok->spisovy_znak}
                <br />
                {$dok->skartacni_znak} / {$dok->skartacni_lhuta}
                <br />
                {if isset($zapujcky[$dok->id])}
                zapůjčen
                {elseif $dok->stav_dokumentu==6}
                předán do spisovny
                {elseif $dok->stav_dokumentu==7}
                vyřízen
                {elseif $dok->stav_dokumentu==8}
                skartační řízení
                {elseif $dok->stav_dokumentu==9}
                archivován
                {elseif $dok->stav_dokumentu==10}
                skartován
                {elseif $dok->stav_dokumentu==11}
                zapůjčen
                {/if}
            </td>
        </tr>
        {/foreach}


    </table>
    <div id="hromadna_akce" n:if="isset($akce_select) && !empty($akce_select)">
        <span id="checkbox_all_on">Zaškrtnout vše</span> / <span id="checkbox_all_off">Odškrtnout vše</span>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Vybrané položky:&nbsp;&nbsp;
        <select name="hromadna_akce">
            <option value="">(žádná akce)</option>
            {if isset($akce_select)}{foreach $akce_select as $as_index => $as_value}
            <option value="{$as_index}">{$as_value}</option>
            {/foreach}{/if}
        </select>
        <input type="submit" name="hromadna_submit" value="Provést" />
    </div>
    </form>
    {widget vp}
    {else}
        <div>&nbsp;</div>
        {if isset($no_items)}
        {if $no_items==1}
        <div class="prazdno">Nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==2}
        <div class="prazdno">K danému filtru nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==3}
        <div class="prazdno">Dokumenty odpovidající hledanému výrazu nebyly nalezeny.</div>
        {elseif $no_items==4}
        <div class="prazdno">Dokumenty odpovidající daným požadavkům nebyly nalezeny.</div>
        {/if}
        {else}
    <div class="prazdno">Nebyly zjištěny žádné dokumenty.</div>
        {/if}
    {/if}
    </div>

    <div id="dialog"></div>