@{block title}Dokument{/block}
@{block javascript}
	<script type="text/javascript">
                function vybratSpisovyZnak() {

                    var spisz_skart = new Array();
                    var spisz_lhuta = new Array();
                    var spisz_udalost = new Array();
                    spisz_skart['0'] = '';
                    spisz_lhuta['0'] = '';
                    spisz_udalost['0'] = '';
                {if count($SpisoveZnaky)>0}
                {foreach $SpisoveZnaky as $sznak}
                    spisz_skart[{$sznak->id}] = {$sznak->skartacni_znak};
                    spisz_lhuta[{$sznak->id}] = {$sznak->skartacni_lhuta};
                    spisz_udalost[{$sznak->id}] = {$sznak->spousteci_udalost_id};
                {/foreach}
                {/if}

                    var frm_spis  = document.forms['frm-vyrizovaniForm'].spisovy_znak_id;
                    var frm_skart  = document.forms['frm-vyrizovaniForm'].skartacni_znak;
                    var frm_lhuta  = document.forms['frm-vyrizovaniForm'].skartacni_lhuta;
                    var frm_udalost  = document.forms['frm-vyrizovaniForm'].spousteci_udalost_id;

                    var key  = document.forms['frm-vyrizovaniForm'].spisovy_znak_id.selectedIndex;
                    var value = document.forms['frm-vyrizovaniForm'].spisovy_znak_id.options[key].value;
                    document.forms['frm-vyrizovaniForm'].skartacni_znak.value = spisz_skart[value];
                    document.forms['frm-vyrizovaniForm'].skartacni_lhuta.value = spisz_lhuta[value];
                    //document.forms['frm-vyrizovaniForm'].spousteci_udalost.value = spisz_udalost[value];
                    select_set_value(document.forms['frm-vyrizovaniForm'].spousteci_udalost_id,spisz_udalost[value]);
                    return true;
                }


	</script>
@{/block}
@{block debug}
<?php echo "\n\nDokument: "; print_r($Dok); ?>
<?php echo "\n\nZapujcky: "; print_r($Zapujcka); ?>

@{/block}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovna:Dokumenty:default}">Seznam dokumentů ve spisovně</a> - Detail dokumentu
    </div>

    <div id="tisk">
        <a href="{link :Spisovna:Dokumenty:detail, 'id'=>$Dok->id, 'print' => 1}" title="vytisknout tuto stránku" target="_blank">
            <img src="{$baseUri}images/icons/printer.png" alt="printer.png" width="32" height="32" />
        </a>
        <a href="{link :Spisovna:Dokumenty:detail, 'id'=>$Dok->id, 'pdfprint' => 1}" title="Vytisknout tuto stránku do PDF" target="_blank">
            <img src="{$baseUri}images/mimetypes/application-pdf.png" alt="application-pdf.png" width="32" height="32" />
        </a>        
    </div>

    <div id="dokument_blok_volby">
        {if $AccessEdit==1}
        <a href="{link :Spisovna:Dokumenty:detail , 'id'=>$Dok->id , 'upravit'=>'vyrizeni' }">Upravit skartační režim</a>
        {/if}
        {if empty($Zapujcka->id)}
        <a href="{link :Spisovna:Zapujcky:nova, 'dokument_id'=>$Dok->id}">Žádost o zápůjčku</a>
        {/if}
    </div>

    {if $Skartacni_dohled==1}
    <div class="dokument_blok2">
        <div class="h2">Připojit dokument do skartačního řízení k posuzení</div>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd title="{$Dok->spisovy_znak_popis}">{$Dok->spisovy_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Dok->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>&nbsp;</dt>
            <dd>
                <a href="{link :Spisovna:Dokumenty:keskartaci, 'id'=>$Dok->id, 'user'=>$user->id, 'org'=>@$orgjednotka->id}" id="keskartacidokument">Přidat do skartačního řízení</a>
            </dd>
        </dl>
    </div>
    {/if}

    {if $Skartacni_komise==1}
    <div class="dokument_blok2">
        <div class="h2">Rozhodnutí o skartaci dokumentu</div>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd title="{$Dok->spisovy_znak_popis}">{$Dok->spisovy_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Dok->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Rozhodnutí:</dt>
            <dd>
                <a href="{link :Spisovna:Dokumenty:archivovat, 'id'=>$Dok->id, 'user'=>$user->id, 'org'=>@$orgjednotka->id}" id="archivovatdokument">Archivovat</a>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{link :Spisovna:Dokumenty:skartovat, 'id'=>$Dok->id, 'user'=>$user->id, 'org'=>@$orgjednotka->id}" id="skartovatdokument">Skartovat</a>
            </dd>
        </dl>
    </div>
    {/if}



    <div id="dokument_blok_hlavni">
        <div class="h2">{$Dok->typ_dokumentu->nazev}</div>
        <dl class="detail_item">
            <dt>JID:</dt>
            <dd>{$Dok->jid}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací{if $Typ_evidence == 'sberny_arch'} {$Oddelovac_poradi} pořadí{/if}:</dt>
            <dd class="nadpis">{$Dok->cislo_jednaci}{if $Typ_evidence == 'sberny_arch'}{$Oddelovac_poradi}{$Dok->poradi}{/if}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Název spisu:</dt>
            <dd>
            {if isset($Dok->spisy) }
                {foreach $Dok->spisy as $s}
                {$s->nazev}<br />
                {/foreach}
            {else}
                nepřidělen k žádnému spisu
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd class="nadpis"><u>{$Dok->nazev}</u>&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{!$Dok->popis|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum doručení/vzniku:</dt>
            <dd>{$Dok->datum_vzniku|edatetime}&nbsp;</dd>
        </dl>
        {if !empty($Dok->zpusob_doruceni)}
        <dl class="detail_item">
            <dt>Způsob doručení:</dt>
            <dd>{$Dok->zpusob_doruceni}&nbsp;</dd>
        </dl>        
        {/if}        
        {if !empty($Dok->cislo_jednaci_odesilatele)}
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$Dok->cislo_jednaci_odesilatele}&nbsp;</dd>
        </dl>
        {/if}
        {if !empty($Dok->cislo_doporuceneho_dopisu)}
        <dl class="detail_item">
            <dt>Číslo doporučeného dopisu:</dt>
            <dd>{$Dok->cislo_doporuceneho_dopisu}&nbsp;</dd>
        </dl>
        {/if}        
        {if !empty($Dok->zmocneni)}
        <dl class="detail_item">
            <dt>Zmocnění:</dt>
            <dd>{$Dok->zmocneni}&nbsp;</dd>
        </dl>
        {/if}
        {if !empty($Dok->poznamka)}
        <dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{!$Dok->poznamka|html2br}&nbsp;</dd>
        </dl>
        {/if}
        {if $Typ_evidence=='priorace'}
        <dl class="detail_item">
            <dt>Spojeno s dokumentem:</dt>
            <dd>
                <span id="dok_spojit">
                {if count($SouvisejiciDokumenty)>0 }
                    {foreach $SouvisejiciDokumenty as $s}
                    <a href="{link :Spisovka:Dokumenty:detail, 'id'=>$s->id}">{$s->cislo_jednaci} ({$s->jid})</a>
                    <br>
                    {/foreach}
                {/if}
                </span>
                &nbsp;
            </dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Počet listů / příloh:</dt>
            <dd>{!$Dok->pocet_listu|num} / {!$Dok->pocet_priloh|num}</dd>
        </dl>
        {if !empty($Dok->identifikator)}
        <dl class="detail_item">
            <dt>Identifikátor epodatelny:</dt>
            <dd><pre>{$Dok->identifikator['popis']}</pre></dd>
        </dl>
        {if $Dok->identifikator['typ'] == "email" }
        <dl class="detail_item">
            <dt>Ověření identifikátoru:</dt>
            <dd>
            {if $Dok->identifikator['cert_signed'] >= 0 }
                {$Dok->identifikator['cert_log']['aktualne']['date']} &nbsp;
                {if $Dok->identifikator['cert_log']['aktualne']['status']==1 }
                <span style="color:#009900;">{$Dok->identifikator['cert_log']['aktualne']['message']}</span>
                {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_log']['aktualne']['message']}</span>
                {/if}
                <br />
                {$Dok->identifikator['cert_log']['prijato']['date']} &nbsp;
                {if $Dok->identifikator['cert_log']['prijato']['status']==1 }
                <span style="color:#009900;">{$Dok->identifikator['cert_log']['prijato']['message']}</span>
                {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_log']['prijato']['message']}</span>
                {/if}
                <br />
                {$Dok->identifikator['cert_log']['doruceno']['date']} &nbsp;
                {if $Dok->identifikator['cert_log']['doruceno']['status']==1 }
                <span style="color:#009900;">{$Dok->identifikator['cert_log']['doruceno']['message']}</span>
                {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_log']['doruceno']['message']}</span>
                {/if}
            {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_status']}</span>
            {/if}
            </dd>
        </dl>
        {/if}

        {/if}
    </div>
    
    <div id="dokument_blok_vyrizeni">
        <div class="h2">Vyřízení <span class='toggler' onclick='toggleWindow(this);'>&nbsp;</span></div>
        <div class="dokument_blok">
        {if ($FormUpravit=='vyrizeni')}
        {$vyrizovaniForm->render('begin')}
        <dl class="detail_item">
            <dt>Způsob vyřízení:</dt>
            <dd>{$Dok->zpusob_vyrizeni}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyřízení:</dt>
            <dd>{$Dok->datum_vyrizeni|edatetime}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{$vyrizovaniForm['spisovy_znak_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$vyrizovaniForm['skartacni_znak']->control}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$vyrizovaniForm['skartacni_lhuta']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{=SpisovyZnak::spousteci_udalost($Dok->spousteci_udalost_id,10)}&nbsp;</dd>
        </dl>
        {if $Dok->stav_dokumentu>=5}
        <dl class="detail_item">
            <dt>Datum spuštění události:</dt>
            <dd>{$Dok->datum_spousteci_udalosti|edate}&nbsp;</dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Počet listů / příloh:</dt>
            <dd>{!$Dok->vyrizeni_pocet_listu|num} / {!$Dok->vyrizeni_pocet_priloh|num}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Uložení dokumentu:</dt>
            <dd>{$vyrizovaniForm['ulozeni_dokumentu']->control}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{!$Dok->poznamka_vyrizeni|enl2br}&nbsp;</dd>
        </dl>        
        <div>
            {$vyrizovaniForm['upravit']->control}
            &nbsp;&nbsp;
            {$vyrizovaniForm['storno']->control}
        </div>
        {$vyrizovaniForm->render('end')}
        {else}        
        <dl class="detail_item">
            <dt>Způsob vyřízení:</dt>
            <dd>{$Dok->zpusob_vyrizeni}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyřízení:</dt>
            <dd>{$Dok->datum_vyrizeni|edatetime}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd title="{$Dok->spisovy_znak_popis}">{$Dok->spisovy_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Dok->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd class="normal"><strong>{$Dok->skartacni_lhuta}</strong>&nbsp;{if $Dok->stav_dokumentu>4}(datum skartace {$Dok->skartacni_rok|edate}){/if}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{=SpisovyZnak::spousteci_udalost($Dok->spousteci_udalost_id,10)}&nbsp;</dd>
        </dl>
        {if $Dok->stav_dokumentu>=5}
        <dl class="detail_item">
            <dt>Datum spuštění události:</dt>
            <dd>{$Dok->datum_spousteci_udalosti|edate}&nbsp;</dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Počet listů / příloh:</dt>
            <dd>{!$Dok->vyrizeni_pocet_listu|num} / {!$Dok->vyrizeni_pocet_priloh|num}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Uložení dokumentu:</dt>
            <dd>{!$Dok->ulozeni_dokumentu|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{!$Dok->poznamka_vyrizeni|enl2br}&nbsp;</dd>
        </dl>
        {/if}
        </div>
    </div>

    <div id="dokument_blok_poznamka">
        <div class="h2">Vytvořil a vyřídil</div>
        {if $Dok->typ_dokumentu->smer == 1}
        {foreach $Dok->workflow as $workflow}
        {if $workflow->stav_dokumentu==1}
        <dl class="detail_item">
            <dt>Vytvořil:</dt>
            <dd>
            {if empty($workflow->prideleno_id) }
                organizační jednotce
                <br />
                {$workflow->orgjednotka_info->zkraceny_nazev}
            {else}
                {$workflow->prideleno_jmeno}
                <br />
                {=@$workflow->orgjednotka_info->zkraceny_nazev}
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Vytvořil dne:</dt>
            <dd>{$workflow->date|edatetime}</dd>
        </dl>         
        <?php break; ?>
        {/if}
        {/foreach}
        {/if}        
        {if is_null($Dok->prideleno)}
        <div class="prazdno">K tomuto dokumentu není nikdo přidělen!</div>
        {else}
        <dl class="detail_item">
            <dt>Vyřídil:</dt>
            <dd>
            {if empty($Dok->prideleno->prideleno_id) }
                organizační jednotce
                <br />
                {$Dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {else}
                {$Dok->prideleno->prideleno_jmeno}
                <br />
                {=@$Dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyřízení:</dt>
            <dd>{$Dok->datum_vyrizeni|edatetime}&nbsp;</dd>
        </dl>           
        {/if}
    </div>
    
    {if !empty($Zapujcka->id)}
    <div id="dokument_blok_poznamka">
        <div class="h2">Zápůjčka</div>
        <dl class="detail_item">
            <dt>Zapůjčeno:</dt>
            <dd>
                {=Osoba::displayName($Zapujcka)}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Důvod zapůjčení:</dt>
            <dd>{!$Zapujcka->duvod|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum výpůjčky:</dt>
            <dd>{$Zapujcka->date_od|edate}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vrácení:</dt>
            <dd>{$Zapujcka->date_do|edate}</dd>
        </dl>          
    </div>
    {/if}

    <div id="dokument_blok_subjekty">
        <div class="h2">
            Adresáti / odesílatelé
        </div>
        <div id="dok-subjekty">
        {if count($Dok->subjekty)>0}
        <table class="seznam">
            {foreach $Dok->subjekty as $subjekt}
            <tr>
            <td class="icon">
                <img src="{$baseUri}images/icons/subjekt_{$subjekt->rezim_subjektu|lower}.png" alt="{$subjekt->rezim_subjektu}" title="{$subjekt->rezim_subjektu}" width="32" height="32" />
            </td>
            <td class="meta">
                <strong>{=Subjekt::displayName($subjekt,'jmeno_item')}</strong>
                <div class="info">
                <span>{$subjekt->type} - {=Subjekt::typ_subjektu($subjekt->type)}</span>
                <br />
                <span>
                    {if $subjekt->rezim_subjektu == 'O'}
                    odesílatel
                    {elseif $subjekt->rezim_subjektu == 'A'}
                    adresát
                    {elseif $subjekt->rezim_subjektu == 'AO'}
                    odesílatel i adresát
                    {else}
                    nespecifikováno
                    {/if}
                </span>

                <br />
                {=Subjekt::displayName($subjekt,'adresa')}
                </div>
            </td>
            <td class="meta_plus">
                &nbsp;
                <div class="info">
                <dl>
                    <dt>email:</dt>
                    <dd>{$subjekt->email}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>telefon:</dt>
                    <dd>{$subjekt->telefon}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>isds:</dt>
                    <dd>{$subjekt->id_isds}&nbsp;</dd>
                </dl>

                </div>
            </td>
        </tr>
        {/foreach}
        </table>
        {else}
        <div class="prazdno">K tomuto dokumentu nejsou připojeni žádní odesílatelé nebo adresáti.</div>
        {/if}
        </div>
    </div>

    <div id="dokument_blok_prilohy">
    <div class="h2">
        Přílohy
    </div>
    <div id="dok-prilohy">
    {accessview}
    {if count($Dok->prilohy)>0}
    <table class="seznam">
        {foreach $Dok->prilohy as $file}
        <tr>
            <td class="icon">
                <img src="{$file->mime_type_icon}" alt="{$file->mime_type}" title="{$file->mime_type}" width="32" height="32" />
            </td>
            <td class="meta">
                <a href="{link :Spisovka:Dokumenty:download, 'id'=>$Dok->id, 'file'=>$file->id}">{$file->nazev}</a>
                <div class="info">
                {$file->real_name}
                <br />
                <span>
                    {$file->typ_name}, {$file->size|bytes}, {$file->mime_type}
                    <br />
                    MD5 hash: {$file->md5_hash}
                </span>
                </div>
                {if !empty($file->popis)}<div class="popis">{!$file->popis|enl2br}</div>{/if}
            </td>
            <td class="user">
                nahráno {$file->date_created|edate}
                <br />
                {$file->user_name}
            </td>
        </tr>
        {/foreach}
    </table>
    {else}
        <div class="prazdno">K tomuto dokumentu nejsou připojené žádné elektronické přílohy.</div>
    {/if}
    {/accessview}
    {noaccessview}
        <div class="prazdno">Dokument obsahuje {=count($Dok->prilohy)} příloh. K jejím zobrazení nemáte oprávnění.</div>
    {/noaccessview}
    </div>
    </div>

    {if count($Dok->odeslani)>0}
    {include '../../SpisovkaModule/Dokumenty/detail-odeslani.phtml'}
    {/if}

    {include '../../SpisovkaModule/Dokumenty/detail-historie.phtml'}


    <div id="dialog"></div>