@{block title}Seznam dokumentů pro příjem do spisovny{/block}
@{block debug}
<?php print_r($seznam); ?>
@{/block}
@{block content}
    <h2>Seznam dokumentů pro příjem do spisovny</h2>

    <div id="filtr">
        {$filtrForm->render('begin')}
        {$filtrForm['filtr']->label} {$filtrForm['filtr']->control}
        {$filtrForm['go_filtr']->control}
        {$filtrForm->render('end')}
    </div>
    <div id="search">
        {control searchForm}
        <div id="search_advanced">
        {access :Spisovna:Vyhledat:}<a href="{link :Spisovna:Vyhledat:default}" id="dialog-search">Pokročilé vyhledávání</a>{/access}
        </div>
    </div>
    
    <div style="clear:both;">&nbsp;</div>

    <div style="margin: 3px 0px;">
    seřadit podle:
    {if $seradit == "cj"}
        <a href="{link this, 'seradit'=>'cj_desc'}" title="Seřadit podle čísla jednacího">čísla jednacího</a> &nbsp;
    {else}
        <a href="{link this, 'seradit'=>'cj'}" title="Seřadit podle čísla jednacího">čísla jednacího</a> &nbsp;
    {/if}
    {if $seradit == "dvzniku"}
        <a href="{link this, 'seradit'=>'dvzniku_desc'}" title="Seřadit podle data přijetí/vzniku">data přijetí/vzniku</a> &nbsp;
    {else}
        <a href="{link this, 'seradit'=>'dvzniku'}" title="Seřadit podle data přijetí/vzniku">data přijetí/vzniku</a> &nbsp;
    {/if}
    {if $seradit == "vec"}
        <a href="{link this, 'seradit'=>'vec_desc'}" title="Seřadit podle věci">věci</a> &nbsp;
    {else}
        <a href="{link this, 'seradit'=>'vec'}" title="Seřadit podle věci">věci</a> &nbsp;
    {/if}
    {if $seradit == "prideleno"}
        <a href="{link this, 'seradit'=>'prideleno_desc'}" title="Seřadit podle příjmení osoby přidělené k dokumentu">přidělené osoby</a> &nbsp;
    {else}
        <a href="{link this, 'seradit'=>'prideleno'}" title="Seřadit podle příjmení osoby přidělené k dokumentu">přidělené osoby</a> &nbsp;
    {/if}
    {if $seradit == "skartacni_znak"}
        <a href="{link this, 'seradit'=>'skartacni_znak_desc'}" title="Seřadit podle skartačního znaku">skartačního znaku</a> &nbsp;
    {else}
        <a href="{link this, 'seradit'=>'skartacni_znak'}" title="Seřadit podle skartačního znaku">skartačního znaku</a> &nbsp;
    {/if}
    {if $seradit == "spisovy_znak"}
        <a href="{link this, 'seradit'=>'spisovy_znak_desc'}" title="Seřadit podle spisové značky">spisové značky</a> &nbsp;
    {else}
        <a href="{link this, 'seradit'=>'spisovy_znak'}" title="Seřadit podle spisové značky">spisové značky</a> &nbsp;
    {/if}
    </div>

    <div id="dokumenty">
    {if count($seznam)>0}
    <form action="{link this}" method="post">
        <input type="hidden" name="url_referer" value="">
    <table>
        <tr>
            <th class="akce">&nbsp;</th>
            <th class="typ">Typ dokumentu</th>
            <th class="prijato">Přijato<br />Vyřízeno</th>
            <th class="cislo_jadnaci">Číslo jednací<br />JID<br />Název spisu</th>
            <th class="vec">Věc<br />Adresáti/odesílatelé<br />počet listů a příloh</th>
            <th class="prideleno">Přiděleno</th>
            <th class="stav">Spisový znak<br/>Skartační znak<br/>Skartační lhůta</th>
        </tr>
        {foreach $seznam as $dok}
        <tr{if $dok->lhuta_stav==2} class="red"{elseif $dok->lhuta_stav==1} class="yellow"{/if}">
            <td class="akce">
                <input type="checkbox" class="checkbox" name="dokument_vyber[]" value="{$dok->id}" title="Vybrat tento dokument" />
            </td>
            <td class="typ">
                <img src="{$baseUri}images/icons/smer{$dok->typ_dokumentu->smer}.png" alt="{$dok->typ_dokumentu->nazev}" title="{$dok->typ_dokumentu->nazev}" width="16" height="16" />
                {if !empty($dok->epod_is_email)}
                <img src="{$baseUri}images/icons/typdok1.png" alt="přijato emailem" title="přijato emailem" width="24" height="16" />
                {elseif !empty($dok->epod_is_isds)}
                <img src="{$baseUri}images/icons/typdok2.png" alt="přijato datovou schránkou" title="přijato datovou schránkou" width="24" height="16" />
                {/if}
            </td>
            <td class="prijato">
                <span title="{$dok->datum_vzniku|edatetime}">{$dok->datum_vzniku|edate}</span>
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
            </td>
            <td class="cislo_jadnaci">
                &nbsp;<strong><a href="{link :Spisovna:Dokumenty:detail, 'id'=>$dok->id}">
                   {$dok->cislo_jednaci}{if $Typ_evidence=='sberny_arch'}{$Oddelovac_poradi}{$dok->poradi}{/if}
                </a></strong>
                <div class="small">&nbsp;{$dok->jid}</div>
                {if isset($dok->spisy)}
                {foreach $dok->spisy as $spis}
                <a href="{link :Spisovna:Spisy:detail, 'id'=>$spis->id}">{$spis->nazev}</a><br />
                {/foreach}
                {/if}
            </td>
            <td class="vec">
                <strong title="{$dok->popis}"><a href="{link :Spisovna:Dokumenty:detail, 'id'=>$dok->id}">
                    {$dok->nazev}
                </a></strong>
                <br />
                <div class="mezera">
                {if count($dok->subjekty)>0}

                {foreach $dok->subjekty as $subjekt}
                {=Subjekt::displayName($subjekt,'plna_adresa')}<br />
                {/foreach}
                {else}
                nejsou přiděleny žádné subjekty!
                <br />
                {/if}
                </div>
                <span class="small">přílohy:
                {=($dok->pocet_listu)+0} listů,
                {=($dok->pocet_priloh)+0} list. příloh,
                {=(count($dok->prilohy)+0)} příloh</span>
                <br/>
                <span class="small">způsob vyřízení:
                {$dok->zpusob_vyrizeni}</span>

            </td>
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                {$dok->spisovy_znak}
                <br />
                {$dok->skartacni_znak} / {$dok->skartacni_lhuta}
            </td>
        </tr>
        {/foreach}


    </table>
    <div id="hromadna_akce">
        <span id="checkbox_all_on">Zaškrtnout vše</span> / <span id="checkbox_all_off">Odškrtnout vše</span>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Vybrané položky:&nbsp;&nbsp;
        <select name="hromadna_akce">
            <option value="prevzit_spisovna">převzetí seznamu dokumentů do spisovny</option>
        </select>
        <input type="submit" name="hromadna_submit" value="Provést" />
    </div>
    </form>
    {widget vp}
    {else}
        <div>&nbsp;</div>
        {if isset($no_items)}
        {if $no_items==1}
        <div class="prazdno">Nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==2}
        <div class="prazdno">K danému filtru nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==3}
        <div class="prazdno">Dokumenty odpovidající hledanému výrazu nebyly nalezeny.</div>
        {elseif $no_items==4}
        <div class="prazdno">Dokumenty odpovidající daným požadavkům nebyly nalezeny.</div>
        {/if}
        {else}
    <div class="prazdno">Nebyly zjištěny žádné dokumenty.</div>
        {/if}
    {/if}
    </div>

    <div id="dialog"></div>