{block title}Seznam roli{/block}
{block content}
    <div class="navigate">
    Seznam roli
    </div>

    <h2>Seznam roli</h2>

    <div class="blok_menu">
        <a href="{link :Admin:Opravneni:novy}">Nová role</a>
    </div>
    {if count($seznam)>0}
    <table class="seznam">
        <tr>
            <th>Název role</th>
            <th>Popis</th>
            <th>Kódové označení</th>
            <th>Dědí z role</th>
        </tr>
        {foreach $seznam as $role}
        <tr>
            <td><a href="{vlink :Admin:Opravneni:detail, 'id'=>$role->id}">{$role->name}</a></td>
            <td>{!$role->note|enl2br}</td>
            <td>{$role->code}</td>
            <td>{$role->parent_name}</td>
        </tr>
        {/foreach}
    </table>
    {else}
    <div class="prazdno">Nebyly zjištěny žádné role.</div>
    {/if}
