@{block title}Seznam dokumentů{/block}
@{block debug}
<?php print_r($seznam); ?>
@{/block}
@{block content}
    <h2>Seznam dokumentů</h2>

    <div id="tisk">
        <a href="{link this, 'print' => 1}" title="vytisknout tuto stránku" target="_blank">
            <img src="{$baseUri}images/icons/printer.png" alt="printer.png" width="32" height="32" />
        </a>
        <a href="{link this, 'pdfprint' => 1}" title="Vytisknout tuto stránku do PDF" target="_blank">
            <img src="{$baseUri}images/mimetypes/application-pdf.png" alt="application-pdf.png" width="32" height="32" />
        </a>        
    </div>
    
    <div id="filtr">
        {$filtrForm->render('begin')}
        {$filtrForm['filtr']->label} {$filtrForm['filtr']->control}
        {$filtrForm['go_filtr']->control}
        <br/>
        {$filtrForm['bez_vyrizenych']->control}{$filtrForm['bez_vyrizenych']->label}<br/>
        {$filtrForm['jen_moje']->control}{$filtrForm['jen_moje']->label}
        {$filtrForm->render('end')}
    </div>
    <div id="search">
        {control searchForm}
        <div id="search_advanced">
        {if !empty($s3_hledat)}<a href="{link :Spisovka:Vyhledat:reset}" style="color:#ff0000;">Zrušit vyhledávání</a>&nbsp;&nbsp;&nbsp;{/if}
        {access :Spisovka:Vyhledat:}<a href="{link :Spisovka:Vyhledat:default}" id="dialog-search">Pokročilé vyhledávání</a>{/access}
        {if is_array($s3_hledat)}<br/><br/>Aplikováno pokročilé vyhledávání{/if}
        </div>
    </div>
    
    <br style="clear:both;" />

    <div style="margin: 3px 0px;" id="seradit">
    {control seraditForm}
    </div>

    <div id="dokumenty">
    {if count($seznam)>0}
    <form action="{link this}" method="post">
        <input type="hidden" name="url_referer" value="">
    <table>
        <tr>
            <th class="akce">&nbsp;</th>
            <th class="typ">Typ dokumentu</th>
            <th class="prijato">Přijato</th>
            <th class="cislo_jednaci">Číslo jednací<br />JID<br />Název spisu</th>
            <th class="vec">Věc<br />Adresáti/odesílatelé<br />počet listů a příloh</th>
            <th class="prideleno">Přiděleno / Vyřídil<br />> Předáno</th>
            <th class="stav">Stav</th>
        </tr>
        {foreach $seznam as $dok}
        <tr{if $dok->lhuta_stav==2} class="red"{elseif $dok->lhuta_stav==1} class="yellow"{/if}">
            <td class="akce">
                <input type="checkbox" class="checkbox" name="dokument_vyber[]" value="{$dok->id}" title="Vybrat tento dokument" />
            </td>
            <td class="typ">
                <img src="{$baseUri}images/icons/smer{$dok->typ_dokumentu->smer}.png" alt="{$dok->typ_dokumentu->nazev}" title="{$dok->typ_dokumentu->nazev}" width="16" height="16" />
                {if !empty($dok->epod_is_email)}
                <img src="{$baseUri}images/icons/typdok1.png" alt="přijato emailem" title="přijato nebo odesláno emailem" width="24" height="16" />
                {elseif !empty($dok->epod_is_isds)}
                <img src="{$baseUri}images/icons/typdok2.png" alt="přijato datovou schránkou" title="přijato nebo odesláno datovou schránkou" width="24" height="16" />
                {/if}
            </td>
            <td class="prijato" title="{$dok->datum_vzniku|edatetime}">
                {$dok->datum_vzniku|edate}
            </td>
            <td class="cislo_jednaci">
                &nbsp;<strong><a href="{link :Spisovka:Dokumenty:detail, 'id'=>$dok->id}">
                   {if empty($dok->cislo_jednaci)}
                   (není evidován)
                   {else}
                   {$dok->cislo_jednaci}{if $Typ_evidence=='sberny_arch'}{$Oddelovac_poradi}{$dok->poradi}{/if}
                   {/if}
                </a></strong>
                <div class="small">&nbsp;{$dok->jid}</div>
                {if isset($dok->spisy)}
                {foreach $dok->spisy as $spis}
                <a href="{link :Spisovka:Spisy:detail, 'id'=>$spis->id}">{$spis->nazev}</a><br />
                {/foreach}
                {/if}
            </td>
            <td class="vec">
                <strong title="{$dok->popis}"><a href="{link :Spisovka:Dokumenty:detail, 'id'=>$dok->id}">
                    {$dok->nazev}
                </a></strong>
                <br />
                <div class="mezera">
                {if count($dok->subjekty)>0}

                {foreach $dok->subjekty as $subjekt}
                {=Subjekt::displayName($subjekt,'plna_adresa')}<br />
                {/foreach}
                {else}
                nejsou přiděleny žádné subjekty!
                <br />
                {/if}
                </div>
                <span class="small">přílohy:
                {=($dok->pocet_listu)+0} listů,
                {=($dok->pocet_priloh)+0} list. příloh,
                {=(count($dok->prilohy)+0)} příloh</span>
            </td>



            {if $dok->stav_dokumentu == 1 && !empty($dok->prideleno)}
            <td class="prideleno">
            {if empty($dok->prideleno->prideleno_id) }
                {$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {else}
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {/if}
            </td>
            <td class="stav {if $dok->lhuta_stav==2}stav_red" title="Vypršela lhůta k vyřízení! Vyříďte neprodleně tento dokument."{elseif $dok->lhuta_stav==1}stav_yellow" title="Za pár dní vyprší lhůta k vyřízení! Vyříďte co nejrychleji tento dokument."{else}stav"{/if}>
                nový
                <br />
                <span title="{$dok->prideleno->date|edatetime}">{$dok->prideleno->date|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 2 && !empty($dok->predano) }
            <td class="prideleno">
            {if empty($dok->prideleno->prideleno_id) }
                {$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {else}
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {/if}
                <br />
            {if empty($dok->predano->prideleno_id) }
                > {$dok->predano->orgjednotka_info->zkraceny_nazev}
            {else}
                > {$dok->predano->prideleno_jmeno}
                <br />
                > {=@$dok->predano->orgjednotka_info->zkraceny_nazev}
            {/if}
            
            </td>
            <td class="stav {if $dok->lhuta_stav==2}stav_red{elseif $dok->lhuta_stav==1}stav_yellow{else}stav{/if}">
                předáno
                <br />
                <span title="{$dok->predano->date_predani|edatetime}">{$dok->predano->date_predani|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 2 && !empty($dok->prideleno) }
            <td class="prideleno">
            {if empty($dok->prideleno->prideleno_id) }
                {$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {else}
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {/if}
            </td>
            <td class="stav {if $dok->lhuta_stav==2}stav_red{elseif $dok->lhuta_stav==1}stav_yellow{else}stav{/if}">
                přiděleno
                <br />
                <span title="{$dok->prideleno->date|edatetime}">{$dok->prideleno->date|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 3 }
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav {if $dok->lhuta_stav==2}stav_red{elseif $dok->lhuta_stav==1}stav_yellow{else}stav{/if}">
                vyřizuje se
                <br />
                <span title="{$dok->prideleno->date|edatetime}">{$dok->prideleno->date|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 4 }
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                vyřízeno
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 5 }
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                vyřízeno
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 6 }
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                vyřízeno<br />předáno do spisovny
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 7 }
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                vyřízeno<br />ve spisovně
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 11 }
            <td class="prideleno">
                {if !empty($dok->predano)}
                {$dok->predano->prideleno_jmeno}
                <br />
                {=@$dok->predano->orgjednotka_info->zkraceny_nazev}
                {else}
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
                {/if}
            </td>
            <td class="stav">
                zapůjčen
                <br />
            </td>
            {else}
            <td class="prideleno">
                &nbsp;
            </td>
            <td class="stav">
                nepřiřazeno!
                <br />
                lhůta {$dok->lhuta} dní
            </td>
            {/if}



        </tr>
        {/foreach}


    </table>
    <div id="hromadna_akce">
        <span id="checkbox_all_on">Zaškrtnout vše</span> / <span id="checkbox_all_off">Odškrtnout vše</span>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Vybrané položky:&nbsp;&nbsp;
        <select name="hromadna_akce">
            <option value="">(žádná akce)</option>
            <option value="prevzit">převzít</option>
            <option value="predat_spisovna">předat do spisovny</option>
            <option value="tisk">tisknout</option>
        </select>
        <input type="submit" name="hromadna_submit" value="Provést" />
    </div>
    </form>
    {widget vp}
    {else}
        <div>&nbsp;</div>
        {if isset($no_items)}
        {if $no_items==1}
        <div class="prazdno">Nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==2}
        <div class="prazdno">Danému filtru neodpovídá žádný dokument.</div>
        {elseif $no_items==3}
        <div class="prazdno">Dokumenty odpovídající hledanému výrazu nebyly nalezeny.</div>
        {elseif $no_items==4}
        <div class="prazdno">Dokumenty odpovídající daným požadavkům nebyly nalezeny.</div>
        {/if}
        {else}
    <div class="prazdno">Nebyly zjištěny žádné dokumenty.</div>
        {/if}
    {/if}
    </div>

    <div id="dialog"></div>