@{block title}Seznam dokumentů{/block}
@{block debug}
<?php print_r($seznam); ?>
@{/block}
@{block content}
    <h2>Seznam dokumentů</h2>

    <div id="filtr">
        {$filtrForm->render('begin')}
        {$filtrForm['filtr']->label} {$filtrForm['filtr']->control}
        {$filtrForm['go_filtr']->control}
        <br/>
        {$filtrForm['bez_vyrizenych']->control}{$filtrForm['bez_vyrizenych']->label}
        {$filtrForm->render('end')}
    </div>
    <div id="search">
        {control searchForm}
        <div id="search_advanced">
        {access :Spisovka:Vyhledat:default}<a href="{link :Spisovka:Vyhledat:default}" id="dialog-search">Pokročilé vyhledávání</a>{/access}
        </div>
    </div>
    
    <div style="clear:both;">&nbsp;</div>

    <div style="margin: 3px 0px;">
    seřadit podle:
    {if $seradit == "stav"}
        <a href="{link this, 'seradit'=>'stav_desc'}" title="Seřadit podle stavu dokumentu (nový, předaný, vyřizuje se, vyřízený, ...)">stavu</a> &nbsp;
    {else}
        <a href="{link this, 'seradit'=>'stav'}" title="Seřadit podle stavu dokumentu (nový, předaný, vyřizuje se, vyřízený, ...)">stavu</a> &nbsp;
    {/if}
    {if $seradit == "cj"}
        <a href="{link this, 'seradit'=>'cj_desc'}" title="Seřadit podle čísla jednacího">čísla jednacího</a> &nbsp;
    {else}
        <a href="{link this, 'seradit'=>'cj'}" title="Seřadit podle čísla jednacího">čísla jednacího</a> &nbsp;
    {/if}
    {if $seradit == "dvzniku"}
        <a href="{link this, 'seradit'=>'dvzniku_desc'}" title="Seřadit podle data přijetí/vzniku">data přijetí/vzniku</a> &nbsp;
    {else}
        <a href="{link this, 'seradit'=>'dvzniku'}" title="Seřadit podle data přijetí/vzniku">data přijetí/vzniku</a> &nbsp;
    {/if}
    {if $seradit == "vec"}
        <a href="{link this, 'seradit'=>'vec_desc'}" title="Seřadit podle věci">věci</a> &nbsp;
    {else}
        <a href="{link this, 'seradit'=>'vec'}" title="Seřadit podle věci">věci</a> &nbsp;
    {/if}
    {if $seradit == "prideleno"}
        <a href="{link this, 'seradit'=>'prideleno_desc'}" title="Seřadit podle příjmení osoby přidělené k dokumentu">přidělené osoby</a> &nbsp;
    {else}
        <a href="{link this, 'seradit'=>'prideleno'}" title="Seřadit podle příjmení osoby přidělené k dokumentu">přidělené osoby</a> &nbsp;
    {/if}
    </div>

    <div id="dokumenty">
    {if count($seznam)>0}
    <table>
        <tr>
            <th class="typ">Typ dokumentu</th>
            <th class="prijato">Přijato</th>
            <th class="cislo_jadnaci">Číslo jednací<br />JID<br />Spisová značka</th>
            <th class="vec">Věc<br />Adresáti/odesílatelé<br />počet listů a příloh</th>
            <th class="prideleno">Přiděleno</th>
            <th class="stav">Stav</th>
        </tr>
        {foreach $seznam as $dok}
        <tr{if $dok->lhuta_stav==2} class="red"{elseif $dok->lhuta_stav==1} class="yellow"{/if}">
            <td class="typ">
                <img src="{$baseUri}images/icons/smer{$dok->typ_dokumentu->smer}.png" alt="{$dok->typ_dokumentu->nazev}" title="{$dok->typ_dokumentu->nazev}" width="16" height="16" />
                <!--<img src="{$baseUri}images/icons/typdok{$dok->typ_dokumentu->typ}.png" alt="{$dok->typ_dokumentu->nazev}" title="{$dok->typ_dokumentu->nazev}" width="24" height="16" />-->
            </td>
            <td class="prijato" title="{$dok->datum_vzniku|edatetime}">
                {$dok->datum_vzniku|edate}
            </td>
            <td class="cislo_jadnaci">
                &nbsp;<strong><a href="{link :Spisovka:Dokumenty:detail, 'id'=>$dok->id}">
                   {$dok->cislo_jednaci}{if $Typ_evidence=='sberny_arch'}{$Oddelovac_poradi}{$dok->poradi}{/if}
                </a></strong>
                <div class="small">&nbsp;{$dok->jid}</div>
                {if count($dok->spisy)>0}
                {foreach $dok->spisy as $spis}
                <a href="{link :Spisovka:Spisy:detail, 'id'=>$spis->id}">{$spis->nazev}</a><br />
                {/foreach}
                {/if}
            </td>
            <td class="vec">
                <strong title="{$dok->popis}"><a href="{link :Spisovka:Dokumenty:detail, 'id'=>$dok->id}">
                    {$dok->nazev}
                </a></strong>
                <br />
                <div class="mezera">
                {if count($dok->subjekty)>0}

                {foreach $dok->subjekty as $subjekt}
                {=Subjekt::displayName($subjekt,'plna_adresa')}<br />
                {/foreach}
                {else}
                nejsou přiděleny žádné subjekty!
                <br />
                {/if}
                </div>
                <span class="small">přílohy:
                {=($dok->pocet_listu)+0} listů,
                {=($dok->pocet_priloh)+0} list. příloh,
                {=(count($dok->prilohy)+0)} příloh</span>
            </td>



            {if $dok->stav_dokumentu == 1}
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
            </td>
            <td class="stav {if $dok->lhuta_stav==2}stav_red" title="Vypršela lhůta k vyřízení! Vyříďte neprodleně tento dokument."{elseif $dok->lhuta_stav==1}stav_yellow" title="Za pár dní vyprší lhůta k vyřízení! Vyříďte co nejrychleji tento dokument."{else}stav"{/if}>
                nový
                <br />
                <span title="{$dok->prideleno->date|edatetime}">{$dok->prideleno->date|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 2 && !empty($dok->predano) }
            <td class="prideleno">
            {if empty($dok->prideleno->prideleno_id) }
                {$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {else}
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {/if}
            </td>
            <td class="stav {if $dok->lhuta_stav==2}stav_red{elseif $dok->lhuta_stav==1}stav_yellow{else}stav{/if}">
                předáno
                <br />
                <span title="{$dok->predano->date_predani|edatetime}">{$dok->predano->date_predani|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 2 && !empty($dok->prideleno) }
            <td class="prideleno">
            {if empty($dok->prideleno->prideleno_id) }
                {$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {else}
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {/if}
            </td>
            <td class="stav {if $dok->lhuta_stav==2}stav_red{elseif $dok->lhuta_stav==1}stav_yellow{else}stav{/if}">
                přiděleno
                <br />
                <span title="{$dok->prideleno->date|edatetime}">{$dok->prideleno->date|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 3 }
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav {if $dok->lhuta_stav==2}stav_red{elseif $dok->lhuta_stav==1}stav_yellow{else}stav{/if}">
                vyřizuje se
                <br />
                <span title="{$dok->prideleno->date|edatetime}">{$dok->prideleno->date|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 4 }
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                vyřízeno
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 5 }
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                vyřízeno
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
            </td>

            {else}
            <td class="prideleno">
                &nbsp;
            </td>
            <td class="stav">
                nepřiřazeno!
                <br />
                lhůta {$dok->lhuta} dní
            </td>
            {/if}



        </tr>
        {/foreach}


    </table>
    {widget vp}
    {else}
        <div>&nbsp;</div>
        {if isset($no_items)}
        {if $no_items==1}
        <div class="prazdno">Nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==2}
        <div class="prazdno">K danému filtru nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==3}
        <div class="prazdno">Dokumenty odpovidající hledanému výrazu nebyly nalezeny.</div>
        {elseif $no_items==4}
        <div class="prazdno">Dokumenty odpovidající daným požadavkům nebyly nalezeny.</div>
        {/if}
        {else}
    <div class="prazdno">Nebyly zjištěny žádné dokumenty.</div>
        {/if}
    {/if}
    </div>

    <div id="dialog"></div>