@{block title}Dokument{/block}
{assign Select2 => true}
@{block javascript}
	<script type="text/javascript" src="{$baseUri}js/webtoolkit.aim.js"></script>
	<script type="text/javascript">
function startCallback() {
			return true;
		}

		function completeCallback(response) {

                        if ( response.indexOf('###vybrano###') != - 1) {
    alert('Příloha byl nahrána.');
            $('#dialog').dialog('close');
            renderPrilohy({$Dok->id});
    } else if (response.indexOf('###zmemeno###') != - 1) {
    alert('Příloha byla upravena.');
            $('#dialog').dialog('close');
            renderPrilohy({$Dok->id});
    } else {
    $('#dialog').html(response);
    }
    }


    function onChangeRadioButtonSpousteciUdalost(elm) {

    var isChecked = $('#frmudalostForm-udalost_typ-1').is(':checked');
            var sel = $('#frmudalostForm-datum_spousteci_udalosti');
            if (!isChecked)
            sel.prop('disabled', true);
            else {
            sel.prop('disabled', false);
                    sel.focus();
            }
    }

    $(document).ready(function() {
    $('#frmudalostForm-datum_spousteci_udalosti').prop('disabled', true);
            //$('#frmvyrizovaniForm-spisovy_znak_id').select2({ width: 'resolve' });

    });   

     var smer_typu_dokumentu = new Array();
    {foreach $typy_dokumentu as $t}
    smer_typu_dokumentu[{$t->id}] = {$t->smer};
    {/foreach}

    var typ_dokumentu_id = {$Dok->typ_dokumentu->id};    
	</script>
    {include ../../@vlozSpisZnak.phtml}
@{/block}
@{block debug}
<?php echo "\n\nDokument: "; print_r($Dok); ?>

@{/block}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovka:Dokumenty:default}">Seznam dokumentů</a> - Detail dokumentu
    {if ($FormUpravit=='metadata')}
    - Úprava metadat
    {elseif ($FormUpravit=='vyrizeni')}
    - Úprava vyřízení
    {/if}
    </div>

    <div id="tisk">
        <a href="{link :Spisovka:Dokumenty:detail, 'id'=>$Dok->id, 'print' => 1}" title="vytisknout tuto stránku" target="_blank">
            <img src="{$baseUri}images/icons/printer.png" alt="printer.png" width="32" height="32" />
        </a>
        <a href="{link :Spisovka:Dokumenty:detail, 'id'=>$Dok->id, 'pdfprint' => 1}" title="Vytisknout tuto stránku do PDF" target="_blank">
            <img src="{$baseUri}images/mimetypes/application-pdf.png" alt="application-pdf.png" width="32" height="32" />
        </a>        
    </div>

    <div id="dokument_blok_volby">
       {accessedit}
       {if $Pridelen==1 }
       <a href="{link :Spisovka:Dokumenty:detail , 'id'=>$Dok->id , 'upravit'=>'metadata'  }">Upravit metadata</a>
       <?php if ( isset($nutnyNadpis) ) { ?>
       <script type="text/javascript"> alert("Název dokumentu (věc) je prázdný. Je nutné ho vyplnit!"); </script>     
       <?php } ?>
       {/if}
       {if ($Pridelen==1 && $Vyrizovani == 1 ) }
       <a href="{link :Spisovka:Dokumenty:detail , 'id'=>$Dok->id , 'upravit'=>'vyrizeni'  }">Upravit vyřízení</a>
       {/if}
       <a href="{link :Spisovka:Uzivatel:vyber, 'dok_id'=>$Dok->id}" id="dialog-uzivatel">Předat dokument</a>
       {if $Predan==1 }
       <a href="{link :Spisovka:Dokumenty:prevzit, 'id'=>$Dok->id}" id="prevzitdokument">Převzít dokument</a>
       <a href="{link :Spisovka:Dokumenty:odmitnoutprevzeti, 'id'=>$Dok->id}" id="zrusitprevzetidokument">Odmítnout převzetí</a>
       {/if}
       {if ($Pridelen==1 && !empty($Dok->predano) ) }
       <a href="{link :Spisovka:Dokumenty:zrusitprevzeti, 'id'=>$Dok->id}" id="zrusitprevzetidokument">Zrušit převzetí dokumentu</a>
       {/if}
       {if ($Pridelen==1 && $Vyrizovani == 0 ) }
       <a href="{link :Spisovka:Dokumenty:kvyrizeni, 'id'=>$Dok->id}" id="kvyrizenidokument">Označit k vyřízení</a>
       {/if}
       {if ($povolitOdpoved && $Pridelen==1 && !empty($Dok->cislo_jednaci)) }
       <a href="{link :Spisovka:Dokumenty:odpoved, 'id'=>$Dok->id}" >Vytvořit odpověď</a>
       {/if}
       {if ($Pridelen==1 && $Vyrizovani == 1 ) }
       <a href="{link :Spisovka:Dokumenty:odeslat , 'id'=>$Dok->id }">Odeslat dokument</a>
       {/if}
       {if ($Pridelen==1 && $Vyrizovani == 1 ) }
       <a href="{link :Spisovka:Dokumenty:vyrizeno, 'id'=>$Dok->id}" id="vyrizenodokument">Označit dokument za vyřízený</a>
       {/if}
       &nbsp;
       {/accessedit}
       <a href="{link this, 'id'=>$Dok->id, 'udalost'=>1}" n:if="$Dok->stav_dokumentu == 4">Spouštěcí událost</a>
    </div>
    {if $Zapujcka}
    <div id="dokument_blok_volby">
       {if !empty($Dok->predano->prideleno_id) }
       <a href="{link :Spisovka:Dokumenty:prevzit, 'id'=>$Dok->id}" id="prevzitdokument">Převzít dokument k zapůjčení</a>
       {/if}
       <a href="{link :Spisovna:Zapujcky:vratit, 'id'=>$Zapujcka->id}">Vrátit dokument</a>
    </div>
    {/if}    

    {if ($FormUdalost)}
    <div class="dokument_blok2">
        <div class="h2">Vyberte datum spouštěcí události</div>
        <p><strong>Poznámka:</strong> Spouštěcí událost je okamžik rozhodný pro počátek plynutí skartační lhůty. Skartační lhůta se určuje počtem celých roků počítaných od 1. ledna kalendářního roku následujícího po kalendářním roce, v němž nastala spouštěcí událost.</p>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{=SpisovyZnak::spousteci_udalost($Dok->spousteci_udalost_id,10)}&nbsp;</dd>
        </dl>
        {$udalostForm->render('begin')}
        <dl class="detail_item">
            <dt>Určete rozhodný okamžik:</dt>
            <dd>
                {$udalostForm['udalost_typ']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum spouštěcí události:</dt>
            <dd>
                {$udalostForm['datum_spousteci_udalosti']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>&nbsp;</dt>
            <dd>
                {$udalostForm['ok']->control}
            </dd>
        </dl>
        {$udalostForm->render('end')}
    </div>
    {/if}

    {if $Skartacni_dohled==1}
    <div class="dokument_blok2">
        <div class="h2">Připojit dokument do skartačního řízení k posouzení</div>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd title="{$Dok->spisovy_znak_popis}">{$Dok->spisovy_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Dok->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>&nbsp;</dt>
            <dd>
                <a href="{link :Spisovka:Dokumenty:keskartaci, 'id'=>$Dok->id}" id="keskartacidokument">Přidat do skartačního řízení</a>
            </dd>
        </dl>
    </div>
    {/if}

    {if $Skartacni_komise==1}
    <div class="dokument_blok2">
        <div class="h2">Rozhodnutí o skartaci dokumentu</div>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd title="{$Dok->spisovy_znak_popis}">{$Dok->spisovy_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Dok->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Rozhodnutí:</dt>
            <dd>
                <a href="{link :Spisovka:Dokumenty:archivovat, 'id'=>$Dok->id}" id="archivovatdokument">Archivovat</a>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{link :Spisovka:Dokumenty:skartovat, 'id'=>$Dok->id}" id="skartovatdokument">Skartovat</a>
            </dd>
        </dl>
    </div>
    {/if}



    <div id="dokument_blok_hlavni">
        {if ($FormUpravit=='metadata')}
        {$metadataForm->render('begin')}
        <dl class="detail_item">
            <dt>JID:</dt>
            <dd>
                {$Dok->jid}&nbsp;
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Typ dokumentu:</dt>
            {if $isRozdelany}
            <dd>{$metadataForm['dokument_typ_id']->control}</dd>
            {else}
            <dd>{$Dok->typ_dokumentu->nazev}</dd>
            {/if}
        </dl>
        {if empty($Dok->cislo_jednaci)}
        <dl class="detail_item">
            <dt>Číslo jednací{if $Typ_evidence == 'sberny_arch'} {$Oddelovac_poradi} pořadí{/if}:</dt>
            <dd>Dokument není evidován!
                {if $Pridelen==1}
                {if $Typ_evidence == 'sberny_arch'}
                <br /><a href="{link :Spisovka:Dokumenty:pridelitcj, 'id'=>$Dok->id}">Zaevidovat do spisové služby - nový dokument/spis</a>
                <br /><a href="{link :Spisovka:Dokumenty:cjednaci, 'id'=>$Dok->id, 'evidence'=>1}" id="dialog-cjednaci">Zaevidovat do spisové služby - vložit do dokumentu/spisu</a>
                {else}
                <br /><a href="{link :Spisovka:Dokumenty:pridelitcj, 'id'=>$Dok->id}">Zaevidovat do spis. služby</a>
                {/if}
                {/if}
            </dd>
        </dl>
        {else}
        <dl class="detail_item">
            <dt>Číslo jednací{if $Typ_evidence == 'sberny_arch'} {$Oddelovac_poradi} pořadí{/if}:</dt>
            <dd class="nadpis">{$Dok->cislo_jednaci}{if $Typ_evidence == 'sberny_arch'}{$Oddelovac_poradi}{$Dok->poradi}{/if}&nbsp;</dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Název spisu:</dt>
            <dd>
                <span id="dok_spis">
                {if isset($Dok->spisy) }
                    {foreach $Dok->spisy as $s}
                    <a href="{link :Spisovka:Spisy:detail, 'id'=>$s->id}">{$s->nazev}</a>&nbsp;&nbsp;&nbsp;&nbsp; <a href="{link :Spisovka:Spisy:odebratspis, 'dok_id'=>$Dok->id, 'id'=>$s->id}" onclick="return confirm('Opravdu chcete vyjmout tento dokument ze spisu?');">Vyjmout ze spisu</a><br />
                    {/foreach}
                {else}
                    nepřidělen k žádnému spisu
                {/if}
                </span>
                {if $Typ_evidence != 'sberny_arch'}
                <a href="{link :Spisovka:Spisy:vyber, 'id'=>$Dok->id}" id="dialog-spis">Připojit spis</a>
                {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>{$metadataForm['nazev']->label}</dt>
            <dd>{$metadataForm['nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{$metadataForm['popis']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum doručení/vzniku:</dt>
            {if $isRozdelany}
            <dd>{$metadataForm['datum_vzniku']->control} {$metadataForm['datum_vzniku_cas']->control}</dd>
            {else}
            <dd>{$Dok->datum_vzniku|edatetime}&nbsp;</dd>
            {/if}
        </dl>
        {if $isRozdelany && $isPodatelna}
        <dl class="detail_item">
            <dt>{$metadataForm['zpusob_doruceni_id']->label}</dt>
            <dd>{$metadataForm['zpusob_doruceni_id']->control}</dd>
        </dl> 
        {elseif !empty($Dok->zpusob_doruceni)}
        <dl class="detail_item">
            <dt>Způsob doručení:</dt>
            <dd>{$Dok->zpusob_doruceni}&nbsp;</dd>
        </dl>        
        {/if}
        {if $isPodatelna}
        <dl class="detail_item">
            <dt>Číslo doporučeného dopisu:</dt>
            <dd>{$metadataForm['cislo_doporuceneho_dopisu']->control}</dd>
        </dl>    
        {/if}                
        {if $isPodatelna}
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$metadataForm['cislo_jednaci_odesilatele']->control}</dd>
        </dl>
        {/if}
        
        {if !empty($Dok->poznamka)}<dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{$metadataForm['poznamka']->control}</dd>
        </dl>{/if}
        {if $Typ_evidence == 'priorace'}
        <dl class="detail_item">
            <dt>Spojit s dokumentem:</dt>
            <dd>
                <span id="dok_spojit">
                {if count($SouvisejiciDokumenty)>0 }
                    {foreach $SouvisejiciDokumenty as $s}
                    <a href="{link :Spisovka:Dokumenty:detail, 'id'=>$s->id}">{$s->cislo_jednaci} ({$s->jid})</a>
                    {if $s->spojeni == "zpetne_spojen"}
                    &nbsp;&nbsp;&nbsp;[<a href="{link :Spisovka:Spojit:odebrat, 'id'=>$Dok->id, 'zpetne_spojeny'=>$s->id}">odebrat spojení</a>]
                    {else}
                    &nbsp;&nbsp;&nbsp;[<a href="{link :Spisovka:Spojit:odebrat, 'id'=>$Dok->id, 'spojeny'=>$s->id}">odebrat spojení</a>]
                    {/if}
                    <br />
                    {/foreach}
                {/if}
                </span>
                &nbsp;[<a href="{link :Spisovka:Spojit:vyber, 'id'=>$Dok->id}" id="dialog-spojit">spojit s dokumentem</a>]
            </dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Počet listů:</dt>
            <dd>{$metadataForm['pocet_listu']->control}
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: normal;">Počet listů příloh: </span>{$metadataForm['pocet_priloh']->control}
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: normal;">Typ přílohy: </span>{$metadataForm['typ_prilohy']->control}
            </dd>
        </dl>
        <div>
            {$metadataForm['upravit']->control}
            &nbsp;&nbsp;
            {$metadataForm['storno']->control}
        </div>
        {$metadataForm->render('end')}
        {else}
        <div class="h2">{$Dok->typ_dokumentu->nazev}</div>
        <dl class="detail_item">
            <dt>JID:</dt>
            <dd>{$Dok->jid}&nbsp;</dd>
        </dl>
        {if empty($Dok->cislo_jednaci)}
        <dl class="detail_item">
            <dt>Číslo jednací{if $Typ_evidence == 'sberny_arch'} / pořadí{/if}:</dt>
            <dd>Dokument není evidován!
                {if $Pridelen==1}
                {if $Typ_evidence == 'sberny_arch'}
                <br /><a href="{link :Spisovka:Dokumenty:pridelitcj, 'id'=>$Dok->id}">Zaevidovat do spisové služby - nový dokument/spis</a>
                <br /><a href="{link :Spisovka:Dokumenty:cjednaci, 'id'=>$Dok->id, 'evidence'=>1}" id="dialog-cjednaci">Zaevidovat do spisové služby - vložit do dokumentu/spisu</a>
                {else}
                <br /><a href="{link :Spisovka:Dokumenty:pridelitcj, 'id'=>$Dok->id}">Zaevidovat do spis. služby</a>
                {/if}
                {/if}
            </dd>
        </dl>
        {else}
        <dl class="detail_item">
            <dt>Číslo jednací{if $Typ_evidence == 'sberny_arch'} {$Oddelovac_poradi} pořadí{/if}:</dt>
            <dd class="nadpis">{$Dok->cislo_jednaci}{if $Typ_evidence == 'sberny_arch'}{$Oddelovac_poradi}{$Dok->poradi}{/if}&nbsp;</dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Název spisu:</dt>
            <dd>
            {if isset($Dok->spisy) }
                {foreach $Dok->spisy as $s}
                <a href="{link :Spisovka:Spisy:detail, 'id'=>$s->id}">{$s->nazev}</a><br />
                {/foreach}
            {else}
                nepřidělen k žádnému spisu
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd class="nadpis"><u>{$Dok->nazev}</u>&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{!$Dok->popis|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum doručení/vzniku:</dt>
            <dd>{$Dok->datum_vzniku|edatetime}&nbsp;</dd>
        </dl>
        {if !empty($Dok->zpusob_doruceni)}
        <dl class="detail_item">
            <dt>Způsob doručení:</dt>
            <dd>{$Dok->zpusob_doruceni}&nbsp;</dd>
        </dl>        
        {/if}
        {if !empty($Dok->cislo_jednaci_odesilatele)}
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$Dok->cislo_jednaci_odesilatele}&nbsp;</dd>
        </dl>
        {/if}
        {if !empty($Dok->cislo_doporuceneho_dopisu)}
        <dl class="detail_item">
            <dt>Číslo doporučeného dopisu:</dt>
            <dd>{$Dok->cislo_doporuceneho_dopisu}&nbsp;</dd>
        </dl>
        {/if}
        
        {if !empty($Dok->poznamka)}
        <dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{!$Dok->poznamka|html2br}&nbsp;</dd>
        </dl>
        {/if}
        {if count($SouvisejiciDokumenty)>0 }
        <dl class="detail_item">
            <dt>Spojeno s dokumentem:</dt>
            <dd>
                <span id="dok_spojit">
                {foreach $SouvisejiciDokumenty as $s}
                    <a href="{link :Spisovka:Dokumenty:detail, 'id'=>$s->id}">{$s->cislo_jednaci} ({$s->jid})</a><br />
                {/foreach}
                </span>
                &nbsp;
            </dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Počet listů / příloh / typ přílohy:</dt>
            <dd>{!$Dok->pocet_listu|num} / {!$Dok->pocet_priloh|num} {if !empty($Dok->typ_prilohy)}/ {$Dok->typ_prilohy}{/if}</dd>
        </dl>
        {if !empty($Dok->identifikator)}
        <dl class="detail_item">
            <dt>Identifikátor epodatelny:</dt>
            <dd><pre>{$Dok->identifikator['popis']}</pre></dd>
        </dl>
        {if $Dok->identifikator['typ'] == "email" }
        <dl class="detail_item">
            <dt>Ověření identifikátoru:</dt>
            <dd>
            {if $Dok->identifikator['cert_signed'] >= 0 }
                {$Dok->identifikator['cert_log']['aktualne']['date']} &nbsp;
                {if $Dok->identifikator['cert_log']['aktualne']['status']==1 }
                <span style="color:#009900;">{$Dok->identifikator['cert_log']['aktualne']['message']}</span>
                {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_log']['aktualne']['message']}</span>
                {/if}
                <br />
                {$Dok->identifikator['cert_log']['prijato']['date']} &nbsp;
                {if $Dok->identifikator['cert_log']['prijato']['status']==1 }
                <span style="color:#009900;">{$Dok->identifikator['cert_log']['prijato']['message']}</span>
                {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_log']['prijato']['message']}</span>
                {/if}
                <br />
                {$Dok->identifikator['cert_log']['doruceno']['date']} &nbsp;
                {if $Dok->identifikator['cert_log']['doruceno']['status']==1 }
                <span style="color:#009900;">{$Dok->identifikator['cert_log']['doruceno']['message']}</span>
                {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_log']['doruceno']['message']}</span>
                {/if}
            {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_status']}</span>
            {/if}
            </dd>
        </dl>
        {/if}
        {if $Dok->identifikator['typ'] == "isds" }
        <dl class="detail_item">
            <dt>Ověření identifikátoru:</dt>
            <dd id="isds_overeni">
                <a href="{link :Spisovka:Dokumenty:isdsovereni, 'id'=>$Dok->id}" onclick="return overitISDS(this);">Ověřit datovou zprávu</a>
            </dd>
        </dl>
        {/if}

        
        {/if}
        {/if}
    </div>
    {if $Vyrizovani == 1 }
    <div id="dokument_blok_vyrizeni">
        <div class="h2">Vyřízení <span class='toggler' onclick='toggleWindow(this);'>&nbsp;</span></div>
        <div class="dokument_blok">
        {if ($FormUpravit=='vyrizeni')}
        {$vyrizovaniForm->render('begin')}
        <dl class="detail_item">
            <dt>Způsob vyřízení:</dt>
            <dd>{$vyrizovaniForm['zpusob_vyrizeni_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyřízení:</dt>
            <dd>{$vyrizovaniForm['datum_vyrizeni']->control} {$vyrizovaniForm['datum_vyrizeni_cas']->control}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{$vyrizovaniForm['spisovy_znak_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$vyrizovaniForm['skartacni_znak']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$vyrizovaniForm['skartacni_lhuta']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{$vyrizovaniForm['spousteci_udalost_id']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Počet listů:</dt>
            <dd>{$vyrizovaniForm['vyrizeni_pocet_listu']->control}
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: normal;">Počet listů příloh: </span>{$vyrizovaniForm['vyrizeni_pocet_priloh']->control}
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: normal;">Typ přílohy: </span>{$vyrizovaniForm['vyrizeni_typ_prilohy']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Uložení dokumentu:</dt>
            <dd>{$vyrizovaniForm['ulozeni_dokumentu']->control}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{$vyrizovaniForm['poznamka_vyrizeni']->control}&nbsp;</dd>
        </dl>
        <div>
            {$vyrizovaniForm['upravit']->control}
            &nbsp;&nbsp;
            {$vyrizovaniForm['storno']->control}
        </div>
        {$vyrizovaniForm->render('end')}
        {else}
        <dl class="detail_item">
            <dt>Způsob vyřízení:</dt>
            <dd>{$Dok->zpusob_vyrizeni}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyřízení:</dt>
            <dd>{$Dok->datum_vyrizeni|edatetime}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd title="{$Dok->spisovy_znak_popis}">{$Dok->spisovy_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Dok->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd class="normal"><strong>{$Dok->skartacni_lhuta}</strong>&nbsp;{if $Dok->stav_dokumentu>4}(rok skartace {$Dok->skartacni_rok}){/if}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{=SpisovyZnak::spousteci_udalost($Dok->spousteci_udalost_id,10)}&nbsp;</dd>
        </dl>
        {if $Dok->stav_dokumentu>=5}
        <dl class="detail_item">
            <dt>Datum spouštěcí události:</dt>
            <dd>{$Dok->datum_spousteci_udalosti|edate}&nbsp;</dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Počet listů / příloh / typ příloh:</dt>
            <dd>{!$Dok->vyrizeni_pocet_listu|num} / {!$Dok->vyrizeni_pocet_priloh|num} {if !empty($Dok->vyrizeni_typ_prilohy)}/ {$Dok->vyrizeni_typ_prilohy}{/if}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Uložení dokumentu:</dt>
            <dd>{!$Dok->ulozeni_dokumentu|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{!$Dok->poznamka_vyrizeni|enl2br}&nbsp;</dd>
        </dl>
        {/if}
        </div>
    </div>
    {/if}

    <div id="dokument_blok_poznamka">
        <div class="h2">Předání</div>
        {if $Dok->typ_dokumentu->smer == 1}
        {foreach $Dok->workflow as $workflow}
        {if $workflow->stav_dokumentu==1}
        <dl class="detail_item">
            <dt>Vytvořil:</dt>
            <dd>
            {if empty($workflow->prideleno_id) }
                organizační jednotce
                <br />
                {$workflow->orgjednotka_info->zkraceny_nazev}
            {else}
                {$workflow->prideleno_jmeno}
                <br />
                {=@$workflow->orgjednotka_info->zkraceny_nazev}
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Vytvořil dne:</dt>
            <dd>{$workflow->date|edatetime}</dd>
        </dl>        
        <?php break; ?>
        {/if}
        {/foreach}
        {/if}
        {if is_null($Dok->prideleno)}
        <div class="prazdno">K tomuto dokumentu není nikdo přidělen!</div>
        {else}
        <dl class="detail_item">
            <dt>Přiděleno:</dt>
            <dd>
            {if empty($Dok->prideleno->prideleno_id) }
                organizační jednotce
                <br />
                {$Dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {else}
                {$Dok->prideleno->prideleno_jmeno}
                <br />
                {=@$Dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Přiděleno dne:</dt>
            <dd>{$Dok->prideleno->date|edatetime}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka pro přiděleného:</dt>
            <dd>{!$Dok->prideleno->poznamka|enl2br}&nbsp;</dd>
        </dl>
        {/if}

        {if !is_null($Dok->predano)}
        <dl class="detail_item">
            <dt>Předáno:</dt>
            <dd>
            {if empty($Dok->predano->prideleno_id) }
                organizační jednotce
                <br />
                {$Dok->predano->orgjednotka_info->zkraceny_nazev}
            {else}
                {$Dok->predano->prideleno_jmeno}
                <br />
                {=@$Dok->predano->orgjednotka_info->zkraceny_nazev}
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Předáno dne:</dt>
            <dd>{$Dok->predano->date|edatetime}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka pro předávajícího:</dt>
            <dd>{!$Dok->predano->poznamka|enl2br}&nbsp;</dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Lhůta k vyřízení:</dt>
            <dd>{$Dok->lhuta} dní (do {$Dok->lhuta_do|edate})</dd>
        </dl>
    </div>
    
    {if !empty($Zapujcka->id)}
    <div id="dokument_blok_poznamka">
        <div class="h2">Zápůjčka</div>
        <dl class="detail_item">
            <dt>Zapůjčeno:</dt>
            <dd>
                {=Osoba::displayName($Zapujcka)}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Důvod zapůjčení:</dt>
            <dd>{!$Zapujcka->duvod|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum výpůjčky:</dt>
            <dd>{$Zapujcka->date_od|edate}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vrácení:</dt>
            <dd>{$Zapujcka->date_do|edate}</dd>
        </dl>          
    </div>
    {/if}    

    <div id="dokument_blok_subjekty">
        <div class="h2">
            Adresáti / odesílatelé
        </div>
        {if $Pridelen==1 }
        <div class="blok_akce">
            <a href="#" id="subjekt_pripojit_click">Připojit subjekt</a>
        </div>        
        <div class="blok_akce">
            <input type="hidden" name="subjekt_dokument_id" id="subjekt_dokument_id" value="{$Dok->id}" />
            <div id="subjekt_pripojit" style="display:none;">
            <dl class="detail_item">
                <dt>Vyhledat a připojit subjekt:</dt>
                <dd>
                    <input type="text" name="subjekt_autocomplete" id="subjekt_autocomplete" size="60" />
                    <a href="{link :Spisovka:Subjekty:vyber, 'id'=>0, 'dok_id'=>$Dok->id}" id="dialog-subjekt">Seznam</a>
                </dd>
            </dl>
            <dl class="detail_item_adress" id="subjekt_novy">
                <dt>&nbsp;</dt>
                <dd>
                    <a href="#" id="novysubjekt_click">Vytvořit nový subjekt</a>
                </dd>
            </dl>
            </div>
            <a href="{link :Spisovka:Subjekty:nacti, 'id'=>$Dok->id}" onclick="renderSubjekty({!$Dok->id}); return false;">Obnovit seznam subjektů</a><span id="reload_spinner"></span>
        </div>
        <script type="text/javascript">
        // viz o par radku nize
        // pouzij Javascript jen pokud je uzivatel opravnen menit subjekty
        $('#dok-subjekty td.icon img').live('click', zmen_rezim_subjektu);
        </script>
        {/if}
        <div id="dok-subjekty">
        {if count($Dok->subjekty)>0}
        <table class="seznam">
            {foreach $Dok->subjekty as $subjekt}
            <tr>
            <td class="icon">
                <img id="subjekt_ikona_{$subjekt->id}" src="{$baseUri}images/icons/subjekt_{$subjekt->rezim_subjektu|lower}.png" alt="{$subjekt->rezim_subjektu}" title="{$subjekt->rezim_subjektu}" width="32" height="32" />
            </td>
            <td class="meta">
                <strong>{=Subjekt::displayName($subjekt,'jmeno_item')}</strong>
                <div class="info">
                <span>{$subjekt->type} - {=Subjekt::typ_subjektu($subjekt->type)}</span>
                <br />
                <span>
                    {if $subjekt->rezim_subjektu == 'O'}
                    odesílatel
                    {elseif $subjekt->rezim_subjektu == 'A'}
                    adresát
                    {elseif $subjekt->rezim_subjektu == 'AO'}
                    odesílatel i adresát
                    {else}
                    nespecifikováno
                    {/if}
                </span>

                <br />
                {=Subjekt::displayName($subjekt,'adresa')}
                </div>
                {if $Pridelen==1 }
                <div class="vyber">
                    <a href="{link :Spisovka:Subjekty:odebrat, 'id'=>$subjekt->id, 'dok_id'=>$Dok->id }" onclick="return odebratSubjekt(this, {!$Dok->id});">odebrat</a>&nbsp;&nbsp;
                    <a href="{link :Spisovka:Subjekty:upravit, 'id'=>$subjekt->id, 'dok_id'=>$Dok->id }" onclick="return subjektzmenit(this);">změnit</a>&nbsp;&nbsp;
                </div>
                {/if}
            </td>
            <td class="meta_plus">
                &nbsp;
                <div class="info">
                <dl>
                    <dt>email:</dt>
                    <dd>{$subjekt->email}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>telefon:</dt>
                    <dd>{$subjekt->telefon}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>isds:</dt>
                    <dd>{$subjekt->id_isds}&nbsp;</dd>
                </dl>

                </div>
            </td>
        </tr>
        {/foreach}
        </table>
        {else}
        <div class="prazdno">K tomuto dokumentu nejsou připojeni žádní odesílatelé nebo adresáti.</div>
        {/if}
        </div>
    </div>

    <div id="dokument_blok_prilohy">
    <div class="h2">
        Přílohy
    </div>
    {if 0 }
    <div class="blok_akce">
        <a href="{link :Spisovka:Prilohy:pridat, 'id'=>0, 'dok_id'=>$Dok->id}" id="dialog-pridat-prilohu">Přidat přílohu</a>
        &nbsp;&nbsp;&nbsp;
        <a href="{link :Spisovka:Prilohy:nacti, 'id'=>$Dok->id}" onclick="renderPrilohy({!$Dok->id}); return false;">Obnovit seznam příloh</a>
    </div>
    {/if}
    {if $Pridelen==1 }
    <div id="dok-prilohy-form">
        <div class="blok_akce">
            <a href="{link :Spisovka:Prilohy:pridat, 'id'=>0, 'dok_id'=>$Dok->id}" id="dialog-pridat-prilohu">Přidat přílohu</a>
        </div>
    </div>
    <div class="blok_akce">
        <a href="{link :Spisovka:Prilohy:nacti, 'id'=>$Dok->id}" onclick="renderPrilohy({!$Dok->id}); return false;">Obnovit seznam příloh</a>
    </div>
    {/if}
    <div id="dok-prilohy">
    {accessview}
    {if count($Dok->prilohy)>0}
    <table class="seznam">
        {foreach $Dok->prilohy as $file}
        <tr>
            <td class="icon">
                <img src="{$file->mime_type_icon}" alt="{$file->mime_type}" title="{$file->mime_type}" width="32" height="32" />
            </td>
            <td class="meta">
                <a href="{link :Spisovka:Dokumenty:download, 'id'=>$Dok->id, 'file'=>$file->id}">{$file->nazev}</a>
                <div class="info">
                {$file->real_name}
                <br />
                <span>
                    {$file->typ_name}, {$file->size|bytes}, {$file->mime_type}
                    <br />
                    MD5 hash: {$file->md5_hash}
                </span>
                </div>
                {if !empty($file->popis)}<div class="popis">{!$file->popis|enl2br}</div>{/if}
                {if $Pridelen==1 }
                <div class="vyber">
                    <a href="{link :Spisovka:Prilohy:odebrat, 'id'=>$file->id, 'dok_id'=>$Dok->id }" onclick="return odebratPrilohu(this, {!$Dok->id});">odebrat</a>&nbsp;&nbsp;
                    <a href="{link :Spisovka:Prilohy:upravit, 'id'=>$file->id, 'dok_id'=>$Dok->id }" onclick="return prilohazmenit(this);">změnit</a>&nbsp;&nbsp;
                </div>
                {/if}
            </td>
            <td class="user">
                nahráno {$file->date_created|edate}
                <br />
                {$file->user_name}
            </td>
        </tr>
        {/foreach}
    </table>
    {else}
        <div class="prazdno">K tomuto dokumentu nejsou připojené žádné elektronické přílohy.</div>
    {/if}
    {/accessview}
    {noaccessview}
        <div class="prazdno">Dokument obsahuje {=count($Dok->prilohy)} příloh. K jejím zobrazení nemáte oprávnění.</div>
    {/noaccessview}
    </div>
    </div>

    {if count($Dok->odeslani)>0}
    {include 'detail-odeslani.phtml'}
    {/if}

    {include 'detail-historie.phtml'}

    <div id="dialog"></div>