@{block title}Dokument{/block}
@{block javascript}
	<script type="text/javascript" src="{$baseUri}js/webtoolkit.aim.js"></script>
	<script type="text/javascript">
		function startCallback() {
			return true;
		}

		function completeCallback(response) {

                        if ( response.indexOf('###vybrano###') != -1 ) {
                            alert('Příloha byl nahrána.');
                            $('#dialog').dialog('close');
                            renderPrilohy({$Dok->dokument_id});
                        } else if ( response.indexOf('###zmemeno###') != -1 ) {
                            alert('Příloha byla upravena.');
                            $('#dialog').dialog('close');
                            renderPrilohy({$Dok->dokument_id});
                        } else {
                            $('#dialog').html(response);
                        }
		}


                function vybratSpisovyZnak() {

                    var spisz_skart = new Array();
                    var spisz_lhuta = new Array();
                    var spisz_udalost = new Array();
                    spisz_skart['0'] = '';
                    spisz_lhuta['0'] = '';
                    spisz_udalost['0'] = '';
                {if count($SpisoveZnaky)>0}
                {foreach $SpisoveZnaky as $sznak}
                    spisz_skart[{$sznak->spisznak_id}] = {$sznak->skartacni_znak};
                    spisz_lhuta[{$sznak->spisznak_id}] = {$sznak->skartacni_lhuta};
                    spisz_udalost[{$sznak->spisznak_id}] = {=SpisovyZnak::spousteci_udalost($sznak->spousteci_udalost)};
                {/foreach}
                {/if}

                    var frm_spis  = document.forms['frm-vyrizovaniForm'].spisovy_znak;
                    var frm_skart  = document.forms['frm-vyrizovaniForm'].skartacni_znak;
                    var frm_lhuta  = document.forms['frm-vyrizovaniForm'].skartacni_lhuta;
                    var frm_udalost  = document.forms['frm-vyrizovaniForm'].spousteci_udalost;

                    var key  = document.forms['frm-vyrizovaniForm'].spisovy_znak.selectedIndex;
                    var value = document.forms['frm-vyrizovaniForm'].spisovy_znak.options[key].value;
                    document.forms['frm-vyrizovaniForm'].skartacni_znak.value = spisz_skart[value];
                    document.forms['frm-vyrizovaniForm'].skartacni_lhuta.value = spisz_lhuta[value];
                    document.forms['frm-vyrizovaniForm'].spousteci_udalost.value = spisz_udalost[value];
                    return true;
                }


	</script>
@{/block}
@{block debug}
<?php echo "\n\nDokument: "; print_r($Dok); ?>

@{/block}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovka:Dokumenty:default}">Seznam dokumentů</a> - Detail dokumentu
    </div>

    {accessedit}
    <div id="dokument_blok_volby">
       {if $Pridelen==1 }
       <a href="{link :Spisovka:Dokumenty:detail , 'id'=>$Dok->dokument_id , 'upravit'=>'metadata'  }">Upravit metadata</a>
       {/if}
       {if ($Pridelen==1 && $Vyrizovani == 1 ) }
       <a href="{link :Spisovka:Dokumenty:detail , 'id'=>$Dok->dokument_id , 'upravit'=>'vyrizeni'  }">Upravit vyřízení</a>
       {/if}
       <a href="{link :Spisovka:Uzivatel:vyber, 'id'=>0, 'dok_id'=>$Dok->dokument_id}" id="dialog-uzivatel">Předat dokument</a>
       {if $Predan==1 }
       <a href="{link :Spisovka:Dokumenty:prevzit, 'id'=>$Dok->dokument_id, 'user'=>$user->user_id}" id="prevzitdokument">Převzít dokument</a>
       {/if}
       {if ($Pridelen==1 && $Vyrizovani == 0 ) }
       <a href="{link :Spisovka:Dokumenty:kvyrizeni, 'id'=>$Dok->dokument_id, 'user'=>$user->user_id}" id="kvyrizenidokument">Označit k vyřízení</a>
       <a href="{link :Spisovka:Dokumenty:odpoved, 'id'=>$Dok->dokument_id}" >Vytvořit odpověď</a>
       {/if}
       {if ($Pridelen==1 && $Vyrizovani == 1 ) }
       <a href="{link :Spisovka:Dokumenty:odeslat , 'id'=>$Dok->dokument_id }">Odeslat dokument</a>
       {/if}
       {if ($Pridelen==1 && $Vyrizovani == 1 ) }
       <a href="{link :Spisovka:Dokumenty:vyrizeno, 'id'=>$Dok->dokument_id, 'user'=>$user->user_id}" id="vyrizenodokument">Označit dokument za vyřízený</a>
       {/if}


    </div>
    {/accessedit}

    <div id="dokument_blok_hlavni">
        {if ($FormUpravit=='metadata')}
        {$metadataForm->render('begin')}
        <dl class="detail_item">
            <dt>JID:</dt>
            <dd>
                {$Dok->jid}&nbsp;
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Typ dokumentu:</dt>
            <dd>{$metadataForm['typ_dokumentu']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací:</dt>
            <dd class="nadpis">
                {$Dok->cislo_jednaci}&nbsp;
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisová značka:</dt>
            <dd>
                <span id="dok_spis">
                {if count($Dok->spisy)>0 }
                    {foreach $Dok->spisy as $s}
                    {$s->nazev}<br />
                    {/foreach}
                {else}
                    nepřidělen k žádnemu spisu
                {/if}
                </span>
                
                <a href="{link :Spisovka:Spisy:vyber, 'id'=>$Dok->dokument_id}" id="dialog-spis">Připojit spisovou značku</a>
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd>{$metadataForm['nazev']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{$metadataForm['popis']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$metadataForm['datum_vzniku']->label}</dt>
            <dd>{$metadataForm['datum_vzniku']->control} {$metadataForm['datum_vzniku_cas']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$metadataForm['cislo_jednaci_odesilatele']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Zmocnění:</dt>
            <dd><span id="dok_zmocneni"></span>&nbsp;<a href="{link :Spisovka:Dokumenty:zmocneni, 'id'=>$Dok->dokument_id}" id="dialog-zmocneni">Připojit zmocnění</a></dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{$metadataForm['poznamka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spojit s dokumentem:</dt>
            <dd>
                <span id="dok_spojit">
                {if count($SouvisejiciDokumenty)>0 }
                    {foreach $SouvisejiciDokumenty as $s}
                    <a href="{link :Spisovka:Dokumenty:detail, 'id'=>$s->dokument_id}">{$s->cislo_jednaci} ({$s->jid})</a>
                    &nbsp;&nbsp;&nbsp;[<a href="{link :Spisovka:Spojit:odebrat, 'id'=>$Dok->dokument_id, 'spojeny'=>$s->dokument_id}">odebrat spojení</a>]
                    {/foreach}
                {/if}
                </span>
                &nbsp;[<a href="{link :Spisovka:Spojit:vyber, 'id'=>$Dok->dokument_id}" id="dialog-spojit">spojit s dokumentem</a>]
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Počet listů:</dt>
            <dd>{$metadataForm['pocet_listu']->control}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: normal;">Počet listů příloh: </span>{$metadataForm['pocet_priloh']->control}</dd>
        </dl>
        <div>
            {$metadataForm['upravit']->control}
            &nbsp;&nbsp;
            {$metadataForm['storno']->control}
        </div>
        {$metadataForm->render('end')}
        {else}
        <div class="h2">{$Dok->typ_dokumentu->nazev}</div>
        <dl class="detail_item">
            <dt>JID:</dt>
            <dd>{$Dok->jid}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Číslo jednací:</dt>
            <dd class="nadpis">{$Dok->cislo_jednaci}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisová značka:</dt>
            <dd>
            {if count($Dok->spisy)>0 }
                {foreach $Dok->spisy as $s}
                {$s->nazev}<br />
                {/foreach}
            {else}
                nepřidělen k žádnemu spisu
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd class="nadpis"><u>{$Dok->nazev}</u>&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{!$Dok->popis|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vytvoření:</dt>
            <dd>{$Dok->datum_vzniku|edatetime}&nbsp;</dd>
        </dl>
        {if !empty($Dok->cislo_jednaci_odesilatele)}
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$Dok->cislo_jednaci_odesilatele}&nbsp;</dd>
        </dl>
        {/if}
        {if !empty($Dok->zmocneni)}
        <dl class="detail_item">
            <dt>Zmocnění:</dt>
            <dd>{$Dok->zmocneni}&nbsp;</dd>
        </dl>
        {/if}
        {if !empty($Dok->poznamka)}
        <dl class="detail_item">
            <dt>Poznamka:</dt>
            <dd>{!$Dok->poznamka|enl2br}&nbsp;</dd>
        </dl>
        {/if}
        {if $Typ_evidence=='priorace'}
        <dl class="detail_item">
            <dt>Spojeno s dokumentem:</dt>
            <dd>
                <span id="dok_spojit">
                {if count($SouvisejiciDokumenty)>0 }
                    {foreach $SouvisejiciDokumenty as $s}
                    <a href="{link :Spisovka:Dokumenty:detail, 'id'=>$s->dokument_id}">{$s->cislo_jednaci} ({$s->jid})</a>
                    {/foreach}
                {/if}
                </span>
                &nbsp;
            </dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Počet listů / příloh:</dt>
            <dd>{!$Dok->pocet_listu|num} / {!$Dok->pocet_priloh|num}</dd>
        </dl>

        {/if}
    </div>
    {if $Vyrizovani == 1 }
    <div id="dokument_blok_vyrizeni">
        <div class="h2">Vyřízení</div>
        {if ($FormUpravit=='vyrizeni')}
        {$vyrizovaniForm->render('begin')}
        <dl class="detail_item">
            <dt>Způsob vyžízení:</dt>
            <dd>{$vyrizovaniForm['zpusob_vyrizeni']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyžízení:</dt>
            <dd>{$vyrizovaniForm['datum_vyrizeni']->control} {$vyrizovaniForm['datum_vyrizeni_cas']->control}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{$vyrizovaniForm['spisovy_znak']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$vyrizovaniForm['skartacni_znak']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$vyrizovaniForm['skartacni_lhuta']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{$vyrizovaniForm['spousteci_udalost']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Počet listů:</dt>
            <dd>{$vyrizovaniForm['vyrizeni_pocet_listu']->control}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span style="font-weight: normal;">Počet listů příloh: </span>{$vyrizovaniForm['vyrizeni_pocet_priloh']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Uložení dokumentu:</dt>
            <dd>{$vyrizovaniForm['ulozeni_dokumentu']->control}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{$vyrizovaniForm['poznamka_vyrizeni']->control}&nbsp;</dd>
        </dl>
        <div>
            {$metadataForm['upravit']->control}
            &nbsp;&nbsp;
            {$metadataForm['storno']->control}
        </div>
        {$metadataForm->render('end')}
        {else}
        <dl class="detail_item">
            <dt>Způsob vyžízení:</dt>
            <dd>{$Dok->zpusob_vyrizeni}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyžízení:</dt>
            <dd>{$Dok->datum_vyrizeni|edatetime}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd title="{$Dok->spisovy_znak_popis}">{$Dok->spisovy_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Dok->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$Dok->skartacni_lhuta}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{$Dok->spousteci_udalost}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Počet listů / příloh:</dt>
            <dd>{!$Dok->vyrizeni_pocet_listu|num} / {!$Dok->vyrizeni_pocet_priloh|num}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Uložení dokumentu:</dt>
            <dd>{!$Dok->ulozeni_dokumentu|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{!$Dok->poznamka_vyrizeni|enl2br}&nbsp;</dd>
        </dl>
        {/if}
    </div>
    {/if}

    <div id="dokument_blok_poznamka">
        <div class="h2">Předání</div>
        {if is_null($Dok->prideleno)}
        <div class="prazdno">K tomuto dokumentu není nikdo přidělen!</div>
        {else}
        <dl class="detail_item">
            <dt>Přiděleno:</dt>
            <dd>
                {$Dok->prideleno->prideleno_jmeno}
                <br />
                IT
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Přiděleno dne:</dt>
            <dd>{$Dok->prideleno->date|edatetime}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka pro přiděleného:</dt>
            <dd>{!$Dok->prideleno->poznamka|enl2br}&nbsp;</dd>
        </dl>
        {/if}

        {if !is_null($Dok->predano)}
        <dl class="detail_item">
            <dt>Předáno:</dt>
            <dd>
                {$Dok->predano->prideleno_jmeno}
                <br />
                IT
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Předáno dne:</dt>
            <dd>{$Dok->predano->date|edatetime}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka pro předávajícího:</dt>
            <dd>{!$Dok->predano->poznamka|enl2br}&nbsp;</dd>
        </dl>
        {/if}
    </div>

    <div id="dokument_blok_subjekty">
        <div class="h2">
            Adresáti / odesílatelé
        </div>
        {if $Pridelen==1 }
        <div class="blok_akce">
            <a href="{link :Spisovka:Subjekty:vyber, 'id'=>0, 'dok_id'=>$Dok->dokument_id}" id="dialog-subjekt">Připojit subjekt</a>
            &nbsp;&nbsp;&nbsp;
            <a href="{link :Spisovka:Subjekty:nacti, 'id'=>$Dok->dokument_id}" onclick="renderSubjekty({!$Dok->dokument_id}); return false;">Obnovit seznam subjektu</a>
        </div>
        {/if}
        <div id="dok-subjekty">
        {if count($Dok->subjekty)>0}
        <table class="seznam">
            {foreach $Dok->subjekty as $subjekt}
            <tr>
            <td class="icon">
                <img src="{$baseUri}images/icons/subjekt_{$subjekt->rezim_subjektu|lower}.png" alt="{$subjekt->rezim_subjektu}" title="{$subjekt->rezim_subjektu}" width="32" height="32" />
            </td>
            <td class="meta">
                <strong>{=Subjekt::displayName($subjekt,'jmeno_item')}</strong>
                <div class="info">
                <span>{$subjekt->type} - {=Subjekt::typ_subjektu($subjekt->type)}</span>
                <br />
                <span>
                    {if $subjekt->rezim_subjektu == 'O'}
                    odesílatel
                    {elseif $subjekt->rezim_subjektu == 'A'}
                    adresát
                    {elseif $subjekt->rezim_subjektu == 'AO'}
                    odesílatel i adresát
                    {else}
                    nespecifikováno
                    {/if}
                </span>

                <br />
                {=Subjekt::displayName($subjekt,'adresa')}
                </div>
                {if $Pridelen==1 }
                <div class="vyber">
                    <a href="{link :Spisovka:Subjekty:odebrat, 'id'=>$subjekt->subjekt_id, 'dok_id'=>$Dok->dokument_id }" onclick="return confirm('Opravdu chcete odebrat subjekt z dokumentu?');">odebrat</a>&nbsp;&nbsp;
                    <a href="{link :Spisovka:Subjekty:upravit, 'id'=>$subjekt->subjekt_id, 'dok_id'=>$Dok->dokument_id }" id="dialog-subjektzmenit">změnit</a>&nbsp;&nbsp;
                </div>
                {/if}
            </td>
            <td class="meta_plus">
                &nbsp;
                <div class="info">
                <dl>
                    <dt>email:</dt>
                    <dd>{$subjekt->email}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>telefon:</dt>
                    <dd>{$subjekt->telefon}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>isds:</dt>
                    <dd>{$subjekt->id_isds}&nbsp;</dd>
                </dl>

                </div>
            </td>
        </tr>
        {/foreach}
        </table>
        {else}
        <div class="prazdno">K tomuto dokumentu nejsou připojeni žádní odesilatelé nebo adresáti.</div>
        {/if}
        </div>
    </div>

    <div id="dokument_blok_prilohy">
    <div class="h2">
        Přílohy
    </div>
    {if $Pridelen==1 }
    <div class="blok_akce">
        <a href="{link :Spisovka:Prilohy:pridat, 'id'=>0, 'dok_id'=>$Dok->dokument_id}" id="dialog-pridat-prilohu">Přidat přílohu</a>
        &nbsp;&nbsp;&nbsp;
        <a href="{link :Spisovka:Prilohy:nacti, 'id'=>$Dok->dokument_id}" onclick="renderPrilohy({!$Dok->dokument_id}); return false;">Obnovit seznam příloh</a>
    </div>
    {/if}
    <div id="dok-prilohy">
    {accessview}
    {if count($Dok->prilohy)>0}
    <table class="seznam">
        {foreach $Dok->prilohy as $file}
        <tr>
            <td class="icon">
                <img src="{$baseUri}images/mimetypes/{$file->mime_type|webalize}.png" alt="{$file->mime_type}" title="{$file->mime_type}" width="32" height="32" />
            </td>
            <td class="meta">
                <a href="{link :Spisovka:Dokumenty:download, 'id'=>$Dok->dokument_id, 'file'=>$file->file_id}">{$file->nazev}</a>
                <div class="info">
                {$file->real_name}
                <br />
                <span>
                    {$file->typ_name}, {$file->size|bytes}, {$file->mime_type}
                    <br />
                    MD5 hash: {$file->md5_hash}
                </span>
                </div>
                {if !empty($file->popis)}<div class="popis">{!$file->popis|enl2br}</div>{/if}
                {if $Pridelen==1 }
                <div class="vyber">
                    <a href="{link :Spisovka:Prilohy:odebrat, 'id'=>$file->file_id, 'dok_id'=>$Dok->dokument_id }" onclick="return confirm('Opravdu chcete odebrat přílohu z dokumentu?');">odebrat</a>&nbsp;&nbsp;
                    <a href="{link :Spisovka:Prilohy:upravit, 'id'=>$file->file_id, 'dok_id'=>$Dok->dokument_id }" onclick="return prilohazmenit(this);">změnit</a>&nbsp;&nbsp;
                </div>
                {/if}
            </td>
            <td class="user">
                nahráno {$file->date_created|edate}
                <br />
                {$file->user_name}
            </td>
        </tr>
        {/foreach}
    </table>
    {else}
        <div class="prazdno">K tomuto dokumentu nejsou připojené žádné elektronické přílohy.</div>
    {/if}
    {/accessview}
    {noaccessview}
        <div class="prazdno">Dokument obsahuje {=count($Dok->prilohy)} příloh. K jejím zobrazení nemáte oprávnění.</div>
    {/noaccessview}
    </div>
    </div>

    {if count($Dok->odeslani)>0}
    <div class="dokument_blok2">
        <div class="h2">Odesilání</div>
        {foreach $Dok->odeslani as $odes}
        <dl class="detail_item">
            <dt>
            {if $odes->zpusob_odeslani <= 2}
                {$odes->datum_odeslani|edatetime}
            {else}
                {$odes->datum_odeslani|edate}
            {/if}
            </dt>
            <dd>
            {if $odes->zpusob_odeslani == 1}
                {=Subjekt::displayName($odes->subjekt_info,'email')}
                <br />
                <span style="font-weight:normal;">odesláno emailem</span>
            {elseif $odes->zpusob_odeslani == 2}
                {=Subjekt::displayName($odes->subjekt_info,'isds')}
                <br />
                <span style="font-weight:normal;">odesláno datovou schránkou</span>
            {elseif $odes->zpusob_odeslani == 3}
                {=Subjekt::displayName($odes->subjekt_info,'plna_adresa')}
                <br />
                <span style="font-weight:normal;">odesláno poštou</span>
            {elseif $odes->zpusob_odeslani == 4}
                {=Subjekt::displayName($odes->subjekt_info,'telefon')}
                <br />
                <span style="font-weight:normal;">odesláno faxem</span>
            {elseif $odes->zpusob_odeslani == 5}
                {=Subjekt::displayName($odes->subjekt_info,'jmeno')}
                <br />
                <span style="font-weight:normal;">předáno osobně</span>
            {elseif $odes->zpusob_odeslani == 6}
                {=Subjekt::displayName($odes->subjekt_info,'telefon')}
                <br />
                <span style="font-weight:normal;">předáno telefonicky</span>
            {else}
                {=Subjekt::displayName($odes->subjekt_info)}
                <br />
                <span style="font-weight:normal;">způsob odeslání nespecifikováno</span>
            {/if}
            </dd>
        </dl>
        {/foreach}
    </div>
    {/if}

    <div id="dialog"></div>