@{block title}Dokument{/block}
@{block content}

    <div class="navigate">
    <a href="{link :Spisovka:Dokumenty:default}">Seznam dokumentů</a> - Detail dokumentu
    </div>

    <div id="error">
        <h2>Požadovaný dokument neexistuje!</h2>
        <p>
            Pokoušíte se zobrazit dokument, který neexistuje.
            <br />
            Zkontrolujte správnost zadané adresy nebo odkazu.
        </p>
    </div>