<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <title>Spisová služba</title>
    <style type="text/css" media="screen, print">
        <?php echo file_get_contents(APP_DIR .'/../public/css/printdetail_site.css'); ?>
    </style>
</head>
<body>
<div id="content">
    <div id="dokument_blok_hlavni">
        <dl class="detail_item">
            <dt>JID:</dt>
            <dd>{$Dok->jid}&nbsp;</dd>
        </dl>
        {if empty($Dok->cislo_jednaci)}
        <dl class="detail_item">
            <dt>Číslo jednací{if $Typ_evidence == 'sberny_arch'} / pořadí{/if}:</dt>
            <dd>Dokument není evidován!</dd>
        </dl>
        {else}
        <dl class="detail_item">
            <dt>Číslo jednací{if $Typ_evidence == 'sberny_arch'} {$Oddelovac_poradi} pořadí{/if}:</dt>
            <dd class="nadpis">{$Dok->cislo_jednaci}{if $Typ_evidence == 'sberny_arch'}{$Oddelovac_poradi}{$Dok->poradi}{/if}&nbsp;</dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Název spisu:</dt>
            <dd>
            {if count($Dok->spisy)>0 }
                {foreach $Dok->spisy as $s}
                {$s->nazev}<br />
                {/foreach}
            {else}
                nepřidělen k žádnemu spisu
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Věc:</dt>
            <dd class="nadpis"><u>{$Dok->nazev}</u>&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{!$Dok->popis|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Typ dokumentu:</dt>
            <dd>{$Dok->typ_dokumentu->nazev}&nbsp;</dd>
        </dl>        
        <dl class="detail_item">
            <dt>Datum doručení/vzniku:</dt>
            <dd>{$Dok->datum_vzniku|edatetime}&nbsp;</dd>
        </dl>
        {if !empty($Dok->zpusob_doruceni)}
        <dl class="detail_item">
            <dt>Způsob doručení:</dt>
            <dd>{$Dok->zpusob_doruceni}&nbsp;</dd>
        </dl>        
        {/if}
        {if !empty($Dok->cislo_jednaci_odesilatele)}
        <dl class="detail_item">
            <dt>Číslo jednací odesilatele:</dt>
            <dd>{$Dok->cislo_jednaci_odesilatele}&nbsp;</dd>
        </dl>
        {/if}
        {if !empty($Dok->cislo_doporuceneho_dopisu)}
        <dl class="detail_item">
            <dt>Číslo doporučeného dopisu:</dt>
            <dd>{$Dok->cislo_doporuceneho_dopisu}&nbsp;</dd>
        </dl>
        {/if}
        
        {if !empty($Dok->zmocneni)}
        <dl class="detail_item">
            <dt>Zmocnění:</dt>
            <dd>{$Dok->zmocneni}&nbsp;</dd>
        </dl>
        {/if}
        {if !empty($Dok->poznamka)}
        <dl class="detail_item">
            <dt>Poznámka:</dt>
            <dd>{!$Dok->poznamka|html2br}&nbsp;</dd>
        </dl>
        {/if}
        {if $Typ_evidence=='priorace'}
        {if count($SouvisejiciDokumenty)>0 }
        <dl class="detail_item">
            <dt>Spojeno s dokumentem:</dt>
            <dd>
                <span id="dok_spojit">
                {foreach $SouvisejiciDokumenty as $s}
                    {$s->cislo_jednaci} ({$s->jid})
                {/foreach}
                </span>
                &nbsp;
            </dd>
        </dl>
        {/if}
        {/if}
        <dl class="detail_item">
            <dt>Počet listů / příloh / typ přílohy:</dt>
            <dd>{!$Dok->pocet_listu|num} / {!$Dok->pocet_priloh|num} {if !empty($Dok->typ_prilohy)}/ {$Dok->typ_prilohy}{/if}</dd>
        </dl>
        {if !empty($Dok->identifikator)}
        <dl class="detail_item">
            <dt>Identifikátor epodatelny:</dt>
            <dd><pre>{$Dok->identifikator['popis']}</pre></dd>
        </dl>
        {if $Dok->identifikator['typ'] == "email" }
        <dl class="detail_item">
            <dt>Ověření identifikátoru:</dt>
            <dd>
            {if $Dok->identifikator['cert_signed'] >= 0 }
                {$Dok->identifikator['cert_log']['aktualne']['date']} &nbsp;
                {if $Dok->identifikator['cert_log']['aktualne']['status']==1 }
                <span style="color:#009900;">{$Dok->identifikator['cert_log']['aktualne']['message']}</span>
                {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_log']['aktualne']['message']}</span>
                {/if}
                <br />
                {$Dok->identifikator['cert_log']['prijato']['date']} &nbsp;
                {if $Dok->identifikator['cert_log']['prijato']['status']==1 }
                <span style="color:#009900;">{$Dok->identifikator['cert_log']['prijato']['message']}</span>
                {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_log']['prijato']['message']}</span>
                {/if}
                <br />
                {$Dok->identifikator['cert_log']['doruceno']['date']} &nbsp;
                {if $Dok->identifikator['cert_log']['doruceno']['status']==1 }
                <span style="color:#009900;">{$Dok->identifikator['cert_log']['doruceno']['message']}</span>
                {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_log']['doruceno']['message']}</span>
                {/if}
            {else}
                <span style="color:#990000;">{$Dok->identifikator['cert_status']}</span>
            {/if}
            </dd>
        </dl>
        {/if}
        {/if}
    </div>
    {if $Vyrizovani == 1 }
    <div id="dokument_blok_vyrizeni">
        <div class="h2">Vyřízení</div>
        <div class="dokument_blok">
        <dl class="detail_item">
            <dt>Způsob vyřízení:</dt>
            <dd>{$Dok->zpusob_vyrizeni}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vyřízení:</dt>
            <dd>{$Dok->datum_vyrizeni|edatetime}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd title="{$Dok->spisovy_znak_popis}">{$Dok->spisovy_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Dok->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd class="normal"><strong>{$Dok->skartacni_lhuta}</strong>&nbsp;{if $Dok->stav_dokumentu>4}(datum skartace {$Dok->skartacni_rok|edate}){/if}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{=SpisovyZnak::spousteci_udalost($Dok->spousteci_udalost_id,10)}&nbsp;</dd>
        </dl>
        {if $Dok->stav_dokumentu>=5}
        <dl class="detail_item">
            <dt>Datum spuštění události:</dt>
            <dd>{$Dok->datum_spousteci_udalosti|edate}&nbsp;</dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Počet listů / příloh / typ příloh:</dt>
            <dd>{!$Dok->vyrizeni_pocet_listu|num} / {!$Dok->vyrizeni_pocet_priloh|num} {if !empty($Dok->vyrizeni_typ_prilohy)}/ {$Dok->vyrizeni_typ_prilohy}{/if}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Uložení dokumentu:</dt>
            <dd>{!$Dok->ulozeni_dokumentu|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka k vyřízení:</dt>
            <dd>{!$Dok->poznamka_vyrizeni|enl2br}&nbsp;</dd>
        </dl>
        </div>
    </div>
    {/if}

    <div id="dokument_blok_poznamka">
        <div class="h2">Předání</div>
        {if $Dok->typ_dokumentu->smer == 1}
        {foreach $Dok->workflow as $workflow}
        {if $workflow->stav_dokumentu==1}
        <dl class="detail_item">
            <dt>Vytvořil:</dt>
            <dd>
            {if empty($workflow->prideleno_id) }
                organizační jednotce
                <br />
                {$workflow->orgjednotka_info->zkraceny_nazev}
            {else}
                {$workflow->prideleno_jmeno}
                <br />
                {=@$workflow->orgjednotka_info->zkraceny_nazev}
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Vytvořil dne:</dt>
            <dd>{$workflow->date|edatetime}</dd>
        </dl>         
        <?php break; ?>
        {/if}
        {/foreach}
        {/if}         
        {if is_null($Dok->prideleno)}
        <div class="prazdno">K tomuto dokumentu není nikdo přidělen!</div>
        {else}
        <dl class="detail_item">
            <dt>Přiděleno:</dt>
            <dd>
            {if empty($Dok->prideleno->prideleno_id) }
                organizační jednotce
                <br />
                {$Dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {else}
                {$Dok->prideleno->prideleno_jmeno}
                <br />
                {=@$Dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Přiděleno dne:</dt>
            <dd>{$Dok->prideleno->date|edatetime}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka pro přiděleného:</dt>
            <dd>{!$Dok->prideleno->poznamka|enl2br}&nbsp;</dd>
        </dl>
        {/if}

        {if !is_null($Dok->predano)}
        <dl class="detail_item">
            <dt>Předáno:</dt>
            <dd>
            {if empty($Dok->predano->prideleno_id) }
                organizační jednotce
                <br />
                {$Dok->predano->orgjednotka_info->zkraceny_nazev}
            {else}
                {$Dok->predano->prideleno_jmeno}
                <br />
                {=@$Dok->predano->orgjednotka_info->zkraceny_nazev}
            {/if}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Předáno dne:</dt>
            <dd>{$Dok->predano->date|edatetime}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Poznámka pro předávajícího:</dt>
            <dd>{!$Dok->predano->poznamka|enl2br}&nbsp;</dd>
        </dl>
        {/if}
        <dl class="detail_item">
            <dt>Lhůta k vyřízení:</dt>
            <dd>{$Dok->lhuta} dní (do {$Dok->lhuta_do|edate})</dd>
        </dl>
    </div>
    
    {if !empty($Zapujcka->id)}
    <div id="dokument_blok_poznamka">
        <div class="h2">Zápůjčka</div>
        <dl class="detail_item">
            <dt>Zapůjčeno:</dt>
            <dd>
                {=Osoba::displayName($Zapujcka)}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Důvod zapůjčení:</dt>
            <dd>{$Zapujcka->duvod|enl2br}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum výpůjčky:</dt>
            <dd>{$Zapujcka->date_od|edate}</dd>
        </dl>
        <dl class="detail_item">
            <dt>Datum vrácení:</dt>
            <dd>{$Zapujcka->date_do|edate}</dd>
        </dl>           
    </div>
    {/if}    

    <div id="dokument_blok_subjekty">
        <div class="h2">
            Adresáti / odesílatelé
        </div>
        <div id="dok-subjekty">
        {if count($Dok->subjekty)>0}
        <table class="seznam">
            {foreach $Dok->subjekty as $subjekt}
            <tr>
            <td class="icon">
                &nbsp;
            </td>
            <td class="meta">
                <div style="font-weight: bold; padding:5px 0px;">{=Subjekt::displayName($subjekt,'jmeno_item')}</div>
                <div class="info">
                {=Subjekt::displayName($subjekt,'adresa')}
                <br />
                <span style="color:#c0c0c0; font-size: 8pt;">{$subjekt->type} - {=Subjekt::typ_subjektu($subjekt->type)}</span>
                <br />
                <span style="color:#c0c0c0; font-size: 8pt;">
                    {if $subjekt->rezim_subjektu == 'O'}
                    odesílatel
                    {elseif $subjekt->rezim_subjektu == 'A'}
                    adresát
                    {elseif $subjekt->rezim_subjektu == 'AO'}
                    odesílatel i adresát
                    {else}
                    nespecifikováno
                    {/if}
                </span>
                </div>
            </td>
            <td class="meta_plus">
                <div style="font-weight: bold; padding:5px 0px;">&nbsp;</div>
                <div class="info">
                    email:&nbsp;&nbsp;&nbsp;<strong>{$subjekt->email}</strong>
                <br />
                telefon:&nbsp;&nbsp;&nbsp;<strong>{$subjekt->telefon}</strong>
                <br>
                isds:&nbsp;&nbsp;&nbsp;<strong>{$subjekt->id_isds}</strong>
                </div>
            </td>
        </tr>
        {/foreach}
        </table>
        {else}
        <div class="prazdno">K tomuto dokumentu nejsou připojeni žádní odesílatelé nebo adresáti.</div>
        {/if}
        </div>
    </div>

    <div id="dokument_blok_prilohy">
    <div class="h2">
        Přílohy
    </div>
    <div id="dok-prilohy">
    {accessview}
    {if count($Dok->prilohy)>0}
    <table class="seznam">
        {foreach $Dok->prilohy as $file}
        <tr>
            <td class="icon">
                <img src="{$baseUri}images/mimetypes/{$file->mime_type|webalize}.png" alt="{$file->mime_type}" title="{$file->mime_type}" width="32" height="32" />
            </td>
            <td class="meta">
                <strong>{$file->nazev}</strong>
                <div class="info">
                {$file->real_name}
                <br />
                <span style="color:#c0c0c0; font-size: 8pt;">
                    {$file->typ_name}, {$file->size|bytes}, {$file->mime_type}
                    <br />
                    MD5 hash: {$file->md5_hash}
                </span>
                </div>
                {if !empty($file->popis)}<div class="popis">{!$file->popis|enl2br}</div>{/if}
            </td>
            <td class="user">
                nahráno {$file->date_created|edate}
                <br />
                {$file->user_name}
            </td>
        </tr>
        {/foreach}
    </table>
    {else}
        <div class="prazdno">K tomuto dokumentu nejsou připojené žádné elektronické přílohy.</div>
    {/if}
    {/accessview}
    {noaccessview}
        <div class="prazdno">Dokument obsahuje {=count($Dok->prilohy)} příloh. K jejím zobrazení nemáte oprávnění.</div>
    {/noaccessview}
    </div>
    </div>

    {if count($Dok->odeslani)>0}
    <div class="dokument_blok2">
        <div class="h2">Odesilání</div>
        {foreach $Dok->odeslani as $odes}
        <dl class="detail_item">
            <dt>
            {if $odes->zpusob_odeslani_id <= 2}
                {$odes->datum_odeslani|edatetime}
            {else}
                {$odes->datum_odeslani|edate}
            {/if}
            </dt>
            <dd>
            {if $odes->zpusob_odeslani_id == 1}
                {=Subjekt::displayName($odes,'email')}
                <br />
                <span style="font-weight:normal;">odesláno emailem</span>
            {elseif $odes->zpusob_odeslani_id == 2}
                {=Subjekt::displayName($odes,'isds')}
                <br />
                <span style="font-weight:normal;">odesláno datovou schránkou</span>
            {elseif $odes->zpusob_odeslani_id == 3}
                {=Subjekt::displayName($odes,'plna_adresa')}
                <br />
                <span style="font-weight:normal;">
                    odesláno poštou
                    {if !empty($odes->druh_zasilky)}<br />druh zásilky: {!=DruhZasilky::vypis($odes->druh_zasilky)}{/if}
                    {if !empty($odes->cena)}<br />cena: {$odes->cena} Kč{/if}
                    {if !empty($odes->hmotnost)}<br />hmotnost: {$odes->hmotnost}{/if}
                </span>
            {elseif $odes->zpusob_odeslani_id == 4}
                {=Subjekt::displayName($odes,'telefon')}
                <br />
                <span style="font-weight:normal;">odesláno faxem na číslo {$odes->cislo_faxu}</span>
            {elseif $odes->zpusob_odeslani_id == 5}
                {=Subjekt::displayName($odes,'jmeno')}
                <br />
                <span style="font-weight:normal;">předáno osobně</span>
            {elseif $odes->zpusob_odeslani_id == 6}
                {=Subjekt::displayName($odes,'telefon')}
                <br />
                <span style="font-weight:normal;">předáno telefonicky</span>
            {else}
                {=Subjekt::displayName($odes)}
                <br />
                <span style="font-weight:normal;">způsob odeslání nespecifikováno</span>
            {/if}
            </dd>
        </dl>
        {/foreach}
    </div>
    {/if}

    <div class="dokument_blok2">
        <div class="h2">Historie</div>
        {foreach $Dok->workflow as $wf}
        <dl class="detail_item">
            <dt>{$wf->date|edatetime}</dt>
            {if $wf->stav_dokumentu == 1}
            <dd>dokument vytvořen</dd>
            <dd class="normal">vytvořil a přiděleno {$wf->prideleno_jmeno}</dd>
            {elseif $wf->stav_dokumentu == 2}
            <dd>dokument předán</dd>
            <?php

                if ( empty($wf->prideleno_id) ) {
                    $wf_jmeno = $wf->orgjednotka_info->zkraceny_nazev;
                    $wf_neprijato = 'předáno organizační jednotce '. $wf_jmeno .'. Ta dokument zatím nepřijala.';
                } else {
                    $wf_jmeno = $wf->prideleno_jmeno;
                    $wf_neprijato = 'předáno '. $wf_jmeno .', ale zaměstnanec dokument zatím nepřijal';
                }

            ?>
            {if $wf->stav_osoby == 0}
            <dd class="normal">{$wf_neprijato}</dd>
            {elseif $wf->stav_osoby >= 100}
            <dd class="normal">předáno {$wf_jmeno}, ale převzetí bylo zrušeno</dd>
            {else}
            <dd class="normal">předáno {$wf_jmeno}</dd>
            {/if}


            {elseif $wf->stav_dokumentu == 3}
            <dd>dokument předán k vyřízení</dd>
            <dd class="normal">vyřizuje {$wf->prideleno_jmeno}</dd>
            {elseif $wf->stav_dokumentu == 4}
            <dd>dokument vyřízen, ale není spuštěna událost</dd>
            <dd class="normal">vyřídil {$wf->prideleno_jmeno}</dd>
            {elseif $wf->stav_dokumentu == 5}
            <dd>dokument vyřízen a běží skartační lhůta</dd>
            <dd class="normal">vyřídil {$wf->prideleno_jmeno}</dd>
            {elseif $wf->stav_dokumentu == 6}
            <dd>dokument předán do spisovny</dd>
            <dd class="normal">předal {$wf->user_jmeno}</dd>
            {elseif $wf->stav_dokumentu == 7}
            <dd>dokument přidán do spisovny</dd>
            <dd class="normal">provedl {$wf->user_jmeno}</dd>
            {elseif $wf->stav_dokumentu == 8}
            <dd>dokument předán do skartačního řízení</dd>
            <dd class="normal">provedl {$wf->user_jmeno}</dd>
            {elseif $wf->stav_dokumentu == 9}
            <dd>dokument přidán do archivu</dd>
            <dd class="normal">rozhodl {$wf->prideleno_jmeno}</dd>
            {elseif $wf->stav_dokumentu == 10}
            <dd>dokument byl skartován</dd>
            <dd class="normal">rozhodl {$wf->prideleno_jmeno}</dd>
            {elseif $wf->stav_dokumentu == 11}
            <dd>dokument byl zapůjčen</dd>
            <dd class="normal">rozhodl {$wf->prideleno_jmeno}</dd>
            {else}
            {/if}
            {if !empty($wf->poznamka)}
            <dd class="normal">poznámka: {$wf->poznamka}</dd>
            {/if}
        </dl>
        {/foreach}
    </div>
    
</div>
</body>
</html>    