{block title}Přístup zamítnut{/block}
{block content}
<div id="no_access">
<h1>Přístup zamítnut</h1>

<p>
    Nemáte potřebné oprávnění k zobrazení této stránky. Přejděte zpět na předchozí stránku.
</p>

<p>
Jste-li si vědom, že máte oprávnění stránku zobrazit, kontaktujte svého správce, který má na starost spisovou službu, a danou situaci vyřešte.
</p>

<p>
Pokud se tato stránka zobrazila po přihlášení a jste nově přihlášený, kontaktujte svého správce, který má na starost spisovou službu, a požádejte o přidělení role.
</p>

<p>
Nejste-li zaměstnanec, ale byl Vám udělen přístup, kontaktujte pověřenou osobou k vyřešení této situace.
</p>

</div>