    <h2>Detail subjektu</h2>
<p>    
Pokud si chcete prohlédnout detaily subjektu, tak na jeho název klepněte levým tlačítkem myši a poté budete přesměrováni do detailů daného subjektu. V něm můžete vidět a upravovat všechny položky, které se zadávají při vytváření nového adresáta/odesilatele. Navíc je zde možnost měnit stav subjektu a to tak, že najedete a klepnete na odkaz Změnit stav a poté vyberete jednu z možností v rozbalovacím menu.    
</p>
