    <h2>Nový subjekt</h2>
<p>
Pakliže chcete vytvořit nový subjekt, tak najeďte na stejnojmenný nápis pod tlačítkem Odesílatelé/Adresáti.
</p>
<p>
V následujícím formuláři naleznete tyto položky (položky se mění podle toho, jaký typ subjektu vyberete):    
    
    <dl>
        <dt>Typ subjektu</dt>
        <dt>Název subjektu</dt>
        <dt>IČ</dt>
        <dd>IČ disponuje funkcí Vyhledat přes systém ARES, to znamená, že pokud zadáte správné IČ a v systému ARES má majitel IČ vyplněné požadované položky, tak se vám tento formulář zčásti či celý vyplní automaticky.</dd>
        <dt>DIČ</dt>
        <dt>Titul před jménem</dt>
        <dt>Jméno</dt>
        <dt>Prostřední jméno</dt>
        <dt>Příjmení</dt>
        <dt>Titul za jménem</dt>
        <dt>Rodné jméno</dt>
        <dt>Datum narození</dt><dd>Datum lze zadat přes implementovaný kalendář.</dd>
        <dt>Místo narození</dt>
        <dt>Okres narození</dt>
        <dt>Stát narození</dt><dd>Na výběr buď Česká republika nebo Slovensko</dd>
        <dt>Ulice/část obce, č.p., č.o.</dt>
        <dt>PSČ a město</dt>
        <dt>Stát</dt><dd>Opět máte na výběr z ČR nebo SR.</dd>
        <dt>Email</dt>
        <dt>Telefon</dt>
        <dt>ID datové schránky</dt>
        <dt>Poznámka</dt>
    </dl>    

Jakmile máte vše vyplněné podle vašich představ, stačí již jen najet a klepnout na tlačítko Vytvořit. Pokud jste však změnili názor a nový subjekt nechcete tvořit, klepněte na tlačítko Zrušit.
</p>