    <h2>Seznam subjektů</h2>
    <p>
        Další položkou menu v sekci Administrace je tlačítko Odesílatelé/Adresáti.
        Pokud na toto tlačítko kliknete, zobrazí se vám seznam odesílatelů a adresátů,
        které již máte vytvořené. Tento seznam již známe ze sekce spisová služba, kde
        jsme při tvoření nového dokumentu přiřazovali adresáty a odesílatele. Narazili
        jsme tam i na možnost vytvořit nový subjekt, ale blíže jsme se mu nevěnovali,
        ten čas nastává až nyní. Pakliže chcete vytvořit nový subjekt, tak najeďte na
        stejnojmenný nápis pod tlačítkem Odesílatelé/Adresáti.
        V následujícím formuláři naleznete tyto položky:
    </p>
    <dl>
        <dt>Typ subjektu</dt>
        <dt>Název subjektu</dt>
        <dt>IČ</dt><dd>to lze vyhledat přes systém ARES</dd>
        <dt>DIČ</dt>
        <dt>Titul před jménem</dt>
        <dt>Jméno</dt>
        <dt>Prostřední jméno</dt>
        <dt>Příjmení</dt>
        <dt>Titul za jménem</dt>
        <dt>Rodné jméno</dt>
        <dt>Datum narození</dt><dd>Datum lze zadat přes implementovaný kalendář.</dd>
        <dt>Místo narození</dt>
        <dt>Okres narození</dt>
        <dt>Stát narození</dt><dd>Na výběr buď Česká republika nebo Slovensko</dd>
        <dt>Ulice/část obce, č.p., č.o.</dt>
        <dt>PSČ a město</dt>
        <dt>Stát</dt><dd>Opět máte na výběr z ČR nebo SR.</dd>
        <dt>Email</dt>
        <dt>Telefon</dt>
        <dt>ID datové schránky</dt>
        <dt>Poznámka</dt>
    </dl>
    <p>
        Jakmile máte vše vyplněné podle vašich představ, stačí již jen najet a kliknout
        na tlačítko Vytvořit. Pokud jste však změnili názor a nový subjekt nechcete tvořit,
        klikněte na tlačítko Zrušit.
    </p>