{block title}Instalace - databáze{/block}
{block menu}
<a href="{link :Install:Default:uvod}">Úvod</a> >
<a href="{link :Install:Default:kontrola}">Kontrola</a> >
<strong>Nahrání databáze</strong> >
<span>Nastavení klienta</span> >
<span>Nastavení evidence</span> >
<span>Nastavení správce</span> >
<span>Konec</span>
{/block}
{block content}
<h1>Instalace - Databáze</h1>

<p>V tomto kroku se nejdříve zkontroluje, zda je databáze dostupná a zda již dané tabulky v databázi neexistují. Pokud je vše v pořádku, provedete nahrání potřebných tabulek a dat do databáze.</p>

<div id="kontrola">
<?php if (isset($db_install)): ?>
    <?php if ($error): ?>
    <div class="failed result">
        <h2>Při nahrání tabulek do databáze nastala chyba!</h2>
        <p>V detailu vyhledejte označenou položku a zjistěte příčinu chyby.</p>
        <p>Máte tyto možnosti:
            <ul>
                <li>Označené chyby ručně opravit a <a href="{link :Install:Default:urad}">pokračovat v instalaci</a>. Pouze na vlastní riziko!</li>
                <li>Odstranit všechny tabulky určené aplikaci a <a href="{link :Install:Default:databaze, 'install'=>'1'}">provést nahrání znovu</a></li>
                <li>Kontaktovat pověřenou osobu nebo technickou podporu aplikace.</li>
            </ul>
        </p>
        <p>V této fázi není možné pokračovat v instalaci. Pro pokračování instalace je potřeba provést nápravu.</p>
    </div>
    <?php else: ?>
    <div class="passed result">
        <h2>Blahopřeji! Nahrání tabulek a dat proběhlo v pořádku.</h2>
        <p>Můžete pokračovat v instalaci.</p>
        <p><a href="{link :Install:Default:urad}">Pokračovat v instalaci</a></p>
    </div>
    <?php endif ?>
<?php else: ?>
    <?php if (isset($provedeno)): ?>
    <div class="passed result">
        <h2>Tabulky a data jsou již nahrané.</h2>
        <p>Nahrání tabulek a dat proběhlo v pořádku. Můžete pokračovat v instalaci.</p>
        <p><a href="{link :Install:Default:urad}">Pokračovat v instalaci</a></p>
    </div>
    <?php elseif ($tabulka_jiz_existuje): ?>
    <div class="failed result">
        <h2>Nelze nahrát tabulky a data do databáze!</h2>
        <p>V uvedené databázi již existují tabulky určené pro tuto aplikaci. </p>
        <p>V případě, že chcete ponechat existující tabulky, je potřeba v nastavení změnit prefix tabulek nebo jméno databáze. Jinak bude potřeba uvedené tabulky smazat z databáze.</p>
        <p>V této fázi není možné pokračovat v instalaci. Pro pokračování instalace je potřeba provést nápravu. Po dokončení úprav proveďte <a href="?">novou kontrolu</a>. </p>
    </div>
    <?php elseif ($error): ?>
    <div class="failed result">
        <h2>Došlo k výjimce!</h2>
		<p>Popis chyby: {$error}</p>
		<p>Pravděpodobně není nastaveno připojení v souboru system.ini.</p>
    </div>
    <?php else: ?>
    <div class="passed result">
        <h2>Před kontrola databáze proběhla v pořádku.</h2>
        <p>Můžete pokračovat v nahrání tabulek do databáze.</p>
        <p><a href="{link :Install:Default:databaze, 'install'=>'1'}">Nahrát tabulky a data</a></p>

    </div>
    <?php endif ?>
<?php endif ?>



    <h2>Detail kontroly:</h2>

    <table>
    <?php foreach ($database as $id => $requirement):?>
    <?php $class = isset($requirement->passed) ? ($requirement->passed ? 'passed' : ($requirement->required ? 'failed' : 'warning')) : 'info' ?>
    <tr id="res<?php echo $id ?>" class="<?php echo $class ?>">
    	<td class="th"><?php echo htmlSpecialChars($requirement->title) ?></td>

        <?php if (empty($requirement->passed) && isset($requirement->errorMessage)): ?>
	<td><?php echo htmlSpecialChars($requirement->errorMessage) ?></td>
	<?php elseif (isset($requirement->message)): ?>
	<td><?php echo htmlSpecialChars($requirement->message) ?></td>
	<?php elseif (isset($requirement->passed)): ?>
	<td><?php echo $requirement->passed ? 'Enabled' : 'Disabled' ?></td>
	<?php else: ?>
	<td></td>
	<?php endif ?>
    </tr>

    <?php if (isset($requirement->passed) && !$requirement->passed): ?>
    <tr class="<?php echo $class ?> description">
        <td colspan="2"><?php echo $requirement->description ?></td>
    </tr>
    <?php endif ?>

    <?php endforeach ?>
    </table>
