{block title}Instalace - nastavení e-podatelny{/block}
{block menu}
<a href="{link :Install:Default:uvod}">Úvod</a> >
<a href="{link :Install:Default:kontrola}">Kontrola</a> >
<a href="{link :Install:Default:databaze}">Nahrání databáze</a> >
<a href="{link :Install:Default:urad}">Nastavení klienta</a> >
<a href="{link :Install:Default:evidence}">Nastavení evidence</a> >
<a href="{link :Install:Default:spravce}">Nastavení správce</a> >
<a href="{link :Install:Default:konec}">Konec</a>
{/block}
{block content}
<h1>Instalace - nastavení e-podatelny</h1>

<p>Vítejte...</p>