{block title}Instalace - kontrola{/block}
{block menu}
Úvod - Kontrola - Nahrání databáze - Nastavení klienta - Nastavení e-podatelny - Nastavení autorizované konverze - Konec
{/block}
{block content}
<h1>Instalace - kontrola</h1>

<p>Vítejte...</p>

<div id="kontrola">
<?php if ($errors): ?>
    <div class="failed result">
        <h2>Omlováme se, ale konfigurace serveru nesplňuje požadavky pro použití aplikace!</h2>
        <p>Není možné pokračovat v instalaci.</p>
        <p>Podívejte se do detailu a u vyznačených bodech sjednejte nápravu. Poté <a href="?">znovu ověřte</a>.</p>
    </div>
<?php else: ?>
    <div class="passed result">
        <h2>Blahopřeji! Konfigurace serveru splňuje minimální požadavky pro použití aplikace.</h2>
        <p>Můžete pokračovat v instalaci.</p>
	<?php if ($warnings):?><p>Byly zjistěny nesrovnalosti, které mohou ovlivnit chod aplikace. Podívejte se do detailu a u vyznačených bodech se rozhodněte,
            zda je daná položka nutná pro běch aplikace nebo ne.</p><?php endif ?>

        <p><a href="{link :Install:Default:databaze}">Pokračovat v instalaci</a></p>

    </div>
<?php endif ?>

    <h2>Detail kontroly:</h2>

    <table>
    <?php foreach ($requirements_ess as $id => $requirement):?>
    <?php $class = isset($requirement->passed) ? ($requirement->passed ? 'passed' : ($requirement->required ? 'failed' : 'warning')) : 'info' ?>
    <tr id="res<?php echo $id ?>" class="<?php echo $class ?>">
    	<td class="th"><?php echo htmlSpecialChars($requirement->title) ?></td>

        <?php if (empty($requirement->passed) && isset($requirement->errorMessage)): ?>
	<td><?php echo htmlSpecialChars($requirement->errorMessage) ?></td>
	<?php elseif (isset($requirement->message)): ?>
	<td><?php echo htmlSpecialChars($requirement->message) ?></td>
	<?php elseif (isset($requirement->passed)): ?>
	<td><?php echo $requirement->passed ? 'Enabled' : 'Disabled' ?></td>
	<?php else: ?>
	<td></td>
	<?php endif ?>
    </tr>

    <?php if (isset($requirement->passed) && !$requirement->passed): ?>
    <tr class="<?php echo $class ?> description">
        <td colspan="2"><?php echo $requirement->description ?></td>
    </tr>
    <?php endif ?>

    <?php if (isset($requirement->script)): ?>
    <script type="text/javascript"><?php echo $requirement->script ?></script>
    <?php endif ?>

    <?php endforeach ?>
    </table>

    <br />
    <h2>Detaily jádra aplikace (Nette Framework)</h2>

    <table>
    <?php foreach ($requirements as $id => $requirement):?>
    <?php $class = isset($requirement->passed) ? ($requirement->passed ? 'passed' : ($requirement->required ? 'failed' : 'warning')) : 'info';

            if( $class == "passed" || $class == "info" ) continue;

    ?>
    <tr id="res<?php echo $id ?>" class="<?php echo $class ?>">
    	<td class="th"><?php echo htmlSpecialChars($requirement->title) ?></td>

        <?php if (empty($requirement->passed) && isset($requirement->errorMessage)): ?>
	<td><?php echo htmlSpecialChars($requirement->errorMessage) ?></td>
	<?php elseif (isset($requirement->message)): ?>
	<td><?php echo htmlSpecialChars($requirement->message) ?></td>
	<?php elseif (isset($requirement->passed)): ?>
	<td><?php echo $requirement->passed ? 'Enabled' : 'Disabled' ?></td>
	<?php else: ?>
	<td></td>
	<?php endif ?>
    </tr>

    <?php if (isset($requirement->passed) && !$requirement->passed): ?>
    <tr class="<?php echo $class ?> description">
        <td colspan="2"><?php echo $requirement->description ?></td>
    </tr>
    <?php endif ?>

    <?php if (isset($requirement->script)): ?>
    <script type="text/javascript"><?php echo $requirement->script ?></script>
    <?php endif ?>

    <?php endforeach ?>
    </table>

</div>
