{block title}Instalace - úvod{/block}
{block menu}

<strong>Úvod</strong> >
<span>Kontrola</span> >
<span>Nahrání databáze</span> >
<span>Nastavení klienta</span> >
<span>Nastavení evidence</span> >
<span>Nastavení správce</span> >
<span>Konec</span>


{/block}
{block content}
<h1>Vítejte v instalaci spisové služby.</h1>

<p>
Instalace bude probíhat v několika krocích. V prvním kroku se zkontrolují minimální požadavky serveru
na provoz spisové služby. V druhém kroku dojde k nahrání potřebných tabulek a dat pro databázi.
Ve třetím kroku nastavíte informace o sobě. Ve čtvrtém kroku nastavíte možnosti evidence,
jako typ evidence, masku čísla jednacího. V posledním kroku si vytvoříte správce, který bude mít
nad spisovou službu dohled.
</p>
<p>
Před započetím instalace si zkontrolujte, zda máte správně nastavený systémový konfigurační soubor
(nastavení databáze, úložiště, apod) a potřebné informace pro vyplnění údajů o sobě, možnostech evidence a
pověřenou osobu pro správu spisové služby.</p>


<p><a href="{link :Install:Default:kontrola}">Pokračovat v instalaci</a></p>

