@{block title}Seznam spisů{/block}
@{block debug}
<?php print_r($seznam); ?>
@{/block}
@{block content}

    <div class="dokument_blok2">
        <a href="{link :Spisovka:Spisy:novy}">Nový spis</a>
    </div>    
    
    <div id="search">
        {control searchForm}
    </div>

    <div id="dokumenty">
    {if count($seznam)>0}
    <form action="{link this}" method="post">
        <input type="hidden" name="url_referer" value="">
    <table>
        <tr>
            <th class="akce">&nbsp;</th>
            <th>Spis</th>
        </tr>
        {foreach $seznam as $spis}
        <tr class="item{=str_replace("."," item",$spis->sekvence)}" id="sitem{$spis->id}">
            <td class="akce">
                {if $spis->typ=='S' && $spis->stav==0}
                <input type="checkbox" class="checkbox" name="spis_vyber[]" value="{$spis->id}" title="Vybrat tento spis" />
                {else}
                <input type="checkbox" name="off_spis_vyber[]" value="{$spis->id}" disabled="disabled" />
                {/if}
            </td>
            <td>
                {!=str_repeat("&nbsp;", 10*$spis->uroven)}
                {if $spis->typ=='VS'}
                <img src="{$baseUri}images/icons/folder_yellow.png" alt="složka" title="složka" width="16" height="16" onclick="return toggle('item{!$spis->id}');" />
                &nbsp;&nbsp;
                {$spis->nazev}
                {elseif $spis->typ=='SP'}
                <img src="{$baseUri}images/icons/folder_green.png" alt="Spisový plán" title="Spisový plán" width="16" height="16" onclick="return toggle('item{!$spis->id}');" />
                &nbsp;&nbsp;
                {$spis->nazev}
                {else}
                <img src="{$baseUri}images/icons/spisy.png" alt="Spis" title="Spis" width="16" height="16" />
                &nbsp;&nbsp;
                <a href="{link :Spisovka:Spisy:detail, id => $spis->id}">{$spis->nazev}</a>
                {/if}
            </td>
        </tr>
        {/foreach}

    </table>
    <div id="hromadna_akce">
        <span id="checkbox_all_on">Zaškrtnout vše</span> / <span id="checkbox_all_off">Odškrtnout vše</span>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Vybrané položky:&nbsp;&nbsp;
        <select name="hromadna_akce">
            <option value="">(žádná akce)</option>
            <option value="predat_spisovna">předat do spisovny</option>
        </select>
        <input type="submit" name="hromadna_submit" value="Provést" />
    </div>
    </form>
    {widget vp}
    {else}
    <div class="prazdno">Nebyly zjištěny žádné spisy.</div>
    {/if}
    </div>

