{block title}Seznam spisů{/block}
{block debug}
<?php print_r($seznam); ?>
{/block}
{block content}

    <div class="dokument_blok2">
        <a href="{link :Spisovka:Spisy:novy}">Nový spis</a>
    </div>    

    <div id="tisk">
        <a href="{link this, 'print' => 1}" title="vytisknout tuto stránku" target="_blank">
            <img src="{$publicUrl}images/icons/printer.png" alt="printer.png" width="32" height="32" />
        </a>
        <a href="{link this, 'pdfprint' => 1}" title="Vytisknout tuto stránku do PDF" target="_blank">
            <img src="{$publicUrl}images/mimetypes/application-pdf.png" alt="application-pdf.png" width="32" height="32" />
        </a>        
    </div>

    <div id="search">
        {control searchForm}
    </div>
    <br class="clear" />
    <div id="dokumenty">
    {if count($seznam)>0}
    <form action="{link this}" method="post">
        <input type="hidden" name="url_referer" value="">
    <table>
        <tr>
            <th class="akce">&nbsp;</th>
            <th>Spis</th>
            <th>Počet dokumentů</th>
            <th>Přiděleno</th>
            <th>Předáno</th>
            <th>Spisový znak</th>
            <th>Skartační znak/lhůta</th>
            <th>Stav</th>            
        </tr>
        {foreach $seznam as $spis}
        <tr class="item{=str_replace("."," item",$spis->sekvence)}" id="sitem{$spis->id}">
            <td class="akce">
                {if $spis->typ=='S' && $spis->stav==0}
                <input type="checkbox" class="checkbox" name="spis_vyber[]" value="{$spis->id}" title="Vybrat tento spis" />
                {else}
                <input type="checkbox" name="off_spis_vyber[]" value="{$spis->id}" disabled="disabled" />
                {/if}
            </td>
            {if $spis->typ=='VS'}
            <td colspan="7">
                {!=@str_repeat("&nbsp;", 10*($spis->uroven))}
                <img src="{$publicUrl}images/icons/folder_yellow.png" alt="složka" title="složka" width="16" height="16" onclick="return toggle('item{!$spis->id}');" />
                &nbsp;&nbsp;
                {$spis->nazev}                
            </td>
            {elseif $spis->typ=='SP'}
            <td colspan="7">
                {!=@str_repeat("&nbsp;", 10*($spis->uroven))}
                <img src="{$publicUrl}images/icons/folder_green.png" alt="Hlavní spis" title="Hlavní spis" width="16" height="16" onclick="return toggle('item{!$spis->id}');" />
                &nbsp;&nbsp;
                {$spis->nazev}                
            </td>
            {else}
            <td>
                {!=@str_repeat("&nbsp;", 10*($spis->uroven))}
                <img src="{$publicUrl}images/icons/spisy.png" alt="Spis" title="Spis" width="16" height="16" />
                &nbsp;&nbsp;
                <a href="{link :Spisovka:Spisy:detail, id => $spis->id}">{$spis->nazev}</a>
            </td>
            <td>{if isset($seznam_dokumentu[$spis->id])}{=count($seznam_dokumentu[$spis->id])}{else}0{/if}</td>
            <td>{$spis->orgjednotka_prideleno}</td>              
            <td>{$spis->orgjednotka_predano}</td>              
            <td>{if isset($SpisoveZnaky[$spis->spisovy_znak_id])}{$SpisoveZnaky[$spis->spisovy_znak_id]->nazev}{/if} </td>
            <td>{$spis->skartacni_znak} / {$spis->skartacni_lhuta}</td>
            <td>{=Spis::stav($spis->stav)}</td>      
            {/if}
        </tr>
        {/foreach}

    </table>
    <div id="hromadna_akce">
        <span id="checkbox_all_on">Zaškrtnout vše</span> / <span id="checkbox_all_off">Odškrtnout vše</span>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        Vybrané položky:&nbsp;&nbsp;
        <select name="hromadna_akce">
            <option value="">(žádná akce)</option>
            <option value="predat_spisovna">předat do spisovny</option>
        </select>
        <input type="submit" name="hromadna_submit" value="Provést" />
    </div>
    </form>
    {widget vp}
    {else}
    <div class="prazdno">Nebyly zjištěny žádné spisy.</div>
    {/if}
    </div>

