@{block title}Seznam spisů{/block}
@{block debug}
<?php print_r($seznam); ?>
@{/block}
@{block javascript}
	<script type="text/javascript">

                function vybratSpisovyZnak() {

                    var spisz_skart = new Array();
                    var spisz_lhuta = new Array();
                    var spisz_udalost = new Array();
                    spisz_skart['0'] = '';
                    spisz_lhuta['0'] = '';
                    spisz_udalost['0'] = '';
                {if count($SpisoveZnaky)>0}
                {foreach $SpisoveZnaky as $sznak}
                    spisz_skart[{$sznak->id}] = {$sznak->skartacni_znak};
                    spisz_lhuta[{$sznak->id}] = {$sznak->skartacni_lhuta};
                    spisz_udalost[{$sznak->id}] = {=SpisovyZnak::spousteci_udalost($sznak->spousteci_udalost)};
                {/foreach}
                {/if}

                    var frm_spis  = document.forms['frm-upravitForm'].spisovy_znak;
                    var frm_skart  = document.forms['frm-upravitForm'].skartacni_znak;
                    var frm_lhuta  = document.forms['frm-upravitForm'].skartacni_lhuta;
                    var frm_udalost  = document.forms['frm-upravitForm'].spousteci_udalost;

                    var key  = document.forms['frm-upravitForm'].spisovy_znak.selectedIndex;
                    var value = document.forms['frm-upravitForm'].spisovy_znak.options[key].value;
                    document.forms['frm-upravitForm'].skartacni_znak.value = spisz_skart[value];
                    document.forms['frm-upravitForm'].skartacni_lhuta.value = spisz_lhuta[value];
                    document.forms['frm-upravitForm'].spousteci_udalost.value = spisz_udalost[value];
                    return true;
                }


	</script>
@{/block}
@{block content}
    <div class="navigate">
    <a href="{link :Spisovka:Dokumenty:default}">Seznam dokumentů</a> -
    <a href="{link :Spisovka:Spisy:default}">Seznam spisů</a> -
    Detail spisu
    </div>

    <h2>{$Spis->nazev}</h2>

        {if ($FormUpravit=='info')}
    <div class="detail_blok">
        <div class="detail_hlavicka">Info</div>
        {control $upravitForm}
    </div>
        {else}
    <div class="detail_blok">
        <div class="detail_hlavicka">Informace o spisu</div>
        <dl class="detail_item">
            <dt>Spisová značka:</dt>
            <dd>{$Spis->nazev}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{$Spis->popis}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd title="{$SpisZnak_popis}">{$SpisZnak_nazev}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Spis->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$Spis->skartacni_lhuta}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{$Spis->spousteci_udalost}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Stav:</dt>
            <dd>{=Spis::stav($Spis->stav)}&nbsp;</dd>
        </dl>
        <a href="{link :Spisovka:Spisy:detail, 'id'=>$Spis->id, 'upravit'=>'info'}">Upravit</a>
    </div>
        {/if}

    <div class="detail_blok">
        <div class="detail_hlavicka">Seznam dokumentů</div>
    </div>
    <div id="dokumenty">
    {if count($seznam)>0}
    <table>

        <tr>
            <th class="typ">Typ dokumentu</th>
            <th class="prijato">Přijato</th>
            <th class="cislo_jadnaci">JID<br />Číslo jednací<br />Spisová značka</th>
            <th class="vec">Věc<br />Adresáti/odesílatelé<br />počet listů a příloh</th>
            <th class="prideleno">Přiděleno</th>
            <th class="stav">Stav</th>
        </tr>

        {foreach $seznam as $dok}
        <tr>
            <td class="typ">
                <img src="{$baseUri}images/icons/smer{$dok->typ_dokumentu->smer}.png" alt="{$dok->typ_dokumentu->nazev}" title="{$dok->typ_dokumentu->nazev}" width="16" height="16" />
                <img src="{$baseUri}images/icons/typdok{$dok->typ_dokumentu->typ}.png" alt="{$dok->typ_dokumentu->nazev}" title="{$dok->typ_dokumentu->nazev}" width="24" height="16" />
            </td>
            <td class="prijato">
                {$dok->datum_vzniku|edate}
            </td>
            <td class="cislo_jadnaci">
                <span style="font-size: 8pt;">&nbsp;{$dok->jid}</span>
                <br />
                &nbsp;<strong><a href="{link :Spisovka:Dokumenty:detail, 'id'=>$dok->id}">
                   {$dok->cislo_jednaci}
                </a></strong>
                <br />
                {if count($dok->spisy)>0}
                {foreach $dok->spisy as $spis}
                <a href="{link :Spisovka:Spisy:detail, 'id'=>$spis->id}">{$spis->nazev}</a><br />
                {/foreach}
                {/if}
            </td>
            <td class="vec">
                <strong title="{$dok->popis}"><a href="{link :Spisovka:Dokumenty:detail, 'id'=>$dok->id}">
                    {$dok->nazev}
                </a></strong>
                <br />
                {if count($dok->subjekty)>0}
                {foreach $dok->subjekty as $subjekt}
                {=Subjekt::displayName($subjekt,'plna_adresa')}<br />
                {/foreach}
                {else}
                nejsou přiděleny žádné subjekty!<br />
                {/if}
                <span style="font-size: 8pt;">přílohy:
                {=($dok->pocet_listu)+0} listů,
                {=($dok->pocet_priloh)+0} list. příloh,
                {=(count($dok->prilohy)+0)} příloh</span>
            </td>



            {if $dok->stav_dokumentu == 1}
            <td class="prideleno">
                {if !empty($dok->prideleno->prideleno_jmeno)}
                {$dok->prideleno->prideleno_jmeno}
                {/if}&nbsp;
            </td>
            <td class="stav">
                nový
                <br />
                {$dok->prideleno->date|edate}
            </td>
            {elseif $dok->stav_dokumentu == 2 && !empty($dok->predano) }
            <td class="prideleno">
                {if !empty($dok->predano->prideleno_jmeno)}
                {$dok->predano->prideleno_jmeno}
                {/if}&nbsp;
            </td>
            <td class="stav">
                předáno
                <br />
                {$dok->predano->date_predani|edate}
            </td>
            {elseif $dok->stav_dokumentu == 2 && !empty($dok->prideleno) }
            <td class="prideleno">
                {if !empty($dok->prideleno->prideleno_jmeno)}
                {$dok->prideleno->prideleno_jmeno}
                {/if}&nbsp;
            </td>
            <td class="stav">
                přiděleno
                <br />
                {$dok->prideleno->date|edate}
            </td>
            {elseif $dok->stav_dokumentu == 3 }
            <td class="prideleno">
                {if !empty($dok->prideleno->prideleno_jmeno)}
                {$dok->prideleno->prideleno_jmeno}
                {/if}&nbsp;
            </td>
            <td class="stav">
                vyřizuje se
                <br />
                {if !empty($dok->prideleno->date)}
                {$dok->prideleno->date|edate}
                {/if}
            </td>
            {elseif $dok->stav_dokumentu == 4 }
            <td class="prideleno">
                {if !empty($dok->prideleno->prideleno_jmeno)}
                {$dok->prideleno->prideleno_jmeno}
                {/if}&nbsp;
            </td>
            <td class="stav">
                vyřízeno
                <br />
                {$dok->datum_vyrizeni|edate}
            </td>
            {else}
            <td class="prideleno">
                &nbsp;
            </td>
            <td class="stav">
                nepřiřazeno!
                <br />
                lhůta {$dok->lhuta} dní
            </td>
            {/if}



        </tr>
        {/foreach}


    </table>
    {else}
        <div>&nbsp;</div>
        {if isset($no_items)}
        {if $no_items==1}
        <div class="prazdno">Nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==2}
        <div class="prazdno">K danému filtru nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==3}
        <div class="prazdno">Dokument odpovidající hledanému výrazu nebyl nalezen.</div>
        {/if}
        {else}
    <div class="prazdno">K tomuto spisu nebyly zjištěny žádné dokumenty.</div>
        {/if}
    {/if}
    </div>