@{block title}Detail spisu{/block}
@{block javascript}
	<script type="text/javascript">

                function vybratSpisovyZnak() {

                    var spisz_skart = new Array();
                    var spisz_lhuta = new Array();
                    var spisz_udalost = new Array();
                    spisz_skart['0'] = '';
                    spisz_lhuta['0'] = '';
                    spisz_udalost['0'] = '';
                {if count($SpisoveZnaky)>0}
                {foreach $SpisoveZnaky as $sznak}
                    spisz_skart[{$sznak->id}] = {$sznak->skartacni_znak};
                    spisz_lhuta[{$sznak->id}] = {$sznak->skartacni_lhuta};
                    spisz_udalost[{$sznak->id}] = {$sznak->spousteci_udalost_id};
                {/foreach}
                {/if}

                    var frm_spis  = document.forms['frm-upravitForm'].spisovy_znak_id;
                    var frm_skart  = document.forms['frm-upravitForm'].skartacni_znak;
                    var frm_lhuta  = document.forms['frm-upravitForm'].skartacni_lhuta;
                    var frm_udalost  = document.forms['frm-upravitForm'].spousteci_udalost_id;

                    var key  = document.forms['frm-upravitForm'].spisovy_znak_id.selectedIndex;
                    var value = document.forms['frm-upravitForm'].spisovy_znak_id.options[key].value;
                    document.forms['frm-upravitForm'].skartacni_znak.value = spisz_skart[value];
                    document.forms['frm-upravitForm'].skartacni_lhuta.value = spisz_lhuta[value];
                    //document.forms['frm-novyForm'].spousteci_udalost.value = spisz_udalost[value];
                    select_set_value(document.forms['frm-upravitForm'].spousteci_udalost_id,spisz_udalost[value]);
                    return true;
                }

	</script>
@{/block}
@{block debug}
<?php print_r($seznam); ?>
@{/block}
@{block content}
    <div class="navigate">
    <a href="{link :Spisovka:Spisy:default}">Seznam spisů</a> -
    Detail spisu
    </div>

    <h2>{$Spis->nazev}</h2>

    <div id="tisk">
        <a href="{link :Spisovka:Spisy:detail, 'id'=>$Spis->id, 'print' => 1}" title="vytisknout tuto stránku" target="_blank">
            <img src="{$baseUri}images/icons/printer.png" alt="printer.png" width="32" height="32" />
        </a>
        <a href="{link :Spisovka:Spisy:detail, 'id'=>$Spis->id, 'pdfprint' => 1}" title="Vytisknout tuto stránku do PDF" target="_blank">
            <img src="{$baseUri}images/mimetypes/application-pdf.png" alt="application-pdf.png" width="32" height="32" />
        </a>        
    </div>    
    
    <div id="dokument_blok_volby">
       {if $Pridelen==1 }
       <a href="{link :Spisovka:Spisy:detail, 'id'=>$Spis->id, 'upravit'=>'info'}">Upravit spis</a>
       <a href="{link :Spisovka:Uzivatel:vyberspis, 'id'=>$user->id, 'spis_id'=>$Spis->id}" id="dialog-spis">Předat spis</a>
       {/if}
       {if $Predan==1 }
       <a href="{link :Spisovka:Spisy:prevzit, 'id'=>$Spis->id, 'user'=>$user->id, 'org'=>@$orgjednotka->id}" id="prevzitdokument">Převzít spis</a>
       <a href="{link :Spisovka:Spisy:odmitnoutprevzeti, 'id'=>$Spis->id, 'user'=>$user->id, 'org'=>@$orgjednotka->id}" id="zrusitprevzetidokument">Odmítnout převzetí</a>
       {/if}
       {if ($Pridelen==1 && !empty($Spis->orgjednotka_id_predano) ) }
       <a href="{link :Spisovka:Spisy:zrusitprevzeti, 'id'=>$Spis->id, 'user'=>$user->id, 'org'=>@$orgjednotka->id}" id="zrusitprevzetidokument">Zrušit převzeti spisu</a>
       {/if}
       {if empty($Spis->orgjednotka_id)}
       <a href="{link :Spisovka:Spisy:prevzitspis, 'id'=>$Spis->id, 'user'=>$user->id, 'org'=>@$orgjednotka->id}" id="prevzitdokument">Převzít spis do vlastnictví</a>
       {/if}
       
       {if $Pridelen==1 }
       {if $Spis->stav==1}<a href="{link :Spisovka:Spisy:stav, 'id'=>$Spis->id, 'stav'=>'uzavrit'}" onclick="return confirm('Opravdu chcete uzavřít tento spis?');">Uzavřít spis</a>{/if}
       {if $Spis->stav==0}<a href="{link :Spisovka:Spisy:stav, 'id'=>$Spis->id, 'stav'=>'otevrit'}" onclick="return confirm('Opravdu chcete otevřít tento spis?');">Otevřít spis</a>{/if}
       {/if}
        
    </div>
    
        {if ($FormUpravit=='info')}
    <div class="detail_blok">
        <div class="detail_hlavicka">Info</div>
        {control $upravitForm}
    </div>
        {else}
    <div class="detail_blok">
        <div class="detail_hlavicka">Informace o spisu</div>
        <dl class="detail_item">
            <dt>Název spisu:</dt>
            <dd>{$Spis->nazev}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Popis:</dt>
            <dd>{$Spis->popis}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spisový znak:</dt>
            <dd>{$SpisZnak_nazev}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační znak:</dt>
            <dd>{$Spis->skartacni_znak}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Skartační lhůta:</dt>
            <dd>{$Spis->skartacni_lhuta}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Spouštěcí událost:</dt>
            <dd>{=SpisovyZnak::spousteci_udalost($Spis->spousteci_udalost_id,10)}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Přiděleno organizační jednotce:</dt>
            <dd>{if !empty($Spis->orgjednotka_prideleno)}{$Spis->orgjednotka_prideleno->zkraceny_nazev}{else}(není přidělěno k žádné organizační jednotce){/if}&nbsp;</dd>
        </dl>  
        {if !empty($Spis->orgjednotka_predano)}
        <dl class="detail_item">
            <dt>Předáno organizační jednotce:</dt>
            <dd>{$Spis->orgjednotka_predano->zkraceny_nazev}&nbsp;</dd>
        </dl> 
        {/if}
        <dl class="detail_item">
            <dt>Stav:</dt>
            <dd>
                {=Spis::stav($Spis->stav)}
            </dd>
        </dl>
    </div>
        {/if}
        
    <div class="detail_blok">
        <div class="detail_hlavicka">Seznam dokumentů</div>
    </div>
        
    {if $AccessView}    

    {if $Pridelen==1 }
    <div class="dokument_blok2">
        <a href="{link :Spisovka:Dokumenty:novy, 'spis_id'=>$Spis->id}">Nový dokument</a>
    </div>         
    {/if}
        
    <div id="dokumenty">
    {if count($seznam)>0}
    <table>

        <tr>
            <th class="typ">Typ dokumentu</th>
            <th class="prijato">Přijato</th>
            <th class="cislo_jadnaci">Číslo jednací<br />JID<br />Název spisu</th>
            <th class="vec">Věc<br />Adresáti/odesílatelé<br />počet listů a příloh</th>
            <th class="prideleno">Přiděleno</th>
            <th class="stav">Stav</th>
        </tr>

        {foreach $seznam as $dok}
        <tr {if $dok->stav==2} style="background-color: #d0d0d0;"{/if}">
            <td class="typ">
                <img src="{$baseUri}images/icons/smer{$dok->typ_dokumentu->smer}.png" alt="{$dok->typ_dokumentu->nazev}" title="{$dok->typ_dokumentu->nazev}" width="16" height="16" />
                {if !empty($dok->epod_is_email)}
                <img src="{$baseUri}images/icons/typdok1.png" alt="přijato emailem" title="přijato emailem" width="24" height="16" />
                {elseif !empty($dok->epod_is_isds)}
                <img src="{$baseUri}images/icons/typdok2.png" alt="přijato datovou schránkou" title="přijato datovou schránkou" width="24" height="16" />
                {/if}
            </td>
            <td class="prijato">
                {$dok->datum_vzniku|edate}
            </td>
            <td class="cislo_jadnaci">
                &nbsp;<strong><a href="{if $dok->stav==2}{link :Spisovna:Dokumenty:detail, 'id'=>$dok->id}{else}{link :Spisovka:Dokumenty:detail, 'id'=>$dok->id}{/if}">
                   {$dok->cislo_jednaci}{if $Typ_evidence=='sberny_arch'}{$Oddelovac_poradi}{$dok->poradi}{/if}
                </a></strong>
                <div class="small">&nbsp;{$dok->jid}</div>
                {if count($dok->spisy)>0}
                {foreach $dok->spisy as $spis}
                <a href="{link :Spisovka:Spisy:detail, 'id'=>$spis->id}">{$spis->nazev}</a><br />
                {/foreach}
                {/if}
            </td>
            <td class="vec">
                <strong title="{$dok->popis}"><a href="{if $dok->stav==2}{link :Spisovna:Dokumenty:detail, 'id'=>$dok->id}{else}{link :Spisovka:Dokumenty:detail, 'id'=>$dok->id}{/if}">
                    {$dok->nazev}
                </a></strong>
                <br />
                {if count($dok->subjekty)>0}
                {foreach $dok->subjekty as $subjekt}
                {=Subjekt::displayName($subjekt,'plna_adresa')}<br />
                {/foreach}
                {else}
                nejsou přiděleny žádné subjekty!<br />
                {/if}
                <span style="font-size: 8pt;">přílohy:
                {=($dok->pocet_listu)+0} listů,
                {=($dok->pocet_priloh)+0} list. příloh,
                {=(count($dok->prilohy)+0)} příloh</span>
            </td>



            {if $dok->stav_dokumentu == 1}
            <td class="prideleno">
            {if empty($dok->prideleno->prideleno_id) }
                {$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {else}
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {/if}  
            </td>
            <td class="stav">
                nový
                <br />
                {$dok->prideleno->date|edate}
            </td>
            {elseif $dok->stav_dokumentu == 2 && !empty($dok->predano) }
            <td class="prideleno">
            {if empty($dok->prideleno->prideleno_id) }
                {$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {else}
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {/if}
                <br />
            {if empty($dok->predano->prideleno_id) }
                > {$dok->predano->orgjednotka_info->zkraceny_nazev}
            {else}
                > {$dok->predano->prideleno_jmeno}
                <br />
                > {=@$dok->predano->orgjednotka_info->zkraceny_nazev}
            {/if}
            </td>
            <td class="stav">
                předáno
                <br />
                {$dok->predano->date_predani|edate}
            </td>
            {elseif $dok->stav_dokumentu == 2 && !empty($dok->prideleno) }
            <td class="prideleno">
            {if empty($dok->prideleno->prideleno_id) }
                {$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {else}
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            {/if}            
            </td>
            <td class="stav">
                přiděleno
                <br />
                {$dok->prideleno->date|edate}
            </td>
            {elseif $dok->stav_dokumentu == 3 }
            <td class="prideleno">
                {if !empty($dok->prideleno->prideleno_jmeno)}
                {$dok->prideleno->prideleno_jmeno}
                {/if}&nbsp;
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}                
            </td>
            <td class="stav">
                vyřizuje se
                <br />
                {if !empty($dok->prideleno->date)}
                {$dok->prideleno->date|edate}
                {/if}
            </td>
            {elseif $dok->stav_dokumentu == 4 }
            <td class="prideleno">
                {if !empty($dok->prideleno->prideleno_jmeno)}
                {$dok->prideleno->prideleno_jmeno}
                {/if}&nbsp;
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}                  
            </td>
            <td class="stav">
                vyřízeno
                <br />
                {$dok->datum_vyrizeni|edate}
            </td>
            {elseif $dok->stav_dokumentu == 5 }
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                vyřízeno
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 6 }
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                vyřízeno<br />předáno do spisovny
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 7 }
            <td class="prideleno">
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
            </td>
            <td class="stav">
                vyřízeno<br />ve spisovně
                <br />
                <span title="{$dok->datum_vyrizeni|edatetime}">{$dok->datum_vyrizeni|edate}</span>
            </td>
            {elseif $dok->stav_dokumentu == 11 }
            <td class="prideleno">
                {if !empty($dok->predano)}
                {$dok->predano->prideleno_jmeno}
                <br />
                {=@$dok->predano->orgjednotka_info->zkraceny_nazev}
                {else}
                {$dok->prideleno->prideleno_jmeno}
                <br />
                {=@$dok->prideleno->orgjednotka_info->zkraceny_nazev}
                {/if}
            </td>
            <td class="stav">
                zapůjčen
                <br />
            </td>
            {elseif $dok->stav == 2}
            <td class="prideleno">
                {if !empty($dok->prideleno->prideleno_jmeno)}
                {$dok->prideleno->prideleno_jmeno}
                {/if}&nbsp;
            </td>
            <td class="stav">
                ve spisovně
                <br />
                {$dok->datum_vyrizeni|edate}
            </td>            
            {else}
            <td class="prideleno">
                &nbsp;
            </td>
            <td class="stav">
                nepřiřazeno!
                <br />
                lhůta {$dok->lhuta} dní
            </td>
            {/if}



        </tr>
        {/foreach}


    </table>
    {else}
        <div>&nbsp;</div>
        {if isset($no_items)}
        {if $no_items==1}
        <div class="prazdno">Nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==2}
        <div class="prazdno">K danému filtru nemáte k dispozici žádné dokumenty.</div>
        {elseif $no_items==3}
        <div class="prazdno">Dokument odpovidající hledanému výrazu nebyl nalezen.</div>
        {/if}
        {else}
    <div class="prazdno">K tomuto spisu nebyly zjištěny žádné dokumenty.</div>
        {/if}
    {/if}
    </div>
    
    {else}
    <div class="prazdno">Nemáte oprávnění vidět seznam dokumentů.</div>
    {/if}
        
<div id="dialog"></div>        