{block title}Nový spis{/block}
@{block javascript}
	<script type="text/javascript">

                function vybratSpisovyZnak() {

                    var spisz_skart = new Array();
                    var spisz_lhuta = new Array();
                    var spisz_udalost = new Array();
                    spisz_skart['0'] = '';
                    spisz_lhuta['0'] = '';
                    spisz_udalost['0'] = '';
                {if count($SpisoveZnaky)>0}
                {foreach $SpisoveZnaky as $sznak}
                    spisz_skart[{$sznak->id}] = {$sznak->skartacni_znak};
                    spisz_lhuta[{$sznak->id}] = {$sznak->skartacni_lhuta};
                    spisz_udalost[{$sznak->id}] = {$sznak->spousteci_udalost_id};
                {/foreach}
                {/if}

                    var frm_spis  = document.forms['frm-novyForm'].spisovy_znak_id;
                    var frm_skart  = document.forms['frm-novyForm'].skartacni_znak;
                    var frm_lhuta  = document.forms['frm-novyForm'].skartacni_lhuta;
                    var frm_udalost  = document.forms['frm-novyForm'].spousteci_udalost_id;

                    var key  = document.forms['frm-novyForm'].spisovy_znak_id.selectedIndex;
                    var value = document.forms['frm-novyForm'].spisovy_znak_id.options[key].value;
                    document.forms['frm-novyForm'].skartacni_znak.value = spisz_skart[value];
                    document.forms['frm-novyForm'].skartacni_lhuta.value = spisz_lhuta[value];
                    //document.forms['frm-novyForm'].spousteci_udalost.value = spisz_udalost[value];
                    select_set_value(document.forms['frm-novyForm'].spousteci_udalost_id,spisz_udalost[value]);
                    return true;
                }


	</script>
@{/block}
{block content}
    <div class="navigate">
    <a href="{link :Spisovka:Dokumenty:default}">Seznam dokumentů</a> -
    <a href="{link :Spisovka:Spisy:default}">Seznam spisů</a> -
    nový spis
    </div>        

    <h2>Nový spis</h2>

    <div class="detail_blok">
        <div class="detail_hlavicka">Info</div>
        {control $spisForm}
    </div>