    <h2>Detail spisového znaku</h2>

<p>    
Pokud si přejete vidět detaily nějakého spisového znaku, stačí na jeden z nich klepnout a zobrazí se vám jeho detaily, které samozřejmě lze upravovat tím, že kliknete na nápis Upravit. To však není všechno, co můžete dělat v detailech spisového znaku. V něm totiž lze i spisový znak odstranit, k tomu slouží odkaz Odebrat a poté tu je ještě možnost Odebrat včetně podřízených spisových znaků.    
</p>