    <h2>Spisový znak</h2>
<p>    
    <dl>
        <dt>Spisový znak</dt>
        <dd>Číselný kód, zpravidla oddělený tečkami.</dd>
        <dt>Popis</dt>
        <dd>Popis spisového znaku.</dd>
        <dt>Skartační znak</dt>
        <dd>A - archivovat<br />S - skartovat<br />V - posouzení</dd>
        <dt>Skartační lhůta</dt>
        <dd>Do tohoto pole se zadává lhůta v rocích, po které dochází ke skartačnímu řízení.</dd>
        <dt>Spouštěcí událost</dt>
        <dd>V rozbalovacím menu naleznete předdefinované spouštěcí události.</dd>
        <dt>Připojit k</dt>
        <dd>Toto pole umožňuje uspořádat spisového znaky do stromové struktury. V současnosti hierarchie spisových znaků nemá jinou funkci, než lepší přehlednost při výběru z dlouhého seznamu.</dd>
        <dt>Stav</dt>
        <dd>Určuje, zda je možné spisový znak vybrat a přiřadit např. dokumentu. Používá se pro nadpis / skupinu spisových znaků. V&nbsp;tom případě může být skartační lhůta nevyplněná.</dd>
    </dl>
</p>