    <h2>Nový spisový znak</h2>
<p>    
V sekci Spisové znaky můžete klepnout na odkaz Nový spisový znak. Otevře se vám nová obrazovka, která obsahuje tyto položky:

    <dl>
        <dt>Spisový znak</dt>
        <dd>Představuje číselný kód věcné skupiny</dd>
        <dt>Věcná skupina</dt>
        <dd>Název věcné skupiny, popis spisového znaku</dd>
        <dt>Skartační znak</dt>
        <dd>V rozbalovacím menu vyberte jeden ze skartačních znaků</dd>
        <dt>Skartační lhůta</dt>
        <dd>Do tohoto pole se zadává lhůta, po které dochází ke skartaci.</dd>
        <dt>Spouštěcí událost</dt>
        <dd>V rozbalovacím menu naleznete mnoho spouštěcích událostí.</dd>
        <dt>Připojit k</dt>
        <dd>Toto pole udává návaznost nového spisového znaku. Buď můžete vybrat možnost hlavní větev anebo jeden z již existujících spisových znaků, čímž udáte závislost na tomto znaku.</dd>
</dl>

Poté již jen najeďte a klepněte na tlačítko Vytvořit, po případě chcete-li  vytvořit více spisových znaků za sebou, klepněte na tlačítko Vytvořit spisový znak a založit nový nebo můžete nový spisový znak smazat a to tak, že klepnete na tlačítko Zrušit.    
</p>