    <h2>Seznam spisových znaků</h2>
    <p>
        Předposledním tlačítkem je položka Spisové znaky. Když na něj kliknete, zobrazí se vám soupis již existujících spisových znaků a jejich návaznost na sebe. Pokud na jeden z těchto spisových znaků kliknete, zobrazí se vám jeho detaily, které samozřejmě lze upravovat tím, že kliknete na nápis Upravit.
        V této sekci jdou ale spisové znaky i vytvářet, stačí se jen navrátit na původní obrazovku sekce Spisové znaky a kliknout na nápis Nový spisový znak. Otevře se vám nová obrazovka, která obsahuje tyto položky:
    </p>
    <dl>
        <dt>Spisový znak</dt><dd>Jedná se o povinnou položku</dd>
        <dt>Popis</dt>
        <dt>Skartační znak</dt><dd>V rozbalovacím menu vyberte jeden ze skartačních znaků</dd>
        <dt>Skartační lhůta</dt><dd>Do tohoto pole se zadává lhůta, po které dochází ke skartaci.</dd>
        <dt>Spouštěcí událost</dt><dd>V rozbalovacím menu naleznete mnoho spouštěcích událostí.</dd>
        <dt>Připojit k</dt><dd>Toto pole udává návaznost nového spisového znaku. Buď můžete vybrat možnost hlavní větev anebo jeden z již existujících spisových znaků, čímž udáte závislost na tomto znaku.</dd>
</dl>
<p>
Poté již jen najeďte a klikněte na tlačítko Vytvořit nebo můžete nový spisový
znak smazat a to tak, že kliknete na tlačítko Zrušit.
</p>