    <h2>Nastavení e-podatelny</h2>
    <p>
        Pokud chcete provádět základní úpravu nastavení osobních údajů nebo třeba změnit
        heslo, musíte najet na tlačítko Nastavení, které naleznete v horním pravém rohu.
        Jakmile na toto tlačítko najedete, zobrazí se vám nová obrazovka, kde máte dvě
        možnosti Upravit osobní udaje a Změnit heslo. Nejprve se podívejme na první možnost.
        Pokud tedy chcete upravit své osobní údaje, najeďte a klikněte na nápis Upravit osobní
        údaje. Máte možnost upravit tyto možnosti:
    </p>
    <ul>
        <li>Jméno</li>
        <li>Příjmení</li>
        <li>Titul před jménem</li>
        <li>Titul za jménem</li>
        <li>Email</li>
        <li>Telefon</li>
        <li>Funkce</li>
    </ul>
<p>
    Jakmile máte vše nastavené, můžete potvrdit tyto změny kliknutím na tlačítko
    Upravit. Pokud si změny rozmyslíte a žádné provádět nechcete, klikněte na
    tlačítko Zrušit. Pokud chcete změnit své přístupové heslo, klikněte na nápis
    Změnit heslo. Poté jen zadejte nové heslo a následně ho přepište znovu do
    kolonky Heslo znovu kvůli případným překlepům. Pak již stačí jen kliknout na
    tlačítko Změnit heslo. Opět platí, že pokud byste si změnu hesla rozmysleli,
    klikněte na tlačítko Zrušit.
</p>