    <h2>Nastavení e-podatelny - detail</h2>

<br />
<h3>Nastavení datové schránky</h3>
<p>
Pokud si přejete nastavit datovou schránku, najeďte a klepněte na odkaz Upravit.
Zobrazí se vám nastavení účtu, kde můžete upravit následující údaje:
</p>
    <dl>
        <dt>Název účtu</dt>
        <dd>Tato položka je povinná.</dd>
    </dl> 
    <dl>
        <dt>Aktivní účet</dt>
        <dd>Jedná se o zaškrtávací box určující, zda je účet aktivní.</dd>
    </dl> 
    <dl>
        <dt>Typ přihlášení</dt>
        <dd>Zde v rozbalovacím poli vyberte jednu z možností. Výchozí volba je pouze jménem a heslem.</dd>
    </dl> 
    <dl>
        <dt>Přihlašovací jméno</dt>
        <dd>Uživatelké jméno do datové schránky.</dd>
    </dl> 
    <dl>
        <dt>Heslo</dt>
        <dd></dd>
    </dl> 
    <dl>
        <dt>Cesta k certifikátu (formát X.509)</dt>
        <dd>Zde se nachází tlačítko Procházet, na které když klepnete, můžete zadat cestu k vašemu certifikátu.</dd>
    </dl> 
    <dl>
        <dt>Heslo ke klíči certifikátu</dt>
        <dd>Zadejte heslo</dd>
    </dl> 
    <dl>
        <dt>Režim</dt>
        <dd></dd>
    </dl> 
    <dl>
        <dt>Podatelna pro příjem</dt>
        <dd>Slouží pro velké organizace, kde mají více oddělení, které pracují s e-podatelnou. Příjem zpráv z datové schránky bude dostupný jenom pro pracovníky organizační jednotky, kterou zde vyberete.<br />Standardní volba je "kterákoli podatelna".</dd>
    </dl> 
<p>
Jakmile máte vše vyplněné, najeďte a klepněte na tlačítko Uložit. Pakliže jste si úpravy rozmysleli, klepněte levým tlačítkem myši na tlačítko Zrušit.
</p>

<br />
<h3>Nastavení emailové schránky</h3>
<p>
Pokud chcete upravit emailovou schránku, tak si otevřete detaily emailové schránky. Zobrazí se vám souhrn informací týkající se emailové schránky. Pro editaci těchto údajů musíte klepnout na nápis Upravit.
Opět je zde několik položek, které můžete upravovat.
Zde je jejich stručný popis:

    <dl>
        <dt>Název účtu</dt>
        <dd>Opět se jedná o první povinnou položku ve formuláři.</dd>
    </dl> 
    <dl>
        <dt>Aktivní účet</dt>
        <dd>Jedná se o zaškrtávací pole určující, zda je účet aktivní.</dd>
    </dl> 
    <dl>
        <dt>Protokol</dt>
        <dd>Druhou povinnou položkou tohoto formuláře je protokol. Na výběr máte hned z několika možnosti (POP3, POP3-SSL, IMAP, IMAP-SSL a NNTP).</dd>
    </dl> 
    <dl>
        <dt>Adresa serveru</dt>
        <dd>Třetí povinnou položkou je textové pole, kde je nutné zadat adresu hostitelského serveru.</dd>
    </dl> 
    <dl>
        <dt>Port</dt>
        <dd>Čtvrtá povinná položka tohoto formuláře. Doporučené standardní porty jsou uvedeny v závorce u protokolů.</dd>
    </dl> 
    <dl>
        <dt>Složka</dt>
        <dd>Obsahuje název IMAP složky, odku se bude tahat emaily</dd>
    </dl> 
    <dl>
        <dt>Přihlašovací jméno</dt>
        <dd>Jedná se o pátou povinnou položku. Jak již napovídá název, musíte zadat přihlašovací jméno k vašemu emailu.</dd>
    </dl> 
    <dl>
        <dt>Přihlašovací heslo</dt>
        <dd>Šestou, poslední položkou je heslo k vašemu emailu.</dd>
    </dl> 
    <dl>
        <dt>Podatelna pro příjem</dt>
        <dd>Vyberte v rozbalovacím menu jednu možnost</dd>
    </dl> 
    <dl>
        <dt>Přijímat pouze emaily s připojeným e-podpisem</dt>
        <dd>Pokud je tento zaškrtávací box zaškrtnut, pak budou přijímány jen ty emaily, které budou obsahovat elektronický podpis.</dd>
    </dl> 
    <dl>
        <dt>Přijímat pouze emaily s ověřeným kvalifikovaným podpisem/značkou</dt>
        <dd>Opět se jedná o zaškrtávací pole, které po zaškrtnutí bude propouštět jen ty emaily, které budou opatřeny ověřeným kvalifikovaným podpisem či značkou.</dd>
    </dl> 

Jakmile máte všechny údaje vyplněny, můžete klepnout na tlačítko Uložit. Pokud chcete úpravu údajů přerušit, klepněte na tlačítko Zrušit.
</p>

<br /><br /><br />
<h3>Odesílání přes email</h3>
<p>
Stačí jen klepnout na nápis Upravit v detailech této položky, který najdete pod soupisem informací o nastavení účtu.
Jakmile se otevře nová obrazovka, můžete upravovat následující položky:
    <dl>
        <dt>Název účtu</dt>
        <dd>Je jedinou povinnou položkou tohoto formuláře.</dd>
    </dl> 
    <dl>
        <dt>Aktivní účet</dt>
        <dd>Jedná se o zaškrtávací pole určující, zda je účet aktivní.</dd>
    </dl> 
    <dl>
        <dt>Jak odesílat</dt>
        <dd>Zde máte možnost vybrat v rozbalovacím menu buď možnost klasicky bez kvalifikovaného podpisu/značky nebo s kvalifikovaným podpisem/značkou.</dd>
    </dl> 
    <dl>
        <dt>Emailová adresa odesilatele</dt>
        <dd>Můžete určit vlastní adresu nebo nechat pole prázdné, pokud není třeba na e-maily zasílané spisovkou odpovídat. Je-li pole nevyplněné, poštovní server sám určí adresu odesilatele.</dd>
    </dl> 
    <dl>
        <dt>Cesta k certifikátu</dt>
        <dd>Po klepnutí na tlačítko Procházet budete moci zadat cestu k vašemu certifikátu.</dd>
    </dl> 
    <dl>
        <dt>Cesta k privátnímu klíči</dt>
        <dd>U této položky se opět nachází tlačítko Procházet, na které když klepnete, budete moci zadat cestu k vašemu privátnímu klíči.</dd>
    </dl> 
    <dl>
        <dt>Heslo ke klíči certifikátu</dt>
        <dd>Do tohoto pole zadáváte heslo ke klíči vašeho certifikátu.</dd>
    </dl> 

Platí to samé jako v předchozích případech - pokud máte vše vyplněno podle vašich představ, stačí klepnout na tlačítko Uložit. V opačném případě, pokud chcete zrušit upravování emailové schránky pro odesílání přes email, tak klepněte na tlačítko Zrušit.
</p>
