        <h2>Detail organizační jednotky</h2>
<p>        
Pokud si chcete prohlédnout detaily některé organizační jednotky, musíte najet na její zkratku a klepnout na ní. Po rozklepnutí jedné z organizačních jednotek se vám zobrazí informace o této jednotce, které můžete editovat tím, že kliknete na odkaz Upravit, ale hlavně zde naleznete možnost Upravit Organizační strukturu, kde můžete dané organizační jednotce přidělit různé role. Stačí jen kliknout na nápis Upravit organizační strukturu a na další obrazovce zaškrtnout jednu z možností a změny uložit.        
</p>