    <h2>Nová organizační jednotka</h2>

<p>    
Pokud si přejete vytvořit novou organizační jednotku, musíte klepnout na odkaz Nová organizační jednotka, který najdete v horní levé části sekce Organizační jednotky.
V následujícím formuláři se nacházejí tyto položky:

    <dl>
        <dt>Zkrácený název</dt>
        <dd>Jedná se o zkrácený název organizační jednotky. Povinná položka</dd>
    </dl>
    <dl>
        <dt>Plný název jednotky</dt>
        <dd>Jedná se o plný název organizační jednotky</dd>
    </dl>
    <dl>
        <dt>Zkratka/číselná řada</dt>
        <dd>Jedná se o zkratku jendotky. Používá se vnitřně a pro zobrazení identifikace pracovníka. Povinná položka.</dd>
    </dl>
    <dl>
        <dt>Informace</dt>
        <dd>Krátký popis organizační jednotky.</dd>
    </dl>

Jakmile máte vyplněny všechny potřebné údaje, klikněte na tlačítko Vytvořit, v opačném případě klikněte na tlačítko Zrušit.    
</p>