    <h2>Seznam organizačních jednotek</h2>
    <p>
Pod tlačítkem Org. jednotky se ukrývá soupis všech již vytvořených organizačních jednotek. Tyto jednotky jsou zapsány do tabulky, která má dva sloupce. V tom prvním se nacházejí Zkratky/číselné řady a v tom druhém jsou Názvy organizačních jednotek. První jmenovaná položka vždy slouží jako odkaz, který vám zobrazí detaily dané organizační jednotky.
<br>Pro usnadnění práce s vyhledáváním jednotlivých organizačních jednotek je zde pro vás připravena funkce Hledat, kterou naleznete v pravé části nad tabulkou. V levé části je odkaz Nová organizační jednotka.
    </p>