    <h2>Seznam organizačních jednotek</h2>
    <p>
Pod tlačítkem Org. jednotky se ukrývá soupis všech již vytvořených organizačních jednotek. Položky v prvním sloupci slouží jako odkaz, který vám zobrazí detaily dané organizační jednotky.
<br>Pro usnadnění práce s vyhledáváním jednotlivých organizačních jednotek je zde pro vás připravena funkce Hledat, kterou naleznete v pravé části nad tabulkou. V levé části je odkaz Nová organizační jednotka.
    </p>