    <h2>Seznam organizačních jednotek</h2>
    <p>
        Pod tlačítkem Org. jednotky se ukrývá soupis všech již vytvořených organizačních
        jednotek. Tyto jednotky jsou zapsány do tabulky, která má dva sloupce. V tom prvním
        se nacházejí Zkratky/číselné řady a v tom druhém jsou Názvy organizačních jednotek,
        které fungují zároveň jako odkaz, který vám zobrazí detaily dané organizační jednotky.
        Po rozkliknutí jedné z organizačních jednotek se vám zobrazí informace o této jednotce,
        které můžete editovat tím, že kliknete na nápis Upravit, ale hlavně zde naleznete možnost
        Upravit Organizační strukturu, kde můžete dané organizační jednotce přidělit buď roli
        vedoucího nebo referenta. Stačí jen kliknout na nápis Upravit organizační strukturu a na
        další obrazovce zaškrtnout jednu z možností a změny uložit.
    </p>
    <p>
        Ale co když chcete vytvořit organizační jednotku zcela novou? To se musíte vrátit
        do seznamu organizačních jednotek a kliknout na nápis Nová organizační jednotka.
        V následujícím formuláři se nacházejí tyto položky:
    </p>
    <dl>
        <dt>Zkrácený název</dt><dd>Jedná se o povinnou položku, která je v seznamu organizačních jednotek vedena jako Název organizační jednotky.</dd>
        <dt>Plný název jednotky</dt>
        <dt>Zkratka/číselná řada</dt><dd>Toto je druhá povinná položka.</dd>
        <dt>Informace</dt><dd>Krátký popis organizační jednotky.</dd>
    </dl>
    <p>
        Jakmile máte vyplněny všechny potřebné údaje, klikněte na tlačítko Vytvořit,
        v opačném případě klikněte na tlačítko Zrušit.
    </p>