{block title}Seznam dokumentů{/block}
{block content}
    <div class="navigate">
    <a href="{link :Admin:Subjekty:seznam}">Seznam subjektů</a> - Detail subjektu
    </div>
    <h2>{=Subjekt::displayName($Subjekt,'jmeno')}</h2>

        {if ($FormUpravit=='info')}
    <div class="detail_blok">
        <div class="detail_hlavicka">Info</div>
        {$upravitForm->render('begin')}
        <dl class="detail_item">
            <dt>{$upravitForm['type']->label}</dt>
            <dd>{$upravitForm['type']->control}</dd>
        </dl>

        <dl class="detail_item type_ovm">
            <dt>{$upravitForm['nazev_subjektu']->label}</dt>
            <dd>{$upravitForm['nazev_subjektu']->control}</dd>
        </dl>
        <dl class="detail_item type_ovm">
            <dt>{$upravitForm['ic']->label}</dt>
            <dd>{$upravitForm['ic']->control}  <a href="#" onclick="return aresSubjekt('upravitForm');">Vyhledat pomoci systému ARES</a></dd>
        </dl>
        <dl class="detail_item type_ovm">
            <dt>{$upravitForm['dic']->label}</dt>
            <dd>{$upravitForm['dic']->control}</dd>
        </dl>

        <dl class="detail_item type_fo">
            <dt>{$upravitForm['titul_pred']->label}</dt>
            <dd>{$upravitForm['titul_pred']->control}</dd>
        </dl>
        <dl class="detail_item type_fo">
            <dt>{$upravitForm['jmeno']->label}</dt>
            <dd>{$upravitForm['jmeno']->control}</dd>
        </dl>
        <dl class="detail_item type_fo">
            <dt>{$upravitForm['prostredni_jmeno']->label}</dt>
            <dd>{$upravitForm['prostredni_jmeno']->control}</dd>
        </dl>
        <dl class="detail_item type_fo">
            <dt>{$upravitForm['prijmeni']->label}</dt>
            <dd>{$upravitForm['prijmeni']->control}</dd>
        </dl>
        <dl class="detail_item type_fo">
            <dt>{$upravitForm['titul_za']->label}</dt>
            <dd>{$upravitForm['titul_za']->control}</dd>
        </dl>
        <dl class="detail_item type_fo">
            <dt>{$upravitForm['rodne_jmeno']->label}</dt>
            <dd>{$upravitForm['rodne_jmeno']->control}</dd>
        </dl>

        <dl class="detail_item type_fo">
            <dt>{$upravitForm['datum_narozeni']->label}</dt>
            <dd>{$upravitForm['datum_narozeni']->control}</dd>
        </dl>
        <dl class="detail_item type_fo">
            <dt>{$upravitForm['misto_narozeni']->label}</dt>
            <dd>{$upravitForm['misto_narozeni']->control}</dd>
        </dl>
        <dl class="detail_item type_fo">
            <dt>{$upravitForm['okres_narozeni']->label}</dt>
            <dd>{$upravitForm['okres_narozeni']->control}</dd>
        </dl>
        <dl class="detail_item type_fo">
            <dt>{$upravitForm['stat_narozeni']->label}</dt>
            <dd>{$upravitForm['stat_narozeni']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>{$upravitForm['adresa_ulice']->label}</dt>
            <dd>
                {$upravitForm['adresa_ulice']->control}
                č.p. {$upravitForm['adresa_cp']->control}
                č.o. {$upravitForm['adresa_co']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>PSČ a město</dt>
            <dd>
                {$upravitForm['adresa_psc']->control}
                {$upravitForm['adresa_mesto']->control}
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>{$upravitForm['adresa_stat']->label}</dt>
            <dd>{$upravitForm['adresa_stat']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>{$upravitForm['email']->label}</dt>
            <dd>{$upravitForm['email']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$upravitForm['telefon']->label}</dt>
            <dd>{$upravitForm['telefon']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>{$upravitForm['id_isds']->label}</dt>
            <dd>{$upravitForm['id_isds']->control}</dd>
        </dl>

        <dl class="detail_item">
            <dt>{$upravitForm['poznamka']->label}</dt>
            <dd>{$upravitForm['poznamka']->control}</dd>
        </dl>
        <dl class="detail_item">
            <dt>&nbsp;</dt>
            <dd>{$upravitForm['upravit']->control} {$upravitForm['storno']->control}</dd>
        </dl>
        {$upravitForm->render('end')}
    </div>
        {else}
    <div class="detail_blok">
        <div class="detail_hlavicka">Info</div>
        <dl class="detail_item">
            <dt>Typ subjektu:</dt>
            <dd>{$Subjekt->type} - {=Subjekt::typ_subjektu($Subjekt->type)}&nbsp;</dd>
        </dl>

        {if (strpos($Subjekt->type,'OVM')!==false)||(strpos($Subjekt->type,'PO')!==false)||(strpos($Subjekt->type,'PFO')!==false)  }
        <dl class="detail_item">
            <dt>IČ:</dt>
            <dd>{$Subjekt->ic}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>DIČ:</dt>
            <dd>{$Subjekt->dic}&nbsp;</dd>
        </dl>
        {/if}
        {if (strpos($Subjekt->type,'FO')!==false)||(strpos($Subjekt->type,'PFO')!==false)  }
        <dl class="detail_item">
            <dt>Rodné jméno:</dt>
            <dd>{$Subjekt->rodne_jmeno}&nbsp;</dd>
        </dl>

        <dl class="detail_item">
            <dt>Datum narození:</dt>
            <dd>{$Subjekt->datum_narozeni|edate}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Místo narození:</dt>
            <dd>{$Subjekt->misto_narozeni}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Okres narození:</dt>
            <dd>{$Subjekt->okres_narozeni}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Stát narození:</dt>
            <dd>{$Subjekt->stat_narozeni} - {=Subjekt::stat($Subjekt->stat_narozeni,10)}&nbsp;</dd>
        </dl>
        {/if}
    </div>
    <div class="detail_blok">
        <div class="detail_hlavicka">Kontakt</div>
        <dl class="detail_item">
            <dt>Subjekt:</dt>
            <dd>{=Subjekt::displayName($Subjekt,'jmeno')}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Adresa:</dt>
            <dd>
                {!=Subjekt::displayName($Subjekt,'formalni_adresa')}&nbsp;
            </dd>
        </dl>
        <dl class="detail_item">
            <dt>Email:</dt>
            <dd>{$Subjekt->email}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>Telefon:</dt>
            <dd>{$Subjekt->telefon}&nbsp;</dd>
        </dl>
        <dl class="detail_item">
            <dt>ID datové schránky:</dt>
            <dd>{$Subjekt->id_isds}&nbsp;</dd>
        </dl>
    </div>
    <div class="detail_blok">
        <div class="detail_hlavicka">Poznámka</div>
        <dl class="detail_item">
            <dt>&nbsp;</dt>
            <dd>{$Subjekt->poznamka|enl2br}&nbsp;</dd>
        </dl>
        <a href="{link :Admin:Subjekty:detail, 'id'=>$Subjekt->id, 'upravit'=>'info'}">Upravit</a>
    </div>
    <div class="detail_blok">
        <div class="detail_hlavicka">Stav</div>
        {if ($FormUpravit=='stav')}
        {control stavForm}
        {else}
        <dl class="detail_item">
            <dt>&nbsp;</dt>
            <dd>{=Subjekt::stav($Subjekt->stav)}&nbsp;</dd>
        </dl>
        {/if}
        <a href="{link :Admin:Subjekty:detail, 'id'=>$Subjekt->id, 'upravit'=>'stav'}">Změnit stav</a>

    </div>
        {/if}

    <script type="text/javascript">

        $('#frmupravitForm-type').change(function () {
            value = $("#frmupravitForm-type").val();
            //alert(value);
            if ( value.indexOf('OVM')>=0 || value.indexOf('PO')>=0 ) {
                $(".type_fo").hide();
                $(".type_ovm").show();
            } else if ( value.indexOf('PFO')>0 ) {
                $(".type_fo").show();
                $(".type_ovm").show();
            } else {
                $(".type_ovm").hide();
                $(".type_fo").show();
            }

        })
        .trigger('change');


    </script>
