{block title}Seznam dokumentů{/block}
{block content}
    <div class="navigate">
    Seznam subjektů
    </div>

    <h2>Seznam subjektů</h2>

    <div class="blok_menu">
        <a href="{link :Admin:Subjekty:novy}">Nový subjekt</a>
    </div>

    {if count($seznam)>0}
    <table class="seznam">
        {foreach $seznam as $subjekt}
        <tr>
            <td class="icon">
                <img src="{$baseUri}images/subjekt/{$subjekt->type|lower}.png" alt="{$subjekt->type}" title="{$subjekt->type}" width="32" height="32" />
            </td>
            <td class="meta">
                <a href="{link :Admin:Subjekty:detail, id => $subjekt->id}">{=Subjekt::displayName($subjekt,'jmeno_item')}&nbsp;</a>
                <div class="info">
                <span>{$subjekt->type} - {=Subjekt::typ_subjektu($subjekt->type)}</span>
                <br />
                {=Subjekt::displayName($subjekt,'adresa')}
                </div>
            </td>
            <td class="meta_plus">
                &nbsp;
                <div class="info">
                <dl>
                    <dt>email:</dt>
                    <dd>{$subjekt->email}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>telefon:</dt>
                    <dd>{$subjekt->telefon}&nbsp;</dd>
                </dl>
                <dl>
                    <dt>isds:</dt>
                    <dd>{$subjekt->id_isds}&nbsp;</dd>
                </dl>

                </div>
            </td>
        </tr>
        {/foreach}
    </table>
    {widget vp}
    {else}
    <div class="prazdno">Nebyly zjištěny žádné subjekty.</div>
    {/if}
    