    {snippet dokpriloha}
    {if isset($chyba)}

    {if $chyba==1}
    <div class="flash_message flash_warning">Přílohu se nepodařilo připojit k dokumentu. Zkuste to znovu.</div>
    {elseif $chyba==2}
    <div class="flash_message flash_warning">Přílohu se nepodařilo nahrát. Zkuste to znovu.</div>
    <div class="flash_message flash_warning">{$error_message}</div>
    {elseif $chyba==3}
    <div class="flash_message flash_warning">Nějak se to zaseklo</div>
    {/if}

    {/if}
    
    {control uploadForm}

        <dl class="detail_item">
            <dt></dt>
            <dd class="normal">Maximální možná velikost souboru, kterou je možné nahrát: <?php echo DokumentPrilohy::maxVelikostUploadu(true) ?></dd>
        </dl>    

    {/snippet}