    <h2>Detail zaměstnance</h2>
    
<p>
Pokud chcete nahlédnout do detailů nějakého zaměstnance, tak je potřeba na jeho název klepnout. V detailech uvidíte jak základní informace, které se zadávají při tvorbě nového zaměstnance, tak i Uživatelské účty.
</p>
<p>
Pokud si přejete upravit základní informace, tak klepněte na odkaz Upravit v horní části sekce.
</p>
<p>
V případě, že chcete vytvořit nový účet pro zaměstnance, tak klepněte na odkaz Přidat účet. Zobrazí se vám následující povinné položky, které je nutné vyplnit:
    <dl>
        <dt>Uživatelské jméno</dt>
        <dt>Heslo</dt>
        <dt>Heslo znovu</dt>
        <dt>Role</dt>
    </dl>


Jakmile máte vyplněno, můžete klepnout na tlačítko Vytvořit účet. V případě, že jste si tvorbu nového účtu rozmysleli, klepněte na tlačítko Zrušit.
</p>
<p>
Rovněž máte možnost u stávajícího účtu změnit heslo (v tom případě se musí navolit nové), Odebrat účet úplně a poslední možnost, kterou můžete udělat je změnit či přidat roli. Obě tyto funkce se dělají přes odkaz Změnit role a to tak, že buď zaškrtnete pole Další role a tu vyberete nebo odškrtnete původní roli a vyberete novou.    
</p>