    <h2>Nový zaměstnanec</h2>
<p>    
Pokud si přejete vytvořit nového zaměstnance, tak musíte klepnout na tlačítko Zaměstnanci, poté klepnout na odkaz Nový zaměstnanec a následně vyplnit krátký formulář.
Ten obsahuje následující položky:
    <dl>
        <dt>Jméno</dt>
        <dt>Příjmení</dt>
        <dt>Titul před jménem</dt>
        <dt>Titul za jménem</dt>
        <dt>Email</dt>
        <dt>Telefon</dt>
        <dt>Funkce</dt>
    </dl>
Po zadání těchto údajů najeďte na tlačítko Vytvořit a klikněte na něj. Pokud však chcete operaci zrušit, klikněte na stejnojmenné tlačítko.    
</p>