    <h2>Seznam zaměstnanců</h2>
    <p>
        Další položka na liště menu je tlačítko zaměstnanci, pakliže na toto tlačítko
        kliknete, zobrazí se vám soupis všech zadaných zaměstnanců. Pokud chcete přidat
        nového zaměstnance, stačí kliknout na nápis Nový zaměstnanec a následně vyplnit
        krátký formulář. Ten obsahuje následující položky:
    </p>
    <dl>
        <dt>Jméno</dt>
        <dt>Příjmení</dt><dd>jedná se o povinný údaj</dd>
        <dt>Titul před jménem</dt>
        <dt>Titul za jménem</dt>
        <dt>Email</dt>
        <dt>Telefon</dt>
        <dt>Funkce</dt>
    </dl>
    <p>
        Po zadání těchto údajů najeďte na tlačítko Vytvořit a klikněte na něj. Pokud však
        chcete operaci zrušit, klikněte na stejnojmenné tlačítko.
    </p>