{extends @layout.phtml}

{block header}
    {css admin_site}
    <script type="text/javascript" src="{$baseUri}js/jquery-min.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery-min.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/jquery-ui-custom.min.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery-ui-custom.min.js'); ?>"></script>
    <script type="text/javascript">
        var baseUri = '{!$klientUri}';
        var is_simple = '{=IS_SIMPLE_ROUTER}';
    </script>
    {block #javascript}{/block}
    <script type="text/javascript" src="{$baseUri}js/jquery.nette.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery.nette.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/script.js?<?php echo filemtime(APP_DIR.'/../public/js/script.js'); ?>"></script>
{/block}    

{block menu}
    {access :Admin:Nastaveni:}<a href="{vlink :Admin:Nastaveni:}">Nastavení</a>{/access}
    {access :Admin:Epodatelna:}<a href="{vlink :Admin:Epodatelna:}">E-podatelna</a>{/access}
    {access :Admin:Spisy:}<a href="{vlink :Admin:Spisy:seznam}">Spisy</a>{/access}
    {access :Admin:Subjekty:}<a href="{vlink :Admin:Subjekty:seznam}">Odesílatelé/Adresáti</a>{/access}
    {access :Admin:Zamestnanci:}<a href="{vlink :Admin:Zamestnanci:seznam}">Zaměstnanci</a>{/access}
    {access :Admin:Orgjednotky:}<a href="{vlink :Admin:Orgjednotky:seznam}">Org. jednotky</a>{/access}
    {access :Admin:Opravneni:}<a href="{vlink :Admin:Opravneni:seznam}">Oprávnění</a>{/access}
    <!--{access :Admin:Prilohy:}<a href="{vlink :Admin:Prilohy:}">Soubory</a>{/access}-->
    {access :Admin:Spisznak:}<a href="{vlink :Admin:Spisznak:seznam}">Spisové znaky</a>{/access}
    {access :Admin:Ciselniky:}<a href="{vlink :Admin:Ciselniky:default}">Číselníky</a>{/access}
    {access :Admin:Protokol:}<a href="{vlink :Admin:Protokol:default}">Protokoly</a>{/access}
{/block}    
