{extends @layout.phtml}

{block header}
    {css epodatelna_site}
    <script type="text/javascript" src="{$baseUri}js/jquery-min.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery-min.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/jquery-ui-custom.min.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery-ui-custom.min.js'); ?>"></script>
    <script type="text/javascript">
        var baseUri = '{!$klientUri}';
        var is_simple = '{=IS_SIMPLE_ROUTER}';
    </script>
    {block #javascript}{/block}
    <script type="text/javascript" src="{$baseUri}js/jquery.nette.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery.nette.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/script.js?<?php echo filemtime(APP_DIR.'/../public/js/script.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/script_epodatelna.js?<?php echo filemtime(APP_DIR.'/../public/js/script_epodatelna.js'); ?>"></script>
{/block}    

{block menu}
    {access :Epodatelna:Default:}<a href="{vlink :Epodatelna:Default:zkontrolovat}">Zkontrolovat schránku</a>{/access}
    {access :Epodatelna:Default:}<a href="{vlink :Epodatelna:Default:nove}">Nové zprávy</a>{/access}
    {access :Epodatelna:Default:}<a href="{vlink :Epodatelna:Default:prichozi}">Příchozí zprávy</a>{/access}
    {access :Epodatelna:Default:}<a href="{vlink :Epodatelna:Default:odchozi}">Odchozí zprávy</a>{/access}
{/block}    
