<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>Spisová služba - E-podatelna - {block #title}{/block}</title>
    <link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/site.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/epodatelna_site.css" />
    <link type="text/css" href="{$baseUri}css/redmond/jquery-ui-custom.css" rel="stylesheet" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <script type="text/javascript" src="{$baseUri}js/jquery-min.js"></script>
    <script type="text/javascript" src="{$baseUri}js/jquery-ui-custom.min.js"></script>
    <script type="text/javascript">
        var baseUri = '{!$klientUri}';
    </script>
    {block #javascript}{/block}
    <script type="text/javascript" src="{$baseUri}js/jquery.nette.js"></script>
    <script type="text/javascript" src="{$baseUri}js/script.js"></script>
    <script type="text/javascript" src="{$baseUri}js/script_epodatelna.js"></script>
</head>
<body>
<div id="layout_top">
    <div id="top">
        <h1><a href="{vlink :Epodatelna:Default:}">E-podatelna</a> <span id="top_urad">{$Urad->nazev}</span></h1>
        <div id="top_menu">
            {access :Spisovka:Default:}<a href="{vlink :Spisovka:Default:}">Spisová služba</a>&nbsp;&nbsp;{/access}
            {access :Epodatelna:Default:}<a href="{vlink :Epodatelna:Default:}">E-podatelna</a>&nbsp;&nbsp;{/access}
            {access :Admin:Default:}<a href="{vlink :Admin:Default:}">Administrace</a>&nbsp;&nbsp;{/access}
            {access :Spisovka:Uzivatel:}<a href="{vlink :Spisovka:Uzivatel:}">Nastavení</a>&nbsp;&nbsp;{/access}
            <a href="{$klientUri}{$currentUri}">Nápověda</a>&nbsp;&nbsp;
            {access :Spisovka:Uzivatel:logout}<a href="{vlink :Spisovka:Uzivatel:logout}">Odhlásit</a>{/access}
        </div>
        <div id="top_jmeno">
            <strong>{$user->name}</strong>
            <br />
            {foreach $user->user_roles as $role}
                {$role->name}<br />
            {/foreach}
        </div>
    </div>
</div>
<div id="layout">
    <div id="menu">
        {access :Epodatelna:Default:zkontrolovat}<a href="{vlink :Epodatelna:Default:zkontrolovat}">Zkontrolovat schránku</a>{/access}
        {access :Epodatelna:Default:nove}<a href="{vlink :Epodatelna:Default:nove}">Nové zprávy</a>{/access}
        {access :Epodatelna:Default:prichozi}<a href="{vlink :Epodatelna:Default:prichozi}">Příchozí zprávy</a>{/access}
        {access :Epodatelna:Default:odchozi}<a href="{vlink :Epodatelna:Default:odchozi}">Odchozí zprávy</a>{/access}
    </div>
    <div n:if="count($flashes)>0" id="flash">
        {foreach $flashes as $flash}<div class="flash_message flash_{$flash->type}">{if strpos($flash->type,"_ext")!==false}{!$flash->message}{else}{$flash->message}{/if}</div>{/foreach}
    </div>
    <div id="content">
        {snippet main}
        @{include #content}
        {/snippet}
    </div>
    {if $debuger }
    <div id="debug">
        Module:    {$module}
        Presenter: {$presenter}
        View:      {$view}
        SQL:       <?php echo dibi::$numOfQueries ." : ". dibi::$totalTime; ?>

        SQL dotazy:
        {foreach dibi::getProfiler()->tickets as $dblog }
            {$dblog[2]}
        {/foreach}

        {block debug}{/block}

    </div>
    {/if}
</div>
<div id="layout_bottom">
    <div id="bottom">
        <strong>{$AppInfo[2]}</strong><br/>
        Na toto dílo se vztahuje <a href="http://ec.europa.eu/idabc/eupl">licence EUPL V.1.1</a>
    </div>
</div>


</body>
</html>