{extends @layout.phtml}

{block header}
    <link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/site.css?<?php echo filemtime(APP_DIR.'/../public/css/site.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="print" href="{$baseUri}css/print_site.css?<?php echo filemtime(APP_DIR.'/../public/css/print_site.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/epodatelna_site.css?<?php echo filemtime(APP_DIR.'/../public/css/print_site.css'); ?>" />
    <link type="text/css" href="{$baseUri}css/redmond/jquery-ui-custom.css?<?php echo filemtime(APP_DIR.'/../public/css/redmond/jquery-ui-custom.css'); ?>" rel="stylesheet" />
    <script type="text/javascript" src="{$baseUri}js/jquery-min.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery-min.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/jquery-ui-custom.min.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery-ui-custom.min.js'); ?>"></script>
    <script type="text/javascript">
        var baseUri = '{!$klientUri}';
        var is_simple = '{=IS_SIMPLE_ROUTER}';
    </script>
    {block #javascript}{/block}
    <script type="text/javascript" src="{$baseUri}js/jquery.nette.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery.nette.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/script.js?<?php echo filemtime(APP_DIR.'/../public/js/script.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/script_epodatelna.js?<?php echo filemtime(APP_DIR.'/../public/js/script_epodatelna.js'); ?>"></script>
{/block}    

{block menu}
    {access :Epodatelna:Default:}<a href="{vlink :Epodatelna:Default:zkontrolovat}">Zkontrolovat schránku</a>{/access}
    {access :Epodatelna:Default:}<a href="{vlink :Epodatelna:Default:nove}">Nové zprávy</a>{/access}
    {access :Epodatelna:Default:}<a href="{vlink :Epodatelna:Default:prichozi}">Příchozí zprávy</a>{/access}
    {access :Epodatelna:Default:}<a href="{vlink :Epodatelna:Default:odchozi}">Odchozí zprávy</a>{/access}
{/block}    
