{extends @layout.phtml}

{block header}
    <link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/site.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/install_site.css" />
    <script type="text/javascript">
        var baseUri = '{!$klientUri}';
        var is_simple = '{=IS_SIMPLE_ROUTER}';
    </script>
    <script src="{$baseUri}/js/denied/checker.js" type="text/javascript"></script>
    {block #javascript}{/block}
{/block}    

{block menu}
&nbsp;
{/block}    

{= $no_top_menu = true}
