<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>Spisová služba - {include #title}</title>
    <link rel="shortcut icon" href="{$baseUri}favicon.ico" type="image/x-icon" />
    {css site}
    {css print_site, print}
    {css redmond/jquery-ui-custom}
    
    {include #header}
</head>
<body>
{include top.phtml}

<div id="layout">
    <div id="menu">
    {include #menu}
    </div>

    {if isset($zpravy_pocet_neprectenych) && $zpravy_pocet_neprectenych > 0}
    <div id="upozorneni_na_nove_zpravy">
        Máte {$zpravy_pocet_neprectenych} nepřečtených zpráv.
        &nbsp;&nbsp;<a href="{link :Spisovka:Zpravy:}">Přečíst</a>        
    </div>    
    {/if}

    <div n:if="count($flashes)>0" id="flash">
        {foreach $flashes as $flash}<div class="flash_message flash_{$flash->type}">{if strpos($flash->type,"_ext")!==false}{!$flash->message}{else}{$flash->message}{/if}</div>{/foreach}
    </div>
    <div id="content">
        {snippet main}
        @{include #content}
        {/snippet}
    </div>
    {if isset($debuger) && $debuger}
    {include debug.phtml}    
    {/if}
</div>

<div id="layout_bottom">
    <div id="bottom">
        <strong>{$AppInfo[2]}</strong><br/>
        {if isset($KontrolaNovychVerzi) && !$KontrolaNovychVerzi['je_aktualni']}<span style="color:#880000;"><strong>Je k dispozici nová verze aplikace číslo {$KontrolaNovychVerzi['dostupna_verze']}</strong></span><br />{/if}
        Na toto dílo se vztahuje licence {!$licence}
    </div>
</div>

{if $is_authenticated}
<script type="text/javascript"> ajaxcron(); </script>
{/if}

</body>
</html>