<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>Spisová služba - {block #title}{/block}</title>
    <link rel="shortcut icon" href="{$publicUrl}favicon.ico" type="image/x-icon" />
    {css site}
    {css print_site, print}
    {css 'redmond/jquery-ui.min'}

    {js jquery-1.11.1.min}
    {js jquery-ui.min}
    <script type="text/javascript">
        var BASE_URL = '{!$baseUrl}';
        var PUBLIC_URL = '{!$publicUrl}';
        var is_simple = {=IS_SIMPLE_ROUTER};
    </script>
    {js script}
    {js netteForms}
    {if isset($Select2)}
        {css select2}
        {js select2.min}
    {/if}
    
    {block #javascript}{/block}

    {include #header}
</head>
<body>
{include top.phtml}

<div id="layout">
    <div id="menu">
    {include #menu}
    </div>

    {if isset($zpravy_pocet_neprectenych) && $zpravy_pocet_neprectenych > 0 && $presenter->name != "Spisovka:Zpravy"}
    <div id="upozorneni_na_nove_zpravy">
        Máte {$zpravy_pocet_neprectenych}
        {if $zpravy_pocet_neprectenych < 2}
        nepřečtenou zprávu.
        {elseif $zpravy_pocet_neprectenych < 5}
        nepřečtené zprávy.
        {else}
        nepřečtených zpráv.
        {/if}
        &nbsp;&nbsp;<a href="{link :Spisovka:Zpravy:}">Přečíst</a>        
    </div>    
    {/if}

    <div n:if="count($flashes)>0" id="flash">
        {foreach $flashes as $flash}<div class="flash_message flash_{$flash->type}">{if strpos($flash->type,"_ext")!==false}{!$flash->message}{else}{$flash->message}{/if}</div>{/foreach}
    </div>
    <div id="{if $presenter->name == 'Spisovka:Napoveda'}help_content{else}content{/if}">
        {include #content}
    </div>
    {if isset($debugger) && $debugger}
    {capture $debug_data}{block debug}{/block}{/capture}
    {include debug.phtml, extra_data => $debug_data}    
    {/if}
</div>

<div id="layout_bottom">
    <div id="bottom">
        <a href="{link :Spisovka:Seznamzmen:}" title="Zobrazit historii změn"><strong>{$AppInfo[2]}</strong></a><br/>
        {if isset($KontrolaNovychVerzi) && !$KontrolaNovychVerzi['je_aktualni']}<span style="color:#880000;"><strong>Je k dispozici nová verze aplikace číslo {$KontrolaNovychVerzi['dostupna_verze']}</strong></span><br />{/if}
        Na toto dílo se vztahuje licence {!$licence}
    </div>
</div>

{if $is_authenticated}
<script type="text/javascript"> ajaxcron(); </script>
{/if}

</body>
</html>