<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>Spisová služba - {block #title}{/block}</title>
    <link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/site.css?<?php echo filemtime(APP_DIR.'/../public/css/site.css'); ?>" />
    <link rel="stylesheet" type="text/css" media="print" href="{$baseUri}css/print_site.css?<?php echo filemtime(APP_DIR.'/../public/css/print_site.css'); ?>" />
    <link type="text/css" href="{$baseUri}css/redmond/jquery-ui-custom.css?<?php echo filemtime(APP_DIR.'/../public/css/redmond/jquery-ui-custom.css'); ?>" rel="stylesheet" />
    <link rel="shortcut icon" href="{$baseUri}favicon.ico" type="image/x-icon" />
    <script type="text/javascript" src="{$baseUri}js/jquery-min.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery-min.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/jquery-ui-custom.min.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery-ui-custom.min.js'); ?>"></script>
    <script type="text/javascript">
        var baseUri = '{!$klientUri}';
        var is_simple = '{=IS_SIMPLE_ROUTER}';
    </script>
    {block #javascript}{/block}
    <script type="text/javascript" src="{$baseUri}js/jquery.nette.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery.nette.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/script.js?<?php echo filemtime(APP_DIR.'/../public/js/script.js'); ?>"></script>
</head>
<body>
<div id="layout_top">
    <div id="top">
        <h1><a href="{vlink :Spisovka:Default:}">Spisová služba</a> <span id="top_urad">{$Urad->nazev}</span></h1>
        <div id="top_menu">
            {access :Spisovka:Default:}<a href="{vlink :Spisovka:Default:}">Spisová služba</a>&nbsp;&nbsp;{/access}
            {access :Epodatelna:Default:}<a href="{vlink :Epodatelna:Default:}">E-podatelna</a>&nbsp;&nbsp;{/access}
            {access :Spisovna:Default:}<a href="{vlink :Spisovna:Default:}">Spisovna</a>&nbsp;&nbsp;{/access}
            {access :Admin:Default:}<a href="{vlink :Admin:Default:}">Administrace</a>&nbsp;&nbsp;{/access}
            {access :Spisovka:Zpravy:default}<a href="{vlink :Spisovka:Zpravy:default}">Zprávy</a>&nbsp;&nbsp;{/access}
            <a href="{$klientUri}{$helpUri}">Nápověda</a>&nbsp;&nbsp;
            <a href="{vlink :Spisovka:Uzivatel:logout}">Odhlásit</a>
        </div>
        <div id="top_jmeno">
            <a href="{vlink :Spisovka:Uzivatel:}" title="nastavení uživatele"><strong>{$user->name}</strong></a>
            <br />
            {foreach $user->user_roles as $role}
                {$role->name}<br />
            {/foreach}
        </div>
    </div>
</div>
<div id="layout">
    <div id="menu">
        {access :Spisovka:Dokumenty:default}<a href="{link :Spisovka:Dokumenty:default}">Seznam dokumentů</a>{/access}
        {access :Spisovka:Dokumenty:novy}<a href="{link :Spisovka:Dokumenty:novy}">Nový dokument</a>{/access}
        {access :Spisovka:Spisy:default}<a href="{link :Spisovka:Spisy:default}">Spisy</a>{/access}
        {access :Spisovka:Sestavy:default}<a href="{link :Spisovka:Sestavy:default}">Sestavy</a>{/access}
        {access :Spisovka:Vypravna:default}<a href="{link :Spisovka:Vypravna:default}">K odeslání</a>{/access}
    </div>
    <div n:if="count($zpravy)>0" id="info_flash">
        {foreach $zpravy as $zprava}
        <div class="flash_infozprava">
            <strong>{$zprava['datum']} od {$zprava['od']}</strong>
            <p>
            {!$zprava['zprava']}
            </p>
            <p class="flash_action">
                <a href="{link :Spisovka:Zpravy:prectena, 'id'=>$zprava['id']}">Označit za přečtenou</a>
            </p>
        </div>
        {/foreach}
    </div>    
    
    
    <div n:if="count($flashes)>0" id="flash">
        {foreach $flashes as $flash}<div class="flash_message flash_{$flash->type}">{if strpos($flash->type,"_ext")!==false}{!$flash->message}{else}{$flash->message}{/if}</div>{/foreach}
    </div>
    <div id="content">
        {snippet main}
        @{include #content}
        {/snippet}
    </div>
    {if $debuger }
    <div id="debug">
        <div id="debug_head">
            <div id="debug_info">Debug Info</div>
            <div id="debug_route"><strong>{$module}:{$presenter}:{$view}</strong></div>
            <div id="debug_time">Čas: <strong><?php echo sprintf('%0.3f', (microtime(TRUE) - Debug::$time) * 1000); ?> ms</strong></div>
            <div id="debug_memory">Paměť: <strong title="špička: <?php echo TemplateHelpers::bytes(memory_get_peak_usage());  ?>"><?php echo TemplateHelpers::bytes(memory_get_usage()); ?></strong></div>
            <div id="debug_sql">SQL: <strong><?php echo dibi::$numOfQueries ." / ". number_format( (dibi::$totalTime)*1000,3,'.',' '); ?> ms</strong></div>
            <div id="debug_close">Zavřít</div>
            <br class="clear" />
        </div>
        <div id="debug_body">
            <div id="debug_body_route">
        Module:    {$module}
        Presenter: {$presenter}
        View:      {$view}

        User:      {=print_r(Environment::getUser()->getIdentity())}

        Server:
        {foreach $_SERVER as $sname => $svalue}
        <span style="color:#0000ff">{$sname}</span> = <span style="color:#008800">{if is_array($svalue)}Array(){else}{$svalue}{/if}</span>
        {/foreach}
            </div>
            <div id="debug_body_sql">
            {foreach dibi::getProfiler()->tickets as $dblog }
                {if $dblog[1] == 4}
                <div class="debug_body_sql_item">
                <?php dibi::test($dblog[2]); ?>
                </div>
                {/if}
            {/foreach}
            </div>
            <div id="debug_body_info">
            {capture $html_out}{block debug}{/block}{/capture}
            {$html_out}
            </div>

        </div>
    </div>
    <script type="text/javascript" src="{$baseUri}js/script_debug.js"></script>
    {/if}
</div>
<div id="layout_bottom">
    <div id="bottom">
        <strong>{$AppInfo[2]}</strong><br/>
        {if $NovaVerze['aktualni']==0}<span style="color:#880000;"><strong>Je k dispozici nová verze!</strong> Vaše současná verze je {$NovaVerze['soucasna_verze']}. Nová verze je {$NovaVerze['aktualni_verze']}</span><br />{/if}
        Na toto dílo se vztahuje licence {!$licence}
    </div>
</div>
    <script type="text/javascript"> ajaxcron(); </script>
</body>
</html>