<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <title>Spisová služba</title>
    <link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/site.css" />
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
</head>
<body>
<div id="layout_top">
    <div id="top">
        <h1><a href="{link :Spisovka:Default:}">Spisová služba</a> <span id="top_urad">{$Urad->nazev}</span></h1>
        <div id="top_menu">
            &nbsp;
        </div>
        <div id="top_jmeno">
            &nbsp;
        </div>
    </div>
</div>
<div id="layout">
    <div id="menu">
    &nbsp;
    </div>
    <div id="content">

        <h1>Aplikace je na nějakou chvíli odstavena!</h1>

        <p>
            V aplikaci se provádí aktualizace, údržba nebo činnost, která vyžaduje nulovou
            aktivitu uživatele.
        </p>
        <p>
            Aplikace bude obnovena za několik minut, ale může se stát, že k obnovení dojde i za pár hodin.
        </p>
        <p>
            Mějte prosím strpení. Děkujeme za pochopení.
        </p>
        <p>
            Kolektiv OSS Spisové služby v3.
        </p>

    </div>
</div>
<div id="layout_bottom">
    <div id="bottom">
        <strong>{$AppInfo[2]}</strong><br/>
        Na toto dílo se vztahuje <a href="http://www.osor.eu/eupl/european-union-public-licence-eupl-v.1.1">licence EUPL V.1.1</a>
    </div>
</div>


</body>
</html>