{extends @layout.phtml}

{block header}
    <link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/site.css" />
    <link rel="stylesheet" type="text/css" media="screen" href="{$baseUri}css/login.css" />
{/block}    

{block menu}
&nbsp;
{/block}    

{= $no_top_menu = true}

{block content}
    <h1>Aplikace je na nějakou chvíli odstavena!</h1>

    <p>
        V aplikaci se provádí aktualizace, údržba nebo činnost, která vyžaduje nulovou
        aktivitu uživatele.
    </p>
    <p>
        Aplikace bude obnovena za několik minut, ale může se stát, že k obnovení dojde i za pár hodin.
    </p>
    <p>
        Mějte prosím strpení. Děkujeme za pochopení.
    </p>
    <p>
        Kolektiv OSS Spisové služby v3.
    </p>
{/block}
