<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
    <link rel="shortcut icon" href="{$baseUri}favicon.ico" type="image/x-icon" />
    <title>Spisová služba - {block #title}{/block}</title>
    <style type="text/css" media="screen, print">
        <?php echo file_get_contents(APP_DIR .'/../public/css/print_site.css'); ?>
    </style>
</head>
<body{if $view=='tisk'} onload="window.print();"{/if}>
{include #content}
</body>
</html>