{extends @layout.phtml}

{block header}
    {css spisovna_site}
    <script type="text/javascript" src="{$baseUri}js/jquery-min.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery-min.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/jquery-ui-custom.min.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery-ui-custom.min.js'); ?>"></script>
    <script type="text/javascript">
        var baseUri = '{!$klientUri}';
        var is_simple = '{=IS_SIMPLE_ROUTER}';
    </script>
    {block #javascript}{/block}
    <script type="text/javascript" src="{$baseUri}js/jquery.nette.js?<?php echo filemtime(APP_DIR.'/../public/js/jquery.nette.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/script.js?<?php echo filemtime(APP_DIR.'/../public/js/script.js'); ?>"></script>
    <script type="text/javascript" src="{$baseUri}js/script_spisovna.js?<?php echo filemtime(APP_DIR.'/../public/js/script_spisovna.js'); ?>"></script>
{/block}    

{block menu}
    {accessrole skartacni_dohled,superadmin}Příjem 
    <a href="{link :Spisovna:Spisy:prijem}">spisů</a> / 
    <a href="{link :Spisovna:Dokumenty:prijem}">dokumentů</a>
    {/accessrole}
    &nbsp;&nbsp;&nbsp;
    {access :Spisovna:Dokumenty:}
    <a href="{link :Spisovna:Dokumenty:default}">Seznam dokumentů</a>
    <a href="{link :Spisovna:Spisy:default}">Spisy</a>
    {/access}
    &nbsp;&nbsp;&nbsp;
    {access :Spisovna:Zapujcky:}<a href="{link :Spisovna:Zapujcky:default}">Zápůjčky</a>{/access}
    &nbsp;&nbsp;&nbsp;
    {accessrole skartacni_dohled,superadmin}<a href="{link :Spisovna:Dokumenty:keskartaciseznam}">Ke skartaci</a>{/accessrole}
    {accessrole skartacni_dohled,skartacni_rizeni,superadmin}<a href="{link :Spisovna:Dokumenty:skartace}">Skartační řízení</a>{/accessrole}
{/block}
